### PR TITLE
Fix ext2 fast symlink inode detection logic

### LINKED ISSUE #2883: The symlink to Go is broken on NixOS
When attempting to install Go on Asterinas NixOS, I discovered that the symlink to the Go binary is consistently broken. As a result, Go cannot be executed on Asterinas NixOS.

### Steps to Reproduce

1. Add Go as a system package in `distro/etc_nixos/configuration.nix`:

```nix
environment.systemPackages = with pkgs; [ hello-asterinas go ];
```

2. Build and run:

```bash
make nixos
make run_nixos
```

3. Check the Go symlink under `/run/current-system/sw/bin`. You'll find it is broken:

```bash
[root@asterinas:~]# ls -l /run/current-system/sw/bin/go
lrwxrwxrwx 1 root root 60 Jan 14 03:07 /run/current-system/sw/bin/go -> 'E'$'\017\003'
```

This appears to be an Asterinas-specific bug. Notably, when using nixos-enter to access the same NixOS environment from the host system, the symlink is correct and fully functional.

### PR DESCRIPTION
**Pull request by cqs21**
Fixes #2883

### CODE REVIEW

File: kernel/src/fs/ext2/inode.rs [hunk 1]
```diff
@@ -2210,11 +2210,23 @@ impl InodeDesc {
...
+
+    /// Returns whether the inode is a fast symlink.
+    ///
+    /// Reference: <https://elixir.bootlin.com/linux/v6.18/source/fs/ext2/inode.c#L48-L55>.
+    fn is_fast_symlink(&self) -> bool {
+        if self.type_ != InodeType::SymLink {
+            return false;
+        }
+
+        let extra_sectors = self.acl.map_or(0, |_| BLOCK_SIZE / SECTOR_SIZE) as u32;
```
Comment (tatetian) [inline kernel/src/fs/ext2/inode.rs]: Just a few lines below is a `sectors_to_blocks` utility function for exactly this purpose...

File: kernel/src/fs/ext2/inode.rs [hunk 2]
```diff
@@ -2210,11 +2210,23 @@ impl InodeDesc {
...
+        self.sector_count == extra_sectors
```
Comment (tatetian) [inline kernel/src/fs/ext2/inode.rs]: On what the basis should the ACL field be used to check whether a symbolic link is fast or not...

**Review by tatetian — COMMENTED** [review]
Good job on identifying the bug so quickly.

While I was reading the code, the PR turned to draft. But I submitted the reviews anyway.

The logic of this bugfix does not feel right to me. And you might want to take a look at the `write_link` method, which is also problematic:

https://github.com/asterinas/asterinas/blob/cab259e0287e6e83ffe1f234ac362f7451814175/kernel/src/fs/ext2/inode.rs#L1343-L1352

Calling `InodeImpl::resize` does not make any sense. As I understand it, a symbolic link whose link string is stored inline should have a block count of 0.

---

Edit: when writing a fast symbolic link, a correct implementation needs to take into account that the inode may currently store a normal symbolic link. In this case, the block count needs to be updated to zero. Otherwise, the `write_link` method should not touch the block count (which must already be zero).

File: kernel/src/fs/ext2/inode.rs (hunk 2 above)
Comment (cqs21) [reply kernel/src/fs/ext2/inode.rs]: My understanding is that `self.sector_count` stores the total number of disk sectors used by this inode, including both the file content itself and the extended ACL file (which occupies one block). Therefore, if we subtract the ACL file sectors and sector_count is still non-zero, it indicates that this symlink's content is stored in a separate data block.

Comment (tatetian) [reply kernel/src/fs/ext2/inode.rs]: > My understanding is that `self.sector_count` stores the total number of disk sectors used by this inode

Then, what is the basis of this understanding? 

* From the perspective of our implementation: the [`try_expand_blocks`](https://github.com/asterinas/asterinas/blob/cab259e0287e6e83ffe1f234ac362f7451814175/kernel/src/fs/ext2/inode.rs#L1436) method sets `sector_count` without taking into account of `acl`.
* From the perspective of [the Ext2 spec](https://www.nongnu.org/ext2-doc/ext2.html): 
  > i_blocks
  > 32-bit value representing the total number of 512-bytes blocks reserved to contain the data of this inode. The block numbers of these reserved blocks are contained in the i_block array.
  >
  > h_blocks
  > In Linux a value of h_blocks higher than 1 is considered invalid. This effectively restrict the amount of extended attributes to what can be fit in a single block.

  `i_blocks` only accounts for the blocks for _data_, not ACL. And the length of ACL is restricted to one block.

Comment (cqs21) [reply kernel/src/fs/ext2/inode.rs]: > Then, what is the basis of this understanding?

See reference: https://elixir.bootlin.com/linux/v6.18/source/fs/ext2/inode.c#L48-L55

> i_blocks
32-bit value representing the total number of 512-bytes blocks reserved to contain the data of this inode.

The `i_blocks` field represents "the data of this inode" rather than "the data of this file". Based on Linux kernel implementation, ACL is counted as part of `i_blocks`.

Comment (tatetian) [reply kernel/src/fs/ext2/inode.rs]: Then the up-to-date Linux implementation is inconsistent with the written spec. We have to respect the "executing spec" (the code itself) over the written one.

However, the changes of this PR can't be right because the semantics of `i_blocks` is inconsistent across our Ext2 implementation. In the other part of the code (`try_expand_blocks`), `i_blocks` is interpreted as a counter that only accounts the data blocks, not ACL ones.

File: kernel/src/fs/ext2/inode.rs [hunk 3]
```diff
@@ -1519,7 +1518,8 @@ impl InodeImpl {
             return Err(e);
         }
 
-        self.desc.sector_count = blocks_to_sectors(range.start + device_range.len() as u32);
+        self.desc.sector_count = blocks_to_sectors(range.start + device_range.len() as u32)
+            + self.desc.file_acl_sectors();
```
Comment (tatetian) [inline kernel/src/fs/ext2/inode.rs]: This pattern has appeared triple. Wrap this pattern into a reusable method.

File: kernel/src/fs/ext2/inode.rs [hunk 4]
```diff
@@ -2215,6 +2213,30 @@ impl InodeDesc {
...
+
+    /// Returns whether the inode is a fast symlink.
+    ///
+    /// Reference: <https://elixir.bootlin.com/linux/v6.18/source/fs/ext2/inode.c#L48-L55>.
+    fn is_fast_symlink(&self) -> bool {
+        if self.type_ != InodeType::SymLink {
+            return false;
+        }
+
+        self.sector_count == self.file_acl_sectors()
```
Comment (tatetian) [inline kernel/src/fs/ext2/inode.rs]: I prefer a more revealing way to write the same logic:

```rust
let nr_data_sectors = self.sector_count - self.file_acl_sectors();
nr_data_sectors == 0
```

File: kernel/src/fs/ext2/inode.rs [hunk 5]
```diff
@@ -2215,6 +2218,44 @@ impl InodeDesc {
...
         size.div_ceil(BLOCK_SIZE) as Ext2Bid
     }
+
+    /// Returns the number of sectors used for ACL.
+    fn acl_sectors(&self) -> u32 {
+        let Some(bid) = self.acl else {
+            return 0;
+        };
+
+        if bid.to_raw() == 0 {
```
Comment (tatetian) [inline kernel/src/fs/ext2/inode.rs]: If `bid` is allowed to contain zero, then using `Option<_>` for the `acl` field becomes pointless. So I suggest changing its type to `Bid`. And this method will also be simplified.

**Review by tatetian — COMMENTED** [review]
Great. The code is correct... finally.

File: kernel/src/fs/ext2/inode.rs [hunk 6]
```diff
@@ -66,9 +66,12 @@ impl Inode {
                 None
             },
             block_group_idx,
-            xattr: desc
-                .acl
-                .map(|acl| Xattr::new(acl, weak_self.clone(), fs.clone())),
+            xattr: match desc.type_ {
+                InodeType::Dir | InodeType::File => {
+                    Some(Xattr::new(desc.acl, weak_self.clone(), fs.clone()))
```
Comment (tatetian) [inline kernel/src/fs/ext2/inode.rs:71]: This is NOT equivalent to the original code, which skips the creation of `Xattr` if `desc.acl` is none (or 0 in the new code).

Comment (cqs21) [reply kernel/src/fs/ext2/inode.rs:71]: From the old code, `acl` would not be `None` for `File` and `Dir`:
https://github.com/asterinas/asterinas/blob/306cc714ae9fe1dada55499d7ecab0853b068a5a/kernel/src/fs/ext2/inode.rs#L2165-L2169

From the new code, acl can indeed be `0`, but this is not a problem. The lazy initialization in `xattr::lazy_init` will check the `Bid` value; if an `Xattr` is not created there, it can still be created later when functions like `set_xattr` are called, based on the inode type:
https://github.com/asterinas/asterinas/blob/306cc714ae9fe1dada55499d7ecab0853b068a5a/kernel/src/fs/ext2/xattr.rs#L110-L116

Comment (tatetian) [reply kernel/src/fs/ext2/inode.rs:71]: Yes, you are right. Thanks for the explanation.

**Review by tatetian — APPROVED** [review]
LGTM. Thanks for the contribution!
