### PR TITLE
Fix both the preempt count atomicity and the CPU-local init problem

### LINKED ISSUE #1069: CPU local memory is used before initialized
The use (in `ostd`):
`init` → `mm::heap_allocator::init` → `HEAP_ALLOCATOR.init` → `SpinLock::lock_irq_disabled` → `trap::irq::disable_local` → `task::processor::disable_preempt` → `PREEMPT_COUNT.increase_num_locks`, where `PREEMPT_COUNT` is a cpu-local variable.

The initialization:
`init` → `cpu::cpu_local::init_on_bsp` → ...

The use is before the initialization since `mm::heap_allocator::init` is called prior to `cpu::cpu_local::init_on_bsp`.
https://github.com/asterinas/asterinas/blob/94eba6d85eb9e62ddd904c1132d556b808cc3174/ostd/src/lib.rs#L51-L82

---

It does not fault in x86 because `fsbase` is by default `0`, and the OS has write access to the memory near `0x0`, so the error is silent. But in RISC-V, this memory region is not writable, so it faults.

And I guess this is not the only case since `SpinLock` is widely used in `ostd`, it might be other uses of `SpinLock` before CPU local memory is initialized, for example, `mm::kspace::init_boot_page_table` → `BOOT_PAGE_TABLE.lock`.

### PR DESCRIPTION
**Pull request by junyang-zh**
Fix #1069 and checked it using assertions to prevent happening again.

Also, this approach fixes the problem of the preempt count atomicity, as stated in the comment:

```rust
/// Currently, it only holds the number of preemption locks held by the
/// current CPU. When it has a non-zero value, the CPU cannot call
/// [`schedule()`].
///
/// For per-CPU preemption lock count, we cannot afford two non-atomic
/// operations to increment and decrement the count. The [`crate::cpu_local`]
/// implementation is free to read the base register and then calculate the
/// address of the per-CPU variable using an additional instruction. Interrupts
/// can happen between the address calculation and modification to that
/// address. If the task is preempted to another CPU by this interrupt, the
/// count of the original CPU will be mistakenly modified. To avoid this, we
/// introduce [`crate::arch::cpu::local::preempt_lock_count`]. For x86_64 we
/// can implement this using one instruction. In other less expressive
/// architectures, we may need to disable interrupts.
///
/// Also, the preemption count is reserved in the `.cpu_local` section
/// specified in the linker script. The reason is that we need to access the
/// preemption count before we can copy the section for application processors.
/// So, the preemption count is not copied from bootstrap processor's section
/// as the initialization. Instead it is initialized to zero for application
/// processors.
struct PreemptInfo {}
```

The idea is raised during a private discussion with @lrh2000. Thanks very much to him.

---

Also, in this PR the integration test in CI is adjusted to cover debug assertions and remove unnecessarily boot tests.

### CODE REVIEW

File: ostd/src/arch/x86/cpu/local.rs [hunk 1]
```diff
@@ -0,0 +1,98 @@
...
+        let count: u32;
+        // SAFETY: The inline assembly reads the lock count atomically
+        // without side effects.
+        unsafe {
+            core::arch::asm!(
+                "mov {0:e}, fs:[{1}]",
+                out(reg) count,
+                in(reg) offset_of_count(),
+                options(nostack),
+            );
```
Comment (lrh2000) [inline ostd/src/arch/x86/cpu/local.rs:74]: This should have `options(nostack, readonly)`?

File: ostd/src/arch/x86/cpu/local.rs [hunk 2]
```diff
@@ -0,0 +1,98 @@
...
+
+    fn offset_of_count() -> usize {
+        __cpu_local_preempt_lock_count as *const u32 as usize
+            - __cpu_local_start as *const u32 as usize
+    }
+
+    /// The GDT ensures that the FS segment is initialized to zero on boot.
+    /// This assertion checks that the base address has been set.
+    fn debug_assert_initialized() {
+        debug_assert_ne!(super::get_base(), 0);
```
Comment (lrh2000) [inline ostd/src/arch/x86/cpu/local.rs:96]: Perhaps it's better to manually add another `#[cfg(debug_assertions)]`? I'm not sure whether this `super::get_base` can be optimized away when the debug assertions are disabled.

File: ostd/src/cpu/cpu_local.rs [hunk 3]
```diff
@@ -170,6 +182,19 @@ impl<T> Deref for CpuLocalDerefGuard<'_, T> {
     }
 }
 
+/// Sets the base address of the CPU-local storage for the bootstrap processor.
+///
+/// It should be called early to let [`crate::task::disable_preempt`] work,
+/// which needs to update a CPU-local preempt lock count. Otherwise it may
+/// panic when calling [`crate::task::disable_preempt`].
+pub(crate) fn early_init_bsp_local_base() {
```
Comment (lrh2000) [inline ostd/src/cpu/cpu_local.rs:190]: This is not a safe function, but as you said that most initialization functions are not safe. So I'm not sure what's the right way to deal with this problem.

File: ostd/src/cpu/cpu_local.rs [hunk 4]
```diff
@@ -115,6 +122,11 @@ impl<T> CpuLocal<T> {
     /// This function calculates the virtual address of the CPU-local object based on the per-
     /// cpu base address and the offset in the BSP.
     fn get(&self) -> *const T {
+        // CPU-local objects should be initialized before being accessed. It should be ensured
+        // by the implementation of OSTD initialization.
+        #[cfg(debug_assertions)]
+        debug_assert!(IS_INITIALIZED.load(Ordering::Acquire));
```
Comment (lrh2000) [inline ostd/src/cpu/cpu_local.rs:128]: `IS_INITIALIZED` is not used for synchronization, so I think that all accesses to it should use `Ordering::Relaxed`.

File: ostd/src/arch/x86/cpu/local.rs [hunk 5]
```diff
@@ -0,0 +1,98 @@
...
+}
+
+/// Gets the base address for the CPU local storage by reading the FS base model-specific register.
+pub(crate) fn get_base() -> u64 {
+    FS::read_base().as_u64()
+}
+
+pub mod preempt_lock_count {
+    //! We need to atomically increment and decrement the per-CPU preemption
+    //! lock count, requiring the implementation using a single instruction.
```
Comment (lrh2000) [inline ostd/src/arch/x86/cpu/local.rs:28]: Don't use the word "atomic", just say that we need to "use a single instruction".

`inc` is not an atomic operation as it does not synchronize between CPU cores. For an atomic operation, we need to use `lock; inc`. But using `lock; inc` is not necessary here since the preemption count is per-CPU.

This also applies to all the comments below, like:
```patch
-   /// Atomically increments the per-CPU preemption lock count.
+   /// Increments the per-CPU preemption lock count using a single instruction.
```

File: ostd/src/cpu/cpu_local.rs (hunk 3 above)
Comment (junyang-zh) [reply ostd/src/cpu/cpu_local.rs:190]: Ur right, it must be called on the BSP, as a safety condition.

File: ostd/src/arch/x86/cpu/local.rs [hunk 6]
```diff
@@ -0,0 +1,87 @@
...
+            );
+        }
+    }
+
+    /// Gets the per-CPU preemption lock count using one instruction.
+    pub(crate) fn get() -> u32 {
+        debug_assert_initialized!();
+
+        let count: u32;
+        // SAFETY: The inline assembly reads the lock count atomically
```
Comment (lrh2000) [inline ostd/src/arch/x86/cpu/local.rs:76]: So this `atomically` should also be `using one instruction`.

**Review by lrh2000 — APPROVED** [review]
Thanks for the quick implementation!

**Comment by YanWQ-monad** [comment]
To cover debug assertions in intergration tests, I think it might be better to pass `-C debug-assertions` to the compiler (according to the doc of [`debug_assert`](https://doc.rust-lang.org/std/macro.debug_assert.html)) without turning off release. Besides, maybe we can enable `debug-assertions` throughout the CI, not only that test (avoid full rebuild caused by changing `RUSTFLAGS`)?

**Comment by junyang-zh** [comment]
> (avoid full rebuild caused by changing `RUSTFLAGS`)?

We control the build profile by the cargo --release option rather than rustflags. So the release build cache won't be purged when building the debug binary. I think that it is still nessasary to test the debug profile. While to test debug assertions in the release profile would require a build cache miss, it's necessity is still on debate

**Review by tatetian — APPROVED** [review]
LGTM. Thanks for the contribution!
