### PR TITLE
Reimplement vsock

### LINKED ISSUE #2885: Enhance Vsock functionality and performance
### Current Feature

The current Guest Vsock implementation in Asterinas has limitations, lagging behind Linux in both feature completeness and performance. The following lists some functional issues and some experimental data:
#### Functional issues
**issue 1**
https://github.com/asterinas/asterinas/blob/1723e5d9440b02d70ff932726f609cb697496d3f/kernel/src/net/socket/vsock/mod.rs#L18-L26

`vsockspace.poll().unwrap();` This means that if poll encounters an error, the kernel will crash directly.

**issue 2**

In scenarios involving unidirectional data transfer from Host to Guest, the Asterinas Guest Vsock implementation fails to issue explicit Credit Update packets after consuming data from the RX buffer.
Since credit information is typically piggybacked in data packet headers, the sender (Host) only learns of updated credit information when the receiver sends data packets. In unidirectional scenarios where the receiver does not send any data, the sender's cached credit information (peer_fwd_cnt) becomes stale. The sender continues to calculate available buffer space using the stale peer_fwd_cnt value, leading to an incorrect perception that the Guest's buffer is full (credit exhausted).
When the sender attempts to send data and detects insufficient credit, it sends a CreditRequest. However, without the receiver proactively sending CreditUpdates (which only occurs in response to CreditRequest), the sender's view of available buffer space does not get refreshed until a CreditRequest is issued and processed. This can cause transmission failures or stalls despite available buffer space on the Guest side.

#### Performance issue

In two simple scenarios, Asterinas is far inferior to the implementation of Linux.

To ensure a fair and reproducible comparative analysis, we established a unified experimental environment based on QEMU for both Asterinas and Linux (serving as the baseline). The Guest hardware topology was provisioned with a single vCPU and 8 GiB of DRAM. Regarding the device interface, a vhost-backed Virtio-Vsock PCI device was attached.
Specifically, the command for running Asterinas is:
```
make run_kernel \
    VSOCK=on \
    SMP=1 \
    MEM=8G \
    ENABLE_KVM=1 \
    RELEASE_LTO=1
```
Linux uses its equivalent QEMU configuration.

**Test 1**
In the first test we use Linux source  [`tools/testing/vsock/vsock_perf.c`](https://github.com/torvalds/linux/blob/c537e12daeecaecdcd322c56a5f70659d2de7bde/tools/testing/vsock/vsock_perf.c#L4)

In light of the functional constraints of the current Asterinas Vsock implementation, this test is strictly confined to the Guest-to-Host unidirectional data path. The Guest functions as the transmitter (TX) and the Host acts as the receiver (RX).

The test results are as follows:
**Send a total of 1MB of data in 1KB size**
**Linux**
```
Linux(Guest)$ ./vsock_perf --sender 2 --bytes 1M --buf-size 1K
Run as sender
Connect to 2:1234
Send 1048576 bytes
TX buffer 1024 bytes
total bytes sent: 1048576
tx performance: 1.182126 Gbits/s
total time in tx loop: 0.007208 sec
time in 'send()': 0.007096 sec

Host$ ./vsock_perf --buf-size 1K
Run as receiver
Listen port 1234
RX buffer 1024 bytes
vsock buffer 262144 bytes
SO_RCVLOWAT 1 bytes
total bytes received: 1048576
rx performance: 0.966218 Gbits/s
total time in 'read()': 0.003967 sec
average time in 'read()': 3869.884766 ns
POLLIN wakeups: 1025
```
**Asterinas**

```

Asterinas(Guest)$ ./vsock_perf --sender 2 --bytes 1M --buf-size 1K
Run as sender
Connect to 2:1234
Send 1048576 bytes
TX buffer 1024 bytes
total bytes sent: 1048576
tx performance: 0.005869 Gbits/s
total time in tx loop: 1.429323 sec
time in 'send()': 1.429272 sec

Host$ ./vsock_perf --buf-size 1K
Run as receiver
Listen port 1234
RX buffer 1024 bytes
vsock buffer 262144 bytes
SO_RCVLOWAT 1 bytes
total bytes received: 1048576
rx performance: 0.005859 Gbits/s
total time in 'read()': 0.006415 sec
average time in 'read()': 6258.727051 ns
POLLIN wakeups: 1025
```

**Send a total of 100MB with a data size of 1KB**
**Linux**
```
Linux(Guest)$ ./vsock_perf --sender 2 --bytes 100M --buf-size 1K
Run as sender
Connect to 2:1234
Send 104857600 bytes
TX buffer 1024 bytes
total bytes sent: 104857600
tx performance: 0.885672 Gbits/s
total time in tx loop: 0.958665 sec
time in 'send()': 0.947147 sec

Host$ ./vsock_perf --buf-size 1K
Run as receiver
Listen port 1234
RX buffer 1024 bytes
vsock buffer 262144 bytes
SO_RCVLOWAT 1 bytes
total bytes received: 104852480
rx performance: 0.873835 Gbits/s
total time in 'read()': 0.484249 sec
average time in 'read()': 4729.229492 ns
POLLIN wakeups: 102395
```

**Asterinas**

```
Asterinas(Guest)$ ./vsock_perf --sender 2 --bytes 100M --buf-size 1K
Run as sender
Connect to 2:1234
Send 104857600 bytes
TX buffer 1024 bytes
total bytes sent: 104857600
tx performance: 0.007652 Gbits/s
total time in tx loop: 109.628357 sec
time in 'send()': 109.621384 sec

Host$ ./vsock_perf --buf-size 1K
Run as receiver
Listen port 1234
RX buffer 1024 bytes
vsock buffer 262144 bytes
SO_RCVLOWAT 1 bytes
total bytes received: 104857600
rx performance: 0.007653 Gbits/s
total time in 'read()': 0.582053 sec
average time in 'read()': 5684.060547 ns
POLLIN wakeups: 102401
```

Whether in the 1MB short connection burst transmission or the 100MB continuous throughput test, the throughput of Asterinas is far lower than the Linux benchmark, with a performance gap of approximately 115 to 200 times between the two.

**Test2**

In the two-way communication test, I constructed a latency test based on the Ping-pong model. This tool establishes a connection between the Guest and the Host and conducts 10,000 serial message round trips. By calculating the time consumption of each interaction, we output the average value (Avg), maximum value (Max), and minimum value (Min) of RTT to evaluate the performance of Asterinas in handling bidirectional control flow.

**Linux**
RTT min: 45.570 us
RTT max: 268.221 us
RTT avg: 63.714 us

**Asterinas**
RTT min: 1295.851 us
RTT max: 17433.100 us
RTT avg: 2963.942 us

The test show a drastic disparity in response times. While Linux maintains a tight latency profile with an average RTT of 63.71 μs, Asterinas exhibits an average RTT of 2963.94 μs, representing a 46x slowdown.

### Enhancement Description

The goal is to elevate the Asterinas Vsock subsystem to achieve functional parity with the Linux kernel and address critical architectural bottlenecks. This enhancement is necessary to support complex, production-grade applications and ensure high-throughput inter-VM communication.

1. Optimize Functional: Filling the gaps in the current implementation to ensure protocol compliance and API compatibility.
Fix Credit-Based Flow Control: Implement the missing RX credit update mechanism. The Guest must proactively send OP_CREDIT_UPDATE packets upon consuming data to prevent the Host from stalling transmission due to false-positive congestion.
Implement missing setsockopt flags to support advanced application configurations.
Specifically, support SO_VM_SOCKETS_BUFFER_MAX_SIZE, SO_VM_SOCKETS_BUFFER_SIZE, and related flags.Complex applications rely on these flags to tune buffer sizes for performance or memory constraints. Lack of support prevents such applications from running correctly on Asterinas. After supporting functionality, we can run more complex performance tests.
2. Optimize Performance：The test indicate that Asterinas lags significantly behind Linux. In the following text, I will explain several possible points for optimization.

### Motivation

Virtio-Vsock is the standard transport layer for modern virtualization use cases, including AWS Firecracker, Kata Containers, and Confidential Computing Enclaves (e.g., communicating with host agents). To position Asterinas as a viable Guest OS for microVMs or secure enclaves, the Vsock subsystem must support high-throughput, low-latency inter-domain communication.

### Possible Implementations

Several cases regarding functional issues need to be addressed on a case-by-case basis. For instance, regarding the issue of credit, Needed in https://github.com/asterinas/asterinas/blob/1723e5d9440b02d70ff932726f609cb697496d3f/kernel/src/net/socket/vsock/stream/socket.rs#L94C5-L94C17, send a credit data packet to the sender.
For the compatibility of the protocol, it is also necessary to analyze which new functions need to be added.

Apart from functional issues, there are many areas in performance that can be optimized. Here is an example:

https://github.com/asterinas/asterinas/blob/1723e5d9440b02d70ff932726f609cb697496d3f/kernel/src/net/socket/vsock/common.rs#L23-L33

https://github.com/asterinas/asterinas/blob/1723e5d9440b02d70ff932726f609cb697496d3f/kernel/src/net/socket/vsock/common.rs#L194-L204
The `VsockSpace` structure manages the underlying Virtio device through a global `Arc<SpinLock<SocketDevice>>`. This means that no matter how many active Socket connections or parallel Vcpus exist in the system, all data sending requests (TX path) will eventually converge to the contention for this global exclusive lock. The explicit call of `driver.disable_irq().lock()` in the code path not only forces the serialization of all concurrent I/O operations, but also disables local interrupts during the lock holding period.
And the entire send process is locked by a lock, `driver.send` internally involves the operation of writing this buffer to the VirtIO queue. Therefore, this time-consuming process completely occupies the global lock, causing other threads to wait for the lock for a longer time.

`let mut buffer = vec![0u8; reader.sum_lens()];`

The above-mentioned code will also bring about additional data replication.

Redundant data replication and inefficient global locks need to be avoided on the path of Vsock.

### Additional Context

No

### PR DESCRIPTION
**Pull request by lrh2000**
This PR removes the old vsock implementation and reimplements it entirely.

#### The new implementation features:
 1. Better architecture. It is similar to our TCP/IP stack.
   - `kernel/comps/virtio/src/device/socket` (an equivalent to `kernel/comps/virtio/src/device/network`):
```rust
//! Basic virtio-vsock device support.
//!
//! This module implements the transmit and receive primitives of a virtio-vsock device, together
//! with the minimal queue management and callbacks required to drive the hardware. Higher layers
//! are responsible for protocol-level logic, such as interpreting received packet operations and
//! managing connection state.
//!
//! For a quick start, look up the device using the [`get_device`] function, then send packets via
//! the transmit queue using the [`SocketDevice::lock_tx`] method and receive packets via the
//! receive queue using the [`SocketDevice::lock_rx`] method. Notifications for newly received
//! packets happen via the callback specified in the [`SocketDevice::init_rx_callback`] method,
//! which is called in the bottom half.
```
   - `kernel/src/net/socket/vsock/transport` (an equivalent to `kernel/libs/aster-bigtcp`):
```rust
//! The virtio-vsock transport protocol.
//!
//! Built on top of the [`basic virtio-vsock device support`](`aster_virtio::device::socket`), this
//! module manages connections and listeners, handles connection establishment, data transfer, and
//! shutdown, and implements credit-based flow control plus I/O event checking and notification.
//! The socket layer is expected to build on these APIs to provide the user-visible socket
//! interface.
//!
//! For a quick start, bind to a port by creating a [`BoundPort`] instance.
//!  - To connect to a remote address, use the [`BoundPort::connect`] method and get a
//!    [`Connection`] instance. Data can be transmitted or received via the [`Connection::try_send`]
//!    and [`Connection::try_recv`] methods.
//!  - To listen to the local address, use the [`BoundPort::listen`] method and get a [`Listener`]
//!    instance. Incoming connections can be accepted via the [`Listener::try_accept`] method.
//!
//! Drop the [`BoundPort`], [`Connection`], or [`Listener`] instance will shut down the underlying
//! connection (if any) and release the resources.
```
   - `kernel/src/net/socket/vsock/stream` (an equivalent to `kernel/src/net/socket/ip/stream`): It implements the socket API via the `Socket` trait.
   - The socket state machine runs in the bottom half and appears to be the first user of our `Taskless` API.
 2. Better performance.
    - There are still gaps to achieve the Linux one. However, it is at least comparable. Fixes #2885.

| Scenario | Asterinas TX (Gbits/s) | Linux TX (Gbits/s) | Asterinas / Linux TX | Asterinas RX (Gbits/s) | Linux RX (Gbits/s) | Asterinas / Linux RX |
| --- | ---: | ---: | ---: | ---: | ---: | ---: |
| 1 MiB total, 1 KiB buffer | 1.403534 | 3.023200 | 46.43% | 1.150624 | 1.196811 | 96.14% |
| 100 MiB total, 1 KiB buffer | 2.919367 | 3.699530 | 78.91% | 2.885203 | 3.640355 | 79.26% |
 3. Fewer BUGs.
    - There are too many bugs in our previous implementations. However, I'm not sure if it's worth the effort to name them here.

#### There are also some known limitations:
 1. The `Connection::try_send`/`Connection::try_recv` implementation is ugly. However, given the limitations imposed by our `MultiRead`/`MultiWrite` traits, I don't have any better solutions.
```rust
        // We use a packet-pool approach here so a receive attempt either completes for the chosen
        // packets or leaves the receive queue unchanged.
        //
        // Otherwise, consider this case: we fully receive some packets, remove them from the
        // queue, and then hit `EFAULT` while receiving the next packet. That would create several
        // problems:
        // - We should not return `EFAULT`, because some bytes have already been received.
        // - We cannot safely return only the bytes from the fully received packets, because
        //   `writer` would then be left at the wrong position.
        // - We also cannot return the bytes from the fully received packets plus the partial bytes
        //   from the faulting packet, because `MultiWrite` does not report how many bytes were
        //   written before `EFAULT` occurred.
        //
        // TODO: Find a better way to report partially written bytes on fault so we can avoid
        // temporarily staging packets just to preserve correct receive semantics.
        let mut packet_pool = [const { None }; 8];
```
 2. Merge small packets.
   - Merge received small packets. I have no idea how to do this because we cannot write new bytes to a `DmaStream<FromDevice>`.
```rust
        // TODO: If the peer sends too many small packets, we'll exhaust a large amount of kernel
        // memory. We need to support merging small packets to avoid this.
```
   - Merge small packets to send. It need to be more complex in order to allow packets that are already queued to the device queue to be edited? An alternative, simpler way might be to count the entire packet size, even if the trailing space is not used, as the amount of space that will be occupied in the socket buffer.
```rust
        // TODO: If the user sends too many small packets, we'll exhaust a large amount of kernel
        // memory. We need to support merging small packets to avoid this.
```
 3. Support advanced features like socket options, control messages, e.t.c.
    - Currently, only `SO_ERROR` is supported.
 4. Support loopback vsock devices. This will be very helpful when writing tests. See below.
    - However, it is somewhat complex, mostly due to limitations in the DMA stream API (i.e., we cannot read from a TX packet, which is of type `DmaStream<ToDevice>`).
    - Additionally, we will need to address some issues with the lock order. Currently, we use the following order: `device RX -> sockets -> socket state -> device TX`. We need another lock to break the cycle if we have loopback devices.

#### I have made some regression tests. However, they are not currently included in this PR.
 - https://github.com/asterinas/asterinas/commit/ba66a3d2787e77f2c924c5ac0cf20644210ea18d adds [a framework](https://github.com/lrh2000/asterinas/blob/ba66a3d2787e77f2c924c5ac0cf20644210ea18d/test/initramfs/src/regression/network/vsock_common/README.md) that performs guest-host coordinated tests using vsock to send commands from the guest to the host.
 - https://github.com/asterinas/asterinas/commit/1aaa15e24702a6de8d6669820c1d8c8debbe71a0 adds `vsock_err` tests, which behave like [`tcp_err`](https://github.com/asterinas/asterinas/blob/9e961e07d414a44be3e8ccb82681fc9f79f9a3ba/test/initramfs/src/regression/network/tcp_err.c) tests, to verify the error behavior and corner cases of the vsock implementation. However, it communicates with the host vsock using the aforementioned framework instead of the loopback because we don't support the latter.

#### I do not currently include those tests in this PR because:
 - This PR is already quite large. I'm not sure if adding a new test framework to it is a good idea.
 - I don't know if the framework would be useful in other scenarios. Therefore, the motivation to add another complex framework is unclear to me.
 - I've been told that running vsock in the CI will result in environmental issues. Additionally, I have yet to create an automated script to run both the host server and the guest client. More effort is needed to enable these tests in CI.

### CODE REVIEW

File: kernel/comps/network/src/buffer.rs [hunk 1]
```diff
@@ -66,6 +63,46 @@ impl HasDaddr for TxBuffer {
...
 }
 
+pub struct TxBufferBuilder<H> {
+    segment: DmaSegment<ToDevice>,
+    nbytes: usize,
+    _phantom: PhantomData<H>,
+}
+
+impl<H: Pod> TxBufferBuilder<H> {
+    pub fn append<F>(&mut self, f: F) -> Result<usize>
```
Comment (StevenJiang1110) [inline kernel/comps/network/src/buffer.rs]: Naming `append` as `copy_payload`/`copy_packet` may be better. f may be better named as `copy_fn`.

But why not just let append a `VmReader` as a parameter? It should be simpler than a closure.

File: kernel/comps/virtio/src/device/socket/header.rs [hunk 2]
```diff
@@ -0,0 +1,123 @@
...
+
+//! Wire-format virtio-vsock headers and protocol enums.
+
+use bitflags::bitflags;
+use int_to_c_enum::TryFromInt;
+
+/// The socket type encoded in a virtio-vsock packet.
+#[derive(Debug, Clone, Copy, PartialEq, Eq, TryFromInt)]
+#[repr(u16)]
+pub enum VirtioVsockType {
```
Comment (StevenJiang1110) [inline kernel/comps/virtio/src/device/socket/header.rs:11]: According to our current requirements for attribute ordering, should derive always be placed last?

File: kernel/src/net/socket/vsock/transport/connection/recv.rs [hunk 3]
```diff
@@ -0,0 +1,205 @@
...
+    ) -> Result<usize> {
+        // We use a packet-pool approach here so a receive attempt either completes for the chosen
+        // packets or leaves the receive queue unchanged.
+        //
+        // Otherwise, consider this case: we fully receive some packets, remove them from the
+        // queue, and then hit `EFAULT` while receiving the next packet. That would create several
+        // problems:
+        // - We should not return `EFAULT`, because some bytes have already been received.
+        // - We cannot safely return only the bytes from the fully received packets, because
+        //   `writer` would then be left at the wrong position.
```
Comment (StevenJiang1110) [inline kernel/src/net/socket/vsock/transport/connection/recv.rs:32]: It looks like other socket implementations(Like TCP) may have the same issue — when a read fails, the writer is left at an unspecified position. This is actually documented behavior of the `MultiWrite` trait: the position is left unspecified if an `EFAULT` error occurs.

Do you think this is a serious concern? If so, we should consider fixing the `MultiWrite` APIs to return the actual number of bytes written even when an EFAULT occurs. (Though it can be a separate task)

One thing that still seems off to me is that even with the pool-based approach, this problem cannot be fully avoided — at line 50, we still call a method on MultiWrite, which can leave the position in an unspecified state.

File: kernel/src/net/socket/vsock/transport/connection/recv.rs [hunk 4]
```diff
@@ -0,0 +1,205 @@
...
+        let mut total_write_len = 0;
+
+        for (i, packet) in self.packets.iter().enumerate() {
+            let packet = packet.as_ref().unwrap();
+
+            let mut payload = packet.payload();
+            payload.skip(read_offset);
+
+            let write_len = writer.write(&mut payload)?;
+            read_offset += write_len;
```
Comment (StevenJiang1110) [inline kernel/src/net/socket/vsock/transport/connection/recv.rs]: Can line 81 be moved above line 86? If payload has no remaining data, there would be no need to update read_offset.

File: kernel/src/net/socket/vsock/transport/connection/shutdown.rs [hunk 5]
```diff
@@ -0,0 +1,82 @@
...
+        if !self.inner.is_usable() {
+            return;
+        }
+
+        self.shutdown_or_drop_common(SockShutdownCmd::SHUT_RDWR, true);
+    }
+}
+
+impl Connection {
+    fn shutdown_or_drop_common(&self, cmd: SockShutdownCmd, on_drop: bool) {
```
Comment (StevenJiang1110) [inline kernel/src/net/socket/vsock/transport/connection/shutdown.rs]: Having this method doesn't seem like a good idea. It conflates the logic of both shutdown and drop, while the internal implementation still needs to distinguish between the two cases. Ideally, a method named common should only contain logic that is truly shared between both paths — such as sending a RST and removing the connection.

File: kernel/src/net/socket/vsock/transport/connection/recv.rs [hunk 6]
```diff
@@ -0,0 +1,205 @@
...
+        let Some(packets) = self.pop_rx_packets(&mut packet_pool[..], max_bytes) else {
+            self.test_and_clear_error(conn)?;
+
+            if self.shutdown.local_read_closed || self.shutdown.peer_write_closed {
+                return Ok(None);
+            }
+            return_errno_with_message!(Errno::EAGAIN, "the receive buffer is empty");
+        };
+
+        Ok(Some(packets))
```
Comment (StevenJiang1110) [inline kernel/src/net/socket/vsock/transport/connection/recv.rs]: Since the `else` branch is longer than the `Some` branch, using `if let` here could help reduce the indentation level:

```rust
if let Some(packets) = self.pop_rx_packets(&mut packet_pool[..], max_bytes) {
    return Ok(Some(packets));
}

self.test_and_clear_error(conn)?;

if self.shutdown.local_read_closed || self.shutdown.peer_write_closed {
    return Ok(None);
}
return_errno_with_message!(Errno::EAGAIN, "the receive buffer is empty");

```

File: kernel/src/net/socket/vsock/transport/port.rs [hunk 7]
```diff
@@ -0,0 +1,169 @@
...
+        if next_port < Self::EPHEMERAL_PORT_START || next_port == VMADDR_PORT_ANY {
+            next_port = Self::EPHEMERAL_PORT_START;
+        }
+        next_port
+    }
+}
+
+impl BoundPort {
+    /// Binds `addr` and returns the resulting port lease.
+    pub(in crate::net::socket::vsock) fn new_bind(addr: VsockSocketAddr) -> Result<Self> {
```
Comment (StevenJiang1110) [inline kernel/src/net/socket/vsock/transport/port.rs]: Name it `new_exclusive` to keep it symmetric with `new_shared`? Or if we may support `reuse_addr` in the future, add a TODO for it?

File: kernel/src/net/socket/vsock/transport/listener.rs [hunk 8]
```diff
@@ -0,0 +1,128 @@
...
+            pollee,
+            backlog: AtomicUsize::new(backlog.min(MAX_BACKLOG)),
+            num_conns: AtomicUsize::new(0),
+            incoming_conns: SpinLock::new(VecDeque::new()),
+        })
+    }
+
+    pub(super) fn is_full(&self) -> bool {
+        // Race conditions don't matter here.
+        self.num_conns.load(Ordering::Relaxed) > self.backlog.load(Ordering::Relaxed)
```
Comment (StevenJiang1110) [inline kernel/src/net/socket/vsock/transport/listener.rs:80]: Here should be `>=` instead of `>`?

File: kernel/comps/virtio/src/device/socket/mod.rs [hunk 9]
```diff
@@ -1,73 +1,148 @@
...
+        event_taskless: Taskless::new(process_pending_event),
+    });
 }
 
-pub fn get_device(str: &str) -> Option<Arc<SpinLock<SocketDevice>>> {
-    let lock = VSOCK_DEVICE_TABLE.get().unwrap().disable_irq().lock();
-    let (_, device) = lock.get(str)?;
-    Some(device.clone())
+/// Registers a virtio-vsock device under `name`.
+pub fn register_device(name: String, device: Arc<SocketDevice>) {
```
Comment (StevenJiang1110) [inline kernel/comps/virtio/src/device/socket/mod.rs]: The `pub` can be removed?

File: kernel/src/net/socket/vsock/addr.rs [hunk 10]
```diff
@@ -1,36 +1,34 @@
 // SPDX-License-Identifier: MPL-2.0
 
-use aster_virtio::device::socket::header::VsockDeviceAddr;
-
 use crate::{net::socket::util::SocketAddr, prelude::*};
 
-#[derive(Clone, Copy, Debug, Default, Eq, Ord, PartialEq, PartialOrd)]
+pub const VMADDR_CID_ANY: u32 = u32::MAX;
```
Comment (StevenJiang1110) [inline kernel/src/net/socket/vsock/addr.rs]: The constants can be `pub(super)`?

File: kernel/src/net/socket/vsock/transport/connection/mod.rs [hunk 11]
```diff
@@ -0,0 +1,450 @@
...
+        let mut state = self.state.lock();
+
+        if state.phase == Phase::Connecting {
+            state.active_rst(self);
+            return_errno_with_message!(Errno::ENOTCONN, "the connection is not established");
+        }
+
+        state.update_peer_credit(self, header);
+
+        state.credit.credit_request_pending = false;
```
Comment (StevenJiang1110) [inline kernel/src/net/socket/vsock/transport/connection/mod.rs:334]: Currently, the `credit_request_pending` bit is only cleared in response to a `CreditUpdate` message. However, other operations such as `on_rw` can also update the peer credit. Should the bit-clearing logic be moved into `update_peer_credit` instead?

File: kernel/src/net/socket/vsock/transport/connection/mod.rs [hunk 12]
```diff
@@ -0,0 +1,450 @@
...
+
+        if notify_events.is_empty() {
+            return false;
+        }
+
+        let local_fully_closed =
+            state.shutdown.local_read_closed && state.shutdown.local_write_closed;
+        let peer_fully_closed = state.shutdown.peer_read_closed && state.shutdown.peer_write_closed;
+
+        let should_remove = if local_fully_closed && peer_fully_closed {
```
Comment (StevenJiang1110) [inline kernel/src/net/socket/vsock/transport/connection/mod.rs]: This was flagged by Codex:

Linux removes the socket upon remote shutdown without checking the local state. Should we adopt the same behavior?

https://elixir.bootlin.com/linux/v6.19/source/net/vmw_vsock/virtio_transport_common.c#L1438

**Review by StevenJiang1110 — COMMENTED** [review]
Thanks for the great work — this is truly excellent and the PR looks really good to me!

I think it's acceptable to skip the regression tests for now, given that this PR is already quite large. I have validated the changes using Kata.

File: kernel/src/net/socket/vsock/transport/connection/recv.rs (hunk 3 above)
Comment (lrh2000) [reply kernel/src/net/socket/vsock/transport/connection/recv.rs:32]: > we still call a method on MultiWrite, which can leave the position in an unspecified state.

The problem is that **if we return success**, then the writer cannot be left in an unspecified position.

However, I don't think this implementation is problematic because we will always return failure if the writer reports one. Only then will it be left in an unspecified position.

> Do you think this is a serious concern? If so, we should consider fixing the `MultiWrite` APIs to return the actual number of bytes written even when an EFAULT occurs. (Though it can be a separate task)

I am not sure. https://github.com/asterinas/asterinas/pull/2951#discussion_r2999868223 provides more information. We need a specification for the `read`/`write` operations to indicate when the `reader`/`writer`'s position is specified, or explicitly states that it's unspecified regardless of the result.

File: kernel/comps/network/src/buffer.rs (hunk 1 above)
Comment (lrh2000) [reply kernel/comps/network/src/buffer.rs]: > Naming `append` as `copy_payload`/`copy_packet` may be better. f may be better named as `copy_fn`.

Renamed.

> But why not just let append a `VmReader` as a parameter? It should be simpler than a closure.

It is not possible. How to deal with `&dyn MulitRead`?

File: kernel/src/net/socket/vsock/transport/listener.rs (hunk 8 above)
Comment (lrh2000) [reply kernel/src/net/socket/vsock/transport/listener.rs:80]: It is Linux behavior. I have updated the comment:
```rust
        // Race conditions don't matter here. We use `>` instead of `>=` because Linux allows to
        // have `backlog + 1` connections in the backlog queue.
        self.num_conns.load(Ordering::Relaxed) > self.backlog.load(Ordering::Relaxed)
```

File: kernel/src/net/socket/vsock/transport/connection/mod.rs (hunk 11 above)
Comment (lrh2000) [reply kernel/src/net/socket/vsock/transport/connection/mod.rs:334]: From [virtio-spec](https://docs.oasis-open.org/virtio/virtio/v1.3/csd01/virtio-v1.3-csd01.pdf):
>  Sending the VIRTIO_VSOCK_OP_CREDIT_REQUEST packet queries how much buffer space is available. The reply to this query is a VIRTIO_VSOCK_OP_CREDIT_UPDATE packet.

It does not say that the reply can be suppressed, even though other packets can also update the credit. Therefore, I assume that receiving a `CREDIT_UPDATE` reply is mandatory.

File: kernel/src/net/socket/vsock/transport/connection/mod.rs (hunk 12 above)
Comment (lrh2000) [reply kernel/src/net/socket/vsock/transport/connection/mod.rs]: I tried to follow this Linux behavior, which means that we will close the connection, remove it from the table, and send an RST _if and only_ if the peer endpoint shuts down its read and write abilities.

Therefore, we will (almost) never do so in shutdown/drop. The only exception being when we drop a connection that is still in the connecting phase, where we need to send a RST and remove it from the table. It helps to resolve your previous comment https://github.com/asterinas/asterinas/pull/3122#discussion_r3077010952.

**Comment by lrh2000** [comment]
This is the range diff for the force push. I haven't found a way to get GitHub to render it. `git range-diff` is more readable because it highlights the range-diff.
```
git range-diff 9e961e07d414a44be3e8ccb82681fc9f79f9a3ba..5ed5d1d70e358698148cdfa4cb5ae1ab896bf11d main..HEAD
```

In addition to addressing the above comments, Codex caught some additional bugs. I also manually review the code for other fixes.

<details>
<summary> range diff </summary>

```
1:  908034806 ! 1:  0e62b2475 Add `TxBufferBuilder`
    @@ kernel/comps/network/src/buffer.rs: pub struct TxBuffer {
     +        let mut builder = Self::new_builder::<H>(pool)?;
     +
     +        builder
    -+            .append(|mut writer| {
    ++            .copy_packet(|mut writer| {
     +                assert!(writer.avail() >= packet.len());
     +                Ok(writer.write(&mut VmReader::from(packet)))
     +            })
    @@ kernel/comps/network/src/buffer.rs: impl HasDaddr for TxBuffer {
     +}
     +
     +impl<H: Pod> TxBufferBuilder<H> {
    -+    pub fn append<F>(&mut self, f: F) -> Result<usize>
    ++    pub fn copy_packet<F>(&mut self, copy_fn: F) -> Result<usize>
     +    where
     +        F: FnOnce(VmWriter<Infallible>) -> Result<usize>,
     +    {
     +        let mut writer = self.segment.writer().unwrap();
     +        writer.skip(self.nbytes);
     +
    -+        let bytes_written = f(writer)?;
    ++        let bytes_written = copy_fn(writer)?;
     +        self.nbytes += bytes_written;
     +        debug_assert!(self.nbytes <= self.segment.size());
     +
    @@ kernel/comps/virtio/src/device/socket/device.rs: impl SocketDevice {
     +            TxBuffer::new(header, buffer, tx_pool).unwrap()
              };
      
    -         let token = self.send_queue.add_dma_buf(&[&tx_buffer], &[])?;
    +         let token = self.send_queue.add_input_bufs(&[&tx_buffer])?;
2:  f98f7204c = 2:  e7b2112f2 Remove locks from `Taskless`
3:  ea2e66cdc ! 3:  e8d41fe4e Remove vsock code entirely
    @@ kernel/comps/virtio/src/device/socket/device.rs (deleted)
     -        for i in 0..QUEUE_SIZE {
     -            let rx_pool = RX_BUFFER_POOL.get().unwrap();
     -            let rx_buffer = RxBuffer::new(size_of::<VirtioVsockHdr>(), rx_pool).unwrap();
    --            let token = recv_queue.add_dma_buf(&[], &[&rx_buffer])?;
    +-            let token = recv_queue.add_output_bufs(&[&rx_buffer])?;
     -            assert_eq!(i, token);
     -            assert_eq!(rx_buffers.put(rx_buffer) as u16, i);
     -        }
    @@ kernel/comps/virtio/src/device/socket/device.rs (deleted)
     -            TxBuffer::new(header, buffer, tx_pool).unwrap()
     -        };
     -
    --        let token = self.send_queue.add_dma_buf(&[&tx_buffer], &[])?;
    +-        let token = self.send_queue.add_input_bufs(&[&tx_buffer])?;
     -
     -        if self.send_queue.should_notify() {
     -            self.send_queue.notify();
    @@ kernel/comps/virtio/src/device/socket/device.rs (deleted)
     -
     -    /// Add a used rx buffer to recv queue,@index is only to check the correctness
     -    fn add_rx_buffer(&mut self, rx_buffer: RxBuffer, index: u16) -> Result<(), SocketError> {
    --        let token = self.recv_queue.add_dma_buf(&[], &[&rx_buffer])?;
    +-        let token = self.recv_queue.add_output_bufs(&[&rx_buffer])?;
     -        assert_eq!(index, token);
     -        assert!(self.rx_buffers.put_at(token as usize, rx_buffer).is_none());
     -        if self.recv_queue.should_notify() {
4:  d0bd4d9d2 ! 4:  635a8a83f Reimplement vsock devices
    @@ kernel/comps/virtio/src/device/socket/config.rs (new)
     +use crate::transport::{ConfigManager, VirtioTransport};
     +
     +#[repr(C)]
    -+#[derive(Debug, Clone, Copy, Pod)]
    ++#[derive(Clone, Copy, Debug, Pod)]
     +pub(super) struct VirtioVsockConfig {
     +    guest_cid_low: u32,
     +    guest_cid_high: u32,
    @@ kernel/comps/virtio/src/device/socket/config.rs (new)
     +    }
     +
     +    pub(super) fn read_guest_cid(config_manager: &ConfigManager<Self>) -> u64 {
    ++        // We have no way to read the 64-bit CID atomically because the virtio specification says
    ++        // "Drivers MUST NOT assume reads from fields greater than 32 bits wide are atomic." For
    ++        // now, race conditions do not matter because the high 32 bits are always zeros and are
    ++        // reserved. Even if the CID changes concurrently, we should also receive a `TransportReset`
    ++        // event so we will reload the CID later.
     +        let guest_cid_low = config_manager
     +            .read_once::<u32>(offset_of!(Self, guest_cid_low))
    -+            .unwrap_or(0);
    ++            .unwrap();
     +        let guest_cid_high = config_manager
     +            .read_once::<u32>(offset_of!(Self, guest_cid_high))
    -+            .unwrap_or(0);
    ++            .unwrap();
     +        (u64::from(guest_cid_high) << 32) | u64::from(guest_cid_low)
     +    }
     +}
    @@ kernel/comps/virtio/src/device/socket/device.rs (new)
     +        transport.finish_init();
     +        drop(transport);
     +
    ++        // Reload the guest CID after initialization to prevent race conditions if the CID changes
    ++        // at the same time.
    ++        device.reload_guest_id();
    ++
     +        super::register_device(DEVICE_NAME.to_string(), device);
     +        Ok(())
     +    }
    @@ kernel/comps/virtio/src/device/socket/device.rs (new)
     +
     +        if let Some(callback) = self.event_callback.get() {
     +            (callback)();
    ++        } else {
    ++            // Reload the CID, even if the callback is not yet available. Otherwise, the callback is
    ++            // expected to do so.
    ++            self.reload_guest_id();
     +        }
     +    }
     +
    @@ kernel/comps/virtio/src/device/socket/header.rs (new)
     +use int_to_c_enum::TryFromInt;
     +
     +/// The socket type encoded in a virtio-vsock packet.
    -+#[derive(Debug, Clone, Copy, PartialEq, Eq, TryFromInt)]
     +#[repr(u16)]
    ++#[derive(Clone, Copy, Debug, Eq, PartialEq, TryFromInt)]
     +pub enum VirtioVsockType {
     +    /// Identifies a byte-stream vsock connection.
     +    Stream = 1,
     +}
     +
     +/// The operation encoded in a virtio-vsock packet.
    -+#[derive(Debug, Clone, Copy, PartialEq, Eq, TryFromInt)]
     +#[repr(u16)]
    ++#[derive(Clone, Copy, Debug, Eq, PartialEq, TryFromInt)]
     +pub enum VirtioVsockOp {
     +    /// Starts a new connection.
     +    Request = 1,
    @@ kernel/comps/virtio/src/device/socket/header.rs (new)
     +
     +/// The common header of a virtio-vsock packet.
     +#[repr(C, packed)]
    -+#[derive(Debug, Clone, Copy, Pod)]
    ++#[derive(Clone, Copy, Debug, Pod)]
     +pub struct VirtioVsockHdr {
     +    /// The source CID.
     +    pub src_cid: u64,
    @@ kernel/comps/virtio/src/device/socket/header.rs (new)
     +}
     +
     +/// The event identifier carried by the transport event queue.
    -+#[derive(Debug, Clone, Copy, PartialEq, Eq, TryFromInt)]
     +#[repr(u32)]
    ++#[derive(Clone, Copy, Debug, Eq, PartialEq, TryFromInt)]
     +pub(super) enum VirtioVsockEventId {
     +    /// Indicates that the transport has been reset.
     +    TransportReset = 0,
     +}
     +
     +/// The payload stored in the transport event virtqueue.
    -+#[derive(Debug, Clone, Copy, Pod)]
     +#[repr(C)]
    ++#[derive(Clone, Copy, Debug, Pod)]
     +pub(super) struct VirtioVsockEvent {
     +    /// The encoded [`VirtioVsockEventId`].
     +    pub id: u32,
    @@ kernel/comps/virtio/src/device/socket/mod.rs (new)
     +}
     +
     +/// Registers a virtio-vsock device under `name`.
    -+pub fn register_device(name: String, device: Arc<SocketDevice>) {
    ++fn register_device(name: String, device: Arc<SocketDevice>) {
     +    let component = COMPONENT.get().unwrap();
     +    component.devices.lock().insert(name, device);
     +}
    @@ kernel/comps/virtio/src/device/socket/packet.rs (new)
     +    /// The maximum payload bytes that fit in one TX packet.
     +    pub const MAX_NBYTES: usize = TX_BUFFER_LEN - size_of::<VirtioVsockHdr>();
     +
    -+    /// Appends payload bytes produced by `f`.
    -+    pub fn append<F>(&mut self, f: F) -> Result<usize>
    ++    /// Copies payload bytes to the packet via `copy_fn`.
    ++    pub fn copy_payload<F>(&mut self, copy_fn: F) -> Result<usize>
     +    where
     +        F: FnOnce(VmWriter<Infallible>) -> Result<usize>,
     +    {
    -+        self.0.append(f)
    ++        self.0.copy_packet(copy_fn)
     +    }
     +
     +    /// Returns the payload length accumulated so far.
    @@ kernel/comps/virtio/src/device/socket/queue.rs (new)
     +                completion.on_pending_submit();
     +            }
     +
    -+            let token = self.queue.add_dma_buf(&[packet.inner()], &[]).unwrap();
    ++            let token = self.queue.add_input_bufs(&[packet.inner()]).unwrap();
     +
     +            debug_assert!(self.inflight[token as usize].is_none());
     +            self.inflight[token as usize] = Some(packet);
    @@ kernel/comps/virtio/src/device/socket/queue.rs (new)
     +            });
     +        }
     +
    -+        let token = self.queue.add_dma_buf(&[packet.inner()], &[]).unwrap();
    ++        let token = self.queue.add_input_bufs(&[packet.inner()]).unwrap();
     +
     +        debug_assert!(self.inflight[token as usize].is_none());
     +        self.inflight[token as usize] = Some(packet);
    @@ kernel/comps/virtio/src/device/socket/queue.rs (new)
     +    /// Runs when the associated packet moves from the pending queue to the inflight queue.
     +    ///
     +    /// This method is called while the transmit queue lock is held.
    -+    fn on_pending_submit(self: Box<Self>) {}
    ++    fn on_pending_submit(self: Box<Self>);
     +}
     +
     +/// A guard holding a packet returned from [`TxQueue::try_send`] for deferred submission.
    @@ kernel/comps/virtio/src/device/socket/queue.rs (new)
     +        let mut buffers = SlotVec::new();
     +        for index in 0..Self::QUEUE_SIZE {
     +            let buffer = RxPacket::new().expect("allocating recv packet fails");
    -+            let token = queue.add_dma_buf(&[], &[buffer.inner()]).unwrap();
    ++            let token = queue.add_output_bufs(&[buffer.inner()]).unwrap();
     +            assert_eq!(token, index);
     +            assert_eq!(buffers.put(buffer) as u16, index);
     +        }
    @@ kernel/comps/virtio/src/device/socket/queue.rs (new)
     +        }
     +        if self.pending.is_none() {
     +            ostd::warn!("allocating recv packet fails");
    ++            // FIXME: We should find ways to address the error to prevent the receive queue from
    ++            // getting stuck.
     +            return None;
     +        }
     +
    @@ kernel/comps/virtio/src/device/socket/queue.rs (new)
     +        let packet = self.buffers.remove(token as usize).unwrap();
     +
     +        let new_packet = self.pending.take().unwrap();
    -+        let new_token = self.queue.add_dma_buf(&[], &[new_packet.inner()]).unwrap();
    ++        let new_token = self.queue.add_output_bufs(&[new_packet.inner()]).unwrap();
     +        debug_assert_eq!(new_token, token);
     +        self.buffers.put_at(new_token as usize, new_packet);
     +
    @@ kernel/comps/virtio/src/device/socket/queue.rs (new)
     +            .expect("creating event queue fails");
     +
     +        let buffer = DmaStream::alloc_uninit(1, false).expect("allocating event buffer fails");
    -+        let token = queue.add_dma_buf(&[], &[&buffer]).unwrap();
    ++        let token = queue.add_output_bufs(&[&buffer]).unwrap();
     +        debug_assert_eq!(token, 0);
     +
     +        if queue.should_notify() {
    @@ kernel/comps/virtio/src/device/socket/queue.rs (new)
     +            .unwrap();
     +        let event_id = VirtioVsockEventId::try_from(event.id).ok();
     +
    -+        let token = self.queue.add_dma_buf(&[], &[&self.buffer]).unwrap();
    ++        let token = self.queue.add_output_bufs(&[&self.buffer]).unwrap();
     +        debug_assert_eq!(token, 0);
     +
    ++        if self.queue.should_notify() {
    ++            self.queue.notify();
    ++        }
    ++
     +        event_id
     +    }
     +}
5:  2246db31a ! 5:  232dd1dab Reimplement vsock protocol
    @@ kernel/src/net/socket/vsock/transport/conn_id.rs (new)
     +
     +use crate::net::socket::vsock::{VsockSocketAddr, transport::BoundPort};
     +
    -+#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
    ++#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd)]
     +pub(super) struct ConnId {
     +    pub(super) local_cid: u64,
     +    pub(super) peer_cid: u64,
    @@ kernel/src/net/socket/vsock/transport/connection/mod.rs (new)
     +    timer: Option<TimerState>,
     +}
     +
    -+#[derive(Debug, Clone, Copy, PartialEq, Eq)]
    ++#[derive(Clone, Copy, Debug, Eq, PartialEq)]
     +enum Phase {
     +    /// Represents the initial state of a newly created connection.
     +    ///
    @@ kernel/src/net/socket/vsock/transport/connection/mod.rs (new)
     +
     +    /// Represents the initial state of an accepted connection, or the state
     +    /// reached from `Connecting` when the connection request succeeds.
    ++    ///
    ++    /// INVARIANT: In this state, the peer endpoint is _NOT_ fully closed.
     +    Connected,
     +
     +    /// Represents the state reached from `Connected` when the socket is closed
     +    /// locally, but the peer has not reset the connection.
     +    ///
     +    /// INVARIANT: In this state, the local endpoint is fully closed; that is,
    -+    /// both `local_write_closed` and `local_read_closed` are `true`.
    ++    /// both `local_write_closed` and `local_read_closed` are `true`. The peer
    ++    /// endpoint is _NOT_ fully closed.
     +    Closing,
     +
     +    /// Represents the state reached from `Connected` or `Closing` when the peer
    @@ kernel/src/net/socket/vsock/transport/connection/mod.rs (new)
     +            return false;
     +        }
     +
    -+        let local_fully_closed =
    -+            state.shutdown.local_read_closed && state.shutdown.local_write_closed;
    ++        // Remove the connection from the table once the peer has fully shut down. See the Linux
    ++        // commit for the reason:
    ++        // <https://github.com/torvalds/linux/commit/3a5cc90a4d1756072619fe511d07621bdef7f120>
     +        let peer_fully_closed = state.shutdown.peer_read_closed && state.shutdown.peer_write_closed;
    -+
    -+        let should_remove = if local_fully_closed && peer_fully_closed {
    ++        let should_remove = if peer_fully_closed {
     +            state.phase = Phase::Closed;
     +            let _ = state.send_packet(self, VirtioVsockOp::Rst, 0);
     +            true
    @@ kernel/src/net/socket/vsock/transport/connection/mod.rs (new)
     +                // Linux behavior.
     +                //
     +                // Note that Linux does report `ECONNRESET` in the active path (e.g., when the CID
    -+                // changes). Our approach is more aggressive because we also include many protocol
    -+                // errors that should not occur if the peer is functioning properly according to the
    -+                // specification.
    ++                // changes).
    ++                //
    ++                // FIXME: Our approach is more aggressive because we report `ECONNRESET` for many
    ++                // protocol errors. In contrast, Linux only reports `EPROTO` in some cases and does
    ++                // not necessarily cause the connection to be reset.
     +                self.error = is_active.then_some(Error::with_message(
     +                    Errno::ECONNRESET,
     +                    "the connection is reset",
    @@ kernel/src/net/socket/vsock/transport/connection/recv.rs (new)
     +            return Ok(0);
     +        };
     +
    ++        // Packets can only be received from a `&mut connection`. Therefore, releasing the state
    ++        // lock does not cause race conditions. We need to release the lock in order to copy to
    ++        // userspace.
     +        let result = packets.copy_to_userspace(writer);
     +        let recv_len = *result.as_ref().unwrap_or(&0);
     +
    @@ kernel/src/net/socket/vsock/transport/connection/recv.rs (new)
     +            payload.skip(read_offset);
     +
     +            let write_len = writer.write(&mut payload)?;
    -+            read_offset += write_len;
     +            total_write_len += write_len;
     +
     +            if payload.has_remain() {
    ++                read_offset += write_len;
    ++
     +                self.skip_packets(i);
     +                self.read_offset = read_offset;
     +                return Ok(total_write_len);
    @@ kernel/src/net/socket/vsock/transport/connection/recv.rs (new)
     +        packet_pool: &'a mut [Option<RxPacket>],
     +        max_bytes: usize,
     +    ) -> Result<Option<PoppedRxPackets<'a>>> {
    -+        let Some(packets) = self.pop_rx_packets(&mut packet_pool[..], max_bytes) else {
    -+            self.test_and_clear_error(conn)?;
    ++        if max_bytes != 0
    ++            && let Some(packets) = self.pop_rx_packets(&mut packet_pool[..], max_bytes)
    ++        {
    ++            return Ok(Some(packets));
    ++        }
     +
    -+            if self.shutdown.local_read_closed || self.shutdown.peer_write_closed {
    -+                return Ok(None);
    -+            }
    -+            return_errno_with_message!(Errno::EAGAIN, "the receive buffer is empty");
    -+        };
    ++        self.test_and_clear_error(conn)?;
    ++
    ++        if max_bytes == 0 || self.shutdown.local_read_closed || self.shutdown.peer_write_closed {
    ++            return Ok(None);
    ++        }
     +
    -+        Ok(Some(packets))
    ++        return_errno_with_message!(Errno::EAGAIN, "the receive buffer is empty");
     +    }
     +
     +    fn pop_rx_packets<'a>(
    @@ kernel/src/net/socket/vsock/transport/connection/send.rs (new)
     +        reader: &mut dyn MultiRead,
     +        _flags: SendRecvFlags,
     +    ) -> Result<usize> {
    -+        let max_bytes = reader.sum_lens();
    -+        if max_bytes == 0 {
    -+            return Ok(0);
    -+        }
    -+
     +        // See the comments in `try_recv` to know why we use a packet-pool approach here.
     +        let mut packet_pool = [const { None }; 8];
     +
    -+        let num_bytes = self.alloc_send_buffers(&mut packet_pool[..], max_bytes)?;
    ++        let num_bytes = self.alloc_send_buffers(&mut packet_pool[..], reader.sum_lens())?;
    ++        if num_bytes == 0 {
    ++            return Ok(0);
    ++        }
     +
     +        // TODO: If the user sends too many small packets, we'll exhaust a large amount of kernel
     +        // memory. We need to support merging small packets to avoid this.
     +
    ++        // Packets can only be sending to a `&mut connection`. Therefore, releasing the state
    ++        // lock does not cause race conditions. We need to release the lock in order to copy from
    ++        // userspace.
     +        Self::copy_to_send_buffers(&mut packet_pool[..], reader, num_bytes)?;
     +
     +        self.build_and_send_tx_packets(&mut packet_pool[..])?;
    @@ kernel/src/net/socket/vsock/transport/connection/send.rs (new)
     +            return_errno_with_message!(Errno::EPIPE, "the connection is closed for writing");
     +        }
     +
    ++        if max_bytes == 0 {
    ++            return Ok(0);
    ++        }
    ++
     +        let buffer_bytes = self.inner.available_tx_bytes.load(Ordering::Relaxed);
     +        if buffer_bytes == 0 {
     +            return_errno_with_message!(Errno::EAGAIN, "the pending queue is full");
    @@ kernel/src/net/socket/vsock/transport/connection/send.rs (new)
     +            }
     +
     +            let packet_mut = packet_opt.as_mut().unwrap();
    -+            let bytes_written = packet_mut.append(|mut writer| {
    ++            let bytes_written = packet_mut.copy_payload(|mut writer| {
     +                writer.limit(remaining_bytes);
     +                Ok(reader.read(&mut writer)?)
     +            })?;
    @@ kernel/src/net/socket/vsock/transport/connection/send.rs (new)
     +    bytes: usize,
     +}
     +
    -+impl TxCompletion for ReleasePendingBytes {}
    -+
    -+impl Drop for ReleasePendingBytes {
    -+    fn drop(&mut self) {
    ++impl TxCompletion for ReleasePendingBytes {
    ++    fn on_pending_submit(self: Box<Self>) {
     +        self.connection
     +            .available_tx_bytes
     +            .fetch_add(self.bytes, Ordering::Relaxed);
    @@ kernel/src/net/socket/vsock/transport/connection/shutdown.rs (new)
     +    events::IoEvents,
     +    net::socket::{
     +        util::SockShutdownCmd,
    -+        vsock::transport::{Connection, DEFAULT_CLOSE_TIMEOUT, connection::Phase},
    ++        vsock::transport::{
    ++            Connection, DEFAULT_CLOSE_TIMEOUT,
    ++            connection::{ConnectionInner, ConnectionState, Phase},
    ++        },
     +    },
     +    prelude::*,
     +};
     +
     +impl Connection {
     +    /// Applies a local half-close described by `cmd`.
    ++    ///
    ++    /// This method should only be called after the connect attempt has successfully finished.
     +    pub(in crate::net::socket::vsock) fn shutdown(&self, cmd: SockShutdownCmd) -> Result<()> {
    -+        self.shutdown_or_drop_common(cmd, false);
    ++        let notify_events = {
    ++            let mut state = self.inner.state.lock();
    ++            debug_assert_ne!(state.phase, Phase::Connecting);
    ++            state.shutdown(&self.inner, cmd)
    ++        };
    ++
    ++        self.inner.pollee.notify(notify_events);
    ++
     +        Ok(())
     +    }
     +}
    @@ kernel/src/net/socket/vsock/transport/connection/shutdown.rs (new)
     +            return;
     +        }
     +
    -+        self.shutdown_or_drop_common(SockShutdownCmd::SHUT_RDWR, true);
    ++        let mut state = self.inner.state.lock();
    ++
    ++        match state.phase {
    ++            Phase::Connecting => {
    ++                state.active_rst(&self.inner);
    ++                drop(state);
    ++
    ++                // Note that we must release the socket state lock before calling
    ++                // `remove_connection`.
    ++                let vsock_space = self.inner.bound_port.vsock_space();
    ++                vsock_space.remove_connection(&self.inner);
    ++            }
    ++            Phase::ConnectFailed => {}
    ++            Phase::Connected | Phase::Closing => {
    ++                // The `Closing` phase is only set in `drop`.
    ++                debug_assert_eq!(state.phase, Phase::Connected);
    ++
    ++                // No need to notify events since we are in `drop`.
    ++                let _ = state.shutdown(&self.inner, SockShutdownCmd::SHUT_RDWR);
    ++
    ++                state.phase = Phase::Closing;
    ++                state.arm_timeout(&self.inner, DEFAULT_CLOSE_TIMEOUT);
    ++            }
    ++            Phase::Closed => {}
    ++        }
     +    }
     +}
     +
    -+impl Connection {
    -+    fn shutdown_or_drop_common(&self, cmd: SockShutdownCmd, on_drop: bool) {
    -+        let mut state = self.inner.state.lock();
    -+
    ++impl ConnectionState {
    ++    #[must_use]
    ++    fn shutdown(&mut self, conn: &ConnectionInner, cmd: SockShutdownCmd) -> IoEvents {
     +        let mut notify_events = IoEvents::empty();
     +        let mut shutdown_flags = VirtioVsockShutdownFlags::empty();
     +
    -+        if cmd.shut_read() && !state.shutdown.local_read_closed {
    -+            state.shutdown.local_read_closed = true;
    ++        if cmd.shut_read() && !self.shutdown.local_read_closed {
    ++            self.shutdown.local_read_closed = true;
     +            shutdown_flags |= VirtioVsockShutdownFlags::RECEIVE;
     +            notify_events |= IoEvents::IN | IoEvents::RDHUP | IoEvents::HUP;
     +        }
     +
    -+        if cmd.shut_write() && !state.shutdown.local_write_closed {
    -+            state.shutdown.local_write_closed = true;
    ++        if cmd.shut_write() && !self.shutdown.local_write_closed {
    ++            self.shutdown.local_write_closed = true;
     +            shutdown_flags |= VirtioVsockShutdownFlags::SEND;
     +            notify_events |= IoEvents::HUP;
     +        }
     +
    -+        let local_fully_closed =
    -+            state.shutdown.local_read_closed && state.shutdown.local_write_closed;
    -+        let peer_fully_closed = state.shutdown.peer_read_closed && state.shutdown.peer_write_closed;
    -+
    -+        if !local_fully_closed || !peer_fully_closed {
    -+            if !shutdown_flags.is_empty() {
    -+                let _ =
    -+                    state.send_packet(&self.inner, VirtioVsockOp::Shutdown, shutdown_flags.bits());
    -+            }
    -+
    -+            if on_drop {
    -+                debug_assert!(local_fully_closed);
    -+                state.phase = Phase::Closing;
    -+                state.arm_timeout(&self.inner, DEFAULT_CLOSE_TIMEOUT);
    -+            }
    -+
    -+            drop(state);
    -+        } else if state.phase != Phase::Closed {
    -+            state.phase = Phase::Closed;
    -+            let _ = state.send_packet(&self.inner, VirtioVsockOp::Rst, 0);
    -+            drop(state);
    -+
    -+            // Note that we must release the socket state lock before calling `remove_connection`.
    -+            let vsock_space = self.inner.bound_port.vsock_space();
    -+            vsock_space.remove_connection(&self.inner);
    ++        // No need to send anything if the peer endpoint has been fully shut down.
    ++        let peer_fully_closed = self.shutdown.peer_read_closed && self.shutdown.peer_write_closed;
    ++        if !peer_fully_closed && !shutdown_flags.is_empty() {
    ++            let _ = self.send_packet(conn, VirtioVsockOp::Shutdown, shutdown_flags.bits());
     +        }
     +
    -+        if !on_drop {
    -+            self.inner.pollee.notify(notify_events);
    -+        }
    ++        notify_events
     +    }
     +}
     
    @@ kernel/src/net/socket/vsock/transport/listener.rs (new)
     +    }
     +
     +    pub(super) fn is_full(&self) -> bool {
    -+        // Race conditions don't matter here.
    ++        // Race conditions don't matter here. We use `>` instead of `>=` because Linux allows to
    ++        // have `backlog + 1` connections in the backlog queue.
     +        self.num_conns.load(Ordering::Relaxed) > self.backlog.load(Ordering::Relaxed)
     +    }
     +
    @@ kernel/src/net/socket/vsock/transport/mod.rs (new)
     +
     +//! The virtio-vsock transport protocol.
     +//!
    -+//! Built on top of the [`basic virtio-vsock device support`](`aster_virtio::device::socket`), this
    ++//! Built on top of the [_basic virtio-vsock device support_](`aster_virtio::device::socket`), this
     +//! module manages connections and listeners, handles connection establishment, data transfer, and
     +//! shutdown, and implements credit-based flow control plus I/O event checking and notification.
     +//! The socket layer is expected to build on these APIs to provide the user-visible socket
    @@ kernel/src/net/socket/vsock/transport/mod.rs (new)
     +
     +// Reference: <https://elixir.bootlin.com/linux/v6.16.8/source/net/vmw_vsock/af_vsock.c#L136>
     +const DEFAULT_CONNECT_TIMEOUT: Duration = Duration::from_secs(2);
    -+// Reference: <https://elixir.bootlin.com/linux/v6.16.8/source/net/vmw_vsock/virtio_transport_common.c#L82>
    ++// Reference: <https://elixir.bootlin.com/linux/v6.16.8/source/net/vmw_vsock/virtio_transport_common.c#L24>
     +const DEFAULT_CLOSE_TIMEOUT: Duration = Duration::from_secs(8);
    -+// Reference: <https://elixir.bootlin.com/linux/v6.16.8/source/net/vmw_vsock/af_vsock.c#L137>
    ++// Reference: <https://elixir.bootlin.com/linux/v6.16.8/source/net/vmw_vsock/af_vsock.c#L138>
     +const DEFAULT_RX_BUF_SIZE: usize = 256 * 1024;
     +// Reference: <https://elixir.bootlin.com/linux/v6.16.8/source/net/vmw_vsock/af_vsock.c#L138>
     +const DEFAULT_PENDING_TX_BYTES: usize = 256 * 1024;
    -+// Reference: <https://elixir.bootlin.com/linux/v6.16.8/source/include/linux/socket.h#L313>
    ++// Reference: <https://elixir.bootlin.com/linux/v6.16.8/source/include/linux/socket.h#L298>
     +const MAX_BACKLOG: usize = 4096;
    -+// Reference: <https://elixir.bootlin.com/linux/v6.16.8/source/include/linux/virtio_vsock.h#L114>
    -+const VIRTIO_VSOCK_MAX_PKT_BUF_SIZE: usize = 64 * 1024;
     +
    -+const CREDIT_UPDATE_THRESHOLD: u32 = if DEFAULT_RX_BUF_SIZE / 4 < VIRTIO_VSOCK_MAX_PKT_BUF_SIZE {
    -+    (DEFAULT_RX_BUF_SIZE / 4) as u32
    -+} else {
    -+    VIRTIO_VSOCK_MAX_PKT_BUF_SIZE as u32
    -+};
    ++const CREDIT_UPDATE_THRESHOLD: u32 = (DEFAULT_RX_BUF_SIZE / 4) as u32;
     +
     +fn process_rx_callback() {
     +    if let Ok(vsock_space) = space::vsock_space() {
    @@ kernel/src/net/socket/vsock/transport/port.rs (new)
     +};
     +
     +/// An owned lease on a bound local vsock port; dropping the value releases the lease.
    ++//
    ++// TODO: Currently, the port table operates globally and checks whether a port is occupied without
    ++// taking the CID into account. This only works correctly if there is one vsock device.
     +#[derive(Debug)]
     +pub(in crate::net::socket::vsock) struct BoundPort {
     +    port: u32,
    @@ kernel/src/net/socket/vsock/transport/port.rs (new)
     +}
     +
     +impl BoundPort {
    -+    /// Binds `addr` and returns the resulting port lease.
    -+    pub(in crate::net::socket::vsock) fn new_bind(addr: VsockSocketAddr) -> Result<Self> {
    ++    /// Binds exclusively to `addr` and returns the resulting port lease.
    ++    pub(in crate::net::socket::vsock) fn new_exclusive(addr: VsockSocketAddr) -> Result<Self> {
     +        let vsock_space = vsock_space()?;
     +
     +        let guest_cid = vsock_space.guest_cid();
    @@ kernel/src/net/socket/vsock/transport/port.rs (new)
     +    }
     +
     +    pub(super) fn vsock_space(&self) -> &'static VsockSpace {
    ++        // This won't fail because we've checked it in all constructors.
     +        vsock_space().unwrap()
     +    }
     +
    @@ kernel/src/net/socket/vsock/transport/space.rs (new)
     +    process::signal::Pollee,
     +};
     +
    ++// We currently support only one vsock device.
    ++// TODO: Add support for multiple vsock devices and the loopback vsock device.
     +pub(super) struct VsockSpace {
     +    device: Arc<SocketDevice>,
     +    ports: SpinLock<PortTable>,
    @@ kernel/src/net/socket/vsock/transport/space.rs (new)
     +            return;
     +        }
     +
    -+        let rst_header = VirtioVsockHdr::new(
    -+            header.dst_cid,
    -+            header.src_cid,
    -+            header.dst_port,
    -+            header.src_port,
    -+            0,
    -+            VirtioVsockOp::Rst,
    -+            0,
    -+            0,
    -+            0,
    -+        );
    ++        // We do not use `VirtioVsockHdr::new` here because we want to specify the `type_` field. It
    ++        // may not be `VirtioVsockType::Stream`.
    ++        let rst_header = VirtioVsockHdr {
    ++            src_cid: header.dst_cid,
    ++            dst_cid: header.src_cid,
    ++            src_port: header.dst_port,
    ++            dst_port: header.src_port,
    ++            len: 0,
    ++            type_: header.type_,
    ++            op: VirtioVsockOp::Rst as u16,
    ++            flags: 0,
    ++            buf_alloc: 0,
    ++            fwd_cnt: 0,
    ++        };
     +        let _ = self.send_packet(&rst_header);
     +    }
     +
    @@ kernel/src/net/socket/vsock/transport/space.rs (new)
     +    /// Sends a control packet which does not carry payload.
     +    ///
     +    /// This method may be called while holding the socket state lock.
    ++    //
    ++    // TODO: This method may fail if memory allocation fails. For now, we will ignore the error in
    ++    // most cases. If possible, we should find better ways to handle the error.
     +    #[must_use]
     +    pub(super) fn send_packet(&self, header: &VirtioVsockHdr) -> bool {
     +        let Ok(builder) = TxPacket::new_builder() else {
    @@ kernel/src/net/socket/vsock/transport/space.rs (new)
     +        match tx.try_send(packet) {
     +            Ok(()) => (),
     +            Err(pending) => {
    ++                // TODO: Ideally, we should limit the number of in-flight packets. This will prevent
    ++                // the peer endpoint from exhausting a large amount of memory by triggering too many
    ++                // packets but never processing them.
     +                pending.push_pending(None);
     +            }
     +        }
6:  5ed5d1d70 ! 6:  2d9a38cc4 Reimplement vsock sockets
    @@ kernel/src/net/socket/vsock/addr.rs (new)
     +
     +use crate::{net::socket::util::SocketAddr, prelude::*};
     +
    -+pub const VMADDR_CID_ANY: u32 = u32::MAX;
    -+pub const VMADDR_CID_HOST: u32 = 2;
    -+
    -+pub const VMADDR_PORT_ANY: u32 = u32::MAX;
    -+
    -+pub const UNSPECIFIED_VSOCK_ADDR: VsockSocketAddr = VsockSocketAddr {
    -+    cid: VMADDR_CID_ANY,
    -+    port: VMADDR_PORT_ANY,
    -+};
    -+
     +/// A vsock socket address.
    -+#[derive(Debug, Clone, Copy, PartialEq, Eq, Pod)]
     +#[repr(C)]
    ++#[derive(Clone, Copy, Debug, Eq, PartialEq)]
     +pub struct VsockSocketAddr {
     +    pub cid: u32,
     +    pub port: u32,
    @@ kernel/src/net/socket/vsock/addr.rs (new)
     +        SocketAddr::Vsock(value)
     +    }
     +}
    ++
    ++pub(super) const VMADDR_CID_ANY: u32 = u32::MAX;
    ++pub(super) const VMADDR_CID_HOST: u32 = 2;
    ++
    ++pub(super) const VMADDR_PORT_ANY: u32 = u32::MAX;
    ++
    ++pub(super) const UNSPECIFIED_VSOCK_ADDR: VsockSocketAddr = VsockSocketAddr {
    ++    cid: VMADDR_CID_ANY,
    ++    port: VMADDR_PORT_ANY,
    ++};
     
      ## kernel/src/net/socket/vsock/mod.rs (new) ##
     @@
    @@ kernel/src/net/socket/vsock/stream/init.rs (new)
     +use crate::{
     +    events::IoEvents,
     +    net::socket::{
    -+        util::SockShutdownCmd,
    ++        util::{SockShutdownCmd, check_port_privilege},
     +        vsock::{
     +            addr::{VMADDR_CID_HOST, VMADDR_PORT_ANY, VsockSocketAddr},
     +            stream::{ConnectingStream, ListenStream},
    @@ kernel/src/net/socket/vsock/stream/init.rs (new)
     +            return_errno_with_message!(Errno::EINVAL, "the socket is already bound");
     +        }
     +
    -+        self.bound_port = Some(BoundPort::new_bind(addr)?);
    ++        if let Ok(port) = u16::try_from(addr.port) {
    ++            check_port_privilege(port)?;
    ++        }
    ++
    ++        // Linux does not support `SO_REUSEADDR`/`SO_REUSEPORT` for `AF_VSOCK`. Therefore, port
    ++        // binding is always exclusive.
    ++        self.bound_port = Some(BoundPort::new_exclusive(addr)?);
     +        Ok(())
     +    }
     +
    @@ kernel/src/net/socket/vsock/stream/init.rs (new)
     +    pub(super) fn shutdown(&self, _cmd: SockShutdownCmd) -> Result<()> {
     +        if !self.is_connect_done {
     +            // There is no need to do anything because the socket is permanently unusable. However,
    -+            // returning `Ok(())` mimics the Linux behaviour.
    ++            // returning `Ok(())` mimics the Linux behavior.
     +            return Ok(());
     +        }
     +
    @@ kernel/src/net/socket/vsock/stream/mod.rs (new)
     +            return result;
     +        }
     +
    ++        // FIXME: Linux cancels pending packets and aborts the connection if a blocking `connect()`
    ++        // is interrupted by a signal. Here, we follow the behavior of IP sockets by continuing to
    ++        // establish the connection in the background.
     +        self.wait_events(IoEvents::OUT, None, || self.check_connect())
     +    }
     +
```

</details>

File: kernel/src/net/socket/vsock/stream/mod.rs [hunk 13]
```diff
@@ -1,9 +1,428 @@
...
+    }
+}
+
+impl Socket for VsockStreamSocket {
+    fn bind(&self, socket_addr: SocketAddr) -> Result<()> {
+        let addr = VsockSocketAddr::try_from(socket_addr)?;
+
+        let mut state = self.lock_updated_state();
+        let State::Init(init_stream) = state.as_mut() else {
+            return_errno_with_message!(Errno::EINVAL, "the socket is already bound or connected");
```
Comment (StevenJiang1110) [inline kernel/src/net/socket/vsock/stream/mod.rs:254]: Following the convention used in the TCP case, the error message could be "the socket is already bound to an address"？It's more accurate because the socket may also be in a listening state?

File: kernel/comps/network/src/buffer.rs (hunk 1 above)
Comment (StevenJiang1110) [reply kernel/comps/network/src/buffer.rs]: > It is not possible. How to deal with &dyn MulitRead?

I overlooked this. Thanks for your exaplanation.

File: kernel/src/net/socket/vsock/transport/connection/recv.rs (hunk 3 above)
Comment (StevenJiang1110) [reply kernel/src/net/socket/vsock/transport/connection/recv.rs:32]: > The problem is that if we return success, then the writer cannot be left in an unspecified position.

Thanks for your explanaition!

> We need a specification for the read/write operations to indicate when the reader/writer's position is specified, or explicitly states that it's unspecified regardless of the result.

If possible, always returning the actually read/write bytes if page fault occurs in the middle should be better? Though it can be dealt with saparately.

File: kernel/src/net/socket/vsock/transport/connection/mod.rs (hunk 11 above)
Comment (StevenJiang1110) [reply kernel/src/net/socket/vsock/transport/connection/mod.rs:334]: I also checked the Linux implementation, Linux will always sends a CREDIT_UPDATE reply on response to a CREDIT_REQUEST request. So it should be fine.

File: kernel/comps/virtio/src/device/socket/packet.rs [hunk 14]
```diff
@@ -0,0 +1,91 @@
...
+    pub fn copy_payload<F>(&mut self, copy_fn: F) -> Result<usize>
+    where
+        F: FnOnce(VmWriter<Infallible>) -> Result<usize>,
+    {
+        self.0.copy_packet(copy_fn)
+    }
+
+    /// Returns the payload length accumulated so far.
+    pub fn payload_len(&self) -> usize {
+        self.0.packet_len()
```
Comment (StevenJiang1110) [inline kernel/comps/virtio/src/device/socket/packet.rs:52]: Can we unify the packet/payload usage here?

File: kernel/src/net/socket/vsock/transport/connection/mod.rs [hunk 15]
```diff
@@ -0,0 +1,455 @@
...
+            },
+            timer: None,
+        };
+
+        Arc::new(Self {
+            conn_id: *conn_id,
+            bound_port,
+            pollee,
+            state: SpinLock::new(state),
+            available_tx_bytes: AtomicUsize::new(DEFAULT_PENDING_TX_BYTES),
```
Comment (StevenJiang1110) [inline kernel/src/net/socket/vsock/transport/connection/mod.rs:210]: Naming  `available_tx_bytes` as `pending_tx_bytes`? I think pending is more suitable for tx bytes.

**Review by StevenJiang1110 — APPROVED** [review]
LGTM! Thanks for your contribution!

File: kernel/src/net/socket/vsock/transport/connection/recv.rs (hunk 3 above)
Comment (lrh2000) [reply kernel/src/net/socket/vsock/transport/connection/recv.rs:32]: > If possible, always returning the actually read/write bytes if page fault occurs in the middle should be better?

The return values of `read`/`write` needs to follow the Linux behavior. It may discard the entire message if page faults occur in between.
 - For UDP datagrams, we should discard the entire message rather than truncate it because the boundary matters.

But here the problem may not be the userspace behavior. The problem is the in-kernel contract for `FileLike::read`/`write`, i.e., whether we should require that the reader/writer's position be specified after `FileLike::read`/`FileLike::write`. In other words, should the following case be allowed?
 - `FileLike::read` returns `Ok(100)`, but the writer passed to `FileLike::read` is advanced by 200.

But we check the reader/writer position after `FileLike::read`/`FileLike::write` for our `preadv`/`pwritev` implementations. So we need to consider the interaction....

Actually if we want to improve this situation... Maybe:
 1. Extend the `MultiRead`/`MultiWrite` trait to provide native `short_read`/`short_write` methods. I think we can implement those for `VmReader`/`VmReaderArray`/etc
 2. Don't change the traits, but introduce something like:
```rust
fn short_read(writer: &mut dyn MultiWrite) -> Result<usize> {
    let mut reader = packet_reader();
    let old_avail = reader.avail();

    let res = writer.write(&mut reader);

    let new_avail = reader.avail();
    if new_avail != old_avail {
        return Ok(old_avail - new_avail);
    }

    res
}
```

OK. So we indeed have some opportunities to fix the code here. Doing so may help https://github.com/asterinas/asterinas/pull/3146.

Comment (StevenJiang1110) [reply kernel/src/net/socket/vsock/transport/connection/recv.rs:32]: > FileLike::read returns Ok(100), but the writer passed to FileLike::read is advanced by 200.

I think this should be disallowed. If Ok is returned, the amount by which the writer is advanced must exactly match the number of bytes read. The current implementation should already follow this convention — it is only when an error is returned that the writer's position becomes unspecified, right? Do we have any use case that requires allowing this behavior?

> Don't change the traits, but introduce something like:

What invariant is `short_read` intended to preserve? The idea seems to be that if a page fault is encountered halfway through a read, we should return the number of bytes read so far rather than an error. So `MultiRead::read` corresponds to the UDP case — if a page fault occurs midway, we return an error and discard the packet — while `short_read` corresponds to the TCP case, where a partial read is acceptable.

If that is the intent, I think it might be cleaner to refactor this into `read_stream` and `read_packet` as two separate methods on `MultiRead`, where the current `read` essentially becomes `read_packet`:

```rust
pub trait MultiRead {
    // Similar to VmReader: on success, return the number of bytes read;
    // on failure, return both the number of bytes read so far and the error.
    fn read(&mut self, writer: &mut VmWriter) -> core::Result<usize, (usize, Error)>;

    fn read_packet(&mut self, writer: &mut VmWriter) -> Result<usize> {
        match self.read(writer) {
            Ok(n) => Ok(n),
            Err((_, err)) => Err(err),
        }
    }

    fn read_stream(&mut self, writer: &mut VmWriter) -> Result<usize> {
        match self.read(writer) {
            Ok(n) => Ok(n),
            Err((0, err)) => Err(err),
            Err((bytes, _)) => Ok(bytes),
        }
    }
}

```

How do you like it?

Comment (lrh2000) [reply kernel/src/net/socket/vsock/transport/connection/recv.rs:32]: > Do we have any use case that requires allowing this behavior?

Linux `hwrng` behavior:
 - https://elixir.bootlin.com/linux/v7.0/source/drivers/char/hw_random/core.c#L292-L295
 - https://elixir.bootlin.com/linux/v7.0/source/drivers/char/hw_random/core.c#L312

It means that:
```rust
let writer: &mut MultiWrite = writer_for_filelike();

bytes = get_entropy(); // 1024 bytes
writer.write(&bytes); // Ok(1024)

bytes = get_entropy(); // 1024 bytes
writer.write(&bytes); // EFAULT after 512 bytes

return Ok(1024); // This is Linux behavior. We should return 1024 bytes instead of 1024+512 bytes.
```

However, if we advance `MultiWrite`, we cannot undo the advance. Therefore, the return value and the writer position cannot be synchronized. (There is more information in https://github.com/asterinas/asterinas/pull/2951#discussion_r2999868223).

Unfortunately, the TCP side seems to have similar rules:
 - https://elixir.bootlin.com/linux/v7.0/source/net/ipv4/tcp.c#L2878-L2880
 - https://elixir.bootlin.com/linux/v7.0/source/net/ipv4/tcp.c#L2951

TCP is a stream, but it is composed by packets. Suppose we have two packets to receive, if the page fault occurs in the first packet, we will get a `EFAULT`: 
```
              Packet 1            Packet 2
         |-----------------|---------------------|
recv(..         ^
                | (page fault)
recv() = EFAULT
```

But if the page fault occurs in the second packet, we will get the size of the first packet:
```
              Packet 1            Packet 2
         |-----------------|---------------------|
recv(..                    ^         ^
                           |         |
                           | (note that the first packet is consumed at this point)
                                     |
                                     | (page fault)
recv() = sizeof(Packet 1)
```

It is because the first packet has already been consumed (e.g., we may have it dropped after copying the first packet to userspace). At this point, we cannot return an `EFAULT` because we have permanently consumed some bytes.

Our choices are:
 1. Strictly follow the Linux behavior: Return the size of the first packet.
    - Then the question becomes, how should we synchronize the cursor if a page fault occurs in the second packet? Should we even synchronize it?
 2. Semantically follow the Linux behavior: Return the size of the first packet plus the size of the short-read part in the second packet.
    - I think it's highly unlikely that it will break userspace. The result is semantically correct. In the next `recv()`, we will instruct our kernel to continue reading after the short-read part in the second packet.
    - We only need to extend `MultiWrite` to provide a `read(&mut self) -> Result<usize, (usize, Error)>` API then. It should not be controversial. 

(We may not really need `read_packet()`/`read_stream()` since we can just use `read()?` for the packet case and we should handle the short-read error for the stream case).

Comment (StevenJiang1110) [reply kernel/src/net/socket/vsock/transport/connection/recv.rs:32]: > Linux hwrng behavior:
> Unfortunately, the TCP side seems to have similar rules:

Thanks for the explanation! This behavior was genuinely surprising to me — I had never considered that Linux would behave this way.

> Semantically follow the Linux behavior: Return the size of the first packet plus the size of the short-read part in the second packet.

I think this approach is acceptable, unless we actually encounter a case where it breaks userspace behavior in the future. It also seems like the simpler of the available options, and it should cover the typical userspace usage patterns.

> Then the question becomes, how should we synchronize the cursor if a page fault occurs in the second packet? Should we even synchronize it?

I think, from a long-term perspective, aligning with Linux's behavior is the right direction. The current approach of relying on the writer's position as returned by preadv is also arguably incorrect. Ideally, readv should be implemented as a method on `FileLike`, where short-read scenarios are handled internally by each file. However, since there is no concrete design yet for how `FileLike::readv` should be refactored, this is likely a longer-term effort.

> We may not really need read_packet()/read_stream() since we can just use read()? for the packet case and we should handle the short-read error for the stream case

Agreed — it may not be necessary to introduce these two dedicated functions after all.

Comment (lrh2000) [reply kernel/src/net/socket/vsock/transport/connection/recv.rs:32]: Thanks for the discussion! It seems that there is a way to solve this problem. We can address this problem in a separate PR?

File: kernel/comps/virtio/src/device/socket/packet.rs (hunk 14 above)
Comment (lrh2000) [reply kernel/comps/virtio/src/device/socket/packet.rs]: I guess "payload" is better and it corresponds to "header".

So I rename "packet" to "payload" in `kernel/comps/network/src/buffer.rs`.

File: kernel/src/net/socket/vsock/transport/connection/mod.rs (hunk 15 above)
Comment (lrh2000) [reply kernel/src/net/socket/vsock/transport/connection/mod.rs]: I don't understand this comment. In fact, `available_tx_bytes = DEFAULT_PENDING_TX_BYTES - pending_tx_bytes`, where `pending_tx_bytes` means that the TX bytes in the pending queue.

Perhaps this fact is not very clear. I have
 1. renamed `DEFAULT_PENDING_TX_BYTES` to `DEFAULT_TX_BUF_SIZE` and
 2. changed `available_tx_bytes` (which tracks the **available** bytes that can be added to the pending queue) to `tx_bytes_in_pending_queue` (which tracks the bytes that **have** been added in the pending queue), with the following doc comments:
```rust
    /// The number of TX bytes that have already been queued in the device's pending queue.
    ///
    /// See [`TxQueue`] for more information on the pending queue. This counter is used for
    /// accounting purposes to ensure that the total number of bytes does not exceed the upper
    /// bound, [`DEFAULT_TX_BUF_SIZE`].
    ///
    /// [`TxQueue`]: aster_virtio::device::socket::queue::TxQueue
    /// [`DEFAULT_TX_BUF_SIZE`]: super::DEFAULT_TX_BUF_SIZE
    tx_bytes_in_pending_queue: AtomicUsize,
```

The variable name may be a bit too long... But maybe it has better clarity.

**Comment by lrh2000** [comment]
This updates follow the merged PR https://github.com/asterinas/asterinas/pull/3160:
 - Packet allocation and queue creation will propagate errors instead of panicking.
 - Use the new API `VirtQueue::pop_used_with_min_bytes` to simply things.

In addition, it addresses the review comments.

The full range diff is:
```
git range-diff 18b1fb6255456808b5b42867344f7216179a1cc5..2d9a38cc4090d9cd8493b880b501d706647bb873 main..vsock-without-tests
```
<details>
<summary> range diff </summary>

```
1:  0e62b2475 ! 1:  af85dc5e0 Add `TxBufferBuilder`
    @@ kernel/comps/network/src/buffer.rs: pub struct TxBuffer {
     -    ) -> Result<Self> {
     -        // This wraps `new_impl` to prevent unnecessary monomorphization caused by `H`.
     -        Self::new_impl(header.as_bytes(), packet, pool)
    -+    pub fn new<H: Pod>(header: &H, packet: &[u8], pool: &Arc<DmaPool<ToDevice>>) -> Result<Self> {
    ++    pub fn new<H: Pod>(header: &H, payload: &[u8], pool: &Arc<DmaPool<ToDevice>>) -> Result<Self> {
     +        let mut builder = Self::new_builder::<H>(pool)?;
     +
     +        builder
    -+            .copy_packet(|mut writer| {
    -+                assert!(writer.avail() >= packet.len());
    -+                Ok(writer.write(&mut VmReader::from(packet)))
    ++            .copy_payload(|mut writer| {
    ++                assert!(writer.avail() >= payload.len());
    ++                Ok(writer.write(&mut VmReader::from(payload)))
     +            })
     +            .unwrap();
     +
    @@ kernel/comps/network/src/buffer.rs: impl HasDaddr for TxBuffer {
     +}
     +
     +impl<H: Pod> TxBufferBuilder<H> {
    -+    pub fn copy_packet<F>(&mut self, copy_fn: F) -> Result<usize>
    ++    pub fn copy_payload<F>(&mut self, copy_fn: F) -> Result<usize>
     +    where
     +        F: FnOnce(VmWriter<Infallible>) -> Result<usize>,
     +    {
    @@ kernel/comps/network/src/buffer.rs: impl HasDaddr for TxBuffer {
     +        Ok(bytes_written)
     +    }
     +
    -+    pub const fn packet_len(&self) -> usize {
    ++    pub const fn payload_len(&self) -> usize {
     +        self.nbytes - size_of::<H>()
     +    }
     +
    @@ kernel/comps/network/src/buffer.rs: impl HasDaddr for TxBuffer {
      pub struct RxBuffer {
          segment: DmaSegment<FromDevice>,
          header_len: usize,
    +-    packet_len: usize,
    ++    payload_len: usize,
    + }
    + 
    + impl RxBuffer {
    +@@ kernel/comps/network/src/buffer.rs: impl RxBuffer {
    +         Ok(Self {
    +             segment,
    +             header_len,
    +-            packet_len: 0,
    ++            payload_len: 0,
    +         })
    +     }
    + 
    +-    pub const fn packet_len(&self) -> usize {
    +-        self.packet_len
    ++    pub const fn payload_len(&self) -> usize {
    ++        self.payload_len
    +     }
    + 
    +-    pub fn set_packet_len(&mut self, packet_len: usize) {
    +-        assert!(self.header_len.checked_add(packet_len).unwrap() <= self.segment.size());
    +-        self.packet_len = packet_len;
    ++    pub fn set_payload_len(&mut self, payload_len: usize) {
    ++        assert!(self.header_len.checked_add(payload_len).unwrap() <= self.segment.size());
    ++        self.payload_len = payload_len;
    +     }
    + 
    +-    pub fn packet(&self) -> VmReader<'_, Infallible> {
    ++    pub fn payload(&self) -> VmReader<'_, Infallible> {
    +         self.segment
    +-            .sync_from_device(self.header_len..self.header_len + self.packet_len)
    ++            .sync_from_device(self.header_len..self.header_len + self.payload_len)
    +             .unwrap();
    + 
    +         let mut reader = self.segment.reader().unwrap();
    +-        reader.skip(self.header_len).limit(self.packet_len);
    ++        reader.skip(self.header_len).limit(self.payload_len);
    +         reader
    +     }
    + 
    +     pub fn buf(&self) -> VmReader<'_, Infallible> {
    +         self.segment
    +-            .sync_from_device(0..self.header_len + self.packet_len)
    ++            .sync_from_device(0..self.header_len + self.payload_len)
    +             .unwrap();
    + 
    +         let mut reader = self.segment.reader().unwrap();
    +-        reader.limit(self.header_len + self.packet_len);
    ++        reader.limit(self.header_len + self.payload_len);
    +         reader
    +     }
    + }
    +
    + ## kernel/comps/network/src/driver.rs ##
    +@@ kernel/comps/network/src/driver.rs: impl device::RxToken for RxToken {
    +     where
    +         F: FnOnce(&[u8]) -> R,
    +     {
    +-        let mut packet = self.0.packet();
    +-        let mut buffer = vec![0u8; packet.remain()];
    +-        packet.read(&mut VmWriter::from(&mut buffer as &mut [u8]));
    ++        let mut payload = self.0.payload();
    ++        let mut buffer = vec![0u8; payload.remain()];
    ++        payload.read(&mut VmWriter::from(&mut buffer as &mut [u8]));
    +         f(&buffer)
    +     }
    + }
     
      ## kernel/comps/network/src/lib.rs ##
     @@ kernel/comps/network/src/lib.rs: use aster_softirq::{
    @@ kernel/comps/virtio/src/device/network/device.rs: use core::fmt::Debug;
      
      use super::{config::VirtioNetConfig, header::VirtioNetHdr};
      use crate::{
    +@@ kernel/comps/virtio/src/device/network/device.rs: impl NetworkDevice {
    +         debug!("receive packet: token = {}, len = {}", token, len);
    + 
    +         let mut rx_buffer = self.rx_buffers.remove(token as usize).unwrap();
    +-        rx_buffer.set_packet_len(len as usize - size_of::<VirtioNetHdr>());
    ++        rx_buffer.set_payload_len(len as usize - size_of::<VirtioNetHdr>());
    + 
    +         let new_rx_buffer = self.new_rx_buffer.take().unwrap();
    +         self.add_rx_buffer(new_rx_buffer).unwrap();
     @@ kernel/comps/virtio/src/device/network/device.rs: impl NetworkDevice {
              }
      
    @@ kernel/comps/virtio/src/device/network/device.rs: impl NetworkDevice {
     -            &mut VmReader::from(packet).to_fallible(),
     -            tx_pool,
     -        )
    --        .unwrap();
    -+        let tx_buffer = TxBuffer::new(&self.header, packet, tx_pool).unwrap();
    +-        .map_err(|_| NetError::NoMemory)?;
    ++        let tx_buffer =
    ++            TxBuffer::new(&self.header, packet, tx_pool).map_err(|_| NetError::NoMemory)?;
    + 
    +         let token = self.send_queue.add_input_bufs(&[&tx_buffer]).unwrap();
      
    -         let token = self
    -             .send_queue
     
      ## kernel/comps/virtio/src/device/socket/device.rs ##
     @@ kernel/comps/virtio/src/device/socket/device.rs: use core::{fmt::Debug, hint::spin_loop};
    @@ kernel/comps/virtio/src/device/socket/device.rs: impl SocketDevice {
     +            TxBuffer::new(header, buffer, tx_pool).unwrap()
              };
      
    -         let token = self.send_queue.add_input_bufs(&[&tx_buffer])?;
    +         let token = self
    +@@ kernel/comps/virtio/src/device/socket/device.rs: impl SocketDevice {
    +             .rx_buffers
    +             .remove(token as usize)
    +             .ok_or(SocketError::QueueError)?;
    +-        rx_buffer.set_packet_len(len as usize);
    ++        rx_buffer.set_payload_len(len as usize);
    + 
    +         let rx_pool = RX_BUFFER_POOL.get().unwrap();
    +         let new_rx_buffer = RxBuffer::new(size_of::<VirtioVsockHdr>(), rx_pool).unwrap();
2:  e7b2112f2 = 2:  48580daca Remove locks from `Taskless`
3:  e8d41fe4e ! 3:  79bc21715 Remove vsock code entirely
    @@ kernel/comps/virtio/src/device/socket/device.rs (deleted)
     -            handle_recv_irq, register_device,
     -        },
     -    },
    --    queue::{QueueError, VirtQueue},
    +-    queue::VirtQueue,
     -    transport::VirtioTransport,
     -};
     -
    @@ kernel/comps/virtio/src/device/socket/device.rs (deleted)
     -        for i in 0..QUEUE_SIZE {
     -            let rx_pool = RX_BUFFER_POOL.get().unwrap();
     -            let rx_buffer = RxBuffer::new(size_of::<VirtioVsockHdr>(), rx_pool).unwrap();
    --            let token = recv_queue.add_output_bufs(&[&rx_buffer])?;
    +-            let token = recv_queue.add_output_bufs(&[&rx_buffer]).unwrap();
     -            assert_eq!(i, token);
     -            assert_eq!(rx_buffers.put(rx_buffer) as u16, i);
     -        }
    @@ kernel/comps/virtio/src/device/socket/device.rs (deleted)
     -            TxBuffer::new(header, buffer, tx_pool).unwrap()
     -        };
     -
    --        let token = self.send_queue.add_input_bufs(&[&tx_buffer])?;
    +-        let token = self
    +-            .send_queue
    +-            .add_input_bufs(&[&tx_buffer])
    +-            .map_err(|_| SocketError::QueueError)?;
     -
     -        if self.send_queue.should_notify() {
     -            self.send_queue.notify();
    @@ kernel/comps/virtio/src/device/socket/device.rs (deleted)
     -        }
     -
     -        // Pop out the buffer, so we can reuse the send queue further
    --        let (pop_token, _) = self.send_queue.pop_used()?;
    +-        let (pop_token, _) = self
    +-            .send_queue
    +-            .pop_used()
    +-            .map_err(|_| SocketError::QueueError)?;
     -        debug_assert!(pop_token == token);
     -        if pop_token != token {
    --            return Err(SocketError::QueueError(QueueError::WrongToken));
    +-            return Err(SocketError::QueueError);
     -        }
     -        debug!("send packet succeeds");
     -        Ok(())
    @@ kernel/comps/virtio/src/device/socket/device.rs (deleted)
     -        &mut self,
     -        // connection_info: &mut ConnectionInfo,
     -    ) -> Result<RxBuffer, SocketError> {
    --        let (token, len) = self.recv_queue.pop_used()?;
    +-        let (token, len) = self
    +-            .recv_queue
    +-            .pop_used()
    +-            .map_err(|_| SocketError::QueueError)?;
     -        debug!(
     -            "receive packet in rx_queue: token = {}, len = {}",
     -            token, len
    @@ kernel/comps/virtio/src/device/socket/device.rs (deleted)
     -        let mut rx_buffer = self
     -            .rx_buffers
     -            .remove(token as usize)
    --            .ok_or(QueueError::WrongToken)?;
    --        rx_buffer.set_packet_len(len as usize);
    +-            .ok_or(SocketError::QueueError)?;
    +-        rx_buffer.set_payload_len(len as usize);
     -
     -        let rx_pool = RX_BUFFER_POOL.get().unwrap();
     -        let new_rx_buffer = RxBuffer::new(size_of::<VirtioVsockHdr>(), rx_pool).unwrap();
    @@ kernel/comps/virtio/src/device/socket/device.rs (deleted)
     -
     -    /// Add a used rx buffer to recv queue,@index is only to check the correctness
     -    fn add_rx_buffer(&mut self, rx_buffer: RxBuffer, index: u16) -> Result<(), SocketError> {
    --        let token = self.recv_queue.add_output_bufs(&[&rx_buffer])?;
    +-        let token = self
    +-            .recv_queue
    +-            .add_output_bufs(&[&rx_buffer])
    +-            .map_err(|_| SocketError::QueueError)?;
     -        assert_eq!(index, token);
     -        assert!(self.rx_buffers.put_at(token as usize, rx_buffer).is_none());
     -        if self.recv_queue.should_notify() {
    @@ kernel/comps/virtio/src/device/socket/error.rs (deleted)
     -//
     -use core::{fmt, result};
     -
    --use crate::queue::QueueError;
    --
     -/// The error type of VirtIO socket driver.
     -#[derive(Debug)]
     -pub enum SocketError {
    @@ kernel/comps/virtio/src/device/socket/error.rs (deleted)
     -    /// Recycled a wrong buffer.
     -    RecycledWrongBuffer,
     -    /// Queue Error
    --    QueueError(QueueError),
    --}
    --
    --impl From<QueueError> for SocketError {
    --    fn from(value: QueueError) -> Self {
    --        Self::QueueError(value)
    --    }
    +-    QueueError,
     -}
     -
     -impl From<int_to_c_enum::TryFromIntError> for SocketError {
    @@ kernel/comps/virtio/src/device/socket/error.rs (deleted)
     -                write!(f, "Peer has insufficient buffer space, try again later")
     -            }
     -            Self::RecycledWrongBuffer => write!(f, "Recycled a wrong buffer"),
    --            Self::QueueError(_) => write!(f, "Error encountered out of vsock itself!"),
    +-            Self::QueueError => write!(f, "Error encountered out of vsock itself!"),
     -        }
     -    }
     -}
    @@ kernel/src/net/socket/vsock/common.rs (deleted)
     -        listen::Listen,
     -    },
     -};
    --use crate::{prelude::*, return_errno_with_message, util::MultiRead};
    +-use crate::{prelude::*, util::MultiRead};
     -
     -/// Manage all active sockets
     -pub struct VsockSpace {
4:  635a8a83f ! 4:  b0072f9c5 Reimplement vsock devices
    @@ kernel/comps/virtio/src/device/socket/device.rs (new)
     +        let config_manager = VirtioVsockConfig::new_manager(transport.as_ref());
     +        let guest_cid = VirtioVsockConfig::read_guest_cid(&config_manager);
     +
    -+        let tx_queue = TxQueue::new(transport.as_mut());
    -+        let rx_queue = RxQueue::new(transport.as_mut());
    -+        let event_queue = EventQueue::new(transport.as_mut());
    ++        let tx_queue = TxQueue::new(transport.as_mut())?;
    ++        let rx_queue = RxQueue::new(transport.as_mut())?;
    ++        let event_queue = EventQueue::new(transport.as_mut())?;
     +
     +        let device = Arc::new(Self {
     +            config_manager,
    @@ kernel/comps/virtio/src/device/socket/mod.rs (new)
     +    component.devices.lock().get(name).cloned()
     +}
     +
    -+/// Returns all registered virtio-vsock devices.
    -+pub fn all_devices() -> Vec<(String, Arc<SocketDevice>)> {
    -+    let component = COMPONENT.get().unwrap();
    -+    component
    -+        .devices
    -+        .lock()
    -+        .iter()
    -+        .map(|(name, device)| (name.clone(), device.clone()))
    -+        .collect()
    -+}
    -+
     +// #### Methods to schedule `Taskless`:
     +
     +fn schedule_rx(device: &Weak<SocketDevice>) {
    @@ kernel/comps/virtio/src/device/socket/packet.rs (new)
     +    where
     +        F: FnOnce(VmWriter<Infallible>) -> Result<usize>,
     +    {
    -+        self.0.copy_packet(copy_fn)
    ++        self.0.copy_payload(copy_fn)
     +    }
     +
     +    /// Returns the payload length accumulated so far.
     +    pub fn payload_len(&self) -> usize {
    -+        self.0.packet_len()
    ++        self.0.payload_len()
     +    }
     +
     +    /// Finalizes the packet with `header`.
    @@ kernel/comps/virtio/src/device/socket/packet.rs (new)
     +        RxBuffer::new(size_of::<VirtioVsockHdr>(), RX_BUFFER_POOL.get().unwrap()).map(Self)
     +    }
     +
    -+    pub(super) fn set_len(&mut self, len: usize) {
    -+        self.0.set_packet_len(len - size_of::<VirtioVsockHdr>());
    ++    pub(super) fn set_payload_len(&mut self, len: usize) {
    ++        self.0.set_payload_len(len);
     +    }
     +
     +    pub(super) fn inner(&self) -> &RxBuffer {
    @@ kernel/comps/virtio/src/device/socket/packet.rs (new)
     +
     +    /// Returns the payload length in bytes.
     +    pub fn payload_len(&self) -> usize {
    -+        self.0.packet_len()
    ++        self.0.payload_len()
     +    }
     +
     +    /// Returns a reader over the packet payload.
     +    pub fn payload(&self) -> VmReader<'_, Infallible> {
    -+        self.0.packet()
    ++        self.0.payload()
     +    }
     +}
     
    @@ kernel/comps/virtio/src/device/socket/queue.rs (new)
     +};
     +
     +use crate::{
    -+    device::socket::{
    -+        header::{VirtioVsockEvent, VirtioVsockEventId, VirtioVsockHdr},
    -+        packet::{RxPacket, TxPacket},
    ++    device::{
    ++        VirtioDeviceError,
    ++        socket::{
    ++            header::{VirtioVsockEvent, VirtioVsockEventId, VirtioVsockHdr},
    ++            packet::{RxPacket, TxPacket},
    ++        },
     +    },
     +    queue::VirtQueue,
     +    transport::VirtioTransport,
    @@ kernel/comps/virtio/src/device/socket/queue.rs (new)
     +    pub(super) const QUEUE_INDEX: u16 = 1;
     +    const QUEUE_SIZE: u16 = 64;
     +
    -+    pub(super) fn new(transport: &mut dyn VirtioTransport) -> Self {
    -+        let queue = VirtQueue::new(Self::QUEUE_INDEX, Self::QUEUE_SIZE, transport)
    -+            .expect("creating send queue fails");
    ++    pub(super) fn new(transport: &mut dyn VirtioTransport) -> Result<Self, VirtioDeviceError> {
    ++        let queue = VirtQueue::new(Self::QUEUE_INDEX, Self::QUEUE_SIZE, transport)?;
     +
     +        let inflight = (0..Self::QUEUE_SIZE).map(|_| None).collect();
     +        let pending = VecDeque::new();
     +
    -+        Self {
    ++        Ok(Self {
     +            queue,
     +            inflight,
     +            pending,
    -+        }
    ++        })
     +    }
     +
     +    pub(super) fn free_processed_tx_buffers(&mut self) {
    @@ kernel/comps/virtio/src/device/socket/queue.rs (new)
     +    pub(super) const QUEUE_INDEX: u16 = 0;
     +    const QUEUE_SIZE: u16 = 64;
     +
    -+    pub(super) fn new(transport: &mut dyn VirtioTransport) -> Self {
    -+        let mut queue = VirtQueue::new(Self::QUEUE_INDEX, Self::QUEUE_SIZE, transport)
    -+            .expect("creating recv queue fails");
    ++    pub(super) fn new(transport: &mut dyn VirtioTransport) -> Result<Self, VirtioDeviceError> {
    ++        let mut queue = VirtQueue::new(Self::QUEUE_INDEX, Self::QUEUE_SIZE, transport)?;
     +
     +        let mut buffers = SlotVec::new();
     +        for index in 0..Self::QUEUE_SIZE {
    -+            let buffer = RxPacket::new().expect("allocating recv packet fails");
    ++            let buffer = RxPacket::new().map_err(VirtioDeviceError::ResourceAlloc)?;
     +            let token = queue.add_output_bufs(&[buffer.inner()]).unwrap();
     +            assert_eq!(token, index);
     +            assert_eq!(buffers.put(buffer) as u16, index);
    @@ kernel/comps/virtio/src/device/socket/queue.rs (new)
     +            queue.notify();
     +        }
     +
    -+        Self {
    ++        Ok(Self {
     +            queue,
     +            buffers,
     +            pending: None,
    -+        }
    ++        })
     +    }
     +
     +    /// Returns the next received packet, if any.
     +    ///
     +    /// Packets shorter than the mandatory header are discarded before they reach the caller.
     +    pub fn recv(&mut self) -> Option<RxPacket> {
    -+        while let Some((mut packet, len)) = self.recv_impl() {
    -+            // As with all other virtio devices, we currently assume that the virtio transport
    -+            // layer is trustworthy, and therefore so is `len`.
    -+            //
    -+            // However, we do not assume that the peer is trustworthy, meaning that `len` may be
    -+            // smaller than the header size.
    -+            if len < size_of::<VirtioVsockHdr>() {
    -+                continue;
    -+            }
    -+
    -+            packet.set_len(len);
    -+            return Some(packet);
    -+        }
    -+
    -+        None
    -+    }
    -+
    -+    fn recv_impl(&mut self) -> Option<(RxPacket, usize)> {
     +        if self.pending.is_none() {
     +            self.pending = RxPacket::new().ok();
     +        }
    @@ kernel/comps/virtio/src/device/socket/queue.rs (new)
     +            return None;
     +        }
     +
    -+        let (token, len) = self.queue.pop_used().ok()?;
    -+        let packet = self.buffers.remove(token as usize).unwrap();
    ++        let (token, len) = self
    ++            .queue
    ++            .pop_used_with_min_bytes(size_of::<VirtioVsockHdr>())
    ++            .ok()?;
    ++        let mut packet = self.buffers.remove(token as usize).unwrap();
    ++        packet.set_payload_len(len as usize - size_of::<VirtioVsockHdr>());
     +
     +        let new_packet = self.pending.take().unwrap();
     +        let new_token = self.queue.add_output_bufs(&[new_packet.inner()]).unwrap();
    @@ kernel/comps/virtio/src/device/socket/queue.rs (new)
     +            self.queue.notify();
     +        }
     +
    -+        Some((packet, len as usize))
    ++        Some(packet)
     +    }
     +}
     +
    @@ kernel/comps/virtio/src/device/socket/queue.rs (new)
     +    pub(super) const QUEUE_INDEX: u16 = 2;
     +    const QUEUE_SIZE: u16 = 1;
     +
    -+    pub(super) fn new(transport: &mut dyn VirtioTransport) -> Self {
    -+        let mut queue = VirtQueue::new(Self::QUEUE_INDEX, Self::QUEUE_SIZE, transport)
    -+            .expect("creating event queue fails");
    ++    pub(super) fn new(transport: &mut dyn VirtioTransport) -> Result<Self, VirtioDeviceError> {
    ++        let mut queue = VirtQueue::new(Self::QUEUE_INDEX, Self::QUEUE_SIZE, transport)?;
     +
    -+        let buffer = DmaStream::alloc_uninit(1, false).expect("allocating event buffer fails");
    ++        let buffer = DmaStream::alloc_uninit(1, false).map_err(VirtioDeviceError::ResourceAlloc)?;
     +        let token = queue.add_output_bufs(&[&buffer]).unwrap();
     +        debug_assert_eq!(token, 0);
     +
    @@ kernel/comps/virtio/src/device/socket/queue.rs (new)
     +            queue.notify();
     +        }
     +
    -+        Self { queue, buffer }
    ++        Ok(Self { queue, buffer })
     +    }
     +
     +    /// Returns the next received event, if any.
5:  232dd1dab ! 5:  168610cda Reimplement vsock protocol
    @@ kernel/src/net/socket/vsock/transport/connection/basic.rs (new)
     +
     +use crate::{
     +    events::IoEvents,
    -+    net::socket::vsock::{VsockSocketAddr, transport::Connection},
    ++    net::socket::vsock::{
    ++        VsockSocketAddr,
    ++        transport::{Connection, DEFAULT_TX_BUF_SIZE},
    ++    },
     +    prelude::*,
     +    process::signal::Pollee,
     +};
    @@ kernel/src/net/socket/vsock/transport/connection/basic.rs (new)
     +        // the logic for vsock appears to be different.
     +        if !state.shutdown.local_write_closed {
     +            if state.peer_credit() != 0
    -+                && self.inner.available_tx_bytes.load(Ordering::Relaxed) != 0
    ++                && self.inner.tx_bytes_in_pending_queue.load(Ordering::Relaxed)
    ++                    < DEFAULT_TX_BUF_SIZE
     +            {
     +                events |= IoEvents::OUT;
     +            }
    @@ kernel/src/net/socket/vsock/transport/connection/mod.rs (new)
     +use crate::{
     +    events::IoEvents,
     +    net::socket::vsock::transport::{
    -+        BoundPort, DEFAULT_CONNECT_TIMEOUT, DEFAULT_PENDING_TX_BYTES, DEFAULT_RX_BUF_SIZE,
    -+        conn_id::ConnId,
    ++        BoundPort, DEFAULT_CONNECT_TIMEOUT, DEFAULT_RX_BUF_SIZE, conn_id::ConnId,
     +    },
     +    prelude::*,
     +    process::signal::Pollee,
    @@ kernel/src/net/socket/vsock/transport/connection/mod.rs (new)
     +    bound_port: BoundPort,
     +    pollee: Pollee,
     +    state: SpinLock<ConnectionState, BottomHalfDisabled>,
    -+    available_tx_bytes: AtomicUsize,
    ++    /// The number of TX bytes that have already been queued in the device's pending queue.
    ++    ///
    ++    /// See [`TxQueue`] for more information on the pending queue. This counter is used for
    ++    /// accounting purposes to ensure that the total number of bytes does not exceed the upper
    ++    /// bound, [`DEFAULT_TX_BUF_SIZE`].
    ++    ///
    ++    /// [`TxQueue`]: aster_virtio::device::socket::queue::TxQueue
    ++    /// [`DEFAULT_TX_BUF_SIZE`]: super::DEFAULT_TX_BUF_SIZE
    ++    tx_bytes_in_pending_queue: AtomicUsize,
     +}
     +
     +struct ConnectionState {
    @@ kernel/src/net/socket/vsock/transport/connection/mod.rs (new)
     +            bound_port,
     +            pollee,
     +            state: SpinLock::new(state),
    -+            available_tx_bytes: AtomicUsize::new(DEFAULT_PENDING_TX_BYTES),
    ++            tx_bytes_in_pending_queue: AtomicUsize::new(0),
     +        })
     +    }
     +
    @@ kernel/src/net/socket/vsock/transport/connection/send.rs (new)
     +    net::socket::{
     +        util::SendRecvFlags,
     +        vsock::transport::{
    -+            Connection,
    ++            Connection, DEFAULT_TX_BUF_SIZE,
     +            connection::{ConnectionInner, ConnectionState},
     +        },
     +    },
    @@ kernel/src/net/socket/vsock/transport/connection/send.rs (new)
     +            return Ok(0);
     +        }
     +
    -+        let buffer_bytes = self.inner.available_tx_bytes.load(Ordering::Relaxed);
    ++        let buffer_bytes =
    ++            DEFAULT_TX_BUF_SIZE - self.inner.tx_bytes_in_pending_queue.load(Ordering::Relaxed);
     +        if buffer_bytes == 0 {
     +            return_errno_with_message!(Errno::EAGAIN, "the pending queue is full");
     +        }
    @@ kernel/src/net/socket/vsock/transport/connection/send.rs (new)
     +
     +        let buffer_bytes = self
     +            .inner
    -+            .available_tx_bytes
    -+            .fetch_sub(num_bytes_in_pending, Ordering::Relaxed);
    -+        debug_assert!(buffer_bytes >= num_bytes_in_pending);
    ++            .tx_bytes_in_pending_queue
    ++            .fetch_add(num_bytes_in_pending, Ordering::Relaxed);
    ++        debug_assert!(buffer_bytes + num_bytes_in_pending <= DEFAULT_TX_BUF_SIZE);
     +
     +        state.consume_peer_credit(num_bytes);
     +
    @@ kernel/src/net/socket/vsock/transport/connection/send.rs (new)
     +impl TxCompletion for ReleasePendingBytes {
     +    fn on_pending_submit(self: Box<Self>) {
     +        self.connection
    -+            .available_tx_bytes
    -+            .fetch_add(self.bytes, Ordering::Relaxed);
    ++            .tx_bytes_in_pending_queue
    ++            .fetch_sub(self.bytes, Ordering::Relaxed);
     +        self.connection.pollee.notify(IoEvents::OUT);
     +    }
     +}
    @@ kernel/src/net/socket/vsock/transport/mod.rs (new)
     +// Reference: <https://elixir.bootlin.com/linux/v6.16.8/source/net/vmw_vsock/af_vsock.c#L138>
     +const DEFAULT_RX_BUF_SIZE: usize = 256 * 1024;
     +// Reference: <https://elixir.bootlin.com/linux/v6.16.8/source/net/vmw_vsock/af_vsock.c#L138>
    -+const DEFAULT_PENDING_TX_BYTES: usize = 256 * 1024;
    ++const DEFAULT_TX_BUF_SIZE: usize = 256 * 1024;
     +// Reference: <https://elixir.bootlin.com/linux/v6.16.8/source/include/linux/socket.h#L298>
     +const MAX_BACKLOG: usize = 4096;
     +
    @@ kernel/src/net/socket/vsock/transport/port.rs (new)
     +use alloc::collections::btree_map::BTreeMap;
     +
     +use crate::{
    -+    error::{Errno, Error},
    ++    error::{Errno, Error, return_errno_with_message},
     +    net::socket::vsock::{
     +        addr::{VMADDR_CID_ANY, VMADDR_PORT_ANY, VsockSocketAddr},
     +        transport::{
    @@ kernel/src/net/socket/vsock/transport/port.rs (new)
     +    },
     +    prelude::Result,
     +    process::signal::Pollee,
    -+    return_errno_with_message,
     +};
     +
     +/// An owned lease on a bound local vsock port; dropping the value releases the lease.
6:  2d9a38cc4 ! 6:  ceba8cc21 Reimplement vsock sockets
    @@ kernel/src/net/socket/vsock/stream/init.rs (new)
     +
     +    pub(super) fn bind(&mut self, addr: VsockSocketAddr) -> Result<()> {
     +        if self.bound_port.is_some() {
    -+            return_errno_with_message!(Errno::EINVAL, "the socket is already bound");
    ++            return_errno_with_message!(Errno::EINVAL, "the socket is already bound to an address");
     +        }
     +
     +        if let Ok(port) = u16::try_from(addr.port) {
    @@ kernel/src/net/socket/vsock/stream/mod.rs (new)
     +
     +        let mut state = self.lock_updated_state();
     +        let State::Init(init_stream) = state.as_mut() else {
    -+            return_errno_with_message!(Errno::EINVAL, "the socket is already bound or connected");
    ++            return_errno_with_message!(Errno::EINVAL, "the socket is already bound to an address");
     +        };
     +
     +        init_stream.bind(addr)
```

</details>

File: kernel/src/net/socket/vsock/transport/connection/recv.rs (hunk 3 above)
Comment (StevenJiang1110) [reply kernel/src/net/socket/vsock/transport/connection/recv.rs:32]: > We can address this problem in a separate PR?

Surely, we can address this problem separately.

File: kernel/src/net/socket/vsock/transport/connection/mod.rs (hunk 15 above)
Comment (StevenJiang1110) [reply kernel/src/net/socket/vsock/transport/connection/mod.rs]: Oh, sorry — I misunderstood the original code's intent.

> renamed DEFAULT_PENDING_TX_BYTES to DEFAULT_TX_BUF_SIZE and

The new name is indeed semantically clearer.

> The variable name may be a bit too long... But maybe it has better clarity.

A long variable name is fine as long as it is clear — the IDE takes care of the repetitive typing anyway. However, I think `tx_bytes_in_pending_queue` could simply be shortened to `pending_tx_bytes`, which should be unambiguous enough.

If you want to preserve the original semantics of `available_tx_bytes`, perhaps `tx_pending_queue_room` would work, as it conveys the idea of remaining capacity. I think either option is acceptable.

Comment (lrh2000) [reply kernel/src/net/socket/vsock/transport/connection/mod.rs]: > I think `tx_bytes_in_pending_queue` could simply be shortened to `pending_tx_bytes`, which should be unambiguous enough.

Agree. 

> If you want to preserve the original semantics of `available_tx_bytes`, perhaps `tx_pending_queue_room` would work, as it conveys the idea of remaining capacity. I think either option is acceptable.

I made this change for another reason: we may need to set the maximum TX buffer size via a socket option. In that case, I guess having `pending_tx_bytes` is friendlier to use. Otherwise, we will have to use confusing logic to adjust the available room when userspace changes the buffer size.

> Oh, sorry — I misunderstood the original code's intent.

Thanks for the confirmation. So I will change it to `pending_tx_bytes` according to this discussion.

**Comment by lrh2000** [comment]
[Diff of the two new force pushes after the previous range-diff](https://github.com/asterinas/asterinas/compare/ceba8cc21b8d1170cab5f1e0cb36a6a8b4f1ebe5..29b8c452bc496dbe632f813a7467bcf401e52a44)

https://github.com/asterinas/asterinas/pull/3122#discussion_r3128430279 is left to a separate PR. Other comments should have been addressed.

Note that although I am not including regression tests in this PR, I ran the tests manually to confirm that my updated version is working. The branch containing the vsock regression tests can be viewed [here](https://github.com/lrh2000/asterinas/tree/vsock-manual).

**Comment by StevenJiang1110** [comment]
@tatetian, this PR needs your further review.

**Review by tatetian — APPROVED** [review]
LGTM. Thanks for the contribution!
