### PR TITLE
Fix the fstatat syscall with empty filename

### LINKED ISSUE #533: The behavior of `fstatat` with an empty filename is wrong
According to the manul of `fstatat` syscall:
If pathname is an empty string, operate on the file referred to by `dirfd` (which may have been obtained using the `open()`.  In this case, dirfd can refer to any type of file, not just a directory, and the behavior of `fstatat()` is similar to that of `fstat()`.

Our current implementation is incorrect because the file descriptor may not necessarily be an inode file; it could simply be a `FileLike` object.

### PR DESCRIPTION
**Pull request by liqinggd**
Fix #533

### CODE REVIEW

File: services/libs/aster-std/src/syscall/stat.rs [hunk 1]
```diff
@@ -53,12 +53,18 @@ pub fn sys_fstatat(
         "dirfd = {}, filename = {:?}, stat_buf_ptr = 0x{:x}, flags = {:?}",
         dirfd, filename, stat_buf_ptr, flags
     );
+
+    if filename.is_empty() {
+        if !flags.contains(StatFlags::AT_EMPTY_PATH) {
```
Comment (tatetian) [inline services/libs/aster-std/src/syscall/stat.rs:58]: > flags can either be 0, or include one or more of the following flags ORed:
>
> AT_NO_AUTOMOUNT (since Linux 2.6.38)
Don't automount the terminal ("basename") component of pathname if it is a directory that is an automount point. > This allows the caller to gather attributes of an automount point (rather than the location it would mount). This flag can be used in tools that scan directories to prevent mass-automounting of a directory of automount points. The AT_NO_AUTOMOUNT flag has no effect if the mount point has already been mounted over.
>
> AT_SYMLINK_NOFOLLOW
> If pathname is a symbolic link, do not dereference it: instead return information about the link itself, like [lstat](https://linux.die.net/man/2/lstat)(2). (By default, fstatat() dereferences symbolic links, like [stat](https://linux.die.net/man/2/stat)(2).)

The man page of [fstatat](https://linux.die.net/man/2/fstatat) does not mention this flag.

Comment (liqinggd) [reply services/libs/aster-std/src/syscall/stat.rs:58]: The manual in https://man7.org/linux/man-pages/man2/lstat.2.html mentions the flag. After I checked the code of Linux, it uses the flag.
```
	if (flags & ~(AT_SYMLINK_NOFOLLOW | AT_NO_AUTOMOUNT | AT_EMPTY_PATH |
		      AT_STATX_SYNC_TYPE))
		return -EINVAL;
```

Comment (tatetian) [reply services/libs/aster-std/src/syscall/stat.rs:58]: Thanks for the explanation!

**Review by tatetian — COMMENTED** [review]
I am cool with this PR. Need to fix the conflict though.

**Comment by liqinggd** [comment]
> I am cool with this PR. Need to fix the conflict though.
Done

**Review by tatetian — APPROVED** [review]
LGTM. Thanks for the contribution!
