### PR TITLE
Fix OSDK and ostd_macro panic problems

### LINKED ISSUE #2957: OSDK-based OS doesn't run at all
I'm following the [OSDK User Guide](https://asterinas.github.io/book/osdk/guide/index.html).

Basically I created an OS project and tried running it:

```bash
cargo osdk new --kernel myos && myos
cargo osdk new mylib
cargo osdk run
```

Then it panics:

```
grub-mkrescue: warning: cannot open directory `/usr/local/grub/share/locale': No such file or directory.
xorriso 1.5.4 : RockRidge filesystem manipulator, libburnia project.

Drive current: -outdev 'stdio:/myos/target/osdk/myos-osdk-bin.iso'
Media current: stdio file, overwriteable
Media status : is blank
Media summary: 0 sessions, 0 data blocks, 0 data, 16.4g free
Added to ISO image: directory '/'='/tmp/grub.fje5aS'
xorriso : UPDATE :     298 files added in 1 seconds
Added to ISO image: directory '/'='/myos/target/osdk/iso_root'
xorriso : UPDATE :     302 files added in 1 seconds
ISO image produced: 15145 sectors
Written to medium : 15145 sectors at LBA 0
Writing to 'stdio:/myos/target/osdk/myos-osdk-bin.iso' completed successfully.

qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID[eax=01h].ECX.pcid [bit 17]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID[eax=01h].ECX.tsc-deadline [bit 24]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID[eax=07h,ecx=00h].EBX.hle [bit 4]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID[eax=07h,ecx=00h].EBX.invpcid [bit 10]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID[eax=07h,ecx=00h].EBX.rtm [bit 11]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID[eax=07h,ecx=00h].EBX.avx512f [bit 16]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID[eax=07h,ecx=00h].EBX.avx512dq [bit 17]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID[eax=07h,ecx=00h].EBX.avx512cd [bit 28]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID[eax=07h,ecx=00h].EBX.avx512bw [bit 30]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID[eax=07h,ecx=00h].EBX.avx512vl [bit 31]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID[eax=07h,ecx=00h].ECX.avx512vbmi [bit 1]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID[eax=07h,ecx=00h].ECX.avx512vbmi2 [bit 6]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID[eax=07h,ecx=00h].ECX.gfni [bit 8]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID[eax=07h,ecx=00h].ECX.vpclmulqdq [bit 10]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID[eax=07h,ecx=00h].ECX.avx512vnni [bit 11]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID[eax=07h,ecx=00h].ECX.avx512bitalg [bit 12]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID[eax=07h,ecx=00h].ECX.avx512-vpopcntdq [bit 14]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID[eax=07h,ecx=00h].EDX.spec-ctrl [bit 26]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID[eax=07h,ecx=00h].EDX.ssbd [bit 31]
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID[eax=0Dh,ecx=01h].EAX.xsavec [bit 1]
3h3h3hBdsDxe: loading Boot0001 "UEFI QEMU DVD-ROM QM00005 " from PciRoot(0x0)/Pci(0x1F,0x2)/Sata(0x2,0xFFFF,0x0)
BdsDxe: starting Boot0001 "UEFI QEMU DVD-ROM QM00005 " from PciRoot(0x0)/Pci(0x1F,0x2)/Sata(0x2,0xFFFF,0x0)
WARNING: no console will be available to OS

error: no suitable video mode found.

Hello world from guest kernel!
Non-resettable panic! PanicInfo {
    message: called `Option::unwrap()` on a `None` value,
    location: Location {
        file: "/myos/src/lib.rs",
        line: 6,
        column: 1,
    },
    can_unwind: true,
    force_no_backtrace: false,
}
Printing stack trace:
   1: fn 0xffffffff880e3090 - pc 0xffffffff880e30db / registers:

     rax 0xffffffff88049cf8; rdx 0xffffffff88139392; rcx  0x1000002010014fe; rbx 0xffffffff80000000;
     rsi 0xffffffff88049d18; rdi 0xffffffff88220771; rbp                0x0; rsp 0xffffffff88049de0;

   2: fn 0xffffffff880e7e30 - pc 0xffffffff880e7eb3 / registers:

     rax 0xffffffff88049cf8; rdx 0xffffffff88139392; rcx  0x1000002010014fe; rbx 0xffffffff80000000;
     rsi 0xffffffff88049d18; rdi 0xffffffff88220771; rbp                0x0; rsp 0xffffffff88049e00;

   3: fn 0xffffffff8804b020 - pc 0xffffffff8804b02a / registers:

     rax 0xffffffff88049cf8; rdx 0xffffffff88139392; rcx  0x1000002010014fe; rbx 0xffffffff80000000;
     rsi 0xffffffff88049d18; rdi 0xffffffff88220771; rbp                0x0; rsp 0xffffffff88049e70;

   4: fn 0xffffffff88201900 - pc 0xffffffff88201946 / registers:

     rax 0xffffffff88049cf8; rdx 0xffffffff88139392; rcx  0x1000002010014fe; rbx 0xffffffff80000000;
     rsi 0xffffffff88049d18; rdi 0xffffffff88220771; rbp                0x0; rsp 0xffffffff88049e80;

   5: fn 0xffffffff882018d0 - pc 0xffffffff882018f6 / registers:

     rax 0xffffffff88049cf8; rdx 0xffffffff88139392; rcx  0x1000002010014fe; rbx 0xffffffff80000000;
     rsi 0xffffffff88049d18; rdi 0xffffffff88220771; rbp                0x0; rsp 0xffffffff88049ec0;

   6: fn 0xffffffff881f2a00 - pc 0xffffffff881f2a15 / registers:

     rax 0xffffffff88049cf8; rdx 0xffffffff88139392; rcx  0x1000002010014fe; rbx 0xffffffff80000000;
     rsi 0xffffffff88049d18; rdi 0xffffffff88220771; rbp                0x0; rsp 0xffffffff88049ee0;

   7: fn 0xffffffff880c8460 - pc 0xffffffff880c84ae / registers:

     rax 0xffffffff88049cf8; rdx 0xffffffff88139392; rcx  0x1000002010014fe; rbx 0xffffffff80000000;
     rsi 0xffffffff88049d18; rdi 0xffffffff88220771; rbp                0x0; rsp 0xffffffff88049ef0;

   8: fn 0xffffffff880caf00 - pc 0xffffffff880caf06 / registers:

     rax 0xffffffff88049cf8; rdx 0xffffffff88139392; rcx  0x1000002010014fe; rbx 0xffffffff80000000;
     rsi 0xffffffff88049d18; rdi 0xffffffff88220771; rbp                0x0; rsp 0xffffffff88049f50;

   9: fn 0xffffffff8809e050 - pc 0xffffffff8809e056 / registers:

     rax 0xffffffff88049cf8; rdx 0xffffffff88139392; rcx  0x1000002010014fe; rbx 0xffffffff80000000;
     rsi 0xffffffff88049d18; rdi 0xffffffff88220771; rbp                0x0; rsp 0xffffffff88049f60;

  10: fn 0xffffffff8807d090 - pc 0xffffffff8807d0a2 / registers:

     rax 0xffffffff88049cf8; rdx 0xffffffff88139392; rcx  0x1000002010014fe; rbx 0xffffffff80000000;
     rsi 0xffffffff88049d18; rdi 0xffffffff88220771; rbp                0x0; rsp 0xffffffff88049f70;

  11: fn 0xffffffff8811ebc0 - pc 0xffffffff8811ebcb / registers:

     rax 0xffffffff88049cf8; rdx 0xffffffff88139392; rcx  0x1000002010014fe; rbx 0xffffffff80000000;
     rsi 0xffffffff88049d18; rdi 0xffffffff88220771; rbp                0x0; rsp 0xffffffff88049f80;

  12: fn 0xffffffff880f9840 - pc 0xffffffff880f9921 / registers:

     rax 0xffffffff88049cf8; rdx 0xffffffff88139392; rcx  0x1000002010014fe; rbx 0xffffffff80000000;
     rsi 0xffffffff88049d18; rdi 0xffffffff88220771; rbp                0x0; rsp 0xffffffff88049f90;

  13: fn                0x0 - pc 0xffffffff880c4fcc / registers:

     rax 0xffffffff88049cf8; rdx 0xffffffff88139392; rcx  0x1000002010014fe; rbx 0xffffffff80000000;
     rsi 0xffffffff88049d18; rdi 0xffffffff88220771; rbp                0x0; rsp 0xffffffff8804a000;
```

You can check out
* the generated `myos` project: https://github.com/os-checker/myos
* CI result: https://github.com/os-checker/myos/actions/runs/21777126461/job/62835408342

Edit: Wait, it successfully prints stuff, but panics due to the default video mode.

Edit2: `cd mylib && cargo osdk test` successfully runs the test.

### PR DESCRIPTION
**Pull request by StevenJiang1110**
Fixes #2957.

# Root Cause

The panic reported in #2957 occurs because the `ostd::main` macro calls `yield_now` after invoking the user-provided main function:

https://github.com/asterinas/asterinas/blob/0f57097ae8251fe7d66c28d3b82e97d2501b7a2f/ostd/libs/ostd-macros/src/lib.rs#L33-L36

Inside `yield_now`, the global scheduler is accessed. However, if no scheduler has been initialized, the unwrap panics:

https://github.com/asterinas/asterinas/blob/0f57097ae8251fe7d66c28d3b82e97d2501b7a2f/ostd/src/task/scheduler/mod.rs#L557-L559

# Changes

This PR contains three commits that address the scheduler panic along with two related issues:

1. Fix `cargo osdk new` when `OSDK_LOCAL_DEV` is set. When `OSDK_LOCAL_DEV` is set, the newly created kernel crate should depend on OSTD from the local path instead of from crates.io.

2. Fix the scheduler panic by introducing a lazy singleton accessor. Instead of accessing and unwrapping the SCHEDULER static directly, all call sites now go through a `scheduler_singleton` method that lazily initializes the scheduler with a default FIFO implementation if no custom scheduler has been injected. This prevents similar panics in the future.

3. Replace` unreachable!` with `poweroff` in `ostd::main`. The code after `yield_now` in `ostd::main` was marked as unreachable, but it is reachable when the user-provided main function does not spawn any tasks. This commit replaces the `unreachable!` call with `poweroff`, which also fixes a failure in the OSDK tests.

### CODE REVIEW

**Comment by StevenJiang1110** [comment]
The two CI failure is not related to this PR, the main branch also reports these two failures. 

https://github.com/asterinas/asterinas/actions/runs/21969411255/job/63467158181

https://github.com/asterinas/asterinas/actions/runs/21969411221/job/63478883624

I am also trying to work on one of them.

File: ostd/src/task/scheduler/mod.rs [hunk 1]
```diff
@@ -108,8 +110,29 @@ pub fn enable_preemption_on_cpu() {
...
+/// is lazily initialized and used.
+fn scheduler_singleton() -> &'static dyn Scheduler<Task> {
+    if let Some(scheduler) = SCHEDULER.get() {
+        return *scheduler;
+    }
+
+    fifo_scheduler::init();
+    *SCHEDULER
+        .get()
+        .expect("SCHEDULER should be initialized after fifo_scheduler::init()")
```
Comment (lrh2000) [inline ostd/src/task/scheduler/mod.rs]: This is racy (looks like Copilot already points it out). Admittedly, race conditions might not matter at this point since the scheduler doesn't even exist yet. However, I think that avoiding race conditions will make the code more elegant.

`Once::call_once` will return a reference to the value and the closure will only be called if the value does not exist yet. I think we can find a way to use it and remove this `expect`.

File: ostd/src/task/scheduler/mod.rs [hunk 2]
```diff
@@ -83,6 +83,8 @@ use crate::{
 /// This function can only be called once and must be called during the initialization phase of kernel,
 /// before any [`Task`]-related APIs are invoked.
 pub fn inject_scheduler(scheduler: &'static dyn Scheduler<Task>) {
+    assert!(SCHEDULER.get().is_none());
+
     SCHEDULER.call_once(|| scheduler);
```
Comment (lrh2000) [inline ostd/src/task/scheduler/mod.rs]: Same. We can set a boolean variable in the closure to indicate whether the scheduler has been initialized, which is always race-free.

Also, consider updating the doc comments and add a "# Panics" section?

File: ostd/libs/ostd-macros/src/lib.rs [hunk 3]
```diff
@@ -51,22 +49,29 @@ pub fn main(_attr: TokenStream, item: TokenStream) -> TokenStream {
...
     )
     .into()
 }
 
+fn ostd_main_body(main_fn_name: &Ident) -> proc_macro2::TokenStream {
+    quote! {
+        let _: () = #main_fn_name();
+        ::ostd::task::Task::yield_now();
+        ::core::assert!(::ostd::task::Task::current().is_none());
+        ::ostd::power::poweroff(::ostd::power::ExitCode::Success)
```
Comment (lrh2000) [inline ostd/libs/ostd-macros/src/lib.rs]:
```suggestion
        ::ostd::power::poweroff(::ostd::power::ExitCode::Success);
```

File: ostd/src/task/scheduler/mod.rs [hunk 4]
```diff
@@ -82,8 +82,19 @@ use crate::{
 ///
 /// This function can only be called once and must be called during the initialization phase of kernel,
 /// before any [`Task`]-related APIs are invoked.
+///
+/// # Panics
+///
+/// This function panics if a scheduler has already been injected,
```
Comment (lrh2000) [inline ostd/src/task/scheduler/mod.rs:89]: It seems that this line of the old doc comments is too long?
```rust
/// This function can only be called once and must be called during the initialization phase of kernel,
```

Try breaking it to align it with the length of the newly added document comments.

File: ostd/src/task/scheduler/mod.rs [hunk 5]
```diff
@@ -108,8 +119,26 @@ pub fn enable_preemption_on_cpu() {
...
+/// and falls back to a default FIFO scheduler if none has been injected.
 static SCHEDULER: Once<&'static dyn Scheduler<Task>> = Once::new();
 
+/// Returns the global scheduler.
+///
+/// If a scheduler has already been injected (e.g., by a custom scheduler),
+/// it is returned directly. Otherwise, a default FIFO scheduler
+/// is lazily initialized and used.
+///
+/// Initialization is atomic: `SCHEDULER.call_once` guarantees that even if
```
Comment (lrh2000) [inline ostd/src/task/scheduler/mod.rs]: Metion `` [`Once::call_once`] `` instead of the implementation details (i.e, `SCHEDULER.call_once`).
