### PR TITLE
Reimplement reading cstring from user space

### LINKED ISSUE #664: [BUG] API fopen doesn't work
I wrote a simple program using the fopen api that worked fine on linux, but reported an error on asterinas

### PR DESCRIPTION
**Pull request by StevenJiang1110**
Fix #664.

### CODE REVIEW

File: services/libs/aster-std/src/util/mod.rs [hunk 1]
```diff
@@ -4,37 +4,52 @@ use crate::prelude::*;
...
+/// Write value of `Pod` type to user space of current process.
 pub fn write_val_to_user<T: Pod>(dest: Vaddr, val: &T) -> Result<()> {
     let current = current!();
     let root_vmar = current.root_vmar();
     Ok(root_vmar.write_val(dest, val)?)
 }
 
-/// read a cstring from user, the length of cstring should not exceed max_len(include null byte)
+/// Read a cstring from user space, the length of cstring should not exceed max_len(include null byte).
+/// Further, the whole string should be in exact one mapping, it cannot cross the mapping boundary.
```
Comment (tatetian) [inline services/libs/aster-std/src/util/mod.rs:37]: Please polish the English writing.

File: services/libs/aster-std/src/util/mod.rs [hunk 2]
```diff
@@ -4,37 +4,52 @@ use crate::prelude::*;
...
+///
+/// FIXME: should we allow that a string can cross the mapping boundary?
 pub fn read_cstring_from_user(addr: Vaddr, max_len: usize) -> Result<CString> {
-    let mut buffer = vec![0u8; max_len];
-    read_bytes_from_user(addr, &mut buffer)?;
+    let vm_mapping = {
```
Comment (tatetian) [inline services/libs/aster-std/src/util/mod.rs:41]: So what is the motivation behind replacing the old English with the new one?

Comment (StevenJiang1110) [reply services/libs/aster-std/src/util/mod.rs:42]: This is because in the syscall, when a C string is passed from the user space, typically only the starting address is provided, not the length. 

The previous implementation of `read_cstring_from_user` first reads a sequence of bytes and then finding the first occurrence of `\0` to convert it into a C string. `max_len` was introduced to control the length of this sequence of bytes. 

However, it was later discovered that if the value of `max_len` is too large and extends beyond the mapping boundary, an error would occur during the byte reading step as it would read into an area without content. Therefore, this PR aims to ensure the successful reading of bytes in all cases.

File: kernel/aster-nix/src/util/mod.rs [hunk 3]
```diff
@@ -5,37 +5,53 @@ use aster_frame::vm::VmIo;
...
+        root_vmar.get_vm_mapping(addr)?
+    };
+
+    let max_read_len = {
+        let max_len_in_mapping = vm_mapping.map_to_addr() + vm_mapping.map_size() - addr;
+        max_len.min(max_len_in_mapping)
+    };
+
+    let mut buffer = vec![0u8; max_read_len];
+    vm_mapping.read_bytes(addr - vm_mapping.map_to_addr(), &mut buffer)?;
```
Comment (junyang-zh) [inline kernel/aster-nix/src/util/mod.rs:55]: Seems not a good idea: strings tend to be much shorter than `max_len` or the length of mapping. Here it reads at least `min(max_len, max_len_in_mapping)`, which may read a lot of useless bytes. We should devise a method to early stop on null terminator while reading.

Also, long `Vec`s are horrible... but such usages scatters through our codebase now. We may design some copy-less patterns in the future.

Comment (StevenJiang1110) [reply kernel/aster-nix/src/util/mod.rs]: Thanks for your comment!

> strings tend to be much shorter than max_len or the length of mapping. Here it reads at least min(max_len, max_len_in_mapping), which may read a lot of useless bytes. We should devise a method to early stop on the null terminator while reading.

The new implementation solves this problem. It won't copy so many bytes as before. Referring to [the Linux implementation](https://elixir.bootlin.com/linux/v6.0.9/source/lib/strncpy_from_user.c#L28), the new implementation will at first copy a usize(8 bytes) at a time, and then copy a byte at a time, until it finds the final `\0` byte.

Comment (StevenJiang1110) [reply kernel/aster-nix/src/util/mod.rs]: > Also, long, infallible Vecs are horrible... but such usages scatters through our codebase now. We may design some copy-less patterns in the future.

I quite agree. 

1. For the infallible heap allocation, @cchanging has developed a reservation-based method, but it doesn't seem to be mature enough for use in Asterinas at present.
2. A copy-less design is exactly what we need! We often perform excessive data copying, which undoubtedly impacts performance in both the network and fs subsystems. We have considered implementing `VmReader` and `VmWriter` for `Vmar`, similar to what has been done for `VmFrame` and `VmSegment`. This approach would allow us to delay actual data copying and minimize the introduction of temporary buffers. However, the situation with Vmar is different from that of VmFrame or VmSegment. If you have any insights or ideas regarding this issue, we can discuss it later.

File: kernel/aster-nix/src/util/mod.rs [hunk 4]
```diff
@@ -5,37 +5,85 @@ use aster_frame::vm::VmIo;
...
+
+        if byte == 0 {
+            return Ok(CString::from(CStr::from_bytes_until_nul(&bytes)?));
+        }
+
+        read_addr += core::mem::size_of::<u8>();
+        remain -= core::mem::size_of::<u8>();
+    }
+
+    return_errno_with_message!(Errno::EFAULT, "Fails to read CString from user");
```
Comment (junyang-zh) [inline kernel/aster-nix/src/util/mod.rs:88]:
```suggestion
    let mut addr = addr;
    let mut buffer = Vec::<u8>::new();
    // Handle the first few bytes to make addr aligned
    while (addr % size_of::<usize>()) != 0 && buffer.len() < max_len {
        let byte = read_val_from_user::<u8>(addr)?;
        buffer.push(byte);
        if byte == 0 {
            return Ok(CString::from(CStr::from_bytes_until_nul(&buffer)?));
        }
        addr += 1;
    }
    // Handle the rest of the bytes in bulk
    fn dup_magic_byte(byte: u8) -> isize {
        let mut byte = byte as usize;
        for _ in 0..size_of::<usize>() {
            byte |= byte << 8;
        }
        byte as isize
    }
    let himagic = dup_magic_byte(0x80);
    let lomagic = dup_magic_byte(0x01);
    while (buffer.len() + size_of::<usize>()) < max_len {
        let word = read_val_from_user::<usize>(addr)?;
        buffer.extend_from_slice(&word.to_ne_bytes());
        if (word as isize - lomagic) & !(word as isize) & himagic != 0 {
            return Ok(CString::from(CStr::from_bytes_until_nul(&buffer)?));
        }
        addr += size_of::<usize>();
    }
    // Handle the last few bytes
    while buffer.len() < max_len {
        let byte = read_val_from_user::<u8>(addr)?;
        buffer.push(byte);
        if byte == 0 {
            return Ok(CString::from(CStr::from_bytes_until_nul(&buffer)?));
        }
        addr += 1;
    }
    // Max length exceeded when finding the null terminator
    return_errno_with_message!(Errno::EFAULT, "Fails to read CString from user");
```

File: kernel/aster-nix/src/util/mod.rs [hunk 5]
```diff
@@ -5,37 +5,85 @@ use aster_frame::vm::VmIo;
...
 
-/// read a cstring from user, the length of cstring should not exceed max_len(include null byte)
+/// Read a C string from the user space of the current process.
+/// The length of the string should not exceed `max_len`,
+/// including the final `\0` byte.
+///
+/// This implementation is inspired by
+/// the `do_strncpy_from_user` function in Linux kernel.
+/// The original Linux implementation can be found at:
+/// <https://elixir.bootlin.com/linux/v6.0.9/source/lib/strncpy_from_user.c#L28>
```
Comment (junyang-zh) [inline kernel/aster-nix/src/util/mod.rs:45]: LOL, you didn't find the most clever implementation!
I am trying out some advanced Github feature. You can quickly apply this suggestion.

```suggestion
/// The magical algorithm used here is adapted from strlen.c in glibc, reducing
/// 4 branch dependencies to 1, enabling the compiler to optimize the loop
/// more efficiently.
```

**Review by junyang-zh — CHANGES_REQUESTED** [review]
I have an idea.

**Comment by StevenJiang1110** [comment]
> I have an idea.

@junyang-zh, I noticed your suggested change in the email, but I couldn't find it on GitHub. Therefore, I made the change and committed it again. You can review the updated changes.

The algorithm for determining whether a usize contains a zero byte is quite fascinating! I also discovered its version in the kernel, which can be found [here](https://elixir.bootlin.com/linux/v6.0.9/source/include/asm-generic/word-at-a-time.h#L93). To align with the kernel's naming convention, I have updated the names of methods and variables.

**Comment by junyang-zh** [comment]
Checkout my version, which is simpler and more robust.
```rust

/// Read a C string from the user space of the current process.
/// The length of the string should not exceed `max_len`,
/// including the final `\0` byte.
pub fn read_cstring_from_user(addr: Vaddr, max_len: usize) -> Result<CString> {
    let mut buffer = Vec::<u8>::new();
    let mut addr = addr;
    macro_rules! try_read_bytes_from_user_while {
        ($cond:expr) => {
            while $cond {
                let byte = read_val_from_user::<u8>(addr)?;
                buffer.push(byte);
                if byte == 0 {
                    return Ok(CString::from_vec_with_nul(buffer).unwrap());
                }
                addr += 1;
            }
        };
    }
    // Handle the first few bytes to make addr aligned
    try_read_bytes_from_user_while!(addr % size_of::<usize>() != 0 && buffer.len() < max_len);
    // Handle the rest of the bytes in bulk
    let himagic = usize::from_le_bytes([0x80; size_of::<usize>()]);
    let lomagic = usize::from_le_bytes([0x01; size_of::<usize>()]);
    while (buffer.len() + size_of::<usize>()) <= max_len {
        let word = read_val_from_user::<usize>(addr)?;
        if word.wrapping_sub(lomagic) & !word & himagic != 0 {
            for byte in word.to_ne_bytes() {
                buffer.push(byte);
                if byte == 0 {
                    return Ok(CString::from_vec_with_nul(buffer).unwrap());
                }
            }
        } else {
            buffer.extend_from_slice(&word.to_ne_bytes());
        }
        addr += size_of::<usize>();
    }
    // Handle the last few bytes that are not enough for a word
    try_read_bytes_from_user_while!(buffer.len() < max_len);
    // Maximum length exceeded when finding the null terminator
    return_errno_with_message!(Errno::EFAULT, "Fails to read CString from user");
}
```
Your implementation at `3d2c859` fails when UTF-8 encodings are used (that bytes does not range from 0 to 127).

**Comment by tatetian** [comment]
@junyang-zh Need your green light before merging this PR.

File: kernel/aster-nix/src/util/mod.rs [hunk 6]
```diff
@@ -1,41 +1,111 @@
...
+    let mut buffer: Vec<u8> = Vec::with_capacity(max_len);
+    let mut cur_addr = addr;
+
+    macro_rules! read_one_byte_at_a_time_while {
+        ($cond:expr) => {
+            while $cond {
+                let byte = read_val_from_user::<u8>(cur_addr)?;
+                buffer.push(byte);
+                if byte == 0 {
+                    return Ok(CString::from_vec_with_nul(buffer)?);
```
Comment (junyang-zh) [inline kernel/aster-nix/src/util/mod.rs:62]: Maybe we could just unwrap `CString::from_vec_with_nul(buffer)` since `byte == 0`. Indeed the function cannot fail. If it fails this is a bad system state. Returning to the user as `E2BIG` when this happens seems not the right way.

I suggest:
```rust
return Ok(CString::from_vec_with_nul(buffer).except("We provided 0 but no 0 is found"));
```

to look as if we care about error handling.

**Review by junyang-zh — COMMENTED** [review]
LGTM except a thing to discuss.

**Review by junyang-zh — APPROVED** [review]
Looks good to me now!

**Review by tatetian — APPROVED** [review]
LGTM. Thanks for the contribution!
