### PR TITLE
Fix memory leak of Task

### LINKED ISSUE #1491: All tasks are leaked
### Describe the bug

I conducted something similar with #966 , but profiling the page allocater this time. Here's the trace of page allocations that does not get recycled after the parent reaped the child.

Is tasks not getting recycled at all?

mem_trace

[mem_trace](https://github.com/user-attachments/assets/2cd9d8c8-2376-4cb4-a698-f2347180034a)

To answer if tasks are not getting recycled, here I added debug prints to the drop function of `Task`:

```
~ # ./test/fork_c/fork
Building a new task, arcptr: 0xffff8000784fb210
before fork
Building a new task, arcptr: 0xffff8000784f8e10
after fork: Hello from child
after fork: Hello from parent
~ # ./test/fork_c/fork
Building a new task, arcptr: 0xffff8000784f9f10
before fork
Building a new task, arcptr: 0xffff80007851bb10
after fork: Hello from child
after fork: Hello from parent
~ # ./test/fork_c/fork
Building a new task, arcptr: 0xffff8000784f8c10
before fork
Building a new task, arcptr: 0xffff80007851a810
after fork: Hello from child
after fork: Hello from parent
~ # ./test/fork_c/fork
Building a new task, arcptr: 0xffff80007851b910
before fork
Building a new task, arcptr: 0xffff800078519510
after fork: Hello from child
after fork: Hello from parent
~ # 
```

Seems not getting dropped.

`park_current` may be a leaking point. If you print the strong count of the current task (the idle task), it steadily goes up:

<details><summary>Details</summary>
<p>

```
   _   ___ _____ ___ ___ ___ _  _   _   ___
  /_\ / __|_   _| __| _ \_ _| \| | /_\ / __|
 / _ \\__ \ | | | _||   /| || .` |/ _ \\__ \
/_/ \_\___/ |_| |___|_|_\___|_|\_/_/ \_\___/


<add_thread>: tid: 1 strong count: 2, weak count: 0
[posix_thread] building a new task, arcptr: 0xffff80007846e210
[processor] Taking task, arcptr: 0xffff80007846e210, strong: 5, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842db10, strong: 2, weak: 1
~ # [processor] Taking task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Taking task, arcptr: 0xffff80007842ca10, strong: 7, weak: 1
[processor] Dropping task, arcptr: 0xffff80007846e210, strong: 7, weak: 1
[processor] Taking task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Taking task, arcptr: 0xffff80007842c910, strong: 7, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842ca10, strong: 7, weak: 1
[processor] Taking task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Taking task, arcptr: 0xffff80007842ca10, strong: 8, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842c910, strong: 7, weak: 1
[processor] Taking task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Taking task, arcptr: 0xffff80007842c910, strong: 8, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842ca10, strong: 8, weak: 1
[processor] Taking task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Taking task, arcptr: 0xffff80007842ca10, strong: 9, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842c910, strong: 8, weak: 1
[processor] Taking task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Taking task, arcptr: 0xffff80007842c910, strong: 9, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842ca10, strong: 9, weak: 1
[processor] Taking task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Taking task, arcptr: 0xffff80007842ca10, strong: 10, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842c910, strong: 9, weak: 1
[processor] Taking task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Taking task, arcptr: 0xffff80007842c910, strong: 10, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842ca10, strong: 10, weak: 1
[processor] Taking task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Taking task, arcptr: 0xffff80007842ca10, strong: 11, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842c910, strong: 10, weak: 1
[processor] Taking task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Taking task, arcptr: 0xffff80007842c910, strong: 11, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842ca10, strong: 11, weak: 1
[processor] Taking task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Taking task, arcptr: 0xffff80007842ca10, strong: 12, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842c910, strong: 11, weak: 1
[processor] Taking task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Taking task, arcptr: 0xffff80007842c910, strong: 12, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842ca10, strong: 12, weak: 1
[processor] Taking task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Taking task, arcptr: 0xffff80007842ca10, strong: 13, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842c910, strong: 12, weak: 1
[processor] Taking task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Taking task, arcptr: 0xffff80007842c910, strong: 13, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842ca10, strong: 13, weak: 1
[processor] Taking task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Taking task, arcptr: 0xffff80007842ca10, strong: 14, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842c910, strong: 13, weak: 1
[processor] Taking task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Taking task, arcptr: 0xffff80007842c910, strong: 14, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842ca10, strong: 14, weak: 1
[processor] Taking task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Taking task, arcptr: 0xffff80007842ca10, strong: 15, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842c910, strong: 14, weak: 1
[processor] Taking task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Taking task, arcptr: 0xffff80007842c910, strong: 15, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842ca10, strong: 15, weak: 1
[processor] Taking task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Taking task, arcptr: 0xffff80007842ca10, strong: 16, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842c910, strong: 15, weak: 1
[processor] Taking task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Taking task, arcptr: 0xffff80007842c910, strong: 16, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842ca10, strong: 16, weak: 1
[processor] Taking task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Taking task, arcptr: 0xffff80007842ca10, strong: 17, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842c910, strong: 16, weak: 1
[processor] Taking task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Taking task, arcptr: 0xffff80007842c910, strong: 17, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842ca10, strong: 17, weak: 1
[processor] Taking task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Taking task, arcptr: 0xffff80007842ca10, strong: 18, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842c910, strong: 17, weak: 1
[processor] Taking task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Taking task, arcptr: 0xffff80007842c910, strong: 18, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842ca10, strong: 18, weak: 1
[processor] Taking task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Taking task, arcptr: 0xffff80007842ca10, strong: 19, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842c910, strong: 18, weak: 1
[processor] Taking task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Taking task, arcptr: 0xffff80007842c910, strong: 19, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842ca10, strong: 19, weak: 1
[processor] Taking task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Taking task, arcptr: 0xffff80007842ca10, strong: 20, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842c910, strong: 19, weak: 1
[processor] Taking task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Taking task, arcptr: 0xffff80007842c910, strong: 20, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842ca10, strong: 20, weak: 1
[processor] Taking task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Taking task, arcptr: 0xffff80007842ca10, strong: 21, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842c910, strong: 20, weak: 1
[processor] Taking task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Taking task, arcptr: 0xffff80007842c910, strong: 21, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842ca10, strong: 21, weak: 1
[processor] Taking task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Taking task, arcptr: 0xffff80007842ca10, strong: 22, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842c910, strong: 21, weak: 1
[processor] Taking task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Taking task, arcptr: 0xffff80007842c910, strong: 22, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842ca10, strong: 22, weak: 1
[processor] Taking task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Taking task, arcptr: 0xffff80007842ca10, strong: 23, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842c910, strong: 22, weak: 1
[processor] Taking task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Taking task, arcptr: 0xffff80007842c910, strong: 23, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842ca10, strong: 23, weak: 1
[processor] Taking task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Taking task, arcptr: 0xffff80007842ca10, strong: 24, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842c910, strong: 23, weak: 1
[processor] Taking task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Taking task, arcptr: 0xffff80007842c910, strong: 24, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842ca10, strong: 24, weak: 1
[processor] Taking task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Taking task, arcptr: 0xffff80007842ca10, strong: 25, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842c910, strong: 24, weak: 1
[processor] Taking task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
[processor] Dropping task, arcptr: 0xffff80007842cb10, strong: 6, weak: 1
```

</p>
</details>

### PR DESCRIPTION
**Pull request by jellllly420**
Fix #1491 but not completely without #1512 (See https://github.com/asterinas/asterinas/issues/1491#issuecomment-2436722230 and https://github.com/asterinas/asterinas/issues/1491#issuecomment-2439183169).

The problem and solution are the same with @lrh2000 's #821.

### CODE REVIEW

**Comment by jellllly420** [comment]
@boterinas rerun

**Comment by jellllly420** [comment]
@boterinas rerun

**Comment by jellllly420** [comment]
@boterinas rerun

**Comment by jellllly420** [comment]
@boterinas rerun

File: ostd/src/task/mod.rs [hunk 1]
```diff
@@ -159,6 +159,7 @@ impl TaskOptions {
                 .take()
                 .expect("task function is `None` when trying to run");
             task_func();
+            drop(current_task);
```
Comment (tatetian) [inline ostd/src/task/mod.rs:162]: Add a comment to highlight the significance of this drop.

```rust

            // Manually drop all the on-stack variables to prevent memory leakage!
            // This is needed because `scheduler::exit_current()` will never return.
            drop(current_task);

            scheduler::exit_current();
```

I think the return value of the `exit_current` method should be changed to `!`.

**Review by tatetian — APPROVED** [review]
LGTM. Thanks for the contribution!
