### PR TITLE
Validate futex address alignment before waking robust futexes

### LINKED ISSUE #2805: Reachable assertion in `atomic_load` with unaligned `futex_addr`
### Describe the bug
`wake_robust_futex` uses `VmReader::atomic_load::<u32>()`, which asserts `cursor.is_aligned()` in `ostd/src/mm/io.rs`.
The futex address is computed as `entry_ptr + futex_offset` in `RobustListHead::futex_addr`.
If userspace provides a `futex_offset` that makes the futex address misaligned (e.g., `+1`), the kernel calls `atomic_load` on an unaligned address during `exit_group`, triggering the assertion.

### To Reproduce
Compile and run the program:
```C
// PoC: trigger VmReader::atomic_load alignment assert via robust list exit handling.
// Build with the toolchain used for userland programs in Asterinas.

#define _GNU_SOURCE
#include <errno.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <sys/mman.h>
#include <sys/syscall.h>
#include <unistd.h>

struct robust_list {
    uintptr_t next;
};

struct robust_list_head {
    struct robust_list list;
    long futex_offset;
    uintptr_t list_op_pending;
};

int main(void) {
    size_t page = 4096;
    uint8_t *buf = mmap(NULL, page, PROT_READ | PROT_WRITE,
                        MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
    if (buf == MAP_FAILED) {
        perror("mmap");
        return 1;
    }

    // Place one robust_list entry inside the mapping.
    struct robust_list *entry = (struct robust_list *)(buf + 0x100);
    entry->next = (uintptr_t)entry; // Single-entry circular list.

    struct robust_list_head head;
    memset(&head, 0, sizeof(head));
    head.list.next = (uintptr_t)entry;
    head.futex_offset = 1;          // Forces misaligned futex address.
    head.list_op_pending = 0;

    long ret = syscall(SYS_set_robust_list, &head, sizeof(head));
    if (ret != 0) {
        fprintf(stderr, "set_robust_list failed: %ld (errno=%d)\n", ret, errno);
        return 1;
    }

    // Trigger exit path that walks robust list and hits wake_robust_futex.
    syscall(SYS_exit_group, 0);
    _exit(0);
}
```

### Environment
- Official docker asterinas/asterinas:0.16.2-20251211
- Asterinas version: main c4e8bf2c

### Logs
```
~ # /etc/robust_list_misaligned_poc.c 
[     8.114] ERROR: Uncaught panic:
        assertion failed: cursor.is_aligned()
        at /root/asterinas/ostd/src/mm/io.rs:625
        on CPU 0 by thread Some(Thread { task: (Weak), data: Any { .. }, is_exited: true, cpu_affinity: AtomicIdSet { bits: [1], phantom: PhantomData<ostd::cpu::id::CpuId> }, sched_attr: SchedAttr { policy: SchedPolicyState { kind: AtomicSchedPolicyKind(2), policy: UnsafeCell { .. } }, last_cpu: AtomicCpuId(0), real_time: RealTimeAttr { prio: 99, time_slice: 31484940 }, fair: FairAttr { weight: 1024, pending_weight: 0, vruntime: 272979056 } } })
Printing stack trace:
   1: fn 0xffffffff889bede0 - pc 0xffffffff889bee2b / registers:

     rax 0xffffdfffffd705b8; rdx 0xffffffff889e4302; rcx  0x10000020100e364; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88be17e0; rbp                0x0; rsp 0xffffdfffffd706a0;

   2: fn 0xffffffff8804be20 - pc 0xffffffff8804c61d / registers:

     rax 0xffffdfffffd705b8; rdx 0xffffffff889e4302; rcx  0x10000020100e364; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88be17e0; rbp                0x0; rsp 0xffffdfffffd706c0;

   3: fn 0xffffffff8804dd30 - pc 0xffffffff8804dd3a / registers:

     rax 0xffffdfffffd705b8; rdx 0xffffffff889e4302; rcx  0x10000020100e364; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88be17e0; rbp                0x0; rsp 0xffffdfffffd70a90;

   4: fn 0xffffffff8804b000 - pc 0xffffffff8804b00a / registers:

     rax 0xffffdfffffd705b8; rdx 0xffffffff889e4302; rcx  0x10000020100e364; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88be17e0; rbp                0x0; rsp 0xffffdfffffd70aa0;

   5: fn 0xffffffff88af8920 - pc 0xffffffff88af8966 / registers:

     rax 0xffffdfffffd705b8; rdx 0xffffffff889e4302; rcx  0x10000020100e364; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88be17e0; rbp                0x0; rsp 0xffffdfffffd70ab0;

   6: fn 0xffffffff88af88f0 - pc 0xffffffff88af8916 / registers:

     rax 0xffffdfffffd705b8; rdx 0xffffffff889e4302; rcx  0x10000020100e364; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88be17e0; rbp                0x0; rsp 0xffffdfffffd70af0;

   7: fn 0xffffffff886de790 - pc 0xffffffff886de7ee / registers:

     rax 0xffffdfffffd705b8; rdx 0xffffffff889e4302; rcx  0x10000020100e364; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88be17e0; rbp                0x0; rsp 0xffffdfffffd70b10;

   8: fn 0xffffffff880d54a0 - pc 0xffffffff880d5704 / registers:

     rax 0xffffdfffffd705b8; rdx 0xffffffff889e4302; rcx  0x10000020100e364; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88be17e0; rbp                0x0; rsp 0xffffdfffffd70b50;

   9: fn 0xffffffff8824caf0 - pc 0xffffffff8824cd3a / registers:

     rax 0xffffdfffffd705b8; rdx 0xffffffff889e4302; rcx  0x10000020100e364; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88be17e0; rbp                0x0; rsp 0xffffdfffffd70df0;

  10: fn 0xffffffff8824c480 - pc 0xffffffff8824c7ab / registers:

     rax 0xffffdfffffd705b8; rdx 0xffffffff889e4302; rcx  0x10000020100e364; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88be17e0; rbp                0x0; rsp 0xffffdfffffd70f80;

  11: fn 0xffffffff8824c450 - pc 0xffffffff8824c477 / registers:

     rax 0xffffdfffffd705b8; rdx 0xffffffff889e4302; rcx  0x10000020100e364; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88be17e0; rbp                0x0; rsp 0xffffdfffffd710b0;

  12: fn 0xffffffff880acc10 - pc 0xffffffff880acc3f / registers:

     rax 0xffffdfffffd705b8; rdx 0xffffffff889e4302; rcx  0x10000020100e364; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88be17e0; rbp                0x0; rsp 0xffffdfffffd710c0;

  13: fn 0xffffffff88475530 - pc 0xffffffff8849f724 / registers:

     rax 0xffffdfffffd705b8; rdx 0xffffffff889e4302; rcx  0x10000020100e364; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88be17e0; rbp                0x0; rsp 0xffffdfffffd710f0;

  14: fn 0xffffffff88472750 - pc 0xffffffff884727ea / registers:

     rax 0xffffdfffffd705b8; rdx 0xffffffff889e4302; rcx  0x10000020100e364; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88be17e0; rbp                0x0; rsp 0xffffdfffffd844f0;

  15: fn 0xffffffff8833ddb0 - pc 0xffffffff8833e661 / registers:

     rax 0xffffdfffffd705b8; rdx 0xffffffff889e4302; rcx  0x10000020100e364; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88be17e0; rbp                0x0; rsp 0xffffdfffffd84650;

  16: fn 0xffffffff8833e820 - pc 0xffffffff8833e87e / registers:

     rax 0xffffdfffffd705b8; rdx 0xffffffff889e4302; rcx  0x10000020100e364; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88be17e0; rbp                0x0; rsp 0xffffdfffffd84b40;

  17: fn 0xffffffff8806b490 - pc 0xffffffff8806b4be / registers:

     rax 0xffffdfffffd705b8; rdx 0xffffffff889e4302; rcx  0x10000020100e364; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88be17e0; rbp                0x0; rsp 0xffffdfffffd84cf0;

  18: fn 0xffffffff8806ac80 - pc 0xffffffff8806acc6 / registers:

     rax 0xffffdfffffd705b8; rdx 0xffffffff889e4302; rcx  0x10000020100e364; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88be17e0; rbp                0x0; rsp 0xffffdfffffd84d20;

  19: fn 0xffffffff8846b9b0 - pc 0xffffffff8846b9dc / registers:

     rax 0xffffdfffffd705b8; rdx 0xffffffff889e4302; rcx  0x10000020100e364; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88be17e0; rbp                0x0; rsp 0xffffdfffffd84d90;

  20: fn 0xffffffff8806b0c0 - pc 0xffffffff8806b0ff / registers:

     rax 0xffffdfffffd705b8; rdx 0xffffffff889e4302; rcx  0x10000020100e364; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88be17e0; rbp                0x0; rsp 0xffffdfffffd84dd0;

  21: fn 0xffffffff8833e7e0 - pc 0xffffffff8833e807 / registers:

     rax 0xffffdfffffd705b8; rdx 0xffffffff889e4302; rcx  0x10000020100e364; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88be17e0; rbp                0x0; rsp 0xffffdfffffd84f40;

  22: fn 0xffffffff882776c0 - pc 0xffffffff882776dd / registers:

     rax 0xffffdfffffd705b8; rdx 0xffffffff889e4302; rcx  0x10000020100e364; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88be17e0; rbp                0x0; rsp 0xffffdfffffd84f80;

  23: fn 0xffffffff889312b0 - pc 0xffffffff889312d5 / registers:

     rax 0xffffdfffffd705b8; rdx 0xffffffff889e4302; rcx  0x10000020100e364; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88be17e0; rbp                0x0; rsp 0xffffdfffffd84fa0;

  24: fn 0xffffffff889bc130 - pc 0xffffffff889bc1b4 / registers:

     rax 0xffffdfffffd705b8; rdx 0xffffffff889e4302; rcx  0x10000020100e364; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88be17e0; rbp                0x0; rsp 0xffffdfffffd84fd0;

  25: fn 0xffffffff88974d08 - pc 0xffffffff88974d11 / registers:

     rax 0xffffdfffffd705b8; rdx 0xffffffff889e4302; rcx  0x10000020100e364; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88be17e0; rbp                0x0; rsp 0xffffdfffffd85000;


     rax 0xffffdfffffd705b8; rdx 0xffffffff889e4302; rcx  0x10000020100e364; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88be17e0; rbp                0x0; rsp 0xffffdfffffd85008;

OSDK] The kernel seems panicked. Parsing stack trace for source lines:
(  1) ostd::panic::print_stack_trace
          at /root/asterinas/ostd/src/panic.rs:113
(  2) aster_nix::thread::oops::panic_handler
          at /root/asterinas/kernel/src/thread/oops.rs:130
(  3) __ostd_panic_handler
          at ??:?
(  4) __rustc::rust_begin_unwind
          at 7rqnf5etait8fxxiit4kgd2ru:?
(  5) core::panicking::panic_fmt
          at ??:?
(  6) core::panicking::panic
          at ??:?
(  7) <ostd::mm::io::VmReader>::atomic_load::<u32>
          at ??:?
(  8) aster_nix::process::posix_thread::robust_list::wake_robust_futex
          at /root/asterinas/kernel/src/process/posix_thread/robust_list.rs:144
(  9) aster_nix::process::posix_thread::exit::wake_robust_list
          at /root/asterinas/kernel/src/process/posix_thread/exit.rs:146
( 10) aster_nix::process::posix_thread::exit::exit_internal
          at /root/asterinas/kernel/src/process/posix_thread/exit.rs:75
( 11) aster_nix::process::posix_thread::exit::do_exit_group
          at /root/asterinas/kernel/src/process/posix_thread/exit.rs:37
( 12) aster_nix::syscall::exit_group::sys_exit_group
          at /root/asterinas/kernel/src/syscall/exit_group.rs:13
( 13) aster_nix::syscall::arch::syscall_dispatch
          at /root/asterinas/kernel/src/syscall/mod.rs:203
( 14) aster_nix::syscall::handle_syscall
          at /root/asterinas/kernel/src/syscall/mod.rs:374
( 15) aster_nix::thread::task::create_new_user_task::{closure#0}
          at /root/asterinas/kernel/src/thread/task.rs:95
( 16) aster_nix::thread::task::create_new_user_task::{closure#1}
          at /root/asterinas/kernel/src/thread/task.rs:126
( 17) unwinding::panicking::catch_unwind::do_call::<aster_nix::thread::task::create_new_user_task::{closure#1}, ()>
          at /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/unwinding-0.2.8/src/panicking.rs:56
( 18) unwinding::panicking::catch_unwind::<unwinding::panic::RustPanic, (), aster_nix::thread::task::create_new_user_task::{closure#1}>
          at /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/unwinding-0.2.8/src/panicking.rs:42
( 19) unwinding::panic::catch_unwind::<(), aster_nix::thread::task::create_new_user_task::{closure#1}>
          at /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/unwinding-0.2.8/src/panic.rs:87
( 20) aster_nix::thread::oops::catch_panics_as_oops::<aster_nix::thread::task::create_new_user_task::{closure#1}, ()>
          at /root/asterinas/kernel/src/thread/oops.rs:55
( 21) aster_nix::thread::task::create_new_user_task::{closure#2}
          at /root/asterinas/kernel/src/thread/task.rs:131
( 22) <aster_nix::thread::task::create_new_user_task::{closure#2} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
          at /root/.rustup/toolchains/nightly-2025-12-06-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250
( 23) <alloc::boxed::Box<dyn core::ops::function::FnOnce<(), Output = ()> + core::marker::Send> as core::ops::function::FnOnce<()>>::call_once
          at /root/.rustup/toolchains/nightly-2025-12-06-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2206
( 24) kernel_task_entry
          at /root/asterinas/ostd/src/task/mod.rs:196
( 25) kernel_task_entry_wrapper
          at ??:?
```

### PR DESCRIPTION
**Pull request by Marsman1996**
Fix #2805

Refer to the alignment check in `handle_futex_death` in Linux, which is called by `exit_robust_list`.
https://github.com/torvalds/linux/blob/04688d6128b7c8b4ccec2913e7f2ff1c4437da96/kernel/futex/core.c#L1022-L1024

And `wake_robust_list` in Asterinas 
> corresponds to Linux's `exit_robust_list`. Errors are silently ignored.

### CODE REVIEW

File: kernel/src/process/posix_thread/exit.rs [hunk 1]
```diff
@@ -143,6 +143,9 @@ fn wake_robust_list(thread_local: &ThreadLocal, tid: Tid) {
 
     trace!("exit: wake up the rubust list: {:?}", list_head);
     for futex_addr in list_head.futexes() {
+        if futex_addr % align_of::<Vaddr>() != 0 {
```
[the remark this answers is not in the document]
Comment (Marsman1996) [reply kernel/src/process/posix_thread/exit.rs]: You are absoluty right!
My bad

File: kernel/src/process/posix_thread/exit.rs [hunk 2]
```diff
@@ -143,6 +143,9 @@ fn wake_robust_list(thread_local: &ThreadLocal, tid: Tid) {
...
+            return;
```
[the remark this answers is not in the document]
Comment (Marsman1996) [reply kernel/src/process/posix_thread/exit.rs:149]: You are probobly wrong, I guess

**Comment by Marsman1996** [comment]
Copilot is impressive to prevent me from the alignment size error.

However, I think the second suggestion is not right.

In `exit_robust_list` in Linux:
https://github.com/torvalds/linux/blob/04688d6128b7c8b4ccec2913e7f2ff1c4437da96/kernel/futex/core.c#L1154-L1195
```C
while (entry != &head->list) {
		/*
		 * Fetch the next entry in the list before calling
		 * handle_futex_death:
		 */
		rc = fetch_robust_entry(&next_entry, &entry->next, &next_pi);
		/*
		 * A pending lock might already be on the list, so
		 * don't process it twice:
		 */
		if (entry != pending) {
			if (handle_futex_death((void __user *)entry + futex_offset,
						curr, pi, HANDLE_DEATH_LIST))
				return;
```

And in `handle_futex_death`

https://github.com/torvalds/linux/blob/04688d6128b7c8b4ccec2913e7f2ff1c4437da96/kernel/futex/core.c#L1022-L1024
```C
/* Futex address must be 32bit aligned */
	if ((((unsigned long)uaddr) % sizeof(*uaddr)) != 0)
		return -1;
```

So if there is a error, the while loop will end and return.

File: kernel/src/process/posix_thread/exit.rs [hunk 3]
```diff
@@ -143,6 +143,9 @@ fn wake_robust_list(thread_local: &ThreadLocal, tid: Tid) {
 
     trace!("exit: wake up the rubust list: {:?}", list_head);
     for futex_addr in list_head.futexes() {
+        if futex_addr % align_of::<u32>() != 0 {
```
Comment (lrh2000) [inline kernel/src/process/posix_thread/exit.rs]: https://github.com/asterinas/asterinas/blob/c4e8bf2c21aa8ad4b272dbc1d68461fa3b42004e/kernel/src/process/posix_thread/robust_list.rs#L132-L135

I think we can fix the code here, by checking something like:
https://github.com/asterinas/asterinas/blob/c4e8bf2c21aa8ad4b272dbc1d68461fa3b42004e/kernel/src/process/posix_thread/futex.rs#L540-L545

---

In addition, I don't think the Linux implementation checks for the zero address, and we don't check it in our `futex()` syscall implementation either. Given these two reasons, perhaps we should simply remove the zero address check? Checking the alignment should be sufficient.

File: kernel/src/process/posix_thread/exit.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (lrh2000) [reply kernel/src/process/posix_thread/exit.rs:149]: This seems to be a separate issue anyway. I think you're right, but the fix can be:
```rust
if let Err(err) = wake_robust_futex(..) {
    debug!(...);
    return;
}
```

File: kernel/src/process/posix_thread/exit.rs (hunk 3 above)
Comment (Marsman1996) [reply kernel/src/process/posix_thread/exit.rs]: You are absolutly right! 
Without zero address check, it will later throw a error like 
`page fault handler failed: addr: 0x0, err: Error { errno: EACCES, msg: Some("no VM mappings contain the page fault address") }`
and get caught by `if let Err(err) = ...`

File: kernel/src/process/posix_thread/exit.rs [hunk 4]
```diff
@@ -143,8 +143,13 @@ fn wake_robust_list(thread_local: &ThreadLocal, tid: Tid) {
...
     trace!("exit: wake up the rubust list: {:?}", list_head);
     for futex_addr in list_head.futexes() {
-        let _ = wake_robust_futex(futex_addr, tid)
-            .inspect_err(|err| debug!("exit: cannot wake up the robust futex: {:?}", err));
+        if let Err(err) = wake_robust_futex(futex_addr, tid) {
+            debug!(
+                "exit: cannot wake robust futex at {:?}: {:?}",
+                futex_addr, err
+            );
+            return;
```
Comment (lrh2000) [inline kernel/src/process/posix_thread/exit.rs:149]: I realized that this should be a `break` instead of a `return`? We can then ensure that the robust list is none and it makes sense since at least some futexes may already be woken up...

So either (1) change this to a `break`, or (2) change line 139 to `robust_list.take()` and remove the final `*robust_list = None`. It seems that the second option can result in simpler code.

This shouldn't have any practical impact because no one should access the robust list after the thread exit. I'm thinking that (1) having one more invariant for the dead process is slightly better and (2) if we clear the futex list after a full wakeup, then we should also clear it after a partial one.

File: kernel/src/process/posix_thread/robust_list.rs [hunk 5]
```diff
@@ -130,8 +130,11 @@ const FUTEX_TID_MASK: u32 = 0x3FFF_FFFF;
 /// `FUTEX_OWNER_DIED` and one waiter (if any) is woken.  
 /// If the futex is owned by another thread, the operation is canceled.
 pub fn wake_robust_futex(futex_addr: Vaddr, tid: Tid) -> Result<()> {
-    if futex_addr == 0 {
-        return_errno_with_message!(Errno::EINVAL, "invalid futext addr");
+    if !futex_addr.is_multiple_of(align_of::<u32>()) {
+        return_errno_with_message!(
+            Errno::EINVAL,
+            "the futex word is not aligend on a four-byte boundary"
```
Comment (lrh2000) [inline kernel/src/process/posix_thread/robust_list.rs]: Oh well, typo `aligend` -> `aligned`. Same for
https://github.com/asterinas/asterinas/blob/c4e8bf2c21aa8ad4b272dbc1d68461fa3b42004e/kernel/src/process/posix_thread/futex.rs#L540-L545

Could you fix them?

**Review by lrh2000 — COMMENTED** [review]
Thanks for the quick updates!

File: kernel/src/process/posix_thread/robust_list.rs (hunk 5 above)
Comment (Marsman1996) [reply kernel/src/process/posix_thread/robust_list.rs]: Roger 🫡
