### PR TITLE
Make kernel threads and posix threads in seperate tables

### LINKED ISSUE #1199: Reachable unwrap panic in `sys_timer_create()`
### Describe the bug
There is a reachable unwrap panic in `sys_timer_create()` at kernel/aster-nix/src/process/process_filter.rs:24 when make a `timer_create` syscall.

https://github.com/asterinas/asterinas/blob/0160a85ccd130c222ae9b8712b4102c726cba35c/kernel/aster-nix/src/syscall/timer_create.rs#L137

### To Reproduce
1. Compile a program which calls `timer_create`:
```C
#include <errno.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/mman.h>
#include <time.h>

int main() {
  void *addr = mmap(NULL, 4096, 0x3, MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
  timer_create(-3, 0x0, addr);

  return 0;
}
```
2. Run the compiled program in Asterinas.

### Expected behavior
Asterinas reports panic and is terminated.

### Environment
- Official docker asterinas/asterinas:0.6.2
- 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
- Asterinas version: main ce2af1eb

### Logs
```
~ # /root/timer_create.c
panicked at /root/asterinas/kernel/aster-nix/src/syscall/timer_create.rs:137:61:
called `Option::unwrap()` on a `None` value
Printing stack trace:
   1: fn 0xffffffff8878fa60 - pc 0xffffffff8878fa78 / registers:

     rax               0x12; rdx 0xffffffff88a22b28; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff8000013293f0;

   2: fn 0xffffffff8878f840 - pc 0xffffffff8878f9b8 / registers:

     rax               0x12; rdx 0xffffffff88a22b28; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff800001329400;

   3: fn 0xffffffff88049000 - pc 0xffffffff8804900a / registers:

     rax               0x12; rdx 0xffffffff88a22b28; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff800001329580;

   4: fn 0xffffffff889a3060 - pc 0xffffffff889a30e2 / registers:

     rax               0x12; rdx 0xffffffff88a22b28; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff800001329590;

   5: fn 0xffffffff889a3200 - pc 0xffffffff889a3240 / registers:

     rax               0x12; rdx 0xffffffff88a22b28; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff800001329620;

   6: fn 0xffffffff8898c7e0 - pc 0xffffffff8898c7f5 / registers:

     rax               0x12; rdx 0xffffffff88a22b28; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff800001329690;

   7: fn 0xffffffff8829e4b0 - pc 0xffffffff8829f859 / registers:

     rax               0x12; rdx 0xffffffff88a22b28; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff8000013296a0;

   8: fn 0xffffffff883a1240 - pc 0xffffffff883cb92f / registers:

     rax               0x12; rdx 0xffffffff88a22b28; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff800001329f30;

   9: fn 0xffffffff883a0f60 - pc 0xffffffff883a0fee / registers:

     rax               0x12; rdx 0xffffffff88a22b28; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff8000013403d0;

  10: fn 0xffffffff8835ac20 - pc 0xffffffff8835b79f / registers:

     rax               0x12; rdx 0xffffffff88a22b28; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff800001340570;

  11: fn 0xffffffff885caef0 - pc 0xffffffff885caefe / registers:

     rax               0x12; rdx 0xffffffff88a22b28; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff800001340f90;

  12: fn 0xffffffff887a5db0 - pc 0xffffffff887a5dc6 / registers:

     rax               0x12; rdx 0xffffffff88a22b28; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff800001340fb0;

  13: fn 0xffffffff887dd960 - pc 0xffffffff887dd9c9 / registers:

     rax               0x12; rdx 0xffffffff88a22b28; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff800001340fd0;

  14: fn                0x0 - pc                0x0 / registers:

     rax               0x12; rdx 0xffffffff88a22b28; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff800001341000;

[OSDK] The kernel seems panicked. Parsing stack trace for source lines:
(  1) /root/asterinas/ostd/src/panicking.rs:107
(  2) /root/asterinas/ostd/src/panicking.rs:59
(  3) 2aghao2n2kcoquuybdyjuveav:?
(  4) ??:?
(  5) /root/.rustup/toolchains/nightly-2024-06-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:220
(  6) ??:?
(  7) /root/.rustup/toolchains/nightly-2024-06-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:961
(  8) /root/asterinas/kernel/aster-nix/src/syscall/mod.rs:171
(  9) /root/asterinas/kernel/aster-nix/src/syscall/mod.rs:328
( 10) /root/asterinas/kernel/aster-nix/src/thread/task.rs:69
( 11) /root/.rustup/toolchains/nightly-2024-06-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:79
( 12) /root/.rustup/toolchains/nightly-2024-06-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2077
( 13) /root/asterinas/ostd/src/task/task/mod.rs:310
make: *** [Makefile:153: run] Error 1
```

### LINKED ISSUE #1244: Reachable unwrap panic in `read_clock()`
### Describe the bug
There is a reachable unwrap panic in `read_clock()` at kernel/src/syscall/clock_gettime.rs:141 when make a `clock_gettime` syscall with specific argument.

https://github.com/asterinas/asterinas/blob/aa77747f94c4b1cb1237ba52414642827a6efc25/kernel/src/syscall/clock_gettime.rs#L141

### To Reproduce
1. Compile a program which calls `clock_gettime`:
```C
#include <errno.h>
#include <stdio.h>
#include <sys/syscall.h>
#include <time.h>
#include <unistd.h>

int main() {
  clock_gettime(-10, 0x1);
  perror("clock_gettime");

  return 0;
}
```
2. Run the compiled program in Asterinas.

### Expected behavior
Asterinas reports panic and is terminated.

### Environment
- Official docker asterinas/asterinas:0.8.0
- 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
- Asterinas version: main aa77747f

### Logs

```
~ # /root/clock_gettime.c 
panicked at /root/asterinas/kernel/src/syscall/clock_gettime.rs:141:61:
called `Option::unwrap()` on a `None` value
Printing stack trace:
   1: fn 0xffffffff8880e1c0 - pc 0xffffffff8880e1d8 / registers:

     rax               0x12; rdx 0xffffffff88a3a1a0; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f6297c0;

   2: fn 0xffffffff8880dfa0 - pc 0xffffffff8880e118 / registers:

     rax               0x12; rdx 0xffffffff88a3a1a0; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f6297d0;

   3: fn 0xffffffff88049000 - pc 0xffffffff8804900a / registers:

     rax               0x12; rdx 0xffffffff88a3a1a0; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f629950;

   4: fn 0xffffffff889b0fb0 - pc 0xffffffff889b1032 / registers:

     rax               0x12; rdx 0xffffffff88a3a1a0; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f629960;

   5: fn 0xffffffff889b1150 - pc 0xffffffff889b1190 / registers:

     rax               0x12; rdx 0xffffffff88a3a1a0; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f6299f0;

   6: fn 0xffffffff8899a710 - pc 0xffffffff8899a725 / registers:

     rax               0x12; rdx 0xffffffff88a3a1a0; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f629a60;

   7: fn 0xffffffff884f2290 - pc 0xffffffff884f289f / registers:

     rax               0x12; rdx 0xffffffff88a3a1a0; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f629a70;

   8: fn 0xffffffff884f1d20 - pc 0xffffffff884f1d81 / registers:

     rax               0x12; rdx 0xffffffff88a3a1a0; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f629d30;

   9: fn 0xffffffff88161a50 - pc 0xffffffff8818d4ab / registers:

     rax               0x12; rdx 0xffffffff88a3a1a0; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f629f30;

  10: fn 0xffffffff88152f60 - pc 0xffffffff88152fee / registers:

     rax               0x12; rdx 0xffffffff88a3a1a0; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f6403d0;

  11: fn 0xffffffff88110380 - pc 0xffffffff88110eff / registers:

     rax               0x12; rdx 0xffffffff88a3a1a0; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f640570;

  12: fn 0xffffffff8845cb70 - pc 0xffffffff8845cb7e / registers:

     rax               0x12; rdx 0xffffffff88a3a1a0; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f640f90;

  13: fn 0xffffffff887cdc50 - pc 0xffffffff887cdc66 / registers:

     rax               0x12; rdx 0xffffffff88a3a1a0; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f640fb0;

  14: fn 0xffffffff887b0280 - pc 0xffffffff887b02e9 / registers:

     rax               0x12; rdx 0xffffffff88a3a1a0; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f640fd0;


     rax               0x12; rdx 0xffffffff88a3a1a0; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007f641000;

[OSDK] The kernel seems panicked. Parsing stack trace for source lines:
(  1) /root/asterinas/ostd/src/panicking.rs:106
(  2) /root/asterinas/ostd/src/panicking.rs:59
(  3) 89yvfinwjerz0clyodmhm6lzz:?
(  4) ??:?
(  5) /root/.rustup/toolchains/nightly-2024-06-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:220
(  6) ??:?
(  7) /root/.rustup/toolchains/nightly-2024-06-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:961
(  8) /root/asterinas/kernel/src/syscall/clock_gettime.rs:29
(  9) /root/asterinas/kernel/src/syscall/mod.rs:164
( 10) /root/asterinas/kernel/src/syscall/mod.rs:328
( 11) /root/asterinas/kernel/src/thread/task.rs:69
( 12) /root/.rustup/toolchains/nightly-2024-06-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:79
( 13) /root/.rustup/toolchains/nightly-2024-06-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2077
( 14) /root/asterinas/ostd/src/task/task/mod.rs:341
make: *** [Makefile:167: run] Error 1
```

### PR DESCRIPTION
**Pull request by StevenJiang1110**
Fixes #1199 
Fixes #1244

This PR establishes separate ID spaces for kernel threads and POSIX threads, with each stored in its own respective table. The original `thread_table::get_thread` function has been replaced with `thread_table::get_posix_thread`, preventing kernel threads from being accessed via syscalls. This change addresses the issues outlined in PRs #1321 and #1325.

Additionally, this PR resolves a memory leak issue by ensuring that kernel threads are properly removed from the thread table.

### CODE REVIEW

File: kernel/src/thread/mod.rs [hunk 1]
```diff
@@ -107,7 +108,12 @@ impl Thread {
...
-pub fn allocate_tid() -> Tid {
-    TID_ALLOCATOR.fetch_add(1, Ordering::SeqCst)
+/// Allocates a new tid for the new posix thread
+pub fn allocate_posix_tid() -> Tid {
+    POSIX_TID_ALLOCATOR.fetch_add(1, Ordering::SeqCst)
+}
+
+/// Allocates a new tid for the new kernel thread
+pub fn allocate_kernel_tid() -> Tid {
+    KERNEL_TID_ALLOCATOR.fetch_add(1, Ordering::SeqCst)
```
Comment (tatetian) [inline kernel/src/thread/mod.rs:118]: Are there any user of kernel TIDs? I am not convinced that kernel TIDs are useful in the first place. Holding a `Arc<Thread>` or `Weak<Thread>` is almost as space efficient as holding a `Tid`.

Comment (StevenJiang1110) [reply kernel/src/thread/mod.rs]: Kernel TIDs are never used except in some debug code. I have moved `Tid` from `Thread` to `PosixThread`, so kernel thread won't have Tids now.

File: kernel/src/thread/thread_table.rs [hunk 2]
```diff
@@ -1,21 +1,30 @@
 // SPDX-License-Identifier: MPL-2.0
 
+use keyable_arc::KeyableArc;
+
 use super::{Thread, Tid};
-use crate::prelude::*;
+use crate::{prelude::*, process::posix_thread::PosixThreadExt};
+
+static POSIX_THREAD_TABLE: SpinLock<BTreeMap<Tid, Arc<Thread>>> = SpinLock::new(BTreeMap::new());
+static KERNEL_THREAD_TABLE: SpinLock<BTreeSet<KeyableArc<Thread>>> = SpinLock::new(BTreeSet::new());
```
Comment (tatetian) [inline kernel/src/thread/thread_table.rs:9]: I suggest removing `KERNEL_THREAD_TABLE` for three reasons:

1. This table does not make sense. If a user already holds a `KeyableArc<Thread>`, which is same as `Arc<Thread>`, why does she want to query this table? A thread table is only useful when the key is TIDs so that a user can use TIDs to retrieve `Arc<Thread>`.
2. This table is not used by any one. The module does not provide a getter API.
3. This table introduces overheads when spawning and exiting threads, but we are now working hard to squeeze every bit of performance.

Comment (StevenJiang1110) [reply kernel/src/thread/thread_table.rs]: The kernel thread table has been removed. 

Initially, `Task` only held a `Weak<Thread>`. For POSIX threads, the Process held an `Arc<Thread>`, but in the case of kernel threads, there was no owner for `Thread` without the kernel thread table.

To address this, I modified the logic so that `Task` now holds an `Arc<Thread>`, while `Thread` only holds a `Weak<Task>`. This ensures that if a task is running, the corresponding kernel thread will not be dropped. As a result, the `Process` will now hold an `Arc<Task>`. This adjustment also enhances the performance of the `current_thread` macro a bit.

File: ostd/src/task/mod.rs [hunk 3]
```diff
@@ -166,7 +166,7 @@ impl TaskOptions {
     }
 
     /// Builds a new task without running it immediately.
-    pub fn build(self) -> Result<Arc<Task>> {
+    pub fn build(self) -> Result<Task> {
```
Comment (tatetian) [inline ostd/src/task/mod.rs:169]: Could you explain the rationale of this change?

File: kernel/src/thread/mod.rs [hunk 4]
```diff
@@ -45,20 +45,18 @@ impl Thread {
...
-            .data()
-            .downcast_ref::<Weak<Thread>>()?
-            .upgrade()
+        Self::from_task_data(&Task::current()?).cloned()
     }
 
-    pub(in crate::thread) fn task(&self) -> &Arc<Task> {
-        &self.task
+    /// Gets the Thread from task's data
+    pub fn from_task_data(task: &Arc<Task>) -> Option<&Arc<Self>> {
```
Comment (tatetian) [inline kernel/src/thread/mod.rs:52]: First of all, I suggest calling it `borrow_from_task` to make it more clear that the returned value is a reference, not an owned object.

Second, I suggest changing the return type from `Option<&Arc<Self>>` to `&Arc<Self>`. I checked all user code, they either call `unwrap` explicitly or assume that the conversion succeeds implicitly.

File: kernel/src/thread/kernel_thread.rs [hunk 5]
```diff
@@ -67,6 +41,32 @@ impl KernelThreadExt for Thread {
     }
 }
 
+/// Creates a new task of kernel thread, **NOT** run the thread.
+pub fn create_new_kernel_task(mut thread_options: ThreadOptions) -> Arc<Task> {
+    let task_fn = thread_options.take_func();
+    let thread_fn = move || {
+        task_fn();
+        let current_thread = current_thread!();
```
Comment (tatetian) [inline kernel/src/thread/kernel_thread.rs:49]: One interesting observation is that if we create a new strong reference to the current thread at the beginning of the closure, then we won't have to worry about a kernel thread being dropped when its code is sleeping.

```rust
    let thread_fn = move || {
        // Ensure that at least one instance of `Arc<Thread>` exists
        // as long as the thread starts executing.
        let current_thread = current_thread!();
        task_fn();
        // Ensures the thread is exit
        current_thread.exit();
    };
```

Therefore, you don't need to change from `Thread` holding `Task` into `Task` holding `Thread` simply because you need to prevent `Thread` from being dropped. You can decide who holds the strong reference to who from other angles such as performance.

File: kernel/src/thread/thread_table.rs [hunk 6]
```diff
@@ -1,12 +1,9 @@
 // SPDX-License-Identifier: MPL-2.0
 
-use keyable_arc::KeyableArc;
-
 use super::{Thread, Tid};
 use crate::{prelude::*, process::posix_thread::PosixThreadExt};
 
 static POSIX_THREAD_TABLE: SpinLock<BTreeMap<Tid, Arc<Thread>>> = SpinLock::new(BTreeMap::new());
-static KERNEL_THREAD_TABLE: SpinLock<BTreeSet<KeyableArc<Thread>>> = SpinLock::new(BTreeSet::new());
```
Comment (tatetian) [inline kernel/src/thread/thread_table.rs]: Now that `thread_table` only manages POSIX threads, I think this file should be moved to `process/posix_thread/`. And because the module belongs to `posix_thread`, the API can be simply named `get_thread` and `add_thread` (no posix).

File: ostd/src/task/mod.rs (hunk 3 above)
Comment (StevenJiang1110) [reply ostd/src/task/mod.rs:169]: This is because I need to use `Arc::new_cyclic` to pass `weak_task` to Thread when creating a new thread
```rust
fn create_new_kernel_task(....) -> Arc<Task>{
    Arc::new_cyclic(|weak_task| {
        let thread = Thread::new(weak_task.clone(), .......);
        TaskOptions::new(....).data(thread)
    })
}
```

File: kernel/src/thread/kernel_thread.rs (hunk 5 above)
Comment (StevenJiang1110) [reply kernel/src/thread/kernel_thread.rs:49]: Yes, from the performance perspective, I think the new version is also better. For example, the `current!` macro cost decreases from 38ns to 27ns(by avoiding an redundant Arc::clone)

**Review by tatetian — APPROVED** [review]
LGTM. Thanks for the contribution!
