### PR TITLE
Fix the nested bottom half

### LINKED ISSUE #1648: Kernel stack overflow triggered by keyboard interrupt storm in TTY
## Describe the bug

After fixing #1646, I tested the behavior of the Ctrl+Arrow keys in TTY again. This time, QEMU silently exits without any information. GDB also fails to break at the `exit_qemu` or `print_stack_trace` breakpoints.

By adding the `-no-shutdown` and `-no-reboot` options to QEMU, I was able to catch the `exit_qemu` breakpoint. I found that the init process exits normally, but it prints `malloc(): invalid size (unsorted)` before exiting.

### To Reproduce

Press random characters, then continuously press Ctrl+Arrow keys.

```txt
## make profile_server SMP=20
~ # dfasdf asdf asdf asdf asdf asdf asd fasdf asd fasdf asd fasf as fasd fasd f
dasfas fdsf dasf adsf sadf asdf asdf sadf asdf asdf asdf ads fasd fasdf asdf asd
f adsf asdf asd fasd fs fasd fs fas fas faf asd fas fsad fdsa fds fads fads fasd
fasd fasdf asdf asd fsa fasdf asf ds sd fs faf as fasf s asf sf as fsf sf sd fs
df asdf s s fsd asf ^C
~ # for i in `seq 100`; do echo $i; done
malloc(): invalid size (unsorted)
```

Stack trace obtained by adding `-no-shutdown` and `-no-reboot`:

```txt
#0  ostd::arch::x86::qemu::exit_qemu (exit_code=ostd::arch::x86::qemu::QemuExitCode::Failed) at src/arch/x86/qemu.rs:28
#1  0xffffffff882f62c2 in aster_nix::init_thread () at src/lib.rs:166
#2  0xffffffff8842f456 in core::ops::function::FnOnce::call_once<fn(), ()> ()
    at /root/.rustup/toolchains/nightly-2024-10-12-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250
#3  0xffffffff8842e6ce in core::ops::function::FnOnce::call_once<fn(), ()> ()
    at /root/.rustup/toolchains/nightly-2024-10-12-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250
#4  0xffffffff883ecb88 in alloc::boxed::{impl#48}::call_once<(), (dyn core::ops::function::Fn<(), Output=()> + core::marker::Send + core::marker::Sync), alloc::alloc::Global> (self=..., args=())
    at /root/.rustup/toolchains/nightly-2024-10-12-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2454
#5  0xffffffff883d3968 in unwinding::panicking::catch_unwind::do_call<alloc::boxed::Box<(dyn core::ops::function::Fn<(), Output=()> + core::marker::Send + core::marker::Sync), alloc::alloc::Global>, ()> (data=0xffffdffffff75bd8)
    at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/unwinding-0.2.4/src/panicking.rs:54
#6  0xffffffff883d5a08 in __rust_try ()
#7  0xffffffff883d38ce in unwinding::panicking::catch_unwind<unwinding::panic::RustPanic, (), alloc::boxed::Box<(dyn core::ops::function::Fn<(), Output=()> + core::marker::Send + core::marker::Sync), alloc::alloc::Global>> (f=...)
    at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/unwinding-0.2.4/src/panicking.rs:42
#8  0xffffffff8814b7e3 in unwinding::panic::catch_unwind<(), alloc::boxed::Box<(dyn core::ops::function::Fn<(), Output=()> + core::marker::Send + core::marker::Sync), alloc::alloc::Global>> (f=...)
    at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/unwinding-0.2.4/src/panic.rs:87
#9  0xffffffff88512470 in aster_nix::thread::oops::catch_panics_as_oops<alloc::boxed::Box<(dyn core::ops::function::Fn<(), Output=()> + core::marker::Send + core::marker::Sync), alloc::alloc::Global>, ()> (f=...) at src/thread/oops.rs:54
#10 0xffffffff880f2c42 in aster_nix::thread::kernel_thread::{impl#1}::build::{closure#0} () at src/thread/kernel_thread.rs:53
#11 0xffffffff8842e6f8 in core::ops::function::FnOnce::call_once<aster_nix::thread::kernel_thread::{impl#1}::build::{closure_env#0}, ()>
    () at /root/.rustup/toolchains/nightly-2024-10-12-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250
#12 0xffffffff8886e268 in alloc::boxed::{impl#48}::call_once<(), (dyn core::ops::function::FnOnce<(), Output=()> + core::marker::Send), alloc::alloc::Global> (self=..., args=())
    at /root/.rustup/toolchains/nightly-2024-10-12-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2454
#13 0xffffffff8881b07e in ostd::task::{impl#1}::build::kernel_task_entry () at src/task/mod.rs:178
#14 0x0000000000000000 in ?? ()
```

### Expected behavior

QEMU should not silently exit when pressing Ctrl+Arrow keys. If there is a bug, it should either print stack trace or hang instead of failing silently.

### Environment

- Docker: v0.9.4
- Commit: after fixing #1646.

### PR DESCRIPTION
**Pull request by lrh2000**
There are several issues in `call_irq_callback_functions` regarding the processing of the bottom half.

 - First, there is even a FIXME to note that `IN_INTERRUPT_CONTEXT` won't work if the interrupts are enabled in the middle! But the FIXME is apparently ignored when the bottom half support is added.
https://github.com/asterinas/asterinas/blob/6d3bb5a9d0b1d4d53e298402bc8fec57dc899f15/ostd/src/trap/handler.rs#L50
https://github.com/asterinas/asterinas/blob/6d3bb5a9d0b1d4d53e298402bc8fec57dc899f15/ostd/src/trap/handler.rs#L55

 - Second, the current implementation allows an unlimited number of nested interrupts, because the interrupts are _unconditionally_ re-enabled after the top half is processed. Another interrupt can come immediately, causing stack overflows.
    - See also the newly added comments in this PR:
```rust
    // We do not provide support for reentrant interrupt handlers. Otherwise, it's very hard to
    // guarantee the absence of stack overflows.
    //
    // As a concrete example, Linux once supported them in its early days, but has dropped support
    // for this very reason. See
    // <https://github.com/torvalds/linux/commit/d8bf368d0631d4bc2612d8bf2e4e8e74e620d0cc>.
    //
    // Nevertheless, we still need a counter to track the nested level because interrupts are
    // enabled while the bottom half is being processing. The counter cannot exceed two because the
    // bottom half cannot be reentrant for the same reason.
```

 - Third, we should disable preemption _before_ re-enabling the interrupts. Otherwise, race conditions can occur in the middle, triggering unexpected preemption.
https://github.com/asterinas/asterinas/blob/6d3bb5a9d0b1d4d53e298402bc8fec57dc899f15/ostd/src/trap/handler.rs#L37-L39

Another thing is that I don't think it's necessary to use `Box<dyn Fn>` for the bottom half handler, so I change it to `fn()`.

Fix #1648

### CODE REVIEW

**Review by tatetian — APPROVED** [review]
LGTM. Thanks for the contribution!

**Comment by tatetian** [comment]
@lrh2000 Could you investigate the reason of CI failures and see if they were caused by the changes introduced in this PR?

**Comment by tangruize** [comment]
With this fix, the bug in #1648 won't occur again.

File: ostd/src/arch/x86/trap/mod.rs [hunk 1]
```diff
@@ -214,42 +214,41 @@ impl UserContext {
...
+        Some(exception) => {
+            panic!(
+                "cannot handle kernel CPU exception: {:?}, trapframe: {:?}",
+                exception, f
+            );
+        }
+        None => {
+            KERNEL_INTERRUPT_NEST_LEVEL.add_assign(1);
+            call_irq_callback_functions(f, f.trap_num);
+            KERNEL_INTERRUPT_NEST_LEVEL.sub_assign(1);
```
Comment (tatetian) [inline ostd/src/arch/x86/trap/mod.rs:250]: You didn't mean to increase/decrease the nested level here, right? The `call_irq_callback_functions` function already includes this logic.

**Review by tatetian — COMMENTED** [review]
LGTM. Just one minor issue.

File: ostd/src/arch/x86/trap/mod.rs (hunk 1 above)
Comment (lrh2000) [reply ostd/src/arch/x86/trap/mod.rs:250]: `call_irq_callback_functions` increments/decrements `INTERRUPT_NEST_LEVEL` _instead of_ `KERNEL_INTERRUPT_NEST_LEVEL`. They are two different variables.

```rust
pub fn is_kernel_interrupted() -> bool {
    KERNEL_INTERRUPT_NEST_LEVEL.load() != 0
}
```
```rust
pub fn in_interrupt_context() -> bool {
    INTERRUPT_NESTED_LEVEL.load() != 0
}
```

Maybe the variable names are a bit confusing? I don't have a better idea, though.

Comment (tatetian) [reply ostd/src/arch/x86/trap/mod.rs:250]: I see... I thought they were the same counter...

Comment (tatetian) [reply ostd/src/arch/x86/trap/mod.rs:250]: I don't have any better idea, either. Could you make the two names consistent with each other? Renaming `KERNEL_INTERRUPT_NEST_LEVEL` to `KERNEL_INTERRUPT_NESTED_LEVEL` would be good.

**Comment by lrh2000** [comment]
@boterinas rerun

**Comment by lrh2000** [comment]
I don't see how this PR can be related to the network tests?

[Trial 1](https://github.com/asterinas/asterinas/actions/runs/12172009100/job/33949936240):
```
Start network test......
Client: Hello from client
Hello message sent
Hello message sent
Server: Hello from server
Error: The operation was canceled.
```

[Trial 2](https://github.com/asterinas/asterinas/actions/runs/12172009100/job/33951845397?pr=1668):
```
Start network test......

 Connection Failed 
make: *** [Makefile:195: run] Error 1
Error: Process completed with exit code 2.
```

And they're loopback network tests, which are largely unrelated to the IRQ mechanism. Just again, I cannot reproduce this in my local machine.

Checking if this problem exists in the latest main branch...

**Comment by tatetian** [comment]
> I don't see how this PR can be related to the network tests?
> 
> [Trial 1](https://github.com/asterinas/asterinas/actions/runs/12172009100/job/33949936240):
> 
> ```
> Start network test......
> Client: Hello from client
> Hello message sent
> Hello message sent
> Server: Hello from server
> Error: The operation was canceled.
> ```
> 
> [Trial 2](https://github.com/asterinas/asterinas/actions/runs/12172009100/job/33951845397?pr=1668):
> 
> ```
> Start network test......
> 
>  Connection Failed 
> make: *** [Makefile:195: run] Error 1
> Error: Process completed with exit code 2.
> ```
> 
> And they're loopback network tests, which are largely unrelated to the IRQ mechanism. ~Just again, I cannot reproduce this in my local machine.~ (I can reproduce it, but with a low probability.)
> 
> **EDIT:** This should be unrelated to this PR, as I have seen other PRs cause the [same CI failure](https://github.com/asterinas/asterinas/actions/runs/12163004274/job/33921191838).

Yes, I think so.
