### PR TITLE
Fix many wrong error codes and other buggy behavior in various MM syscalls

### LINKED ISSUE #2779: Reachable unwrap panic in `align_up` caused by large size in `mremap` and `msync`
### Describe the bug
Reachable unwrap in `align_up` at ostd/libs/align_ext/src/lib.rs:66 when calling `mremap` syscall with large `size` (i.e., `0xffffffffffffffff`), exactly the same as #1214.

https://github.com/asterinas/asterinas/blob/9c4f644bd9287da1815a13115fbdfa914d8426f0/kernel/src/syscall/mremap.rs#L47

https://github.com/asterinas/asterinas/blob/9c4f644bd9287da1815a13115fbdfa914d8426f0/ostd/libs/align_ext/src/lib.rs#L46-L72

### To Reproduce
1. Compile a program which calls `mremap`:
```C
#define _GNU_SOURCE
#include <errno.h>
#include <stdio.h>
#include <sys/mman.h>
#include <unistd.h>

int main(void) {
    unsigned long old_addr = 0;          // page-aligned
    unsigned long old_size = ~0UL;       // UINT64_MAX to overflow align_up
    unsigned long new_size = 4096;       // 1 page
    unsigned long flags = 0;             // no MREMAP_MAYMOVE/FIXED
    unsigned long new_addr = 0;          // ignored because flags=0

    printf("mremap(old_addr=0x%lx, old_size=%lu, new_size=%lu, flags=%lu)\n",
           old_addr, old_size, new_size, flags);
    void *ret = mremap((void *)old_addr, old_size, new_size, flags, (void *)new_addr);
    printf("mremap ret=%p errno=%d\n", ret, errno);
    return 0;
}

```
2. Run the compiled program in Asterinas.

### Environment
- Official docker asterinas/asterinas:0.16.2-20251211
- Asterinas version: main 9c4f644bd

### Logs
```
~ # /etc/mremap-size-overflow.c 
mremap(old_addr=0x0, old_size=18446744073709551615, new_size=4096, flags=0)
[    12.282] ERROR: Uncaught panic:
        called `Option::unwrap()` on a `None` value
        at /root/asterinas/ostd/libs/align_ext/src/lib.rs:66
        on CPU 0 by thread Some(Thread { task: (Weak), data: Any { .. }, is_exited: false, cpu_affinity: AtomicIdSet { bits: [1], phantom: PhantomData<ostd::cpu::id::CpuId> }, sched_attr: SchedAttr { policy: SchedPolicyState { kind: AtomicSchedPolicyKind(2), policy: UnsafeCell { .. } }, last_cpu: AtomicCpuId(0), real_time: RealTimeAttr { prio: 99, time_slice: 31489920 }, fair: FairAttr { weight: 1024, pending_weight: 0, vruntime: 304945550 } } })
Printing stack trace:
   1: fn 0xffffffff88953cf0 - pc 0xffffffff88953d3b / registers:

     rax 0xffffdfffffd70748; rdx 0xffffffff889b64f2; rcx  0x10000020100d1cf; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88bd6ff0; rbp                0x0; rsp 0xffffdfffffd70830;

   2: fn 0xffffffff8804c3d0 - pc 0xffffffff8804cbcd / registers:

     rax 0xffffdfffffd70748; rdx 0xffffffff889b64f2; rcx  0x10000020100d1cf; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88bd6ff0; rbp                0x0; rsp 0xffffdfffffd70850;

   3: fn 0xffffffff8804e080 - pc 0xffffffff8804e08a / registers:

     rax 0xffffdfffffd70748; rdx 0xffffffff889b64f2; rcx  0x10000020100d1cf; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88bd6ff0; rbp                0x0; rsp 0xffffdfffffd70c20;

   4: fn 0xffffffff8804b000 - pc 0xffffffff8804b00a / registers:

     rax 0xffffdfffffd70748; rdx 0xffffffff889b64f2; rcx  0x10000020100d1cf; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88bd6ff0; rbp                0x0; rsp 0xffffdfffffd70c30;

   5: fn 0xffffffff88af6f50 - pc 0xffffffff88af6f96 / registers:

     rax 0xffffdfffffd70748; rdx 0xffffffff889b64f2; rcx  0x10000020100d1cf; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88bd6ff0; rbp                0x0; rsp 0xffffdfffffd70c40;

   6: fn 0xffffffff88af6f20 - pc 0xffffffff88af6f46 / registers:

     rax 0xffffdfffffd70748; rdx 0xffffffff889b64f2; rcx  0x10000020100d1cf; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88bd6ff0; rbp                0x0; rsp 0xffffdfffffd70c80;

   7: fn 0xffffffff88add0a0 - pc 0xffffffff88add0b5 / registers:

     rax 0xffffdfffffd70748; rdx 0xffffffff889b64f2; rcx  0x10000020100d1cf; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88bd6ff0; rbp                0x0; rsp 0xffffdfffffd70ca0;

   8: fn 0xffffffff886b9f80 - pc 0xffffffff886ba073 / registers:

     rax 0xffffdfffffd70748; rdx 0xffffffff889b64f2; rcx  0x10000020100d1cf; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88bd6ff0; rbp                0x0; rsp 0xffffdfffffd70cb0;

   9: fn 0xffffffff882a89b0 - pc 0xffffffff882a8d25 / registers:

     rax 0xffffdfffffd70748; rdx 0xffffffff889b64f2; rcx  0x10000020100d1cf; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88bd6ff0; rbp                0x0; rsp 0xffffdfffffd70d20;

  10: fn 0xffffffff882a87f0 - pc 0xffffffff882a88dc / registers:

     rax 0xffffdfffffd70748; rdx 0xffffffff889b64f2; rcx  0x10000020100d1cf; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88bd6ff0; rbp                0x0; rsp 0xffffdfffffd70ff0;

  11: fn 0xffffffff882d76f0 - pc 0xffffffff882dfb53 / registers:

     rax 0xffffdfffffd70748; rdx 0xffffffff889b64f2; rcx  0x10000020100d1cf; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88bd6ff0; rbp                0x0; rsp 0xffffdfffffd710f0;

  12: fn 0xffffffff882d4190 - pc 0xffffffff882d422a / registers:

     rax 0xffffdfffffd70748; rdx 0xffffffff889b64f2; rcx  0x10000020100d1cf; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88bd6ff0; rbp                0x0; rsp 0xffffdfffffd844f0;

  13: fn 0xffffffff8809eaf0 - pc 0xffffffff8809f3a1 / registers:

     rax 0xffffdfffffd70748; rdx 0xffffffff889b64f2; rcx  0x10000020100d1cf; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88bd6ff0; rbp                0x0; rsp 0xffffdfffffd84650;

  14: fn 0xffffffff8809f560 - pc 0xffffffff8809f5be / registers:

     rax 0xffffdfffffd70748; rdx 0xffffffff889b64f2; rcx  0x10000020100d1cf; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88bd6ff0; rbp                0x0; rsp 0xffffdfffffd84b40;

  15: fn 0xffffffff8809ea60 - pc 0xffffffff8809ea8e / registers:

     rax 0xffffdfffffd70748; rdx 0xffffffff889b64f2; rcx  0x10000020100d1cf; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88bd6ff0; rbp                0x0; rsp 0xffffdfffffd84cf0;

  16: fn 0xffffffff8809e990 - pc 0xffffffff8809e9d6 / registers:

     rax 0xffffdfffffd70748; rdx 0xffffffff889b64f2; rcx  0x10000020100d1cf; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88bd6ff0; rbp                0x0; rsp 0xffffdfffffd84d20;

  17: fn 0xffffffff8818d0f0 - pc 0xffffffff8818d11c / registers:

     rax 0xffffdfffffd70748; rdx 0xffffffff889b64f2; rcx  0x10000020100d1cf; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88bd6ff0; rbp                0x0; rsp 0xffffdfffffd84d90;

  18: fn 0xffffffff8823c190 - pc 0xffffffff8823c1cf / registers:

     rax 0xffffdfffffd70748; rdx 0xffffffff889b64f2; rcx  0x10000020100d1cf; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88bd6ff0; rbp                0x0; rsp 0xffffdfffffd84dd0;

  19: fn 0xffffffff8809f520 - pc 0xffffffff8809f547 / registers:

     rax 0xffffdfffffd70748; rdx 0xffffffff889b64f2; rcx  0x10000020100d1cf; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88bd6ff0; rbp                0x0; rsp 0xffffdfffffd84f40;

  20: fn 0xffffffff8807f720 - pc 0xffffffff8807f73d / registers:

     rax 0xffffdfffffd70748; rdx 0xffffffff889b64f2; rcx  0x10000020100d1cf; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88bd6ff0; rbp                0x0; rsp 0xffffdfffffd84f80;

  21: fn 0xffffffff889cd540 - pc 0xffffffff889cd565 / registers:

     rax 0xffffdfffffd70748; rdx 0xffffffff889b64f2; rcx  0x10000020100d1cf; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88bd6ff0; rbp                0x0; rsp 0xffffdfffffd84fa0;

  22: fn 0xffffffff889b6d80 - pc 0xffffffff889b6e04 / registers:

     rax 0xffffdfffffd70748; rdx 0xffffffff889b64f2; rcx  0x10000020100d1cf; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88bd6ff0; rbp                0x0; rsp 0xffffdfffffd84fd0;

  23: fn 0xffffffff88962a15 - pc 0xffffffff88962a1e / registers:

     rax 0xffffdfffffd70748; rdx 0xffffffff889b64f2; rcx  0x10000020100d1cf; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88bd6ff0; rbp                0x0; rsp 0xffffdfffffd85000;


     rax 0xffffdfffffd70748; rdx 0xffffffff889b64f2; rcx  0x10000020100d1cf; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88bd6ff0; rbp                0x0; rsp 0xffffdfffffd85008;

OSDK] The kernel seems panicked. Parsing stack trace for source lines:
(  1) ostd::panic::print_stack_trace
          at /root/asterinas/ostd/src/panic.rs:113
(  2) aster_nix::thread::oops::panic_handler
          at /root/asterinas/kernel/src/thread/oops.rs:130
(  3) __ostd_panic_handler
          at ??:?
(  4) __rustc::rust_begin_unwind
          at 15oleklt2dn278x0pmi5ggj0x:?
(  5) core::panicking::panic_fmt
          at ??:?
(  6) core::panicking::panic
          at ??:?
(  7) core::option::unwrap_failed
          at ??:?
(  8) <usize as align_ext::AlignExt>::align_up
          at dbvhjj7g7k09b5lqp7kujr5ot:?
(  9) aster_nix::syscall::mremap::do_sys_mremap
          at /root/asterinas/kernel/src/syscall/mremap.rs:47
( 10) aster_nix::syscall::mremap::sys_mremap
          at /root/asterinas/kernel/src/syscall/mremap.rs:17
( 11) aster_nix::syscall::arch::syscall_dispatch
          at /root/asterinas/kernel/src/syscall/mod.rs:244
( 12) aster_nix::syscall::handle_syscall
          at /root/asterinas/kernel/src/syscall/mod.rs:374
( 13) aster_nix::thread::task::create_new_user_task::{closure#0}
          at /root/asterinas/kernel/src/thread/task.rs:95
( 14) aster_nix::thread::task::create_new_user_task::{closure#1}
          at /root/asterinas/kernel/src/thread/task.rs:126
( 15) unwinding::panicking::catch_unwind::do_call::<aster_nix::thread::task::create_new_user_task::{closure#1}, ()>
          at /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/unwinding-0.2.8/src/panicking.rs:56
( 16) unwinding::panicking::catch_unwind::<unwinding::panic::RustPanic, (), aster_nix::thread::task::create_new_user_task::{closure#1}>
          at /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/unwinding-0.2.8/src/panicking.rs:42
( 17) unwinding::panic::catch_unwind::<(), aster_nix::thread::task::create_new_user_task::{closure#1}>
          at /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/unwinding-0.2.8/src/panic.rs:87
( 18) aster_nix::thread::oops::catch_panics_as_oops::<aster_nix::thread::task::create_new_user_task::{closure#1}, ()>
          at /root/asterinas/kernel/src/thread/oops.rs:55
( 19) aster_nix::thread::task::create_new_user_task::{closure#2}
          at /root/asterinas/kernel/src/thread/task.rs:131
( 20) <aster_nix::thread::task::create_new_user_task::{closure#2} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
          at /root/.rustup/toolchains/nightly-2025-12-06-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250
( 21) <alloc::boxed::Box<dyn core::ops::function::FnOnce<(), Output = ()> + core::marker::Send> as core::ops::function::FnOnce<()>>::call_once
          at /root/.rustup/toolchains/nightly-2025-12-06-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2206
( 22) kernel_task_entry
          at /root/asterinas/ostd/src/task/mod.rs:196
( 23) kernel_task_entry_wrapper
          at ??:?
make: *** [Makefile:308: run_kernel] Error 1
```

### LINKED ISSUE #2781: Capacity overflow in `sys_madvise` when large `len` given
### Describe the bug
Capacity overflow in `sys_madvise` when large `len` given

### To Reproduce
1. Compile the PoC:
```C
#include <errno.h>
#include <stdio.h>
#include <sys/mman.h>
#include <unistd.h>

int main(void) {
    void *addr = (void *)0x0; // page-aligned
    size_t len = (size_t)0x7fffffffffffffffULL; // isize::MAX
    int behavior = MADV_NORMAL;

    printf("madvise(addr=%p, len=%zu, behavior=%d)\n", addr, len, behavior);
    int ret = madvise(addr, len, behavior);
    printf("madvise ret=%d errno=%d\n", ret, errno);
    return ret;
}
```
2. Run the compiled program in Asterinas.

### Environment
- Official docker asterinas/asterinas:0.16.2-20251211
- Asterinas version: main 9c4f644bd

### Logs
```
~ # /etc/madvise-len-overflow.c 
madvise(addr=(nil), len=9223372036854775807, behavior=0)
[     6.472] ERROR: Uncaught panic:
        capacity overflow
        at /root/.rustup/toolchains/nightly-2025-12-06-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/raw_vec/mod.rs:28
        on CPU 0 by thread Some(Thread { task: (Weak), data: Any { .. }, is_exited: false, cpu_affinity: AtomicIdSet { bits: [1], phantom: PhantomData<ostd::cpu::id::CpuId> }, sched_attr: SchedAttr { policy: SchedPolicyState { kind: AtomicSchedPolicyKind(2), policy: UnsafeCell { .. } }, last_cpu: AtomicCpuId(0), real_time: RealTimeAttr { prio: 99, time_slice: 31487460 }, fair: FairAttr { weight: 1024, pending_weight: 0, vruntime: 280295663 } } })
Printing stack trace:
   1: fn 0xffffffff88953cf0 - pc 0xffffffff88953d3b / registers:

     rax 0xffffdfffffd70648; rdx 0xffffffff889b64f2; rcx  0x10000020100d1cf; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88bd6ff0; rbp                0x0; rsp 0xffffdfffffd70730;

   2: fn 0xffffffff8804c3d0 - pc 0xffffffff8804cbcd / registers:

     rax 0xffffdfffffd70648; rdx 0xffffffff889b64f2; rcx  0x10000020100d1cf; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88bd6ff0; rbp                0x0; rsp 0xffffdfffffd70750;

   3: fn 0xffffffff8804e080 - pc 0xffffffff8804e08a / registers:

     rax 0xffffdfffffd70648; rdx 0xffffffff889b64f2; rcx  0x10000020100d1cf; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88bd6ff0; rbp                0x0; rsp 0xffffdfffffd70b20;

   4: fn 0xffffffff8804b000 - pc 0xffffffff8804b00a / registers:

     rax 0xffffdfffffd70648; rdx 0xffffffff889b64f2; rcx  0x10000020100d1cf; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88bd6ff0; rbp                0x0; rsp 0xffffdfffffd70b30;

   5: fn 0xffffffff88af6f50 - pc 0xffffffff88af6f96 / registers:

     rax 0xffffdfffffd70648; rdx 0xffffffff889b64f2; rcx  0x10000020100d1cf; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88bd6ff0; rbp                0x0; rsp 0xffffdfffffd70b40;

   6: fn 0xffffffff88ad09e0 - pc 0xffffffff88ad0a04 / registers:

     rax 0xffffdfffffd70648; rdx 0xffffffff889b64f2; rcx  0x10000020100d1cf; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88bd6ff0; rbp                0x0; rsp 0xffffdfffffd70b80;

   7: fn 0xffffffff88ad08c9 - pc 0xffffffff88ad0922 / registers:

     rax 0xffffdfffffd70648; rdx 0xffffffff889b64f2; rcx  0x10000020100d1cf; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88bd6ff0; rbp                0x0; rsp 0xffffdfffffd70b90;

   8: fn 0xffffffff887690d0 - pc 0xffffffff8876911c / registers:

     rax 0xffffdfffffd70648; rdx 0xffffffff889b64f2; rcx  0x10000020100d1cf; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88bd6ff0; rbp                0x0; rsp 0xffffdfffffd70bd0;

   9: fn 0xffffffff887690b0 - pc 0xffffffff887690c6 / registers:

     rax 0xffffdfffffd70648; rdx 0xffffffff889b64f2; rcx  0x10000020100d1cf; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88bd6ff0; rbp                0x0; rsp 0xffffdfffffd70c30;

  10: fn 0xffffffff88775210 - pc 0xffffffff88775241 / registers:

     rax 0xffffdfffffd70648; rdx 0xffffffff889b64f2; rcx  0x10000020100d1cf; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88bd6ff0; rbp                0x0; rsp 0xffffdfffffd70c50;

  11: fn 0xffffffff88775060 - pc 0xffffffff8877507f / registers:

     rax 0xffffdfffffd70648; rdx 0xffffffff889b64f2; rcx  0x10000020100d1cf; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88bd6ff0; rbp                0x0; rsp 0xffffdfffffd70cd0;

  12: fn 0xffffffff8816c770 - pc 0xffffffff8816cc6b / registers:

     rax 0xffffdfffffd70648; rdx 0xffffffff889b64f2; rcx  0x10000020100d1cf; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88bd6ff0; rbp                0x0; rsp 0xffffdfffffd70cf0;

  13: fn 0xffffffff882d76f0 - pc 0xffffffff882e067b / registers:

     rax 0xffffdfffffd70648; rdx 0xffffffff889b64f2; rcx  0x10000020100d1cf; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88bd6ff0; rbp                0x0; rsp 0xffffdfffffd710f0;

  14: fn 0xffffffff882d4190 - pc 0xffffffff882d422a / registers:

     rax 0xffffdfffffd70648; rdx 0xffffffff889b64f2; rcx  0x10000020100d1cf; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88bd6ff0; rbp                0x0; rsp 0xffffdfffffd844f0;

  15: fn 0xffffffff8809eaf0 - pc 0xffffffff8809f3a1 / registers:

     rax 0xffffdfffffd70648; rdx 0xffffffff889b64f2; rcx  0x10000020100d1cf; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88bd6ff0; rbp                0x0; rsp 0xffffdfffffd84650;

  16: fn 0xffffffff8809f560 - pc 0xffffffff8809f5be / registers:

     rax 0xffffdfffffd70648; rdx 0xffffffff889b64f2; rcx  0x10000020100d1cf; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88bd6ff0; rbp                0x0; rsp 0xffffdfffffd84b40;

  17: fn 0xffffffff8809ea60 - pc 0xffffffff8809ea8e / registers:

     rax 0xffffdfffffd70648; rdx 0xffffffff889b64f2; rcx  0x10000020100d1cf; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88bd6ff0; rbp                0x0; rsp 0xffffdfffffd84cf0;

  18: fn 0xffffffff8809e990 - pc 0xffffffff8809e9d6 / registers:

     rax 0xffffdfffffd70648; rdx 0xffffffff889b64f2; rcx  0x10000020100d1cf; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88bd6ff0; rbp                0x0; rsp 0xffffdfffffd84d20;

  19: fn 0xffffffff8818d0f0 - pc 0xffffffff8818d11c / registers:

     rax 0xffffdfffffd70648; rdx 0xffffffff889b64f2; rcx  0x10000020100d1cf; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88bd6ff0; rbp                0x0; rsp 0xffffdfffffd84d90;

  20: fn 0xffffffff8823c190 - pc 0xffffffff8823c1cf / registers:

     rax 0xffffdfffffd70648; rdx 0xffffffff889b64f2; rcx  0x10000020100d1cf; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88bd6ff0; rbp                0x0; rsp 0xffffdfffffd84dd0;

  21: fn 0xffffffff8809f520 - pc 0xffffffff8809f547 / registers:

     rax 0xffffdfffffd70648; rdx 0xffffffff889b64f2; rcx  0x10000020100d1cf; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88bd6ff0; rbp                0x0; rsp 0xffffdfffffd84f40;

  22: fn 0xffffffff8807f720 - pc 0xffffffff8807f73d / registers:

     rax 0xffffdfffffd70648; rdx 0xffffffff889b64f2; rcx  0x10000020100d1cf; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88bd6ff0; rbp                0x0; rsp 0xffffdfffffd84f80;

  23: fn 0xffffffff889cd540 - pc 0xffffffff889cd565 / registers:

     rax 0xffffdfffffd70648; rdx 0xffffffff889b64f2; rcx  0x10000020100d1cf; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88bd6ff0; rbp                0x0; rsp 0xffffdfffffd84fa0;

  24: fn 0xffffffff889b6d80 - pc 0xffffffff889b6e04 / registers:

     rax 0xffffdfffffd70648; rdx 0xffffffff889b64f2; rcx  0x10000020100d1cf; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88bd6ff0; rbp                0x0; rsp 0xffffdfffffd84fd0;

  25: fn 0xffffffff88962a15 - pc 0xffffffff88962a1e / registers:

     rax 0xffffdfffffd70648; rdx 0xffffffff889b64f2; rcx  0x10000020100d1cf; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88bd6ff0; rbp                0x0; rsp 0xffffdfffffd85000;


     rax 0xffffdfffffd70648; rdx 0xffffffff889b64f2; rcx  0x10000020100d1cf; rbx                0x0;
     rsi                0x0; rdi 0xffffffff88bd6ff0; rbp                0x0; rsp 0xffffdfffffd85008;

OSDK] The kernel seems panicked. Parsing stack trace for source lines:
(  1) ostd::panic::print_stack_trace
          at /root/asterinas/ostd/src/panic.rs:113
(  2) aster_nix::thread::oops::panic_handler
          at /root/asterinas/kernel/src/thread/oops.rs:130
(  3) __ostd_panic_handler
          at ??:?
(  4) __rustc::rust_begin_unwind
          at 15oleklt2dn278x0pmi5ggj0x:?
(  5) core::panicking::panic_fmt
          at ??:?
(  6) alloc::raw_vec::capacity_overflow
          at alloc.fca50d49e7fc4a1d-cgu.1:?
(  7) alloc::raw_vec::handle_error
          at ??:?
(  8) <alloc::raw_vec::RawVecInner>::with_capacity_zeroed_in
          at /root/.rustup/toolchains/nightly-2025-12-06-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/raw_vec/mod.rs:444
(  9) <alloc::raw_vec::RawVec<u8>>::with_capacity_zeroed_in
          at /root/.rustup/toolchains/nightly-2025-12-06-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/raw_vec/mod.rs:211
( 10) <u8 as alloc::vec::spec_from_elem::SpecFromElem>::from_elem::<alloc::alloc::Global>
          at /root/.rustup/toolchains/nightly-2025-12-06-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/spec_from_elem.rs:51
( 11) alloc::vec::from_elem::<u8>
          at /root/.rustup/toolchains/nightly-2025-12-06-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:3510
( 12) aster_nix::syscall::madvise::sys_madvise
          at /root/asterinas/kernel/src/syscall/madvise.rs:41
( 13) aster_nix::syscall::arch::syscall_dispatch
          at /root/asterinas/kernel/src/syscall/mod.rs:217
( 14) aster_nix::syscall::handle_syscall
          at /root/asterinas/kernel/src/syscall/mod.rs:374
( 15) aster_nix::thread::task::create_new_user_task::{closure#0}
          at /root/asterinas/kernel/src/thread/task.rs:95
( 16) aster_nix::thread::task::create_new_user_task::{closure#1}
          at /root/asterinas/kernel/src/thread/task.rs:126
( 17) unwinding::panicking::catch_unwind::do_call::<aster_nix::thread::task::create_new_user_task::{closure#1}, ()>
          at /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/unwinding-0.2.8/src/panicking.rs:56
( 18) unwinding::panicking::catch_unwind::<unwinding::panic::RustPanic, (), aster_nix::thread::task::create_new_user_task::{closure#1}>
          at /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/unwinding-0.2.8/src/panicking.rs:42
( 19) unwinding::panic::catch_unwind::<(), aster_nix::thread::task::create_new_user_task::{closure#1}>
          at /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/unwinding-0.2.8/src/panic.rs:87
( 20) aster_nix::thread::oops::catch_panics_as_oops::<aster_nix::thread::task::create_new_user_task::{closure#1}, ()>
          at /root/asterinas/kernel/src/thread/oops.rs:55
( 21) aster_nix::thread::task::create_new_user_task::{closure#2}
          at /root/asterinas/kernel/src/thread/task.rs:131
( 22) <aster_nix::thread::task::create_new_user_task::{closure#2} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
          at /root/.rustup/toolchains/nightly-2025-12-06-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250
( 23) <alloc::boxed::Box<dyn core::ops::function::FnOnce<(), Output = ()> + core::marker::Send> as core::ops::function::FnOnce<()>>::call_once
          at /root/.rustup/toolchains/nightly-2025-12-06-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2206
( 24) kernel_task_entry
          at /root/asterinas/ostd/src/task/mod.rs:196
( 25) kernel_task_entry_wrapper
          at ??:?
make: *** [Makefile:308: run_kernel] Error 1
```

### PR DESCRIPTION
**Pull request by lrh2000**
~~I'd like to wait until https://github.com/asterinas/asterinas/pull/2744 is merged and rebase this PR (see https://github.com/asterinas/asterinas/pull/2744#issuecomment-3656190723).~~

---

As with all my previous PRs that fix error codes, this one fixes them for MM-related system calls, i.e., `mmap`, `mremap` `msync`, `madvise`, `mprotect`, and `munmap`.

Note that incorrect error codes are the most typical issue, but they won't be the only one. I also fix many other problems, see the detailed explanation below.

#### Fix error codes in mmap

 - An address below `VMAR_LOWEST_ADDR` should result in `EPERM`.
 - An unrecognized flag with `MAP_SHARED_VALIDATED` should result in `EOPNOTSUPP`.
 - `MAP_SHARED_VALIDATED` implies `MAP_SHARED`.
 - `MAP_FIXED_NOREPLACE` implies `can_overwrite(false)`.
 - ...

#### Drop `MAP_SYNC` support

There is no need to support this flag because https://man7.org/linux/man-pages/man2/mmap.2.html says:
>  This flag is supported only for files supporting DAX (direct mapping of persistent memory).  For other files, creating a mapping with this flag results in an EOPNOTSUPP error.

#### Add `is_userspace_vaddr_range`

It seems that we repeat the following logics several times. Let's define a method instead.

https://github.com/asterinas/asterinas/blob/f30bd698d1b3d91452b3dd4311c8d15ebb4caeb8/kernel/src/vm/vmar/mod.rs#L941-L946

#### Fix error codes in MM syscalls

`msync`, `madvise`, `mprotect`, and `munmap` all accept a `vaddr` and a `len`. They all need to align `len` to a page boundary and add it to `vaddr` to get the end address. These steps are prone to integer overflow, and the implementation is inconsistent (some approaches are incorrect and can lead to panic). Fix #2779.

This commit unifies them to a consistent style:
```rust
    if !addr.is_multiple_of(PAGE_SIZE) {
        return_errno_with_message!(Errno::EINVAL, "the mapping address is not aligned");
    }
    if len == 0 {
        return Ok(SyscallReturn::Return(0));
    }
    if VMAR_CAP_ADDR.checked_sub(addr).is_none_or(|gap| gap < len) {
        // FIXME: Linux returns `EINVAL` if `(addr + len).align_up(PAGE_SIZE)` overflows. Here, we
        // perform a stricter validation.
        return_errno_with_message!(Errno::EINVAL, "the mapping range is not in userspace");
    }
    let addr_range = addr..(addr + len).align_up(PAGE_SIZE);
```

#### Fix cases where some pages are not mapped

`msync`, `madvise`, and `mprotect` need to return `ENOMEM` if some pages are not mapped. This PR adjusts the `msync` code and fixes the `mprotect` code. `madvise` will be fixed in the next commit.

#### Fix madvise behavior

The entire `madvise` implementation is problematic (Fix #2781):

 - ??? What's this???
https://github.com/asterinas/asterinas/blob/f30bd698d1b3d91452b3dd4311c8d15ebb4caeb8/kernel/src/syscall/madvise.rs#L37-L43
 - A dummy implementation of `MADV_DONTNEED` is not acceptable because it affects the semantics of the user program.
https://github.com/asterinas/asterinas/blob/f30bd698d1b3d91452b3dd4311c8d15ebb4caeb8/kernel/src/syscall/madvise.rs#L44-L46
 - A dummy implementation of `MADV_FREE` is okay, but the following implementation is wrong:
https://github.com/asterinas/asterinas/blob/f30bd698d1b3d91452b3dd4311c8d15ebb4caeb8/kernel/src/syscall/madvise.rs#L65-L72
 - A dummy implementation of `MADV_DONTFORK` is not acceptable because it affects the semantics of the user program.
https://github.com/asterinas/asterinas/blob/f30bd698d1b3d91452b3dd4311c8d15ebb4caeb8/kernel/src/syscall/madvise.rs#L57-L59

Some madvice behavior affects the semantics of the user program, while other behavior does not. We have dummy implementations for the first set, but not the second.
```rust
/// Madvise that a dummy implementation is also correct.
///
/// This list can only contain madvise behaviors that do not alter the semantics of the user
/// program. In other words, they are intended solely for performance optimization and can safely
/// be ignored by the kernel.
///
/// **Please think twice before adding a new behavior to this list. Not all madvise behaviors can
/// be no-ops.**
const DUMMY_MADVISE: &[MadviseBehavior] = &[
    MadviseBehavior::MADV_NORMAL,
    MadviseBehavior::MADV_RANDOM,
    MadviseBehavior::MADV_SEQUENTIAL,
    MadviseBehavior::MADV_WILLNEED,
    MadviseBehavior::MADV_FREE,
    MadviseBehavior::MADV_MERGEABLE,
    MadviseBehavior::MADV_UNMERGEABLE,
    MadviseBehavior::MADV_HUGEPAGE,
    MadviseBehavior::MADV_NOHUGEPAGE,
];
```

In this commit:
 - `MADV_DONTNEED` has been implemented.
 - `MADV_DONTFORK` has been removed. It is required by QEMU (https://github.com/asterinas/asterinas/issues/2689), so either a workaround should be implemented in userspace, or it should be implemented correctly.

### CODE REVIEW

**Comment by Marsman1996** [comment]
This PR should fix the #2779 and #2781

Did not notice this when creating the issue.

**Comment by lrh2000** [comment]
> This PR should fix the https://github.com/asterinas/asterinas/issues/2779 and https://github.com/asterinas/asterinas/issues/2781

Yes. I noticed the problem of `msync`, as I mentioned in the PR description,
>> `msync`, `madvise`, `mprotect`, and `munmap` all accept a `vaddr` and a `len`. They all need to align `len` to a page boundary and add it to `vaddr` to get the end address. These steps are prone to integer overflow, and the implementation is inconsistent (**some approaches are incorrect and can lead to panic**).

`mremap` is different in some way, but it is also fixed here.

The previous implementation of `madvise` just makes no sense. I don't know how it could have been accepted.

File: kernel/src/syscall/mmap.rs [hunk 1]
```diff
@@ -150,41 +126,83 @@ fn do_sys_mmap(
...
 
-fn check_option(addr: Vaddr, size: usize, option: &MMapOptions) -> Result<()> {
-    if option.typ() == MMapType::File {
-        return_errno_with_message!(Errno::EINVAL, "invalid mmap type");
+fn check_len(len: usize) -> Result<usize> {
+    if len == 0 {
+        return_errno_with_message!(Errno::EINVAL, "the mapping length is zero");
+    }
+
+    if len > VMAR_CAP_ADDR {
```
Comment (cchanging) [inline kernel/src/syscall/mmap.rs]: Check `len > VMAR_CAP_ADDR - VMAR_LOWEST_ADDR` here? Sometimes it can return early.

File: kernel/src/syscall/mmap.rs [hunk 2]
```diff
@@ -150,41 +126,83 @@ fn do_sys_mmap(
...
+        return_errno_with_message!(Errno::EINVAL, "the mapping offset is not aligned");
+    }
+
+    if flags.contains(MMapFlags::MAP_ANONYMOUS) {
+        return Ok(());
+    }
+
+    if offset
+        .checked_add(len)
+        .is_none_or(|end| end >= isize::MAX as usize)
```
Comment (cchanging) [inline kernel/src/syscall/mmap.rs]: I am not sure whether the logic is right here since the manual does not clarify the `EOVERFLOW` condition clearly. However I tried the following process:
```c
#include <stdio.h>
#include <sys/mman.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
#include <errno.h>
#include <string.h>
#include <stdint.h>
#include <stddef.h> // For PTRDIFF_MAX

int main() {
    int fd;
    off_t offset;
    size_t len = 4096 * 2;

    offset = PTRDIFF_MAX - PTRDIFF_MAX % 4096;

    printf("Attempting to mmap at a very high offset...\n");
    printf("Offset: 0x%lx\n", offset);
    printf("Length: %zu\n", len);
    printf("End Address (offset + len): 0x%lx\n", offset + len);

    fd = open("/dev/zero", O_RDONLY);
    if (fd == -1) {
        perror("open");
        return 1;
    }

    void *addr = mmap(NULL, len, PROT_READ, MAP_PRIVATE, fd, offset);

    if (addr == MAP_FAILED) {
        perror("mmap failed");
        if (errno == EOVERFLOW) {
            printf("SUCCESS: Received EOVERFLOW as expected!\n");
        } else {
            printf("FAILURE: Expected EOVERFLOW, but got errno %d\n", errno);
        }
    } else {
        printf("FAILURE: mmap succeeded unexpectedly at address %p\n", addr);
        munmap(addr, len);
    }

    close(fd);
    return 0;
}

```

This program will success in Linux but get `EOVERFLOW` in our kernel.

File: kernel/src/syscall/mmap.rs (hunk 1 above)
Comment (cchanging) [inline kernel/src/syscall/mmap.rs:134]: Check `len > VMAR_CAP_ADDR - VMAR_LOWEST_ADDR` here? Sometimes it can return early.

File: kernel/src/syscall/mmap.rs (hunk 2 above)
Comment (cchanging) [inline kernel/src/syscall/mmap.rs:172]: I am not sure why using `isize::MAX` here since the manual does not clarify the EOVERFLOW condition clearly. However I tried the following process:

```c
#include <stdio.h>
#include <sys/mman.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
#include <errno.h>
#include <string.h>
#include <stdint.h>
#include <stddef.h> // For PTRDIFF_MAX

int main() {
    int fd;
    off_t offset;
    size_t len = 4096 * 2;

    offset = PTRDIFF_MAX - PTRDIFF_MAX % 4096;

    fd = open("/dev/zero", O_RDONLY);
    if (fd == -1) {
        perror("open");
        return 1;
    }

    void *addr = mmap(NULL, len, PROT_READ, MAP_PRIVATE, fd, offset);

    if (addr == MAP_FAILED) {
        perror("mmap failed");
        if (errno == EOVERFLOW) {
            printf("SUCCESS: Received EOVERFLOW as expected!\n");
        } else {
            printf("FAILURE: Expected EOVERFLOW, but got errno %d\n", errno);
        }
    } else {
        printf("FAILURE: mmap succeeded unexpectedly at address %p\n", addr);
        munmap(addr, len);
    }

    close(fd);
    return 0;
}
```
This program will success in Linux but get EOVERFLOW in our kernel. So maybe checking `is_none` here is enough?

File: kernel/src/syscall/mmap.rs [hunk 3]
```diff
@@ -150,41 +126,83 @@ fn do_sys_mmap(
...
+// <https://man7.org/linux/man-pages/man2/mmap.2.html>.
 //
-// The first 4 bits of the flag value represents the type of memory map,
-// while other bits are used as memory map flags.
+// The first 4 bits of the flag value represents the type of the mapping,
+// while other bits are used as the flags of the mapping.
 
-// The map type mask
+/// The mask for the mapping type.
 const MAP_TYPE: u32 = 0xf;
```
Comment (cchanging) [inline kernel/src/syscall/mmap.rs]: Change this name to `MAP_TYPE_MASK`?

File: test/src/apps/mmap/mmap_err.c [hunk 4]
```diff
@@ -52,6 +70,12 @@ FN_TEST(overflow_addr)
 		TEST_ERRNO(mmap(valid_addr, len, PROT_READ,
 				MAP_PRIVATE | MAP_ANONYMOUS | MAP_FIXED, 0, 0),
 			   ENOMEM);
+		TEST_ERRNO(mremap(valid_addr, len, PAGE_SIZE, 0), EINVAL);
+		TEST_ERRNO(mremap(valid_addr, PAGE_SIZE, len, 0), EINVAL);
```
Comment (cchanging) [inline test/src/apps/mmap/mmap_err.c:74]: It seems that some tests will fail when running in Linux? For example I got:
```
test_overflow_addr: `mremap(valid_addr, 4096, len, 0)` failed [got Cannot allocate memory, but expected Invalid argument]
```

Did I miss something?

**Review by cchanging — COMMENTED** [review]
Thank you for significantly correcting the incorrect return values of the mm-related syscalls, and your changes are truly impressive! I have a few issues as follows.

File: kernel/src/syscall/mmap.rs (hunk 2 above)
Comment (lrh2000) [reply kernel/src/syscall/mmap.rs:172]: > /dev/zero

The problem is that `/dev/zero` is special because it isn't a real file.

The offset for *real files* can be as large as `isize::MAX` (in 64-bit systems) or `usize::MAX * PAGE_SIZE` (in 32-bit systems).

https://elixir.bootlin.com/linux/v6.19-rc2/source/mm/mmap.c#L427-L428
https://elixir.bootlin.com/linux/v6.19-rc2/source/mm/mmap.c#L245-L262

I think it's fine to follow a stricter restriction here. Currently, we don't support a per-file mmap offset limit.

Not to mention, `mmap` for `/dev/zero` is not supported at all in Asterinas.

File: test/src/apps/mmap/mmap_err.c (hunk 4 above)
Comment (lrh2000) [reply test/src/apps/mmap/mmap_err.c:74]:
```
test_overflow_addr: `mremap(valid_addr, len, 4096, 0)` passed [got Invalid argument]
test_overflow_addr: `mremap(valid_addr, 4096, len, 0)` passed [got Invalid argument]
```

I think it's an issue of Linux kernel version... Linux 6.18 is happy with this test.

File: kernel/src/syscall/mmap.rs (hunk 1 above)
Comment (lrh2000) [reply kernel/src/syscall/mmap.rs:134]: I'm not sure if it's worth because `VMAR_LOWEST_ADDR` can be a sysctl. Therefore, the current implementation would avoid loading a global variable... (of course, for now, `VMAR_LOWEST_ADDR` is just a constant).

```
> cat /proc/sys/vm/mmap_min_addr
65536
```

Comment (cchanging) [reply kernel/src/syscall/mmap.rs:134]: Thanks for the explanation! This makes sense, I'm fine with either way since it only influences some corner cases.

File: kernel/src/syscall/mmap.rs (hunk 2 above)
Comment (cchanging) [reply kernel/src/syscall/mmap.rs:172]: > The offset for real files can be as large as isize::MAX (in 64-bit systems) or usize::MAX * PAGE_SIZE (in 32-bit systems).

Thanks for the explanation!

File: test/src/apps/mmap/mmap_err.c (hunk 4 above)
Comment (cchanging) [reply test/src/apps/mmap/mmap_err.c:74]: Well, I was running this within our Docker, and its Linux kernel version is a bit old (6.11.0). I was quite surprised to find that there are such differences in how different kernel versions handle the error numbers returned by syscalls. I suspect this is because these edge cases are not clearly defined in the man pages... (they are sometimes indeed ambiguous)

So should we standardize on a single Linux kernel version for our compatibility testing? Otherwise, we might end up in a strange situation where the behavior of some syscalls aligns with version A, while others align with version B. Of course this is unlikely to cause issues for most real-world applications so it may not be a problem.

Comment (lrh2000) [reply test/src/apps/mmap/mmap_err.c:74]: This issue is likely caused by [3215eac ("mm/mremap: refactor initial parameter sanity checks")](https://github.com/torvalds/linux/commit/3215eaceca87625ac5ae4cc5dabfe88ba6e9b183), So, it's actually an intended change that moves the sanity checks to the beginning of the syscall. This commit is present since Linux 6.17.

 - Before this commit, the syscall [should fail here](https://github.com/torvalds/linux/blob/ccd1cdca5cd433c8a5dff78b69a79b31d9b77ee1/mm/mremap.c#L1746-L1747) so it reports `ENOMEM`.
 - After this commit, it fails [at the beginning](https://github.com/torvalds/linux/blob/ccd1cdca5cd433c8a5dff78b69a79b31d9b77ee1/mm/mremap.c#L1778-L1780), so it reports `EINVAL`.

> So should we standardize on a single Linux kernel version for our compatibility testing?

I think the most important benefit of doing this is the ability to perform CI tests. However, I'm not sure if it is considered too burdensome because developers tend to use different versions of Linux, which makes it difficult to run the tests on the specified version.

**Review by junyang-zh — APPROVED** [review]
LGTM! Thanks for contribution.

**Comment by junyang-zh** [comment]
I think we can merge it before #2736 , since #2777 gets merged before that. Consider having a review? @tatetian

**Comment by lrh2000** [comment]
> I think we can merge it before #2736 , since #2766 gets merged before that.

(I assume that you mean #2777 has been merged.)

#2736 should be able to continue concurrently. There doesn't seem to be any logical or physical interaction anyway.

I mentioned it previously because it was one of the motivations for the fix, but in fact there is really little relation.
