### PR TITLE
Streamline the version bump process

### LINKED ISSUE #1911: Streamline the version bump process
[People are complaining](https://github.com/asterinas/asterinas/pull/1907) about the version bump process. And this pain point has been [known for quite some time](https://github.com/asterinas/asterinas/issue/980). So let's revisit it and fix it!

# Background

The project-wide version number is stored in the `VERSION` file under the root directory. Asterinas's published crates and the companion Docker images always share this same version number. This setup makes it trivial to determine which Docker image should be used for which version.

There are primarily two reasons for version bumps:
1. We want to generate a new Docker image, or
2. We want to publish new versions to crates.io.

We do so by invoking the `tools/bump_version.sh` script, which updates the `VERSION` file. This change will be submitted in a bump version PR. When such a PR (changing the `VERSION` file) is merged, the "Publish Docker images" and "Publish OSDK and OSTD" workflows will be triggered.

# Problems

Our current bump version process is **quite fragile and painful.** Since launching new versions and generating new Docker images are done simultaneously, the CI test for a new version always fails first. This creates in **a long time window where the CI status is "failing"**: the `main` branch is "failing" and all new CI results of pending PRs will also be "failing".

After waiting for a long time until the new Docker image is published, we will re-run the CI test again. But there is **no guarantee that the CI test for the new release will succeed**. Quite often, we find that the code changes introduced alongside the version bump commit in the last PR has small issues that must be fixed. This experience has made us **very inconfident** with our version release process.

# Core Idea

I propose to **break down our currently atomic PR of version release into three different PRs**:
* PR 1: "Bump the Docker image version" (triggering the generation of a new Docker image, without actually using it);
* PR 2: "Switch to the latest Docker image" (modifying all code locations that refer to the Docker version);
* PR 3: "Bump the project version" (triggering the publish of new versions of the crates to crates.io)

All these PRs can be submitted to the `main` branch, following our current practice.

Let me explain why this three-step strategy solves our pain points:
1. **No more CI blocked for the new Docker image.** PR 1 only triggers the generation of the new Docker image. No code is actually using it. So all pending PRs can still use the current Docker image for CI test. No PRs will be blocked by the time-consuming Docker image generation.
2. **No more untested version releases.** After the new Docker image is ready, we will submit PR 2 to make all CI tests use the new Docker image. If the new Docker image requires code changes, then we will do so in this PR. This PR serves as an atomic transition to the new environment provided by the new Docker image. All future changes, including crate publishing, can be tested on this new Docker image.
3. **No more useless crate publishing.** If our sole purpose is to create a new Docker image (e.g., adding new utilities or test suites) without substantial code changes, then we can stop at Step 2. We do not have to publish new crates simply to trigger Docker image generation as we used to.

# Detailed Design
## Adding the `DOCKER_IMAGE_VERSION` file

You may wonder: yeah, your idea sounds cool, but why haven't we done this before? I think the answer is that our design priority has been **keeping the version numbers of published crates and their companion Docker images _identical_**. Having identical version numbers makes it trivial for people to understand which Docker images match which crates. To achieve this benefit, we were **forced to merge crate publishing and Docker image generation into one atomic step**, which causes all sorts of aforementioned problems.

So can we **decouple the processes of crate publishing and Docker image generation, while enjoying a straightforward, user-friendly version matching rule?** 
My answer is to introduce a new `DOCKER_IMAGE_VERSION` file. Like the `VERSION` file, it contains only one line of text: a semantic version. More specifically, the version number is in the following form. 

```
MAJOR.MINOR.PATCH+DATE
```

The `+DATE` part is valid in semantic versioning format; it is called the [build metadata](https://semver.org/#spec-item-10). Build metadata is informative only and ignored when determining version precedence.

The `MAJOR.MINOR.PATCH` part of our Docker version will be identical to that of the corresponding crates. So **matching crates with Docker images is still trivial**.

The `DATE` field denotes the date when the Docker image is generated. This field allows us to **create non-breaking Docker images without changing the version number of the crates**.

As an example, a possible content of `DOCKER_IMAGE_VERSION` for Asterinas 0.13.1 is as follows.

```
0.13.1+20250318
```

The Docker command in `README.md` will look like this.

```shell
docker run -it --privileged --network=host --device=/dev/kvm -v $(pwd)/asterinas:/root/asterinas asterinas/asterinas:0.13.1+20250318
```

The Docker tag becomes a bit longer but still quite human readable.

## The relationship between `DOCKER_IMAGE_VERSION` and `VERSION`

Now that we have two versions stored in two files, what are their relationships? We will maintain the following invariant:

```
$DOCKER_IMAGE_VERSION >= $VERSION
```

where `$DOCKER_IMAGE_VERSION` is the content of `DOCKER_IMAGE_VERSION` and `$VERSION` that of `VERSION`. The comparison is done as specified in semantic versioning. Note that the `DATE` part of `$DOCKER_IMAGE_VERSION` is ignored when doing comparison.

As you may probably have figure out yourself, the two versions will be equal for most of the time.

Things gets more interesting when we have made breaking changes to the Docker image or the APIs of the published crates and thus need to publish a new version of these crates. In this situation, we will need to bump the `MINOR` field of our semantic version number. This is done in our three-PR workflow:
1. PR 1 is responsible for generating the new Docker image. This means that the version number in `DOCKER_IMAGE_VERSION` is bumped.
2. PR 2 will update all locations (e.g., the `README` and the Github workflow files) that refer to the Docker image with the new Docker image version. 
3. PR 3 will bump the version number in `VERSION` to match the one in `DOCKER_IMAGE_VERSION`.

Throughout this process, we maintain the aforementioned invariant.

## The CI hooks on `DOCKER_IMAGE_VERSION`

Instead of triggering new Docker image generation on `VERSION`, it will be done on `DOCKER_IMAGE_VERSION` instead.

The crate publishing action CI action will still be triggered on `VERSION`.

## Changes to `bump_version.sh`

The `bump_version.sh` utility should be refactored to provide three sub-commands, which automate the task for PR 1, 2, and 3, respectively.

The first sub-command updates the `DOCKER_IMAGE_VERSION` file only.

```
bump_version.sh --docker_version_file [major | minor | patch | date]
```

The second sub-command updates all the references to the Docker image number, including READMEs and Github workflow files. 

```
bump_version.sh --docker_version_refs
```

Note that this second sub-command does not need to be given `major`/`minor`/`patch`/`date` information because it knows that the target version number is stored in `DOCKER_IMAGE_VERSION`.

The third sub-command updates the `VERSION` file to match `DOCKER_IMAGE_VERSION`.

```
bump_version.sh --version_file
```

`bump_version.sh` should prevent potential misuse that breaks the invariant between `VERSION` and `DOCKER_IMAGE_VERSION`.

# Typical Usage

Let's test the proposed design in real usage scenarios and see how it works and if it can satisfy our needs. To make the example more concrete, we assume the number in `VERSION` is `0.13.0` and the one in `DOCKER_IMAGE_VERSION` is `0.13.1+20250308`. We assume the today is March 18th, 2025.

## Scenario 1: Making non-breaking changes to the Docker image

1. PR 1 bumps the number in `DOCKER_IMAGE_VERSION` to `0.13.1+20250318`, triggering the generation of new Docker image.
2. PR 2 bumps all references to the Docker image version throughout the codebase, after the new Docker image is ready.
3. PR 3 is skipped.

## Scenario 2: Making breaking changes to the Docker image

A breaking change to the Docker image means that it is longer compatible with the current code.

1. PR 1 bumps the number in `DOCKER_IMAGE_VERSION` to `0.14.0+20250318`, triggering the generation of new Docker image.
2. PR 2 bumps all references to the Docker image version throughout the codebase, after the new Docker image is ready. As the new Docker image is incompatible with the current code, PR 2 also includes change the code of OSTD, OSDK, or the kernel.
3. PR 3 bumps the number in `VERSION` to `0.14.0+20250318`, triggering the publish of the new version of the crates.

## Scenario 3: Making breaking changes to the APIs of published crates

1. PR 1 bumps the number in `DOCKER_IMAGE_VERSION` to `0.14.0+20250318`, triggering the generation of new Docker image.
2. PR 2 bumps all references to the Docker image version throughout the codebase, after the new Docker image is ready.
3. PR 3 bumps the number in `VERSION` to `0.14.0+20250318`, triggering the publish of the new version of the crates. Before PR 3, we may merge other PRs to include more features and bugfixes for the new release.

# Alternatives

Similar to the spirit of this proposal, #980 also attempts to make the Docker generation and crate publishing less decoupled. But the two proposals differ in how they achieve it.

> I suggest that the `docker-push` branch should either be a temporary branch that gets deleted after each use or a branch that only retains code related to building the Docker image, such as `tools` and the content under `osdk/tools`.

#980 suggests introducing a dedicated release branch, which needs to be added and deleted manually. This requires synchronizing between the main and release branches, complicating the release process.

> For example, an OSDK/OSTD version of `0.5.1` would correspond to the latest image version of `0.5`. Please note that `0.5` represents the latest image version within the `0.5.z` range.

#980 proposes a version matching rule that is unobvious to the user -- at least, it has to be explained to the user.

In conclusion, I believe this proposal is simpler and more user friendly.

### PR DESCRIPTION
**Pull request by grief8**
fix #1911.

This pull request streamlines the version management and Docker image publishing workflows. The most important changes involve updating the Docker image version handling, modifying the workflow files to use the new Docker version file, and enhancing the version bump script to support more commands and options.

After we run `tools/bump_version.sh --docker_version_file date`, we can see the image building [workflow](https://github.com/grief8/asterinas/actions/runs/13964592629/job/39092058099) here and validate the process on my [docker hub](https://hub.docker.com/repository/docker/llifabing/asterinas/general).

Also, `tools/bump_version.sh --docker_version_refs` updates the following files:
```log
Updating file /home/fabing/projects/asterinas/tools/../README.md
Updating file /home/fabing/projects/asterinas/tools/../README_CN.md
Updating file /home/fabing/projects/asterinas/tools/../README_JP.md
Updating file /home/fabing/projects/asterinas/tools/docker/README.md
Updating file /home/fabing/projects/asterinas/tools/../docs/src/kernel/intel_tdx.md
Updating file /home/fabing/projects/asterinas/tools/../.github/workflows/publish_osdk_and_ostd.yml
Updating file /home/fabing/projects/asterinas/tools/../.github/workflows/push_git_tag.yml
Updating file /home/fabing/projects/asterinas/tools/../.github/workflows/test_asterinas_vsock.yml
Updating file /home/fabing/projects/asterinas/tools/../.github/workflows/check_licenses.yml
Updating file /home/fabing/projects/asterinas/tools/../.github/workflows/publish_docker_images.yml
Updating file /home/fabing/projects/asterinas/tools/../.github/workflows/benchmark_asterinas.yml
Updating file /home/fabing/projects/asterinas/tools/../.github/workflows/test_osdk.yml
Updating file /home/fabing/projects/asterinas/tools/../.github/workflows/test_asterinas.yml
Updating file /home/fabing/projects/asterinas/tools/../.github/workflows/publish_website.yml
Updating file /home/fabing/projects/asterinas/tools/../docs/src/kernel/README.md
```

And `tools/bump_version.sh --version_file` changes nothing.

### CODE REVIEW

**Comment by grief8** [comment]
@boterinas rerun

File: tools/bump_version.sh [hunk 1]
```diff
@@ -89,11 +94,118 @@ validate_bump_type() {
         *)
         echo "Error: Invalid bump_type. Allowed values are: patch, minor, or major."
         print_help
+        echo "Error: Invalid bump_type. Allowed values are: patch, minor, or major."
+        print_help
```
Comment (tatetian) [inline tools/bump_version.sh:98]: This line is redundant

File: tools/bump_version.sh [hunk 2]
```diff
@@ -89,11 +94,118 @@ validate_bump_type() {
...
+    update_dep_version ${OSDK_CARGO_TOML_PATH} linux-bzimage-builder
+
+    # Automatically bump Cargo.lock files
+    cargo update -p aster-nix --precise $new_version # For Cargo.lock
+    cd osdk && cargo update -p cargo-osdk --precise $new_version # For osdk/Cargo.lock
+}
+
+# Synchronize project version to Docker version (update VERSION)
+sync_project_version() {
+    new_version=$(cat ${DOCKER_IMAGE_VERSION_PATH} | cut -d'-' -f1)
```
Comment (tatetian) [inline tools/bump_version.sh:200]: Could you check the invariant that `next_version` is greater or equal to `curr_version` in semantic versioning? If `next_version` is smaller, then report an error. And if they are equal, this function can simply return.

File: tools/bump_version.sh [hunk 3]
```diff
@@ -38,11 +38,16 @@ update_image_versions() {
...
 print_help() {
-    echo "Usage: $0 bump_type"
+    echo "Usage: $0 <command> [options]"
     echo ""
-    echo "The bump_type argument must be either \"patch\", \"minor\", or \"major\","
-    echo "which instructs the script to increment the patch, minor, and major part"
-    echo "of the semantic version number of Asterinas, respectively."
+    echo "Commands:"
+    echo "  --docker_version_file [major|minor|patch|date]   Update Docker image version in DOCKER_IMAGE_VERSION"
+    echo "  --docker_version_refs                            Update all Docker version references (except VERSION)"
```
Comment (tatetian) [inline tools/bump_version.sh:45]: Change "Docker version" to "Docker image version". These are two different things.

Remove the "(except VERSION)" part. The content of `VERSION` is NOT a reference to the Docker image version.

So the final revised version looks as follows:

```
Update all references to the Docker image version throughout the codebase
```

File: tools/bump_version.sh [hunk 4]
```diff
@@ -38,11 +38,16 @@ update_image_versions() {
...
 # Print the help message
 print_help() {
-    echo "Usage: $0 bump_type"
+    echo "Usage: $0 <command> [options]"
     echo ""
-    echo "The bump_type argument must be either \"patch\", \"minor\", or \"major\","
-    echo "which instructs the script to increment the patch, minor, and major part"
-    echo "of the semantic version number of Asterinas, respectively."
+    echo "Commands:"
+    echo "  --docker_version_file [major|minor|patch|date]   Update Docker image version in DOCKER_IMAGE_VERSION"
```
Comment (tatetian) [inline tools/bump_version.sh:44]: Make the writing more precise:

```
Bump the Docker image version in the DOCKER_IMAGE_VERSION file under the project root
```

File: tools/bump_version.sh [hunk 5]
```diff
@@ -38,11 +38,16 @@ update_image_versions() {
...
+    echo "  --docker_version_refs                            Update all Docker version references (except VERSION)"
+    echo "  --version_file                                   Synchronize project version to Docker version (update VERSION)"
```
Comment (tatetian) [inline tools/bump_version.sh:46]: The revised writing:

```
Bump the project version to match the Docker image version
```

**Review by tatetian — COMMENTED** [review]
Good job! I have some suggestions to further improve the code quality.

**Comment by grief8** [comment]
Thank you for your instructions! I have revised the script.

File: tools/bump_version.sh [hunk 6]
```diff
@@ -94,6 +99,129 @@ validate_bump_type() {
...
+    fi
+
+    # Check if versions are equal
+    if [ "$new_version" = "$current_version" ]; then
+        echo "Versions are equal. No action needed."
+        exit 0
+    fi
+
+    # Compare semantic versions
+    lower_version=$(printf '%s\n' "$new_version" "$current_version" | sort -V | head -n1)
```
Comment (tatetian) [inline tools/bump_version.sh:212]: No, we can't compare semantic versions as if they are plain text. For example, "0.9.0" < "0.10.0" in semantic versioning, but "0.10.0" < "0.9.0" when compared as strings. I guess that implementing comparison between semantic versions would be painful. If so, add a TODO here. And later, we can install in the next Docker image the right CLI tool to do this.

Comment (tatetian) [reply tools/bump_version.sh:212]: I was wrong. `sort -V` is smart to handle semantic version numbers.

**Review by tatetian — APPROVED** [review]
LGTM. Thanks for the contribution!
