### PR TITLE
Fix the DMA debug assertion regression

### LINKED ISSUE #2832: `OSTD initialized. Preparing components` process was slowed down drastically
### Describe the bug

(https://github.com/asterinas/asterinas/commit/71681dd947b7cfc46ef28b381d16484c740be347) seems to have slowed down the `[kernel] OSTD initialized. Preparing components.` process drastically. On my local machine, it took about 55 seconds to finish, compared to the previous commit (https://github.com/asterinas/asterinas/commit/0c30edb5da67c21caa8613573086856c58da4cfd) which only took about 5 seconds.

### To Reproduce

1. `git pull upstream main --rebase` to synchronize with the latest repository version.
2. `git reset --hard 71681dd947b7cfc46ef28b381d16484c740be347` and `make run_kernel`, then calculate the time taken to start up.
3. `git reset --hard 0c30edb5da67c21caa8613573086856c58da4cfd` and `make run_kernel`, then calculate the time taken to start up.

### Expected behavior

The startup times of the two versions are not significantly different.

### Environment

- Docker image: official asterinas:0.17.0-20251228
- CPU: Intel Ultra5 225H

### PR DESCRIPTION
**Pull request by junyang-zh**
It makes the debug assertion 4096 times faster?

I found that the DMA assertion is per-byte. But per-page is suffice. That's why the performance degrades so much. I found this easy fix after implementing a proper segment tree with 330 LoC... But I think we can still keep the < 100 LoC `RangeCounter` implementation since we want simple and stupid things in OSTD.

Fix #2832

### CODE REVIEW

File: ostd/src/mm/dma/util.rs [hunk 1]
```diff
@@ -194,21 +198,25 @@ unsafe fn alloc_unprotect_physical_range(pa_range: &Range<Paddr>) {
...
             //  - All of the physical pages are untyped memory.
             unsafe {
                 crate::arch::tdx_guest::protect_gpa_tdvm_call(
-                    pa_range.start,
-                    pa_range.end - pa_range.start,
+                    removed.start * PAGE_SIZE,
+                    removed.len() * PAGE_SIZE,
                 )
-                .expect("Failed to protect the DMA segment in TDX guest");
+                .expect("failed to unprotect the DMA segment in TDX guest");
```
Comment (lrh2000) [inline ostd/src/mm/dma/util.rs]: If you want to change `Failed` -> `failed`, please change line 183 as well?
https://github.com/asterinas/asterinas/blob/48dd714d685f3b0caca1c9a8bdb6de91005b720c/ostd/src/mm/dma/util.rs#L183

I'm okay either way, but I really want to be consistent at least within one file...

File: ostd/src/mm/dma/util.rs [hunk 2]
```diff
@@ -161,29 +161,33 @@ pub(super) unsafe fn unprepare_dma(pa_range: &Range<Paddr>, daddr: Option<Daddr>
...
             //  - All of the physical pages are untyped memory.
             unsafe {
                 crate::arch::tdx_guest::unprotect_gpa_tdvm_call(
-                    partial.start,
-                    partial.end - partial.start,
+                    partial.start * PAGE_SIZE,
+                    partial.len() * PAGE_SIZE,
                 )
-                .expect("Failed to protect the DMA segment in TDX guest");
+                .expect("failed to protect the DMA segment in TDX guest");
```
Comment (lrh2000) [inline ostd/src/mm/dma/util.rs]: I think line 183 should use "unprotect" and line 219 should use "protect"... Right?

Seems to address the copilot comment on the wrong line.
