### PR TITLE
Fix integer overflow when updating vruntime after pending weight update

### LINKED ISSUE #2235: Integer overflow in fair scheduler when rapidly changing nice values
### Describe the bug
The kernel panics with an integer overflow error in the fair scheduler when a user program rapidly changes the nice values of multiple threads. The panic occurs at kernel/src/sched/sched_class/fair.rs:183 during `vruntime` recalculation.

https://github.com/asterinas/asterinas/blob/a13297ae4c0b445ae5e9fed8ed7ffa8c7d334621/kernel/src/sched/sched_class/fair.rs#L183

### To Reproduce
1. Compile and run the program
```
#define _GNU_SOURCE
#include <errno.h>
#include <linux/types.h>
#include <pthread.h>
#include <sched.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/resource.h>
#include <sys/syscall.h>
#include <sys/wait.h>
#include <unistd.h>

struct sched_attr {
  __u32 size;
  __u32 sched_policy;
  __u64 sched_flags;
  __s32 sched_nice;
  __u32 sched_priority;
  __u64 sched_runtime;
  __u64 sched_deadline;
  __u64 sched_period;
};

static volatile int keep_running = 1;

int worker_func(void *arg) {
  int thread_id = *(int *)arg;
  printf("Worker %d started\n", thread_id);

  while (keep_running) {
    for (volatile int i = 0; i < 10000; i++)
      ;
    sched_yield();
  }

  printf("Worker %d exiting\n", thread_id);
  return 0;
}

void change_nice_rapidly(pid_t pid) {
  struct sched_attr attr;
  int nice_values[] = {-20, -10, 0, 10, 19, -20, -5, 15, -15, 5};
  int num_values = sizeof(nice_values) / sizeof(nice_values[0]);

  for (int round = 0; round < 100 && keep_running; round++) {
    for (int i = 0; i < num_values && keep_running; i++) {
      memset(&attr, 0, sizeof(attr));
      attr.size = sizeof(attr);
      attr.sched_policy = SCHED_OTHER;
      attr.sched_nice = nice_values[i];

      if (syscall(SYS_sched_setattr, pid, &attr, 0) == -1) {
        if (errno != ESRCH) {
          perror("sched_setattr failed");
        }
      }

      usleep(1000);
    }
  }
}

int main() {
  const int num_workers = 8;
  pid_t worker_pids[num_workers];
  char *stacks[num_workers];
  int thread_ids[num_workers];

  for (int i = 0; i < num_workers; i++) {
    stacks[i] = malloc(8192);
    if (!stacks[i]) {
      perror("malloc");
      exit(1);
    }

    thread_ids[i] = i;
    char *stack_top = stacks[i] + 8192;

    worker_pids[i] =
        clone(worker_func, stack_top,
              CLONE_VM | CLONE_FILES | CLONE_FS | SIGCHLD, &thread_ids[i]);

    if (worker_pids[i] == -1) {
      perror("clone failed");
      exit(1);
    }
  }

  usleep(50000);

  for (int i = 0; i < num_workers; i++) {
    if (fork() == 0) {
      // Child process - change nice values rapidly
      change_nice_rapidly(worker_pids[i]);
      exit(0);
    }
  }

  sleep(10);

  keep_running = 0;

  for (int i = 0; i < num_workers; i++) {
    kill(worker_pids[i], SIGTERM);
  }

  int status;
  while (wait(&status) > 0)
    ;

  for (int i = 0; i < num_workers; i++) {
    free(stacks[i]);
  }
  return 0;
}

```

### Expected behavior
The Asterinas should not panic.

### Environment
- Official docker asterinas/asterinas:0.15.0-20250603
- Intel(R) Xeon(R) Gold 6230R CPU @ 2.10GHz
- Asterinas version: main a13297a

### Log
```
~ # /root/fair2.c 
Worker 4 started
Worker 3 started
Worker 7 started
Worker 2 started
Worker 6 started
Worker 5 started
Worker 1 started
Worker 0 started
[    47.684] ERROR: Uncaught panic:
        attempt to multiply with overflow
        at /root/asterinas/kernel/src/sched/sched_class/fair.rs:183
        on CPU 0 by thread Some(Thread { task: (Weak), data: Any { .. }, is_exited: false, cpu_affinity: AtomicCpuSet { bits: [1] }, sched_attr: SchedAttr { policy: SchedPolicyState { kind: AtomicSchedPolicyKind(2), policy: UnsafeCell { .. } }, last_cpu: AtomicCpuId(0), real_time: RealTimeAttr { prio: 99, time_slice: 31521000 }, fair: FairAttr { weight: 1024, pending_weight: 0, vruntime: 2737734693608560 } } })
Printing stack trace:
   1: fn 0xffffffff88781770 - pc 0xffffffff887817ba / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f47; rbp                0x0; rsp 0xffffdffffea40890;

   2: fn 0xffffffff88591050 - pc 0xffffffff885917f9 / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f47; rbp                0x0; rsp 0xffffdffffea408e0;

   3: fn 0xffffffff88591040 - pc 0xffffffff8859104a / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f47; rbp                0x0; rsp 0xffffdffffea40cf0;

   4: fn 0xffffffff8804b000 - pc 0xffffffff8804b00a / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f47; rbp                0x0; rsp 0xffffdffffea40d00;

   5: fn 0xffffffff8895ad10 - pc 0xffffffff8895ad54 / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f47; rbp                0x0; rsp 0xffffdffffea40d10;

   6: fn 0xffffffff8893d000 - pc 0xffffffff8893d02e / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f47; rbp                0x0; rsp 0xffffdffffea40d50;

   7: fn 0xffffffff8845fdd0 - pc 0xffffffff8845ff38 / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f47; rbp                0x0; rsp 0xffffdffffea40da0;

   8: fn 0xffffffff88460450 - pc 0xffffffff8846050c / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f47; rbp                0x0; rsp 0xffffdffffea40e40;

   9: fn 0xffffffff88365470 - pc 0xffffffff8836547e / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f47; rbp                0x0; rsp 0xffffdffffea40ec0;

  10: fn 0xffffffff8809ebd0 - pc 0xffffffff8809ec20 / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f47; rbp                0x0; rsp 0xffffdffffea40ed0;

  11: fn 0xffffffff88110d70 - pc 0xffffffff88110dab / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f47; rbp                0x0; rsp 0xffffdffffea40f10;

  12: fn 0xffffffff88110fd0 - pc 0xffffffff88110fe3 / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f47; rbp                0x0; rsp 0xffffdffffea40f30;

  13: fn 0xffffffff8881aec0 - pc 0xffffffff8881aef7 / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f47; rbp                0x0; rsp 0xffffdffffea40f50;

  14: fn 0xffffffff8881b4b0 - pc 0xffffffff8881b4d1 / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f47; rbp                0x0; rsp 0xffffdffffea40fd0;

  15: fn 0xffffffff88110880 - pc 0xffffffff88110918 / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f47; rbp                0x0; rsp 0xffffdffffea41010;

  16: fn 0xffffffff8881b320 - pc 0xffffffff8881b39b / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f47; rbp                0x0; rsp 0xffffdffffea41070;

  17: fn 0xffffffff8881ae70 - pc 0xffffffff8881aeaf / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f47; rbp                0x0; rsp 0xffffdffffea410d0;

  18: fn 0xffffffff88811c50 - pc 0xffffffff88811c94 / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f47; rbp                0x0; rsp 0xffffdffffea41110;

  19: fn 0xffffffff88811ba0 - pc 0xffffffff88811bc0 / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f47; rbp                0x0; rsp 0xffffdffffea41140;

  20: fn 0xffffffff884c8690 - pc 0xffffffff884c8785 / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f47; rbp                0x0; rsp 0xffffdffffea41160;

  21: fn 0xffffffff884d4330 - pc 0xffffffff884d43bc / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f47; rbp                0x0; rsp 0xffffdffffea411f0;

  22: fn 0xffffffff884d2870 - pc 0xffffffff884d2921 / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f47; rbp                0x0; rsp 0xffffdffffea41290;

  23: fn 0xffffffff884d22d0 - pc 0xffffffff884d2355 / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f47; rbp                0x0; rsp 0xffffdffffea41310;

  24: fn 0xffffffff8812e180 - pc 0xffffffff8812e94e / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f47; rbp                0x0; rsp 0xffffdffffea413c0;

  25: fn 0xffffffff8812e0d0 - pc 0xffffffff8812e148 / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f47; rbp                0x0; rsp 0xffffdffffea41900;

  26: fn 0xffffffff8859ab40 - pc 0xffffffff885c0415 / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f47; rbp                0x0; rsp 0xffffdffffea41960;

  27: fn 0xffffffff8859a810 - pc 0xffffffff8859a8a1 / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f47; rbp                0x0; rsp 0xffffdffffea53640;

  28: fn 0xffffffff882ea570 - pc 0xffffffff882eadb4 / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f47; rbp                0x0; rsp 0xffffdffffea537c0;

  29: fn 0xffffffff885343b0 - pc 0xffffffff885343b6 / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f47; rbp                0x0; rsp 0xffffdffffea53d00;

  30: fn 0xffffffff883d0a70 - pc 0xffffffff883d0a87 / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f47; rbp                0x0; rsp 0xffffdffffea53d10;

  31: fn 0xffffffff883d09d0 - pc 0xffffffff883d09f1 / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f47; rbp                0x0; rsp 0xffffdffffea53d30;

  32: fn 0xffffffff88141440 - pc 0xffffffff88141452 / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f47; rbp                0x0; rsp 0xffffdffffea53d80;

  33: fn 0xffffffff884b3b10 - pc 0xffffffff884b3b26 / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f47; rbp                0x0; rsp 0xffffdffffea53db0;

  34: fn 0xffffffff8845ec40 - pc 0xffffffff8845ec4c / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f47; rbp                0x0; rsp 0xffffdffffea53f50;

  35: fn 0xffffffff885329c0 - pc 0xffffffff885329ce / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f47; rbp                0x0; rsp 0xffffdffffea53f80;

  36: fn 0xffffffff887b3b90 - pc 0xffffffff887b3bb5 / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f47; rbp                0x0; rsp 0xffffdffffea53fa0;

  37: fn 0xffffffff887f91c0 - pc 0xffffffff887f9259 / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f47; rbp                0x0; rsp 0xffffdffffea53fd0;


     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f47; rbp                0x0; rsp 0xffffdffffea54000;

OSDK] The kernel seems panicked. Parsing stack trace for source lines:
(  1) /root/asterinas/ostd/src/panic.rs:107
(  2) /root/asterinas/kernel/src/thread/oops.rs:129
(  3) ??:?
(  4) 3c6okf6pq75of6d94iwjhfc6u:?
(  5) ??:?
(  6) ??:?
(  7) b7u5cwwvlzjf1pi502u33g9jd:?
(  8) /root/asterinas/kernel/src/sched/sched_class/fair.rs:319
(  9) /root/asterinas/kernel/src/sched/sched_class/mod.rs:313
( 10) /root/.rustup/toolchains/nightly-2025-02-01-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:1552
( 11) /root/asterinas/kernel/src/sched/sched_class/mod.rs:311
( 12) /root/asterinas/kernel/src/sched/sched_class/mod.rs:343
( 13) /root/asterinas/ostd/src/task/scheduler/mod.rs:147
( 14) /root/asterinas/ostd/src/task/scheduler/mod.rs:246
( 15) /root/asterinas/kernel/src/sched/sched_class/mod.rs:243
( 16) /root/asterinas/ostd/src/task/scheduler/mod.rs:249
( 17) /root/asterinas/ostd/src/task/scheduler/mod.rs:128
( 18) /root/asterinas/ostd/src/sync/wait.rs:274
( 19) /root/asterinas/ostd/src/sync/wait.rs:201
( 20) /root/asterinas/ostd/src/sync/wait.rs:229
( 21) /root/asterinas/kernel/src/time/wait.rs:210
( 22) /root/asterinas/kernel/src/process/signal/pause.rs:133
( 23) /root/asterinas/kernel/src/process/signal/pause.rs:65
( 24) /root/asterinas/kernel/src/syscall/nanosleep.rs:117
( 25) /root/asterinas/kernel/src/syscall/nanosleep.rs:51
( 26) /root/asterinas/kernel/src/syscall/mod.rs:207
( 27) /root/asterinas/kernel/src/syscall/mod.rs:357
( 28) /root/asterinas/kernel/src/thread/task.rs:87
( 29) /root/.rustup/toolchains/nightly-2025-02-01-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250
( 30) /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/unwinding-0.2.5/src/panicking.rs:56
( 31) /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/unwinding-0.2.5/src/panicking.rs:42
( 32) /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/unwinding-0.2.5/src/panic.rs:87
( 33) /root/asterinas/kernel/src/thread/oops.rs:54
( 34) /root/asterinas/kernel/src/thread/task.rs:117
( 35) /root/.rustup/toolchains/nightly-2025-02-01-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250
( 36) /root/.rustup/toolchains/nightly-2025-02-01-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2016
( 37) /root/asterinas/ostd/src/task/mod.rs:234
```

### PR DESCRIPTION
**Pull request by js2xxx**
Fixes #2235.

After the fix, the old component of the accumulated vruntime will not be scaled according to the weight. This fix aligns with the CFS strategy while keeping its monotonic nature and avoiding non-local effects (such as malicious jumps ahead in the run queue or becoming lower than `min_vruntime`).

### CODE REVIEW

File: kernel/src/sched/sched_class/fair.rs [hunk 1]
```diff
@@ -178,9 +178,11 @@ impl FairAttr {
         }
         let old_weight = weight & !HAS_PENDING;
 
-        let vruntime = self.vruntime.load(Ordering::Relaxed);
-        self.vruntime
-            .store(vruntime * old_weight / new_weight, Ordering::Relaxed);
+        // This field is an accumulated value, so we don't update its
+        // old components.
+        if let Some(min_vruntime) = min_vruntime {
+            self.vruntime.fetch_max(min_vruntime, Ordering::Relaxed);
```
Comment (tatetian) [inline kernel/src/sched/sched_class/fair.rs]: It is weird to update `self.vruntime` in `fetch_weight`. The new vruntime update logic has nothing to do with weights at all.

**Comment by Marsman1996** [comment]
It seems that the #2223 does not fix the `subtract with overflow` completely.

### Reproduce
With the following program, a integer overflow could happen in `self.total_weight -= old_weight;` in `pick_next()`

```C
#define _GNU_SOURCE
#include <errno.h>
#include <pthread.h>
#include <sched.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
#include <unistd.h>

// Constants for Linux scheduling policies
#define SCHED_NORMAL 0
#define SCHED_IDLE 5

// This program is designed to trigger the integer overflow bug
// in the fair scheduler's pick_next function where:
// self.total_weight -= old_weight causes an overflow

void trigger_weight_race() {
  struct sched_param param;
  param.sched_priority = 0;

  // The strategy is to:
  // 1. Get enqueued with one weight (NORMAL, nice=0, weight=1024)
  // 2. Update scheduling policy to change weight (IDLE, nice=19, weight=much
  // higher)
  // 3. Force pick_next to be called, which will subtract the new higher weight
  //    from total_weight that was incremented by the old lower weight

  for (int i = 0; i < 10000; i++) {
    // Set to normal scheduling (nice = 0, weight = 1024)
    if (sched_setscheduler(0, SCHED_NORMAL, &param) == -1) {
      printf("Failed to set SCHED_NORMAL: %s\n", strerror(errno));
    }

    // Force the thread to be enqueued with the current weight
    sched_yield();

    // Immediately change to IDLE scheduling (nice = 19, much higher weight)
    // This creates a pending weight update
    if (sched_setscheduler(0, SCHED_IDLE, &param) == -1) {
      printf("Failed to set SCHED_IDLE: %s\n", strerror(errno));
    }

    // Force scheduling to trigger pick_next, which should subtract the new
    // weight from total_weight that was calculated with the old weight
    sched_yield();
  }
}

void *worker_thread(void *arg) {
  int id = *(int *)arg;

  trigger_weight_race();

  return NULL;
}

int main() {
  const int num_threads = 4;
  pthread_t threads[num_threads];
  int thread_ids[num_threads];

  // Create multiple threads to increase chances of race condition
  for (int i = 0; i < num_threads; i++) {
    thread_ids[i] = i;
    if (pthread_create(&threads[i], NULL, worker_thread, &thread_ids[i]) != 0) {
      perror("pthread_create");
      exit(1);
    }
  }

  // Main thread also participates
  trigger_weight_race();

  // Wait for all threads
  for (int i = 0; i < num_threads; i++) {
    pthread_join(threads[i], NULL);
  }

  return 0;
}
```

### Log
```log
~ # /root/fair3.c 
[    27.658] ERROR: Uncaught panic:
        attempt to subtract with overflow
        at /root/asterinas/kernel/src/sched/sched_class/fair.rs:326
        on CPU 0 by thread Some(Thread { task: (Weak), data: Any { .. }, is_exited: false, cpu_affinity: AtomicCpuSet { bits: [1] }, sched_attr: SchedAttr { policy: SchedPolicyState { kind: AtomicSchedPolicyKind(2), policy: UnsafeCell { .. } }, last_cpu: AtomicCpuId(0), real_time: RealTimeAttr { prio: 99, time_slice: 31489560 }, fair: FairAttr { weight: 9223372036854776832, pending_weight: 14, vruntime: 134936245 } } })
Printing stack trace:
   1: fn 0xffffffff88781780 - pc 0xffffffff887817ca / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f57; rbp                0x0; rsp 0xffffdffffedb5170;

   2: fn 0xffffffff8858e010 - pc 0xffffffff8858e7b9 / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f57; rbp                0x0; rsp 0xffffdffffedb51c0;

   3: fn 0xffffffff8858e000 - pc 0xffffffff8858e00a / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f57; rbp                0x0; rsp 0xffffdffffedb55d0;

   4: fn 0xffffffff8804b000 - pc 0xffffffff8804b00a / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f57; rbp                0x0; rsp 0xffffdffffedb55e0;

   5: fn 0xffffffff8895ad20 - pc 0xffffffff8895ad64 / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f57; rbp                0x0; rsp 0xffffdffffedb55f0;

   6: fn 0xffffffff8893cfe0 - pc 0xffffffff8893d00e / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f57; rbp                0x0; rsp 0xffffdffffedb5630;

   7: fn 0xffffffff881c55d0 - pc 0xffffffff881c570b / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f57; rbp                0x0; rsp 0xffffdffffedb5680;

   8: fn 0xffffffff884356c0 - pc 0xffffffff884356ce / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f57; rbp                0x0; rsp 0xffffdffffedb5710;

   9: fn 0xffffffff88115dc0 - pc 0xffffffff88115e10 / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f57; rbp                0x0; rsp 0xffffdffffedb5720;

  10: fn 0xffffffff881d0ea0 - pc 0xffffffff881d0edb / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f57; rbp                0x0; rsp 0xffffdffffedb5760;

  11: fn 0xffffffff881d1100 - pc 0xffffffff881d1113 / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f57; rbp                0x0; rsp 0xffffdffffedb5780;

  12: fn 0xffffffff8881b0f0 - pc 0xffffffff8881b132 / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f57; rbp                0x0; rsp 0xffffdffffedb57a0;

  13: fn 0xffffffff8881b460 - pc 0xffffffff8881b481 / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f57; rbp                0x0; rsp 0xffffdffffedb5800;

  14: fn 0xffffffff881d09b0 - pc 0xffffffff881d0a48 / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f57; rbp                0x0; rsp 0xffffdffffedb5840;

  15: fn 0xffffffff8881b260 - pc 0xffffffff8881b2d6 / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f57; rbp                0x0; rsp 0xffffdffffedb58a0;

  16: fn 0xffffffff8880cf50 - pc 0xffffffff8880cf56 / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f57; rbp                0x0; rsp 0xffffdffffedb5900;

  17: fn 0xffffffff887f8a90 - pc 0xffffffff887f8a96 / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f57; rbp                0x0; rsp 0xffffdffffedb5910;

  18: fn 0xffffffff88345ce0 - pc 0xffffffff88345ce6 / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f57; rbp                0x0; rsp 0xffffdffffedb5920;

  19: fn 0xffffffff880d35f0 - pc 0xffffffff880d360e / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f57; rbp                0x0; rsp 0xffffdffffedb5930;

  20: fn 0xffffffff88597b00 - pc 0xffffffff8859fbaa / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f57; rbp                0x0; rsp 0xffffdffffedb5960;

  21: fn 0xffffffff885977d0 - pc 0xffffffff88597861 / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f57; rbp                0x0; rsp 0xffffdffffedc7640;

  22: fn 0xffffffff883af140 - pc 0xffffffff883af984 / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f57; rbp                0x0; rsp 0xffffdffffedc77c0;

  23: fn 0xffffffff88535ee0 - pc 0xffffffff88535ee6 / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f57; rbp                0x0; rsp 0xffffdffffedc7d00;

  24: fn 0xffffffff88079020 - pc 0xffffffff88079037 / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f57; rbp                0x0; rsp 0xffffdffffedc7d10;

  25: fn 0xffffffff88078f80 - pc 0xffffffff88078fa1 / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f57; rbp                0x0; rsp 0xffffdffffedc7d30;

  26: fn 0xffffffff884db8b0 - pc 0xffffffff884db8c2 / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f57; rbp                0x0; rsp 0xffffdffffedc7d80;

  27: fn 0xffffffff884476e0 - pc 0xffffffff884476f6 / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f57; rbp                0x0; rsp 0xffffdffffedc7db0;

  28: fn 0xffffffff8839c110 - pc 0xffffffff8839c11c / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f57; rbp                0x0; rsp 0xffffdffffedc7f50;

  29: fn 0xffffffff885344f0 - pc 0xffffffff885344fe / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f57; rbp                0x0; rsp 0xffffdffffedc7f80;

  30: fn 0xffffffff887b3ba0 - pc 0xffffffff887b3bc5 / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f57; rbp                0x0; rsp 0xffffdffffedc7fa0;

  31: fn 0xffffffff887f91d0 - pc 0xffffffff887f9269 / registers:

     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f57; rbp                0x0; rsp 0xffffdffffedc7fd0;


     rax 0xffffffff88ca3178; rdx  0x100000000000008; rcx 0xffffffff88ca3178; rbx                0x0;
     rsi 0xffffffff88c9fbca; rdi  0x1ffffff88764f57; rbp                0x0; rsp 0xffffdffffedc8000;

OSDK] The kernel seems panicked. Parsing stack trace for source lines:
(  1) /root/asterinas/ostd/src/panic.rs:107
(  2) /root/asterinas/kernel/src/thread/oops.rs:129
(  3) ??:?
(  4) 3c6okf6pq75of6d94iwjhfc6u:?
(  5) ??:?
(  6) ??:?
(  7) /root/asterinas/kernel/src/sched/sched_class/fair.rs:329
(  8) /root/asterinas/kernel/src/sched/sched_class/mod.rs:313
(  9) /root/.rustup/toolchains/nightly-2025-02-01-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:1552
( 10) /root/asterinas/kernel/src/sched/sched_class/mod.rs:311
( 11) /root/asterinas/kernel/src/sched/sched_class/mod.rs:343
( 12) /root/asterinas/ostd/src/task/scheduler/mod.rs:226
( 13) /root/asterinas/ostd/src/task/scheduler/mod.rs:246
( 14) /root/asterinas/kernel/src/sched/sched_class/mod.rs:243
( 15) /root/asterinas/ostd/src/task/scheduler/mod.rs:249
( 16) /root/asterinas/ostd/src/task/scheduler/mod.rs:232
( 17) /root/asterinas/ostd/src/task/mod.rs:105
( 18) /root/asterinas/kernel/src/thread/mod.rs:119
( 19) /root/asterinas/kernel/src/syscall/sched_yield.rs:7
( 20) /root/asterinas/kernel/src/syscall/mod.rs:179
( 21) /root/asterinas/kernel/src/syscall/mod.rs:357
( 22) /root/asterinas/kernel/src/thread/task.rs:87
( 23) /root/.rustup/toolchains/nightly-2025-02-01-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250
( 24) /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/unwinding-0.2.5/src/panicking.rs:56
( 25) /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/unwinding-0.2.5/src/panicking.rs:42
( 26) /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/unwinding-0.2.5/src/panic.rs:87
( 27) /root/asterinas/kernel/src/thread/oops.rs:54
( 28) /root/asterinas/kernel/src/thread/task.rs:117
( 29) /root/.rustup/toolchains/nightly-2025-02-01-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250
( 30) /root/.rustup/toolchains/nightly-2025-02-01-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2016
( 31) /root/asterinas/ostd/src/task/mod.rs:234
```

**Review by js2xxx — COMMENTED** [review]
> // Immediately change to IDLE scheduling (nice = 19, much higher weight)

Though the bug is currently under investigation, higher nice values corresponding to a lower weight.

**Comment by js2xxx** [comment]
@Marsman1996 The latest commit should fix the bug.

**Comment by Marsman1996** [comment]
> The latest commit should fix the bug.

~8 hours fuzzing does not reproduce the bug, I think the new commit has fixed the bug.

**Review by tatetian — APPROVED** [review]
LGTM. Thanks for the contribution!
