### PR TITLE
Avoid init stack top at `MAX_USERSPACE_VADDR`

### LINKED ISSUE #1592: Asterinas cannot run any program when initialize stack at `MAX_USERSPACE_VADDR`
### Describe the bug
Asterinas cannot run any program when initialize stack at `MAX_USERSPACE_VADDR`

When initialize the stack, Asterinas would generate a random value `nr_pages_padding` and set the stack top as `MAX_USERSPACE_VADDR - nr_pages_padding * PAGE_SIZE`. 
However, when `nr_pages_padding` is 0, Asterinas fail to run any program.

https://github.com/asterinas/asterinas/blob/54e2ffbb71a1e4a49ce1a30e263cc8fdca6b1d7d/kernel/src/process/process_vm/init_stack/mod.rs#L121-L128

### To Reproduce
1. Start Asterinas with 0 value `nr_pages_padding`, we can use this patch to achieve it:
```diff
diff --git a/kernel/src/process/process_vm/init_stack/mod.rs b/kernel/src/process/process_vm/init_stack/mod.rs
index 38373044..95385f4f 100644
--- a/kernel/src/process/process_vm/init_stack/mod.rs
+++ b/kernel/src/process/process_vm/init_stack/mod.rs
@@ -20,7 +20,10 @@ use core::{
 
 use align_ext::AlignExt;
 use aster_rights::Full;
-use ostd::mm::{vm_space::VmItem, VmIo, VmSpace, MAX_USERSPACE_VADDR};
+use ostd::{
+    early_println,
+    mm::{vm_space::VmItem, VmIo, VmSpace, MAX_USERSPACE_VADDR},
+};
 
 use self::aux_vec::{AuxKey, AuxVec};
 use crate::{
@@ -120,11 +123,17 @@ impl Clone for InitStack {
 
 impl InitStack {
     pub(super) fn new() -> Self {
-        let nr_pages_padding = {
-            let mut random_nr_pages_padding: u8 = 0;
-            getrandom(random_nr_pages_padding.as_bytes_mut()).unwrap();
-            random_nr_pages_padding as usize
-        };
+        let nr_pages_padding = loop {
+            let nr_pages_padding = {
+                let mut random_nr_pages_padding: u8 = 0;
+                getrandom(random_nr_pages_padding.as_bytes_mut()).unwrap();
+                random_nr_pages_padding as usize
+            };
+            early_println!("nr_pages_padding is {}", nr_pages_padding);
+            if nr_pages_padding == 0 {
+                break nr_pages_padding;
+            }
+        };
         let initial_top = MAX_USERSPACE_VADDR - PAGE_SIZE * nr_pages_padding;
         let max_size = INIT_STACK_SIZE;
 

```
2. Run any program, Asterinas will report `sh: xxx: Bad address`

### Expected behavior
Asterinas shall run program successfully.

### Environment
- Official docker asterinas/asterinas:0.9.4
- Intel(R) Xeon(R) Gold 6230R CPU @ 2.10GHz
- Asterinas version: main 54e2ffb

### Logs
```
[kernel] Hello world from kernel!


   _   ___ _____ ___ ___ ___ _  _   _   ___
  /_\ / __|_   _| __| _ \_ _| \| | /_\ / __|
 / _ \\__ \ | | | _||   /| || .` |/ _ \\__ \
/_/ \_\___/ |_| |___|_|_\___|_|\_/_/ \_\___/


nr_pages_padding is 41
nr_pages_padding is 240
nr_pages_padding is 45
nr_pages_padding is 167
nr_pages_padding is 254
nr_pages_padding is 2
nr_pages_padding is 62
nr_pages_padding is 45
nr_pages_padding is 200
nr_pages_padding is 94
nr_pages_padding is 225
nr_pages_padding is 54
nr_pages_padding is 0
~ # cat /proc/1/cmdline 
sh: cat: Bad address

~ # /root/fstat.c 
sh: /root/fstat.c: Bad address

~ # /root/lock.c 
sh: /root/lock.c: Bad address
```

### PR DESCRIPTION
**Pull request by Marsman1996**
Fix #1592

### CODE REVIEW

**Comment by Marsman1996** [comment]
@boterinas rerun

**Review by junyang-zh — APPROVED** [review]
My bad, good fix.

File: kernel/src/process/process_vm/init_stack/mod.rs [hunk 1]
```diff
@@ -123,7 +123,7 @@ impl InitStack {
         let nr_pages_padding = {
             let mut random_nr_pages_padding: u8 = 0;
             getrandom(random_nr_pages_padding.as_bytes_mut()).unwrap();
-            random_nr_pages_padding as usize
+            random_nr_pages_padding as usize + 1
```
Comment (tatetian) [inline kernel/src/process/process_vm/init_stack/mod.rs:126]: First, if `random_nr_pages_padding == 255` , then integer overflow will result in `nr_pages_padding = 0`, which leads to the original, problematic situation.

Second, we really want to explain why the add-one here. It is a knowledge that is obtained in the hard way and should be persisted in the code to prevent future regression.

So here is my revised version.

```rust
        let nr_pages_padding = {
            // We do not want the stack top too close to MAX_USERSPACE_VADDR.
            // So we add this fixed padding. Any small value greater than zero will do.
            const NR_FIXED_PADDING_PAGES: u32 = 7;

            // Some random padding pages are added as a simple measure to
            // make the stack values of a buggy user program harder
            // to be exploited by attackers.
            let mut nr_random_padding_pages: u8 = 0;
            getrandom(nr_random_padding_pages.as_bytes_mut()).unwrap();

            NR_FIXED_PADDING_PAGES + nr_random_padding_pages as u32
        };
```

Comment (Marsman1996) [reply kernel/src/process/process_vm/init_stack/mod.rs:126]: For the first problem, `random_nr_pages_padding` has been converted as `usize`, so there will be no overflow problem here.
And I will update the PR for the second problem.

Comment (tatetian) [reply kernel/src/process/process_vm/init_stack/mod.rs]: Yes, I ignored `as usize`.

**Review by tatetian — APPROVED** [review]
LGTM. Thanks for the contribution!
