### PR TITLE
Fix integer overflow in memory related syscall

### LINKED ISSUE #1213: Several Integer overflow problems in syscall `mmap`/`munmap`/`mprotect`/`madvise` caused by large `size`
### Describe the bug
There is a add with overflow error in `find_free_region()` at kernel/aster-nix/src/vm/vmar/mod.rs:167 when make a `mmap` syscall with large `size`.

https://github.com/asterinas/asterinas/blob/562e64437584279783f244edba10b512beddc81d/kernel/aster-nix/src/vm/vmar/mod.rs#L167

### To Reproduce
1. Compile a program which calls `mmap`:
```C
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/mman.h>
#include <unistd.h>

int main() {
  void *addr = mmap(NULL, 0xfffffffffffff000, 0x3, MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);

  return 0;
}

```
2. Run the compiled program in Asterinas.

### Expected behavior
Asterinas reports `attempt to add with overflow` panic and is terminated.

### Environment
- Official docker asterinas/asterinas:0.6.2
- 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
- Asterinas version: main 562e6443

### Logs
```
~ # /root/munmap.c 
panicked at /root/asterinas/kernel/aster-nix/src/vm/vmar/mod.rs:167:43:
attempt to add with overflow
Printing stack trace:
   1: fn 0xffffffff888695b0 - pc 0xffffffff888695c8 / registers:

     rax               0x12; rdx 0xffffffff88a38470; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e4a7a70;

   2: fn 0xffffffff88869390 - pc 0xffffffff88869508 / registers:

     rax               0x12; rdx 0xffffffff88a38470; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e4a7a80;

   3: fn 0xffffffff88049000 - pc 0xffffffff8804900a / registers:

     rax               0x12; rdx 0xffffffff88a38470; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e4a7c00;

   4: fn 0xffffffff889a8690 - pc 0xffffffff889a8712 / registers:

     rax               0x12; rdx 0xffffffff88a38470; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e4a7c10;

   5: fn 0xffffffff88983e50 - pc 0xffffffff88983e7e / registers:

     rax               0x12; rdx 0xffffffff88a38470; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e4a7ca0;

   6: fn 0xffffffff88470450 - pc 0xffffffff884707f7 / registers:

     rax               0x12; rdx 0xffffffff88a38470; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e4a7cf0;

   7: fn 0xffffffff884742b0 - pc 0xffffffff88474c1a / registers:

     rax               0x12; rdx 0xffffffff88a38470; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e4a7f30;

   8: fn 0xffffffff8855aa00 - pc 0xffffffff8855ab86 / registers:

     rax               0x12; rdx 0xffffffff88a38470; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e4a8900;

   9: fn 0xffffffff8855b6d0 - pc 0xffffffff8855b824 / registers:

     rax               0x12; rdx 0xffffffff88a38470; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e4a8dd0;

  10: fn 0xffffffff8844e2f0 - pc 0xffffffff8844f4da / registers:

     rax               0x12; rdx 0xffffffff88a38470; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e4a90f0;

  11: fn 0xffffffff8844e000 - pc 0xffffffff8844e168 / registers:

     rax               0x12; rdx 0xffffffff88a38470; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e4a9da0;

  12: fn 0xffffffff8856ded0 - pc 0xffffffff88572b3c / registers:

     rax               0x12; rdx 0xffffffff88a38470; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e4a9f30;

  13: fn 0xffffffff880df4c0 - pc 0xffffffff880df54e / registers:

     rax               0x12; rdx 0xffffffff88a38470; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e4c03d0;

  14: fn 0xffffffff882db7a0 - pc 0xffffffff882dc31f / registers:

     rax               0x12; rdx 0xffffffff88a38470; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e4c0570;

  15: fn 0xffffffff883ffc40 - pc 0xffffffff883ffc4e / registers:

     rax               0x12; rdx 0xffffffff88a38470; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e4c0f90;

  16: fn 0xffffffff887c0770 - pc 0xffffffff887c0786 / registers:

     rax               0x12; rdx 0xffffffff88a38470; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e4c0fb0;

  17: fn 0xffffffff887a61e0 - pc 0xffffffff887a6249 / registers:

     rax               0x12; rdx 0xffffffff88a38470; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e4c0fd0;

  18: fn                0x0 - pc                0x0 / registers:

     rax               0x12; rdx 0xffffffff88a38470; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff80007e4c1000;

[OSDK] The kernel seems panicked. Parsing stack trace for source lines:
(  1) /root/asterinas/ostd/src/panicking.rs:107
(  2) /root/asterinas/ostd/src/panicking.rs:59
(  3) 0yfjuqijmdltwb3g9ceg2tyxs:?
(  4) ??:?
(  5) ??:?
(  6) axbvs75vp1k66nwsaobv39t4g:?
(  7) /root/asterinas/kernel/aster-nix/src/vm/vmar/mod.rs:607
(  8) /root/asterinas/kernel/aster-nix/src/vm/vmar/vm_mapping.rs:102
(  9) /root/asterinas/kernel/aster-nix/src/vm/vmar/vm_mapping.rs:695
( 10) /root/asterinas/kernel/aster-nix/src/syscall/mmap.rs:137
( 11) /root/asterinas/kernel/aster-nix/src/syscall/mmap.rs:33
( 12) /root/asterinas/kernel/aster-nix/src/syscall/mod.rs:220
( 13) /root/asterinas/kernel/aster-nix/src/syscall/mod.rs:328
( 14) /root/asterinas/kernel/aster-nix/src/thread/task.rs:69
( 15) /root/.rustup/toolchains/nightly-2024-06-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:79
( 16) /root/.rustup/toolchains/nightly-2024-06-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2077
( 17) /root/asterinas/ostd/src/task/task/mod.rs:310
```

### PR DESCRIPTION
**Pull request by Marsman1996**
Fix #1213 

`mprotect` refers https://elixir.bootlin.com/linux/v6.10.5/source/mm/mprotect.c#L707

`madvise` refers https://elixir.bootlin.com/linux/v6.0.9/source/mm/madvise.c#L1404

`munmap` refers https://elixir.bootlin.com/linux/v6.10.5/source/mm/mmap.c#L2734

`mmap` refers https://elixir.bootlin.com/linux/v6.10.5/source/mm/mmap.c#L1729

### CODE REVIEW

**Comment by Marsman1996** [comment]
Fix #1214 

`mprotect` refers https://elixir.bootlin.com/linux/v6.10.5/source/mm/mprotect.c#L707

`madvise` refers https://elixir.bootlin.com/linux/v6.0.9/source/mm/madvise.c#L1407

`munmap` refers https://elixir.bootlin.com/linux/v6.10.5/source/mm/mmap.c#L2738

`mmap` refers https://elixir.bootlin.com/linux/v6.10.5/source/mm/mmap.c#L1248

**Comment by tatetian** [comment]
@cchanging Could you review this PR? Thanks.

File: kernel/src/syscall/madvise.rs [hunk 1]
```diff
@@ -20,11 +20,15 @@ pub fn sys_madvise(
     if start % PAGE_SIZE != 0 {
         return_errno_with_message!(Errno::EINVAL, "the start address should be page aligned");
     }
-    if len == 0 {
+    if len == 0 || len > usize::MAX - PAGE_SIZE + 1 {
         return Ok(SyscallReturn::Return(0));
```
Comment (tatetian) [inline kernel/src/syscall/madvise.rs:24]: Are you sure that a too large value should be treated in the same way as `0`? This looks an `EINVAL` error to me.

File: kernel/src/syscall/mmap.rs [hunk 2]
```diff
@@ -57,6 +57,9 @@ fn do_sys_mmap(
     if len == 0 {
         return_errno_with_message!(Errno::EINVAL, "mmap len cannot be zero");
     }
+    if len > usize::MAX - PAGE_SIZE + 1 {
```
Comment (tatetian) [inline kernel/src/syscall/mmap.rs:60]: First, are you sure that `len == usize::MAX - PAGE_SIZE + 1` is ok? This case the subsequent `align_up` will also overflow.

Second, I think we can choose a much lower upper bound for `len`. For example, `isize::MAX as usize`. This value is good for two reasons: (1) On x86-64, the lower half of the whole address space is reserved for the user space. So it is impossible for a user program to operate on a memory region whose length is beyond `isize::MAX as usize`. (2) Sometimes, it would be convenient to convert `usize` to `isize`. Using ``isize::MAX` as the upper bound ensures that it is ok to convert such a `usize` value to `isize`.

File: kernel/src/syscall/madvise.rs (hunk 1 above)
Comment (Marsman1996) [reply kernel/src/syscall/madvise.rs:24]: Yes, it should be EINVAL as https://elixir.bootlin.com/linux/v6.0.9/source/mm/madvise.c#L1399.
I misunderstand it as #L1407 condition...

File: kernel/src/syscall/mmap.rs [hunk 3]
```diff
@@ -57,6 +57,9 @@ fn do_sys_mmap(
...
+        return_errno_with_message!(Errno::ENOMEM, "mmap len align overflow");
```
Comment (cchanging) [inline kernel/src/syscall/mmap.rs:61]: I think there are some other overflow scenarios. e.g. when specifying `addr` or `offset`, `addr + len` or `offset + len` may be overflow, right?

File: kernel/src/syscall/mmap.rs (hunk 2 above)
Comment (Marsman1996) [reply kernel/src/syscall/mmap.rs:60]: 1. If I do not understand wrong, the `align_up` for `len: usize` is `len.checked_add(align - 1).unwrap()`, whose overflow condition is  `len + PAGE_SIZE - 1 > usize::MAX`. So `len` won't overflow when `len <= usize::MAX - PAGE_SIZE + 1` 
https://github.com/asterinas/asterinas/blob/a72c7dadf3b9bb680b3092af6b64084b98008cb7/ostd/libs/align_ext/src/lib.rs#L61

Comment (Marsman1996) [reply kernel/src/syscall/mmap.rs:60]: 2. Yes, in linux they use a const value `TASK_SIZE` to limit the range, which is `0xFFFFFFFFUL`.
https://elixir.bootlin.com/linux/v6.10.5/source/mm/mmap.c#L1864

File: kernel/src/syscall/mmap.rs (hunk 3 above)
Comment (Marsman1996) [reply kernel/src/syscall/mmap.rs:61]: Though I did not fuzz a `offset` related overflow, but there is possibility.
We should add a check here like https://elixir.bootlin.com/linux/v6.10.5/source/mm/mmap.c#L1251
But do we have something like `PAGE_SHIFT`?

Comment (cchanging) [reply kernel/src/syscall/mmap.rs:61]: You can feel free to add `PAGE_SHIFT`. However, it seems that Linux use `PAGE_SHIFT` is because it turns `offset` into `offset_in_pages` (i.e. pgoff). We may not need this value.

File: kernel/src/syscall/mmap.rs [hunk 4]
```diff
@@ -57,12 +57,22 @@ fn do_sys_mmap(
...
     if offset % PAGE_SIZE != 0 {
         return_errno_with_message!(Errno::EINVAL, "mmap only support page-aligned offset");
     }
+    offset.checked_add(len).ok_or(Error::with_message(
+        Errno::EOVERFLOW,
+        "integer overflow when (offset + len)",
+    ))?;
+    if addr > isize::MAX as usize - len {
+        return_errno_with_message!(Errno::ENOMEM, "mmap (addr + len) too large");
+    }
```
Comment (cchanging) [inline kernel/src/syscall/mmap.rs:75]: This should also be EINVAL. In [man page](https://man7.org/linux/man-pages/man2/mmap.2.html):
>  EINVAL We don't like addr, length, or offset (e.g., they are to large, or not aligned on a page boundary)

I think you use ENOMEM here because this:
> ENOMEM We don't like addr, because it exceeds the virtual address space of the CPU.

I'm not very sure, but I think this case should be `addr > MAX_USER_SPACE_ADDR`, and `addr + len > isize::MAX` is more like an overflow error. Have you tried these two cases in Linux? which errors do they return?

Comment (Marsman1996) [reply kernel/src/syscall/mmap.rs:75]: I use `ENOMEM` here because in https://elixir.bootlin.com/linux/v6.10.5/source/mm/mmap.c#L1248.
Linux uses the `ENOMEM` to report the overflow error, and I don't know why...
```C
/* Careful about overflows.. */
	len = PAGE_ALIGN(len);
	if (!len)
		return -ENOMEM;
```

Comment (Marsman1996) [reply kernel/src/syscall/mmap.rs:75]: As for the `addr > MAX_USER_SPACE_ADDR` condition, linux also uses the `ENOMEM` in https://elixir.bootlin.com/linux/v6.10.5/source/mm/mmap.c#L1896

```C
if (addr > TASK_SIZE - len)
	return -ENOMEM;
```

**Comment by Marsman1996** [comment]
@boterinas rerun

File: kernel/src/syscall/mmap.rs (hunk 4 above)
Comment (cchanging) [reply kernel/src/syscall/mmap.rs:75]: OK, let's keep it consistent with Linux.

File: kernel/src/syscall/mmap.rs (hunk 2 above)
Comment (tatetian) [reply kernel/src/syscall/mmap.rs]: Using `isize::MAX  / 2` looks fine with me.

**Comment by Marsman1996** [comment]
@boterinas rerun

File: kernel/src/syscall/mmap.rs (hunk 2 above)
Comment (Marsman1996) [reply kernel/src/syscall/mmap.rs]: If the boundary is set to `isize::MAX  / 2`, the CI will fail
https://github.com/asterinas/asterinas/actions/runs/10612897770/job/29418119617
And the result could be reproduced locally.

So I keep the boundary to `isize::MAX`

Comment (tatetian) [reply kernel/src/syscall/mmap.rs]: > If the boundary is set to `isize::MAX / 2`, the CI will fail https://github.com/asterinas/asterinas/actions/runs/10612897770/job/29418119617 And the result could be reproduced locally.
> 
> So I keep the boundary to `isize::MAX`

Sorry. I am not thinking straight. I meant `isize::MAX`.

File: kernel/src/syscall/mprotect.rs [hunk 5]
```diff
@@ -22,9 +22,16 @@ pub fn sys_mprotect(addr: Vaddr, len: usize, perms: u64, ctx: &Context) -> Resul
     if len == 0 {
         return Ok(SyscallReturn::Return(0));
     }
+    if len > usize::MAX - PAGE_SIZE + 1 {
```
Comment (tatetian) [inline kernel/src/syscall/mprotect.rs:25]: I thought all occurrences of `usize::MAX - PAGE_SIZE + 1` will be replaced with `isize::MAX`.

**Comment by Marsman1996** [comment]
@boterinas rerun

**Comment by Marsman1996** [comment]
@boterinas rerun

File: kernel/src/syscall/mprotect.rs (hunk 5 above)
Comment (Marsman1996) [reply kernel/src/syscall/mprotect.rs]: Replaced

**Review by tatetian — APPROVED** [review]
LGTM. Thanks for the contribution!
