### PR TITLE
Fix unexpected unlock of mutexes

### LINKED ISSUE #1274: Potential mutex lock bug leading to multiple threads entering critical section
### Describe the bug

Hi there!

I'm working on a testcase for issue #1261 to reproduce the bug, and I noticed a weird behavior. It seems that `mutex.lock()` does not block when another thread has already acquired the lock in `ktest`. This causes multiple threads to enter the critical section simultaneously.

### To Reproduce

1. `git apply ./patch.diff`
2. `make ktest`

Here is the `path.diff` file:

**Note**: I'm not sure if I inited the test environment and used `timer::Jiffies` and `Thread::yield_now()` correctly. I observed that without using `yield_now()`, thread scheduling does not occur. In other words, if `Thread::yield_now()` is commented out, this test case will pass.

```diff
diff --git a/kernel/src/process/sync/condvar.rs b/kernel/src/process/sync/condvar.rs
index 944fe070..52f3e971 100644
--- a/kernel/src/process/sync/condvar.rs
+++ b/kernel/src/process/sync/condvar.rs
@@ -363,4 +363,51 @@ mod test {
             assert!(!*started);
         }
     }
+
+    use ostd::arch::timer::Jiffies;
+
+    fn wait_jiffies(value: u64) {
+        let mut previous = Jiffies::elapsed().as_u64();
+        let ddl = previous + value;
+        loop {
+            let current = Jiffies::elapsed().as_u64();
+            if current >= ddl {
+                break;
+            }
+            if current - previous >= 10 {
+                previous = current;
+                Thread::yield_now();
+            }
+        }
+    }
+
+    #[ktest]
+    fn test_mutex_cs() {
+        let pair = Arc::new((Mutex::new(0), Condvar::new()));
+        let pair2 = Arc::clone(&pair);
+
+        Thread::spawn_kernel_thread(ThreadOptions::new(move || {
+            wait_jiffies(1000);
+            let (lock, _) = &*pair;
+            let mut val = lock.lock();
+            *val = 1;
+            wait_jiffies(1000);
+            assert!(*val == 1);
+            *val = 2;
+            wait_jiffies(1000);
+            assert!(*val == 2);
+        }));
+
+        {
+            let (lock2, _) = &*pair2;
+            let mut val = lock2.lock();
+            *val = 10;
+            wait_jiffies(1000);
+            assert!(*val == 10);
+            *val = 20;
+            wait_jiffies(1000);
+            assert!(*val == 20);
+        }
+
+    }
 }
```

### Expected behavior

Only one thread should enter the critical section at a time.

### Screenshots

28cecd84ca55772867240a21d99ec32

### Environment

Official Docker environment, version 0.8.1

### PR DESCRIPTION
**Pull request by tangruize**
Fixes #1274.

I added a testcase to prevent regression.
```sh
cd kernel && cargo osdk test test_mutex_critical_section
```

**Note**: The test case requires kernel/thread to work, but the mutex implementation is in ostd. Therefore, I created the test file in kernel (Is there a way to use thread in ostd?). I attempted to use Pauser for a more elegant timeout, but failed to `time::init()`. Currently, the testcase uses jiffies to busy-wait a timeout.

### CODE REVIEW

**Review by StevenJiang1110 — COMMENTED** [review]
A good fix! The problem is that `then_some` is eagerly evaluated, so the guard will be created and dropped even when the lock is not acquired successfully. The doc comment already emphasizes that `then_some`

But I can't see the relation between the test you added and the bug. Maybe you can remove the test.

**Comment by tangruize** [comment]
@StevenJiang1110 I removed the test case commit because the unit test isn't directly related to this fix.

However, I believe a test case is essential to prevent regression, as this issue was fixed by #497 and was reintroduced in #778.

The deleted test was useful for detecting the mutual exclusion property of the mutex in certain scenarios. I’ve migrated it from the `kernel` dir to the `ostd` dir (with help from @junyang-zh). If needed, here is the test case for reference:

<details>
<summary>test_mutex_critical_section</summary>

```diff
diff --git a/ostd/src/sync/mutex.rs b/ostd/src/sync/mutex.rs
index e423bde7..6c571093 100644
--- a/ostd/src/sync/mutex.rs
+++ b/ostd/src/sync/mutex.rs
@@ -138,3 +138,55 @@ impl<'a, T: ?Sized> MutexGuard<'a, T> {
         guard.mutex
     }
 }
+
+#[cfg(ktest)]
+mod test {
+    use super::*;
+    use alloc::sync::Arc;
+    use crate::{prelude::*, task::{Task, TaskOptions}, arch::timer::Jiffies};
+
+    fn wait_jiffies(value: u64) {
+        let mut previous = Jiffies::elapsed().as_u64();
+        let ddl = previous + value;
+        loop {
+            let current = Jiffies::elapsed().as_u64();
+            if current >= ddl {
+                break;
+            }
+            if current - previous >= 10 {
+                previous = current;
+                Task::yield_now();
+            }
+        }
+    }
+
+    #[ktest]
+    fn test_mutex_critical_section() {
+        let lock = Arc::new(Mutex::new(0));
+        let lock2 = Arc::clone(&lock);
+
+        TaskOptions::new(move || {
+            wait_jiffies(50);
+            let mut val = lock.lock();
+            *val = 1;
+            wait_jiffies(100);
+            assert!(*val == 1);
+            *val = 2;
+            wait_jiffies(100);
+            assert!(*val == 2);
+        })
+        .data(())
+        .spawn()
+        .unwrap();
+
+        {
+            let mut val = lock2.lock();
+            *val = 10;
+            wait_jiffies(100);
+            assert!(*val == 10);
+            *val = 20;
+            wait_jiffies(100);
+            assert!(*val == 20);
+        }
+    }
+}
```
</details>

**Comment by tangruize** [comment]
@StevenJiang1110 How about this test?


```diff
diff --git a/ostd/src/sync/mutex.rs b/ostd/src/sync/mutex.rs
index e423bde7..9106e2fd 100644
--- a/ostd/src/sync/mutex.rs
+++ b/ostd/src/sync/mutex.rs
@@ -138,3 +138,19 @@ impl<'a, T: ?Sized> MutexGuard<'a, T> {
         guard.mutex
     }
 }
+
+#[cfg(ktest)]
+mod test {
+    use super::*;
+    use crate::prelude::*;
+
+    #[ktest]
+    fn test_mutex_try_lock_does_not_unlock() {
+        let lock = Mutex::new(0);
+        assert!(lock.lock.load(Ordering::Relaxed) == false);
+        let _res1 = lock.try_lock();
+        assert!(lock.lock.load(Ordering::Relaxed) == true);
+        let _res2 = lock.try_lock();
+        assert!(lock.lock.load(Ordering::Relaxed) == true);
+    }
+}
```

**Comment by StevenJiang1110** [comment]
@tangruize, yes, the new test case is more related to the bug, and is suitable to be added to this PR. I just refine it a little below.

```rust
#[ktest]
fn test_mutex_try_lock_does_not_unlock() {
       let lock = Mutex::new(0);
       assert!(lock.lock.load(Ordering::Relaxed) == false);

       // A successful lock
       let guard1 = lock.lock();
       assert!(lock.lock.load(Ordering::Relaxed) == true);
       
       // A failed `try_lock` won't drop the lock
       assert!(lock.try_lock().is_none());
       assert!(lock.lock.load(Ordering::Relaxed) == true);

       drop(guard1);
}
```

File: ostd/src/sync/mutex.rs [hunk 1]
```diff
@@ -138,3 +142,26 @@ impl<'a, T: ?Sized> MutexGuard<'a, T> {
...
     }
 }
+
+#[cfg(ktest)]
+mod test {
+    use super::*;
+    use crate::prelude::*;
+
+    #[ktest]
+    fn test_mutex_try_lock_does_not_unlock() {
```
Comment (tatetian) [inline ostd/src/sync/mutex.rs:152]: I think it would be good to add a comment here, giving the reader some context as to why this test exists.

```rust
    // A regression test for a bug fixed in [#1279](https://github.com/asterinas/asterinas/pull/1279).
    #[ktest]
    fn test_mutex_try_lock_does_not_unlock() {
```

File: ostd/src/sync/mutex.rs [hunk 2]
```diff
@@ -50,7 +50,11 @@ impl<T: ?Sized> Mutex<T> {
     pub fn try_lock(&self) -> Option<MutexGuard<T>> {
         // Cannot be reduced to `then_some`, or the possible dropping of the temporary
         // guard will cause an unexpected unlock.
-        self.acquire_lock().then_some(MutexGuard { mutex: self })
+        //
+        // TODO: Remove the lint suppression when the false positive warning is fixed
+        // upstream.
+        #[allow(clippy::unnecessary_lazy_evaluations)]
```
Comment (tangruize) [inline ostd/src/sync/mutex.rs:56]: @tatetian This TODO comment refers to https://github.com/asterinas/asterinas/commit/3790efb0d9c8c23b268ab3926910f90acb6ab9d1, which is addressed by https://github.com/asterinas/asterinas/commit/576578baf4025686ae4c2893c2aafbc8d1e14722. Would it be better to create a `new` method?

Comment (junyang-zh) [reply ostd/src/sync/mutex.rs:56]: I'll vote for it. If you do create a `new` method please mark it unsafe.

Comment (tangruize) [reply ostd/src/sync/mutex.rs]: OK, pls review.

File: ostd/src/sync/mutex.rs [hunk 3]
```diff
@@ -100,6 +101,16 @@ pub struct MutexGuard_<T: ?Sized, R: Deref<Target = Mutex<T>>> {
 /// A guard that provides exclusive access to the data protected by a [`Mutex`].
 pub type MutexGuard<'a, T> = MutexGuard_<T, &'a Mutex<T>>;
 
+impl<'a, T: ?Sized> MutexGuard<'a, T> {
+    /// # Safety
+    ///
+    /// The caller must ensure that the `MutexGuard`'s lifetime is properly managed. When the
+    /// `MutexGuard` goes out of scope, it will call `drop()` to release the mutex lock.
+    unsafe fn new(mutex: &'a Mutex<T>) -> MutexGuard<'a, T> {
```
Comment (junyang-zh) [inline ostd/src/sync/mutex.rs:109]: The safety precondition of this function should be that the passed `mutex` has successfully acquired the lock (as it's inner state). So it should be documented as:

```rust
    /// # Safety
    ///
    /// The caller must ensure that the given reference of [`Mutex`] lock has been successfully acquired in the
    /// current context. When the created [`MutexGuard`] is dropped, it will unlock the [`Mutex`].
```

File: ostd/src/sync/mutex.rs [hunk 4]
```diff
@@ -50,7 +50,8 @@ impl<T: ?Sized> Mutex<T> {
     pub fn try_lock(&self) -> Option<MutexGuard<T>> {
         // Cannot be reduced to `then_some`, or the possible dropping of the temporary
         // guard will cause an unexpected unlock.
-        self.acquire_lock().then_some(MutexGuard { mutex: self })
+        self.acquire_lock()
+            .then(|| unsafe { MutexGuard::new(self) })
```
Comment (junyang-zh) [inline ostd/src/sync/mutex.rs:54]: Add a safety explanation here:

```rust
        // Cannot be reduced to `then_some`, or the possible dropping of the temporary
        // guard will cause an unexpected unlock.
        // SAFETY: The lock is successfully acquired when creating the guard.
        self.acquire_lock()
            .then(|| unsafe { MutexGuard::new(self) })
```

Comment (tangruize) [reply ostd/src/sync/mutex.rs:55]: OK, pls review

**Review by tatetian — APPROVED** [review]
LGTM. Thanks for the contribution!
