### PR TITLE
Never queue an ignored signal

### LINKED ISSUE #2072: A rare regression test failure
### Describe the bug

The integration test fails by:

```
fatal error: setup_barrier209: `_ret >= 0` is false after `usleep(100 * 1000)` [got Interrupted system call]
fatal error: setup_run_in_new_session: `(((status) & 0x7f) == 0) && (((status) & 0xff00) >> 8) == 0` is false after `wait(&status)` [got Success]
```

This is only caught once in https://github.com/asterinas/asterinas/actions/runs/14953404725/job/42005816258?pr=2070 , but subsequent runs are successful. I guess there's some race involving interrupts.

### PR DESCRIPTION
**Pull request by lrh2000**
An ignored signal shouldn't wake up the process, otherwise it causes issues in https://github.com/asterinas/asterinas/issues/2072, https://github.com/asterinas/asterinas/pull/2151#issuecomment-2958479359, https://github.com/asterinas/asterinas/pull/2082.

However, we do not have a process-wide signal queue. Therefore, it is impossible to determine to which thread's signal queue the signals should be added. All threads block signals, and we don't know which thread will want to change the handler and/or unblock the signal in the future.

It is much more reasonable to ensure that none of the thread signal queues have ignored signals, though this differs from the behavior of Linux:
```rust
    /// Enqueues a thread-directed signal with locked dispositions.
    ///
    /// By locking dispositions, the caller should have already checked the signal is not to be
    /// ignored.
    //
    // FIXME: According to Linux behavior, we should enqueue ignored signals blocked by all
    // threads, as a thread may change the signal handler and unblock them in the future. However,
    // achieving this behavior properly without maintaining a process-wide signal queue is
    // difficult. For instance, if we randomly select a thread-wide signal queue, the thread that
    // modifies the signal handler and unblocks the signal may not be the same one. Consequently,
    // the current implementation uses a simpler mechanism that never enqueues any ignored signals.
    pub(in crate::process) fn enqueue_signal_locked(
        &self,
        signal: Box<dyn Signal>,
        _sig_dispositions: MutexGuard<SigDispositions>,
    );
```

Fixes #2072.

### CODE REVIEW

File: kernel/src/process/kill.rs [hunk 1]
```diff
@@ -132,16 +136,16 @@ fn kill_process(process: &Process, signal: Option<UserSignal>, ctx: &Context) ->
...
+                // If `signal` is `None`, only permission check is required.
                 return Ok(());
             };
 
             if !posix_thread.has_signal_blocked(*signum) {
-                // Send signal to any thread that does not blocks the signal.
-                let signal = signal.unwrap();
-                posix_thread.enqueue_signal(Box::new(signal));
-                return Ok(());
+                // Send the signal to any thread that does not blocks the signal.
```
Comment (StevenJiang1110) [inline kernel/src/process/kill.rs]: blocks -> block

File: kernel/src/process/posix_thread/mod.rs [hunk 2]
```diff
@@ -199,14 +199,41 @@ impl PosixThread {
...
+    /// By locking dispositions, the caller should have already checked the signal is not to be
+    /// ignored.
+    //
+    // FIXME: According to Linux behavior, we should enqueue ignored signals blocked by all
+    // threads, as a thread may change the signal handler and unblock them in the future. However,
+    // achieving this behavior properly without maintaining a process-wide signal queue is
+    // difficult. For instance, if we randomly select a thread-wide signal queue, the thread that
+    // modifies the signal handler and unblocks the signal may not be the same one. Consequently,
+    // the current implementation uses a simpler mechanism that never enqueues any ignored signals.
+    pub(in crate::process) fn enqueue_signal_locked(
```
Comment (StevenJiang1110) [inline kernel/src/process/posix_thread/mod.rs:230]: Can we consider maintaining another invariant: all signals in the sigqueue are either blocked or not ignored?

For signals that are blocked by all threads but should be ignored, could we also enqueue the signal to a random thread to better mimic Linux behavior? Additionally, we may need to discard signals in another scenario: once any signal is unblocked (if any thread calls sigprocmask), we should scan the sigqueue of the calling thread and discard any signals that are ignored.

This approach seems to allow the failed test to pass. Could this introduce any issues?

**Review by StevenJiang1110 — COMMENTED** [review]
Mostly looks good to me! Thanks for your contribution!

File: kernel/src/process/posix_thread/mod.rs (hunk 2 above)
Comment (lrh2000) [reply kernel/src/process/posix_thread/mod.rs:230]: > all signals in the sigqueue are either blocked or not ignored

`sig_mask` is an atomic variable. Nobody can enforce this invariant because it's always possible that the thread is running and concurrently modifying its signal mask. We don't seem to acquire any lock when modifying the signal mask:
https://github.com/asterinas/asterinas/blob/3e32a38316a9b134bea3121fb89887c41eb93dc8/kernel/src/syscall/rt_sigprocmask.rs#L46-L62

> random thread to better mimic Linux behavior

There is no difference between enqueuing to the main thread and to a random thread. They both differ from the Linux behavior. I don't understand why "randomness" helps here.

Perhaps making this PR more complex won't be worth it unless it fixes the inconsistent behavior with Linux. Your proposed solution still differs from the Linux one and is more complex, so I don't understand why it's better.

Comment (StevenJiang1110) [reply kernel/src/process/posix_thread/mod.rs:230]: > sig_mask is an atomic variable. Nobody can enforce this invariant because it's always possible that the thread is running and concurrently modifying its signal mask.

Got it. Since there’s no lock on the signal mask, we cannot simply discard ignored signals after changing it.

> There is no difference between enqueuing to the main thread and to a random thread. They both differ from the Linux behavior. I don't understand why "randomness" helps here.

I didn't mean to emphasize "random" here. What I meant is that maintaining the invariant—"all signals in the sigqueue are either blocked or not ignored"—can better mimic Linux behavior.

> Perhaps making this PR more complex won't be worth it unless it fixes the inconsistent behavior with Linux. Your proposed solution still differs from the Linux one and is more complex, so I don't understand why it's better.

Yes, I admit that maintaining this invariant may not be a significant improvement. However, I think it could help the failed regression test pass, which is why I consider it somewhat better.

That said, it seems unreliable since the signal mask lacks a lock, so the current implementation is acceptable to me.

**Review by StevenJiang1110 — APPROVED** [review]
LGTM! Thanks for your contribution!
