### PR TITLE
Fix `InitStackReader` to access given stack instead of current task

### LINKED ISSUE #1562: Access wrong stack in `InitStackReader`
### Describe the bug

Asterinas access wrong stack in `InitStackReader` when read from other process (i.e., `cat /proc/1/cmdline`).

The Asterinas reads `argv` from the process init stack by 
1. read the `argc` from init stack bottom
2. read `argc` times from init stack

https://github.com/asterinas/asterinas/blob/16a319a8ea7a0e04432bba8dfe0c4d0702083e14/kernel/src/process/process_vm/init_stack/mod.rs#L377-L389

However, because Asterinas accesses wrong stack due to the `get_current_userspace!` returns the user space of `cat` instead of `init`, the value of `argc` is huge (i.e., 0x00007ffffffc7fe7), and causing Asterinas to panic.

And the data is actually from the stack of currently running programs.

```
0x7ffffffc7ea0: 0x0000000000000002      0x00007ffffffc7f9d
0x7ffffffc7eb0: 0x00007ffffffc7fa1      0x0000000000000000
0x7ffffffc7ec0: 0x00007ffffffc7ff6      0x00007ffffffc7fee
0x7ffffffc7ed0: 0x00007ffffffc7fe7      0x00007ffffffc7fda <- The argc of PID 1, is now the ENV of `cat`
0x7ffffffc7ee0: 0x00007ffffffc7fc5      0x00007ffffffc7fb7
0x7ffffffc7ef0: 0x00007ffffffc7fb1      0x0000000000000000
```

### To Reproduce

Just simply run `$ cat /proc/1/cmdline`

### Expected behavior

Asterinas should output the cmdline of the program whose PID is 1.

### Screenshots
image

Green for `cat` stack, and red for `init` stack location.

### Environment

- Official docker asterinas/asterinas:0.9.4
- Intel(R) Xeon(R) Gold 6230R CPU @ 2.10GHz
- Asterinas version: main 16a319a8

### Logs
```
write stack_base = 0x7fffff73d000
write envp into address 0x7ffffff3cff2, envp is "SHELL=/bin/sh"
write envp into address 0x7ffffff3cfe5, envp is "LOGNAME=root"
write envp into address 0x7ffffff3cfde, envp is "HOME=/"
write envp into address 0x7ffffff3cfd4, envp is "USER=root"
write envp into address 0x7ffffff3cfbf, envp is "PATH=/bin:/benchmark"
write argv into address 0x7ffffff3cfbc, argv is "-l"
write argv into address 0x7ffffff3cfb9, argv is "sh"
envp pointer 0x7ffffff3cfbf is written into 0x7ffffff3cf10
envp pointer 0x7ffffff3cfd4 is written into 0x7ffffff3cf08
envp pointer 0x7ffffff3cfde is written into 0x7ffffff3cf00
envp pointer 0x7ffffff3cfe5 is written into 0x7ffffff3cef8
envp pointer 0x7ffffff3cff2 is written into 0x7ffffff3cef0
argv pointer 0x7ffffff3cfbc is written into 0x7ffffff3cee0
argv pointer 0x7ffffff3cfb9 is written into 0x7ffffff3ced8
write argc 2 into argc_addr = 0x7ffffff3ced0
~ # cat /proc/1/cmdline 
write stack_base = 0x7fffff73d000
write envp into address 0x7ffffff3cff6, envp is "USER=root"
write envp into address 0x7ffffff3cfee, envp is "SHLVL=1"
write envp into address 0x7ffffff3cfe7, envp is "HOME=/"
write envp into address 0x7ffffff3cfda, envp is "LOGNAME=root"
write envp into address 0x7ffffff3cfc5, envp is "PATH=/bin:/benchmark"
write envp into address 0x7ffffff3cfb7, envp is "SHELL=/bin/sh"
write envp into address 0x7ffffff3cfb1, envp is "PWD=/"
write argv into address 0x7ffffff3cfa1, argv is "/proc/1/cmdline"
write argv into address 0x7ffffff3cf9d, argv is "cat"
envp pointer 0x7ffffff3cfb1 is written into 0x7ffffff3cef0
envp pointer 0x7ffffff3cfb7 is written into 0x7ffffff3cee8
envp pointer 0x7ffffff3cfc5 is written into 0x7ffffff3cee0
envp pointer 0x7ffffff3cfda is written into 0x7ffffff3ced8
envp pointer 0x7ffffff3cfe7 is written into 0x7ffffff3ced0
envp pointer 0x7ffffff3cfee is written into 0x7ffffff3cec8
envp pointer 0x7ffffff3cff6 is written into 0x7ffffff3cec0
argv pointer 0x7ffffff3cfa1 is written into 0x7ffffff3ceb0
argv pointer 0x7ffffff3cf9d is written into 0x7ffffff3cea8
write argc 2 into argc_addr = 0x7ffffff3cea0
/usr/bin/busybox
read argc from 0x7ffffff3ced0
read argc = 0x7ffffff3cfe7, read_offset = 0x7ffffff3ced8
[    58.264] ERROR: Uncaught panic: Heap allocation error, layout = Layout { size: 2251799800905328, align: 8 (1 << 3) }
at /root/asterinas/ostd/src/mm/heap_allocator/mod.rs:26
```

### PR DESCRIPTION
**Pull request by Marsman1996**
Fix #1562

With this PR we can access the right stack in `InitStackReader`, and `cmdline` finally works.

```
~ # cat /proc/1/cmdline 
sh-l~ #
```

### CODE REVIEW

File: kernel/src/context.rs [hunk 1]
```diff
@@ -226,6 +226,63 @@ impl ReadCString for VmReader<'_, Fallible> {
     }
 }
 
+impl ReadCString for VmReader<'_, Infallible> {
```
Comment (tatetian) [inline kernel/src/context.rs:229]: Is the code (almost) identical with `impl ReadCString for VmReader<'_, Fallible>`? If so, then we need to find a way to avoid the code duplication. One strategy is to convert `VmReader<'_, Infallible>` to `VmReader<'_, Fallible>`, then use the later one's `ReadCString` implementation.

File: kernel/src/process/process_vm/init_stack/mod.rs [hunk 2]
```diff
@@ -366,17 +363,27 @@ fn generate_random_for_aux_vec() -> [u8; 16] {
...
         let stack_base = self.init_stack_bottom();
-        get_current_userspace!().read_val(stack_base)
+        let page_base_addr = stack_base.align_down(PAGE_SIZE);
+
+        let mut cursor = self
+            .vm_space
+            .cursor(&(page_base_addr..page_base_addr + PAGE_SIZE))?;
+        if let VmItem::Mapped { frame, .. } = cursor.query()? {
+            Ok(frame.read_val::<u64>(stack_base - page_base_addr)?)
+        } else {
```
Comment (tatetian) [inline kernel/src/process/process_vm/init_stack/mod.rs:384]: This is a general (and also well known) advice on writing readable code: **do not treat the correct and error branches as equal; return early on error to avoid unnecessary indentation levels.** This is so wide accepted practice that the Rust language assists you with the `let-else` construct.

```rust
let VmItem::Mapped { frame, .. } = cursor.query()? else {
    return_errno_with_message!(Errno::EACCES, "Page not accessible");
};

// Continue on with the correct, main logic...
```

This is a general technique to improve code readability. Use it as much as you can. While this function can benefit from this technique, the improvement on readability is greater on more complex code. For example, apply this technique to the `argv` and `envp` methods (which are much more complex) and see the results for yourself 😄

**Review by tatetian — COMMENTED** [review]
Good job on identifying and fixing the bug!

File: kernel/src/context.rs (hunk 1 above)
Comment (Marsman1996) [reply kernel/src/context.rs:229]: Yes, I just copy the `ReadCString` implement here, I will give a try.

File: kernel/src/process/process_vm/init_stack/mod.rs (hunk 2 above)
Comment (Marsman1996) [reply kernel/src/process/process_vm/init_stack/mod.rs]: improved with `let-else`

**Review by tatetian — APPROVED** [review]
LGTM. Thanks for the contribution!

**Comment by tangruize** [comment]
Directly reading the process stack without protection seems fragile and may introduce security risks. Consider the following cases:

- `./cat argv1`
- `./cat argv2`
- `./cat argc`

```c
// cat.c
// SPDX-License-Identifier: MPL-2.0

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main(int argc, char **argv) {
    if (argc == 2) {
        if (strcmp(argv[1], "argv1") == 0) {
            argv[1][strlen(argv[1])] = '?';
        }
        if (strcmp(argv[1], "argv2") == 0) {
            *((ssize_t *)(argv)) = 0xdeadbeef;
        }
        else if (strcmp(argv[1], "argc") == 0) {
            *((ssize_t *)(argv - 1)) = 0xdeadbeef;
        }
    }
    FILE *file = fopen("/proc/self/cmdline", "r");
    if (file == NULL) {
        perror("Error opening /proc/self/cmdline");
        return 1;
    }

    int c;
    while ((c = fgetc(file)) != EOF) {
        if (c == '\0') {
            c = ' ';  // Replace null characters with spaces for readability
        }
        putchar(c);
    }

    fclose(file);
    putchar('\n');
    return 0;
}
```

**Comment by Marsman1996** [comment]
### What happened:
For `$ ./cat argv2`, the program overwrites the point of `argv` in stack, which makes a sub overflow.
For `./cat argc`, the program overwrites the `argc`in stackm which makes a large allocation and fail.

### How Linux do:
Linux uses a data structure `struct mm_struct` to store the point pointed to `argv` and `envp` instead of reading argc first:
```
unsigned long arg_start, arg_end, env_start, env_end;
```

For Asterinas, maybe we could store the point value in the `pub struct Process`, I will create a PR soon.
