### PR TITLE
Fix mapping between `sched_attr` and `SchedPolicy`

### LINKED ISSUE #2153: Reachable assertion in `IdleClassRq::enqueue` when schedule idel for multiple threads
### Describe the bug
There is a reachable assertion in `IdleClassRq::enqueue()` at kernel/src/sched/sched_class/idle.rs:39 when schedule idel for multiple threads.

https://github.com/asterinas/asterinas/blob/71e08b394257406f7a64cc70bb9c0750b723c923/kernel/src/sched/sched_class/idle.rs#L39-L42

### To Reproduce
1. Compile the program and run:
```C
#define _GNU_SOURCE
#include <pthread.h>
#include <sched.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <errno.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>

#define SCHED_IDLE 5

pthread_barrier_t barrier;

void *thread_func(void *arg) {
    int thread_num = *((int *)arg);
    struct sched_param param = { .sched_priority = 0 };
    
    printf("Thread %d waiting at barrier\n", thread_num);
    pthread_barrier_wait(&barrier);
    
    int ret = sched_setscheduler(0, SCHED_IDLE, &param);
    
    if (ret != 0) {
        printf("Thread %d: sched_setscheduler failed: %s\n", 
               thread_num, strerror(errno));
    } else {
        printf("Thread %d: successfully set to IDLE policy\n", thread_num);
    }
    
    sleep(1);
    return NULL;
}

int main() {
    int num_threads = 4;
    
    if (pthread_barrier_init(&barrier, NULL, num_threads) != 0) {
        perror("pthread_barrier_init failed");
        exit(1);
    }
    
    pthread_t *threads = malloc(num_threads * sizeof(pthread_t));
    int *thread_nums = malloc(num_threads * sizeof(int));
    
    if (!threads || !thread_nums) {
        perror("Memory allocation failed");
        exit(1);
    }
    
    for (int i = 0; i < num_threads; i++) {
        thread_nums[i] = i;
        if (pthread_create(&threads[i], NULL, thread_func, &thread_nums[i]) != 0) {
            perror("pthread_create failed");
            exit(1);
        }
    }
    
    for (int i = 0; i < num_threads; i++) {
        pthread_join(threads[i], NULL);
    }
    
    printf("All threads completed\n");
    
    pthread_barrier_destroy(&barrier);
    free(threads);
    free(thread_nums);
    
    return 0;
}
```

### Expected behavior
Asterinas shall not panic when run the program.

### Environment
- Official docker asterinas/asterinas:0.15.0-20250516
- Intel(R) Xeon(R) Gold 6230R CPU @ 2.10GHz
- Asterinas version: main 8583eea

### Log
```
~ # /root/trigger_idle_bug.c 
Thread 0 waiting at barrier
Thread 2 waiting at barrier
Thread 1 waiting at barrier
Thread 3 waiting at barrier
Thread 3: successfully set to IDLE policy
Thread 2: successfully set to IDLE policy
Thread 1: successfully set to IDLE policy
Thread 0: successfully set to IDLE policy
[    24.468] ERROR: Uncaught panic:
        the length of the idle queue should be no larger than 1
        at /root/asterinas/kernel/src/sched/sched_class/idle.rs:39
        on CPU 0 by thread Some(Thread { task: (Weak), data: Any { .. }, status: AtomicThreadStatus(1), cpu_affinity: AtomicCpuSet { bits: [1] }, sched_attr: SchedAttr { policy: SchedPolicyState { kind: AtomicSchedPolicyKind(3), policy: UnsafeCell { .. } }, last_cpu: AtomicCpuId(0), real_time: RealTimeAttr { prio: 99, time_slice: 31498180 }, fair: FairAttr { weight: 1024, vruntime: 0 } } })
Printing stack trace:
   1: fn 0xffffffff88761120 - pc 0xffffffff8876116a / registers:

     rax 0xffffffff88c74c18; rdx  0x100000000000008; rcx 0xffffffff88c74c18; rbx                0x0;
     rsi 0xffffffff88c74bf8; rdi  0x1ffffff887c1507; rbp                0x0; rsp 0xffffdfffffffce50;

   2: fn 0xffffffff882809b0 - pc 0xffffffff88281159 / registers:

     rax 0xffffffff88c74c18; rdx  0x100000000000008; rcx 0xffffffff88c74c18; rbx                0x0;
     rsi 0xffffffff88c74bf8; rdi  0x1ffffff887c1507; rbp                0x0; rsp 0xffffdfffffffcea0;

   3: fn 0xffffffff882809a0 - pc 0xffffffff882809aa / registers:

     rax 0xffffffff88c74c18; rdx  0x100000000000008; rcx 0xffffffff88c74c18; rbx                0x0;
     rsi 0xffffffff88c74bf8; rdi  0x1ffffff887c1507; rbp                0x0; rsp 0xffffdfffffffd2b0;

   4: fn 0xffffffff8804b000 - pc 0xffffffff8804b00a / registers:

     rax 0xffffffff88c74c18; rdx  0x100000000000008; rcx 0xffffffff88c74c18; rbx                0x0;
     rsi 0xffffffff88c74bf8; rdi  0x1ffffff887c1507; rbp                0x0; rsp 0xffffdfffffffd2c0;

   5: fn 0xffffffff8893b620 - pc 0xffffffff8893b664 / registers:

     rax 0xffffffff88c74c18; rdx  0x100000000000008; rcx 0xffffffff88c74c18; rbx                0x0;
     rsi 0xffffffff88c74bf8; rdi  0x1ffffff887c1507; rbp                0x0; rsp 0xffffdfffffffd2d0;

   6: fn 0xffffffff8819c550 - pc 0xffffffff8819c5a1 / registers:

     rax 0xffffffff88c74c18; rdx  0x100000000000008; rcx 0xffffffff88c74c18; rbx                0x0;
     rsi 0xffffffff88c74bf8; rdi  0x1ffffff887c1507; rbp                0x0; rsp 0xffffdfffffffd310;

   7: fn 0xffffffff8819d2f0 - pc 0xffffffff8819d3c8 / registers:

     rax 0xffffffff88c74c18; rdx  0x100000000000008; rcx 0xffffffff88c74c18; rbx                0x0;
     rsi 0xffffffff88c74bf8; rdi  0x1ffffff887c1507; rbp                0x0; rsp 0xffffdfffffffd370;

   8: fn 0xffffffff8819cab0 - pc 0xffffffff8819cd00 / registers:

     rax 0xffffffff88c74c18; rdx  0x100000000000008; rcx 0xffffffff88c74c18; rbx                0x0;
     rsi 0xffffffff88c74bf8; rdi  0x1ffffff887c1507; rbp                0x0; rsp 0xffffdfffffffd3d0;

   9: fn 0xffffffff8878e630 - pc 0xffffffff8878e696 / registers:

     rax 0xffffffff88c74c18; rdx  0x100000000000008; rcx 0xffffffff88c74c18; rbx                0x0;
     rsi 0xffffffff88c74bf8; rdi  0x1ffffff887c1507; rbp                0x0; rsp 0xffffdfffffffd490;

  10: fn 0xffffffff88753430 - pc 0xffffffff8875346c / registers:

     rax 0xffffffff88c74c18; rdx  0x100000000000008; rcx 0xffffffff88c74c18; rbx                0x0;
     rsi 0xffffffff88c74bf8; rdi  0x1ffffff887c1507; rbp                0x0; rsp 0xffffdfffffffd4d0;

  11: fn 0xffffffff8812c3f0 - pc 0xffffffff8812c402 / registers:

     rax 0xffffffff88c74c18; rdx  0x100000000000008; rcx 0xffffffff88c74c18; rbx                0x0;
     rsi 0xffffffff88c74bf8; rdi  0x1ffffff887c1507; rbp                0x0; rsp 0xffffdfffffffd4f0;

  12: fn 0xffffffff887e5100 - pc 0xffffffff887e5116 / registers:

     rax 0xffffffff88c74c18; rdx  0x100000000000008; rcx 0xffffffff88c74c18; rbx                0x0;
     rsi 0xffffffff88c74bf8; rdi  0x1ffffff887c1507; rbp                0x0; rsp 0xffffdfffffffd500;

  13: fn 0xffffffff881ea5f0 - pc 0xffffffff881ea63d / registers:

     rax 0xffffffff88c74c18; rdx  0x100000000000008; rcx 0xffffffff88c74c18; rbx                0x0;
     rsi 0xffffffff88c74bf8; rdi  0x1ffffff887c1507; rbp                0x0; rsp 0xffffdfffffffd520;

  14: fn 0xffffffff8857fc80 - pc 0xffffffff8857fc8a / registers:

     rax 0xffffffff88c74c18; rdx  0x100000000000008; rcx 0xffffffff88c74c18; rbx                0x0;
     rsi 0xffffffff88c74bf8; rdi  0x1ffffff887c1507; rbp                0x0; rsp 0xffffdfffffffd570;

  15: fn 0xffffffff887e5100 - pc 0xffffffff887e5116 / registers:

     rax 0xffffffff88c74c18; rdx  0x100000000000008; rcx 0xffffffff88c74c18; rbx                0x0;
     rsi 0xffffffff88c74bf8; rdi  0x1ffffff887c1507; rbp                0x0; rsp 0xffffdfffffffd580;

  16: fn 0xffffffff881ea870 - pc 0xffffffff881eaacf / registers:

     rax 0xffffffff88c74c18; rdx  0x100000000000008; rcx 0xffffffff88c74c18; rbx                0x0;
     rsi 0xffffffff88c74bf8; rdi  0x1ffffff887c1507; rbp                0x0; rsp 0xffffdfffffffd5a0;

  17: fn 0xffffffff884d1600 - pc 0xffffffff884d166c / registers:

     rax 0xffffffff88c74c18; rdx  0x100000000000008; rcx 0xffffffff88c74c18; rbx                0x0;
     rsi 0xffffffff88c74bf8; rdi  0x1ffffff887c1507; rbp                0x0; rsp 0xffffdfffffffd690;

  18: fn 0xffffffff882836a0 - pc 0xffffffff882836ab / registers:

     rax 0xffffffff88c74c18; rdx  0x100000000000008; rcx 0xffffffff88c74c18; rbx                0x0;
     rsi 0xffffffff88c74bf8; rdi  0x1ffffff887c1507; rbp                0x0; rsp 0xffffdfffffffd6c0;

  19: fn 0xffffffff885947a0 - pc 0xffffffff88594853 / registers:

     rax 0xffffffff88c74c18; rdx  0x100000000000008; rcx 0xffffffff88c74c18; rbx                0x0;
     rsi 0xffffffff88c74bf8; rdi  0x1ffffff887c1507; rbp                0x0; rsp 0xffffdfffffffd6d0;

  20: fn 0xffffffff88282240 - pc 0xffffffff8828224e / registers:

     rax 0xffffffff88c74c18; rdx  0x100000000000008; rcx 0xffffffff88c74c18; rbx                0x0;
     rsi 0xffffffff88c74bf8; rdi  0x1ffffff887c1507; rbp                0x0; rsp 0xffffdfffffffd720;

  21: fn 0xffffffff887e5100 - pc 0xffffffff887e5116 / registers:

     rax 0xffffffff88c74c18; rdx  0x100000000000008; rcx 0xffffffff88c74c18; rbx                0x0;
     rsi 0xffffffff88c74bf8; rdi  0x1ffffff887c1507; rbp                0x0; rsp 0xffffdfffffffd740;

  22: fn 0xffffffff886bee30 - pc 0xffffffff886bef61 / registers:

     rax 0xffffffff88c74c18; rdx  0x100000000000008; rcx 0xffffffff88c74c18; rbx                0x0;
     rsi 0xffffffff88c74bf8; rdi  0x1ffffff887c1507; rbp                0x0; rsp 0xffffdfffffffd760;

  23: fn 0xffffffff886bedf0 - pc 0xffffffff886bee22 / registers:

     rax 0xffffffff88c74c18; rdx  0x100000000000008; rcx 0xffffffff88c74c18; rbx                0x0;
     rsi 0xffffffff88c74bf8; rdi  0x1ffffff887c1507; rbp                0x0; rsp 0xffffdfffffffd790;

  24: fn 0xffffffff887c1660 - pc 0xffffffff887c16c6 / registers:

     rax 0xffffffff88c74c18; rdx  0x100000000000008; rcx 0xffffffff88c74c18; rbx                0x0;
     rsi 0xffffffff88c74bf8; rdi  0x1ffffff887c1507; rbp                0x0; rsp 0xffffdfffffffd7a0;

  25: fn 0xffffffff887c16f0 - pc 0xffffffff887c1747 / registers:

     rax 0xffffffff88c74c18; rdx  0x100000000000008; rcx 0xffffffff88c74c18; rbx                0x0;
     rsi 0xffffffff88c74bf8; rdi  0x1ffffff887c1507; rbp                0x0; rsp 0xffffdfffffffd7d0;

  26: fn 0xffffffff887d1c60 - pc 0xffffffff887d1cfd / registers:

     rax 0xffffffff88c74c18; rdx  0x100000000000008; rcx 0xffffffff88c74c18; rbx                0x0;
     rsi 0xffffffff88c74bf8; rdi  0x1ffffff887c1507; rbp                0x0; rsp 0xffffdfffffffd800;

  27: fn                0x0 - pc 0xffffffff887c3437 / registers:

     rax 0xffffffff88c74c18; rdx  0x100000000000008; rcx 0xffffffff88c74c18; rbx                0x0;
     rsi 0xffffffff88c74bf8; rdi  0x1ffffff887c1507; rbp                0x0; rsp 0xffffdfffffffd9e0;

OSDK] The kernel seems panicked. Parsing stack trace for source lines:
(  1) /root/asterinas/ostd/src/panic.rs:107
(  2) /root/asterinas/kernel/src/thread/oops.rs:129
(  3) ??:?
(  4) 6xxckaq51vejpy1scqt7q1m7m:?
(  5) ??:?
(  6) ??:?
(  7) 496itk5k1ceazn1jrytonhu6h:?
(  8) /root/asterinas/kernel/src/sched/sched_class/mod.rs:225
(  9) /root/asterinas/ostd/src/task/scheduler/mod.rs:161
( 10) /root/asterinas/ostd/src/sync/wait.rs:268
( 11) /root/asterinas/kernel/src/time/wait.rs:188
( 12) /root/.rustup/toolchains/nightly-2025-02-01-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2031
( 13) /root/asterinas/kernel/src/time/core/timer.rs:137
( 14) /root/asterinas/kernel/src/time/core/timer.rs:89
( 15) /root/.rustup/toolchains/nightly-2025-02-01-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2031
( 16) /root/asterinas/kernel/src/time/core/timer.rs:211
( 17) /root/asterinas/kernel/src/time/clocks/system_wide.rs:238
( 18) /root/.rustup/toolchains/nightly-2025-02-01-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250
( 19) /root/asterinas/kernel/src/time/softirq.rs:51
( 20) /root/.rustup/toolchains/nightly-2025-02-01-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:79
( 21) /root/.rustup/toolchains/nightly-2025-02-01-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2031
( 22) /root/asterinas/kernel/comps/softirq/src/lib.rs:162
( 23) /root/asterinas/kernel/comps/softirq/src/lib.rs:136
( 24) /root/asterinas/ostd/src/trap/handler.rs:45
( 25) /root/asterinas/ostd/src/trap/handler.rs:73
( 26) /root/asterinas/ostd/src/arch/x86/trap/mod.rs:278
```

### PR DESCRIPTION
**Pull request by js2xxx**
Fixes #2153.

Mapping between `sched_attr` and `SchedPolicy`:

- Before:
  - `SCHED_NORMAL` <-> `SchedPolicy::Fair`
  - `SCHED_IDLE` <-> `SchedPolicy::Idle`

- After:
  - `SCHED_NORMAL` -> `SchedPolicy::Fair`
  - `SCHED_IDLE` <-> `SchedPolicy::Fair(Nice::MAX)`
  - <n/a> <- `SchedPolicy::Idle`

### CODE REVIEW

File: test/apps/sched/sched_attr_idle.c [hunk 1]
```diff
@@ -0,0 +1,77 @@
...
+		}
+	}
+
+	for (int i = 0; i < num_threads; i++) {
+		pthread_join(threads[i], NULL);
+	}
+
+	printf("All threads completed\n");
+
+	pthread_barrier_destroy(&barrier);
```
Comment (tatetian) [inline test/apps/sched/sched_attr_idle.c]: This regression test should be greatly simplified. The bug reproducing code given by #2153 is generated automatically by a fuzzer. Most of the code in this file is not essential to reproduce the bug.

**Review by tatetian — COMMENTED** [review]
Thanks for fixing the bug!

**Review by tatetian — APPROVED** [review]
LGTM. Thanks for the contribution!

**Review by StevenJiang1110 — APPROVED** [review]
LGTM! Thanks for your contribution!
