### PR TITLE
Fix panic in `mmap` by invalid `perms`

### LINKED ISSUE #1203: Reachable unwrap panic in `sys_mmap()` caused by invalid `perms`
### Describe the bug
There is a out of bounds error in `sys_mmap()` at kernel/aster-nix/src/syscall/mmap.rs:27 when make a `mmap` syscall with specific arguments.

https://github.com/asterinas/asterinas/blob/0160a85ccd130c222ae9b8712b4102c726cba35c/kernel/aster-nix/src/syscall/mmap.rs#L27

### To Reproduce
1. Compile a program which calls `mmap`:
```C
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/mman.h>
#include <sys/wait.h>

int main(void)
{
  mmap(NULL, 0, 0xb, 0x4f142, -1, 0);
  return 0;
}
```
2. Run the compiled program in Asterinas.

### Expected behavior
Asterinas reports panic and is terminated.

### Environment
- Official docker asterinas/asterinas:0.6.2
- 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
- Asterinas version: main 0160a85c

### Logs
```
~ # /root/mmap_test.c
panicked at /root/asterinas/kernel/aster-nix/src/syscall/mmap.rs:27:61:
called `Option::unwrap()` on a `None` value
Printing stack trace:
   1: fn 0xffffffff8878fa40 - pc 0xffffffff8878fa58 / registers:

     rax               0x12; rdx 0xffffffff88a22ad8; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff8000015a9af0;

   2: fn 0xffffffff8878f820 - pc 0xffffffff8878f998 / registers:

     rax               0x12; rdx 0xffffffff88a22ad8; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff8000015a9b00;

   3: fn 0xffffffff88049000 - pc 0xffffffff8804900a / registers:

     rax               0x12; rdx 0xffffffff88a22ad8; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff8000015a9c80;

   4: fn 0xffffffff889a3040 - pc 0xffffffff889a30c2 / registers:

     rax               0x12; rdx 0xffffffff88a22ad8; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff8000015a9c90;

   5: fn 0xffffffff889a31e0 - pc 0xffffffff889a3220 / registers:

     rax               0x12; rdx 0xffffffff88a22ad8; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff8000015a9d20;

   6: fn 0xffffffff8898c7c0 - pc 0xffffffff8898c7d5 / registers:

     rax               0x12; rdx 0xffffffff88a22ad8; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff8000015a9d90;

   7: fn 0xffffffff88136280 - pc 0xffffffff88136315 / registers:

     rax               0x12; rdx 0xffffffff88a22ad8; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff8000015a9da0;

   8: fn 0xffffffff8839d1f0 - pc 0xffffffff883a1e5c / registers:

     rax               0x12; rdx 0xffffffff88a22ad8; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff8000015a9f30;

   9: fn 0xffffffff882b42e0 - pc 0xffffffff882b436e / registers:

     rax               0x12; rdx 0xffffffff88a22ad8; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff8000015c03d0;

  10: fn 0xffffffff88190fd0 - pc 0xffffffff88191b4f / registers:

     rax               0x12; rdx 0xffffffff88a22ad8; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff8000015c0570;

  11: fn 0xffffffff885cbd10 - pc 0xffffffff885cbd1e / registers:

     rax               0x12; rdx 0xffffffff88a22ad8; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff8000015c0f90;

  12: fn 0xffffffff887a5d90 - pc 0xffffffff887a5da6 / registers:

     rax               0x12; rdx 0xffffffff88a22ad8; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff8000015c0fb0;

  13: fn 0xffffffff887dd940 - pc 0xffffffff887dd9a9 / registers:

     rax               0x12; rdx 0xffffffff88a22ad8; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff8000015c0fd0;

  14: fn                0x0 - pc                0x0 / registers:

     rax               0x12; rdx 0xffffffff88a22ad8; rcx                0x1; rbx                0x0;
     rsi                0x0; rdi                0x0; rbp                0x0; rsp 0xffff8000015c1000;

[OSDK] The kernel seems panicked. Parsing stack trace for source lines:
(  1) /root/asterinas/ostd/src/panicking.rs:107
(  2) /root/asterinas/ostd/src/panicking.rs:59
(  3) 2aghao2n2kcoquuybdyjuveav:?
(  4) ??:?
(  5) /root/.rustup/toolchains/nightly-2024-06-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:220
(  6) ??:?
(  7) 9yd76ggpeli67ls0owdwumxu5:?
(  8) /root/asterinas/kernel/aster-nix/src/syscall/mod.rs:220
(  9) /root/asterinas/kernel/aster-nix/src/syscall/mod.rs:328
( 10) /root/asterinas/kernel/aster-nix/src/thread/task.rs:69
( 11) /root/.rustup/toolchains/nightly-2024-06-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:79
( 12) /root/.rustup/toolchains/nightly-2024-06-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2077
( 13) /root/asterinas/ostd/src/task/task/mod.rs:310
make: *** [Makefile:153: run] Error 1
```

### PR DESCRIPTION
**Pull request by Marsman1996**
Fix #1203

Asterinas shall not panic or report error when receive invalid `perms` of `mmap` syscall.

Taking the test program as an example:
```C
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/mman.h>
#include <sys/wait.h>

int main(void)
{
  int fd = open("/bin/ls", O_RDWR);
  void *addr = mmap(NULL, 1, 0x4, 0x1, fd, 0);
  perror("mmap");
  printf("Memory mapped at address %p\n", addr);
  addr = mmap(NULL, 1, 0, 0x1, fd, 0);
  perror("mmap");
  printf("Memory mapped at address %p\n", addr);
  addr = mmap(NULL, 0xffffffffffffff00, 0x3, 0x1, fd, 0);
  perror("mmap");
  printf("Memory mapped at address %p\n", addr);

  return 0;
}
```

In Linux, the result is:
```
mmap: Success
Memory mapped at address 0x7fbf7bf00000
mmap: Success
Memory mapped at address 0x7fbf7beff000
mmap: Cannot allocate memory
Memory mapped at address 0xffffffffffffffff
```

Even the second `mmap` is fed with a invalid `perms` value `0`, it still allocate a memory region.

### CODE REVIEW

**Comment by Marsman1996** [comment]
However, after this fix, when Asterinas runs this test program, it shows the second call fails, while it still return a address.
```
~ # /root/mmap_test.c 
mmap: Success
Memory mapped at address 0x15000
mmap: Invalid argument
Memory mapped at address 0x16000
mmap: Cannot allocate memory
Memory mapped at address 0xffffffffffffffff
```

And according to the debug log, the `sys_mmap()` is complete without failure or error, which is weird.

```log
[    29.461] DEBUG: addr = 0x0, len = 0x1, perms = EXEC, option = MMapOptions { typ: Shared, flags: (empty) }, fd = 3, offset = 0x0
[    29.462] DEBUG: sys_mmap() finished without error, the res is 0x15000!
[    29.471] DEBUG: addr = 0x0, len = 0x1, perms = (empty), option = MMapOptions { typ: Shared, flags: (empty) }, fd = 3, offset = 0x0
[    29.472] DEBUG: sys_mmap() finished without error, the res is 0x16000!
[    29.475] DEBUG: addr = 0x0, len = 0xffffffffffffff00, perms = READ | WRITE, option = MMapOptions { typ: Shared, flags: (empty) }, fd = 3, offset = 0x0
[    29.476] DEBUG: syscall return error: Error { errno: ENOMEM, msg: Some("mmap len too large") }
```

**Comment by Marsman1996** [comment]
> However, after this fix, when Asterinas runs this test program, it shows the second call fails, while it still return a address.
> 
> ```
> ~ # /root/mmap_test.c 
> mmap: Success
> Memory mapped at address 0x15000
> mmap: Invalid argument
> Memory mapped at address 0x16000
> mmap: Cannot allocate memory
> Memory mapped at address 0xffffffffffffffff
> ```
> 
> And according to the debug log, the `sys_mmap()` is complete without failure or error, which is weird.
> 
> ```
> [    29.461] DEBUG: addr = 0x0, len = 0x1, perms = EXEC, option = MMapOptions { typ: Shared, flags: (empty) }, fd = 3, offset = 0x0
> [    29.462] DEBUG: sys_mmap() finished without error, the res is 0x15000!
> [    29.471] DEBUG: addr = 0x0, len = 0x1, perms = (empty), option = MMapOptions { typ: Shared, flags: (empty) }, fd = 3, offset = 0x0
> [    29.472] DEBUG: sys_mmap() finished without error, the res is 0x16000!
> [    29.475] DEBUG: addr = 0x0, len = 0xffffffffffffff00, perms = READ | WRITE, option = MMapOptions { typ: Shared, flags: (empty) }, fd = 3, offset = 0x0
> [    29.476] DEBUG: syscall return error: Error { errno: ENOMEM, msg: Some("mmap len too large") }
> ```

@junyang-zh please have a look, thank you!

**Comment by Marsman1996** [comment]
@boterinas rerun

**Comment by Marsman1996** [comment]
@boterinas rerun

**Comment by junyang-zh** [comment]
> > However, after this fix, when Asterinas runs this test program, it shows the second call fails, while it still return a address.
> > ```
> > ~ # /root/mmap_test.c 
> > mmap: Success
> > Memory mapped at address 0x15000
> > mmap: Invalid argument
> > Memory mapped at address 0x16000
> > mmap: Cannot allocate memory
> > Memory mapped at address 0xffffffffffffffff
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And according to the debug log, the `sys_mmap()` is complete without failure or error, which is weird.
> > ```
> > [    29.461] DEBUG: addr = 0x0, len = 0x1, perms = EXEC, option = MMapOptions { typ: Shared, flags: (empty) }, fd = 3, offset = 0x0
> > [    29.462] DEBUG: sys_mmap() finished without error, the res is 0x15000!
> > [    29.471] DEBUG: addr = 0x0, len = 0x1, perms = (empty), option = MMapOptions { typ: Shared, flags: (empty) }, fd = 3, offset = 0x0
> > [    29.472] DEBUG: sys_mmap() finished without error, the res is 0x16000!
> > [    29.475] DEBUG: addr = 0x0, len = 0xffffffffffffff00, perms = READ | WRITE, option = MMapOptions { typ: Shared, flags: (empty) }, fd = 3, offset = 0x0
> > [    29.476] DEBUG: syscall return error: Error { errno: ENOMEM, msg: Some("mmap len too large") }
> > ```
> 
> @junyang-zh please have a look, thank you!

I traced all the way to trapframe where `sysretq` is executed, and `rax > 0` does hold. There may be other reasons that `perror` thinks the last system call failed.

Also, I think the `perror` output somewhat don't reliably indicates that there's anything wrong. As excerpted from [perror(3)](https://man7.org/linux/man-pages/man3/perror.3.html):

> Note that [errno](https://man7.org/linux/man-pages/man3/errno.3.html) is undefined
       after a successful system call or library function call: this
       call may well change this variable, even though it succeeds, for
       example because it internally used some other library function
       that failed.  Thus, if a failing call is not immediately followed
       by a call to perror(), the value of [errno](https://man7.org/linux/man-pages/man3/errno.3.html) should be saved.
       
Maybe there's another place that our behavior is not consistent with Linux's.

File: kernel/src/vm/perms.rs [hunk 1]
```diff
@@ -17,8 +17,8 @@ bitflags! {
 }
 
 impl VmPerms {
-    pub fn from_posix_prot_bits(bits: u32) -> Option<Self> {
-        VmPerms::from_bits(bits)
+    pub fn from_posix_prot_bits(bits: u32) -> Self {
+        VmPerms::from_bits_truncate(bits)
```
Comment (junyang-zh) [inline kernel/src/vm/perms.rs:21]: It's better to add a reference to the behavior of Linux's here.

Comment (Marsman1996) [reply kernel/src/vm/perms.rs:23]: Roger that🫡

**Comment by Marsman1996** [comment]
@boterinas reru

**Comment by Marsman1996** [comment]
@boterinas rerun

File: kernel/src/vm/perms.rs (hunk 1 above)
Comment (tatetian) [reply kernel/src/vm/perms.rs:23]: >         // According to Linux's behavior, there should be no panic
>        // https://elixir.bootlin.com/linux/v6.10.5/source/mm/mmap.c#L1278

Linux does not have this exact `VmPerms::from_posix_prot_bits` method and Linux does not have this exact concept of panic. So the statement "according to Linux's behavior, there should be no panic" is not quite accurate. I think what the comment should say it as follows:

>         // Linux ignores/truncates any unsupported bits of the `prot` argument for the mmap system call

And by the way, I don't know why we want to have a `from_posix_prot_bits` method. All callers of this method can call `from_bits_truncate` directly.

Comment (Marsman1996) [reply kernel/src/vm/perms.rs:23]: Fixed

And I have the same question.

Comment (tatetian) [reply kernel/src/vm/perms.rs:23]: > I was not sure about whether VmPerms should strictly follow the POSIX standard at the time of writing. 

Of course, they should have followed POSIX standard. They are defined by the kernel crate.

https://github.com/asterinas/asterinas/blob/53ce7df53ccb497395e87f8ee5261d0c3a3db98e/kernel/src/vm/perms.rs#L7C1-L17C2

Comment (tatetian) [reply kernel/src/vm/perms.rs:23]: @Marsman1996 We have reached the consensus to remove the `from_posix_prot_bits` method and call `from_bits_truncate` directly. Could you modify the code this way?

Comment (Marsman1996) [reply kernel/src/vm/perms.rs]: Fixed

**Review by tatetian — APPROVED** [review]
LGTM. Thanks for the contribution!
