### PR TITLE
Find present pages in xarray

### LINKED ISSUE #2817: System hangs when shrinking a file using `ftruncate` (inconsist with Linux)
### Describe the bug
The issue is located in `kernel/src/vm/vmo/mod.rs`, specifically in the `decommit_pages` method of the `Vmo` struct.

When `ftruncate` shrinks a file, it eventually calls `Vmo::resize`, which calls `decommit_pages` to remove pages in the truncated range.

The `decommit_pages` function iterates over every page index in the range to be decommitted.

However, the Linux won't hang.

### To Reproduce
Compile and run the program:
```C
#define _GNU_SOURCE
#include <sys/mman.h>
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <fcntl.h>
#include <errno.h>

int main() {
    int fd = memfd_create("test_memfd", 0);
    if (fd == -1) {
        perror("memfd_create");
        return 1;
    }

    // Large size: 1 PB (1 << 50)
    // Note: off_t is signed 64-bit, so max is 2^63 - 1.
    // 1 PB is safe.
    off_t large_size = (off_t)1 << 50; 

    printf("Truncating to %ld bytes...\n", large_size);
    if (ftruncate(fd, large_size) == -1) {
        perror("ftruncate large");
        return 1;
    }
    printf("Truncated to large size.\n");

    printf("Truncating to 0 bytes...\n");
    if (ftruncate(fd, 0) == -1) {
        perror("ftruncate zero");
        return 1;
    }
    printf("Truncated to 0 bytes.\n");

    close(fd);
    return 0;
}
```

### Environment
- Official docker asterinas/asterinas:0.16.2-20251211
- Asterinas version: main ebfa7977b1

### Logs
- In Asterinas
```
~ # /etc/ftruncate_hang.c 
Truncating to 1125899906842624 bytes...
Truncated to large size.
Truncating to 0 bytes...
```
Hangs here, and crtl-C won't work

- In Linux
```
root@ps:~/asterinas# ./test/src/etc/ftruncate_hang.c 
Truncating to 1125899906842624 bytes...
Truncated to large size.
Truncating to 0 bytes...
Truncated to 0 bytes.
root@ps:~/asterinas# 
```

### PR DESCRIPTION
**Pull request by lrh2000**
Alternative to https://github.com/asterinas/asterinas/pull/2830. I suppose it's better because the `next_present` logic is much clearer: https://github.com/asterinas/asterinas/pull/2830#issuecomment-3707757852.

Fixes #2817

### CODE REVIEW

File: kernel/libs/xarray/src/cursor.rs [hunk 1]
```diff
@@ -226,6 +226,73 @@ impl<'a, P: NonNullPtr + Send + Sync, M> Cursor<'a, P, M> {
...
+    /// returned.
+    ///
+    /// Otherwise, the cursor will stay where it is and a [`None`] will be returned.
+    pub fn next_present(&mut self) -> Option<u64> {
+        let mut index = self.index.checked_add(1)?;
+        let (mut current_node, mut operation_offset) =
+            if let Some((node, offset)) = core::mem::take(&mut self.state).into_node() {
+                (node, offset + 1)
+            } else if let Some(node) = self.xa.head.read_with(self.guard) {
+                let offset = node.entry_offset(index);
```
Comment (cchanging) [inline kernel/libs/xarray/src/cursor.rs]: According to the handling logic here, if the current `Cursor` is invalid and the index corresponds to the `SLOT_SIZE`-th slot of the root node, then in the loop below, it would directly return None due to the absence of a parent. However, after the current index maps to a leaf node, could there still be valid slots after it?

**Review by cchanging — COMMENTED** [review]
Thanks for clearing the logics! The code is in great shape! 

In my previous comment about `XA_PRESENT`, my original thought was that using the mark system to locate the next valid slot in the current node would be more efficient, so implementing it that way might be the final form. However, I agree with your point that the overall logic would be similar to the current approach, so I think it's acceptable to introduce the `next_present` API first.

File: kernel/libs/xarray/src/cursor.rs (hunk 1 above)
Comment (lrh2000) [reply kernel/libs/xarray/src/cursor.rs]: > the current Cursor is invalid and the index corresponds to the SLOT_SIZE-th slot of the root node

How can `entry_offset()` return `SLOT_SIZE`? `entry_offset()` return something like:
https://github.com/asterinas/asterinas/blob/4f62f2db8e355b67da71e6ac164e41fc727fc1ec/kernel/libs/xarray/src/node.rs#L89-L90

This is guaranteed to be in `0..SLOT_SIZE` because `SLOT_SIZE.is_power_of_two() && SLOT_MASK == SLOT_SIZE - 1`.

> after the current index maps to a leaf node, could there still be valid slots after it?

I don't understand how there can be nodes after the root node.

---

But the logic here is indeed problematic in another way. If the `index` is beyond the maximum index, we should return `None`. However, I forget to check this condition:
https://github.com/asterinas/asterinas/blob/4f62f2db8e355b67da71e6ac164e41fc727fc1ec/kernel/libs/xarray/src/cursor.rs#L139-L142

I fixed the problem and added a new test to confirm the behavior.

**Comment by lrh2000** [comment]
> using the mark system to locate the next valid slot in the current node would be more efficient

Assuming we can remove the empty interior nodes, I'm not sure how it could be more efficient. In other words, if we don't have empty interior nodes, finding a marked item should be as efficient as finding a present item. Am I missing anything?
https://github.com/asterinas/asterinas/blob/4f62f2db8e355b67da71e6ac164e41fc727fc1ec/kernel/libs/xarray/src/cursor.rs#L360

**Comment by cchanging** [comment]
> finding a marked item should be as efficient as finding a present item

My understanding is that with the present mark, we can use bit operations within a node to quickly find the next present child. Of course, this may only offer a constant‑level efficiency improvement.

**Comment by lrh2000** [comment]
> My understanding is that with the present mark, we can use bit operations within a node to quickly find the next present child. Of course, this may only offer a constant‑level efficiency improvement.

Thanks for your explanation. I didn't understand this point before, but now I see what you meant. I think it's okay to find the item according to the mark, just like Linux's implementation. The latest commit should address it. [force-push diff](https://github.com/asterinas/asterinas/compare/a24e515b890c8cc1a7a6de1159aac467c8106f34..9b778d18e27be7ff61d48038a6156c7e128fd15c)

**Review by cchanging — APPROVED** [review]
LGTM! Thanks for the contribution!
