### PR TITLE
Ensure proper handling of out-of-bounds VMO access during page fault processing.

### LINKED ISSUE #2201: `mmap` with mapping size > 4KB for small file causes segmentation fault on access (inconsistent with Linux)
### Describe the bug
When performing an `mmap()` of a small file (e.g., 1KB) with a mapping size greater than 4KB (e.g., 5120 bytes) causes a segmentation fault (SEGV) as soon as any byte in the mapped region is accessed. This is inconsistent with standard Linux behavior, where such mappings are allowed and reading from the mapped region (even beyond the file size) should not cause a crash—Linux will zero-fill the extra memory.

### To Reproduce
1. Compile the program and run:
```C
#define _GNU_SOURCE
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>

int main() {
  const char *filename = "/tmp/asterinas_bug_5kb";
  int fd = open(filename, O_CREAT | O_RDWR | O_TRUNC, 0644);

  // Create 1KB test file
  const char test_data[] =
      "Asterinas kernel bug test data - this file is 1KB when padded...";
  char *file_data = malloc(1024);
  memset(file_data, 'M', 1024);
  memcpy(file_data, test_data, strlen(test_data));

  write(fd, file_data, 1024);
  fsync(fd);

  printf("✓ Created 1KB test file\n");

  // Test 1: 4KB mapping (should work)
  printf("\n--- Test 1: 4KB mapping (expected: SUCCESS) ---\n");
  printf("Creating 4096-byte mapping for 1024-byte file...\n");

  void *ptr_4k = mmap(NULL, 4096, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
  if (ptr_4k != MAP_FAILED) {
    printf("✓ 4KB mapping created at %p\n", ptr_4k);
    printf("✅ Reading first byte: '%c'\n", ((char *)ptr_4k)[0]);
    munmap(ptr_4k, 4096);
  } else {
    perror("❌ 4KB mapping failed unexpectedly\n");
  }

  // Test 2: 5KB mapping (will trigger bug)
  printf("\n--- Test 2: 5KB mapping (expected: SEGV due to kernel bug) ---\n");
  printf("Creating 5120-byte mapping for 1024-byte file...\n");

  void *ptr_5k = mmap(NULL, 5120, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
  if (ptr_5k == MAP_FAILED) {
    perror("❌ 5KB mapping failed");
  } else {
    printf("✓ 5KB mapping created at %p\n", ptr_5k);
    printf("⚠️  About to read first byte - THIS WILL CAUSE SEGV:\n");
    printf("Expected behavior: Should read '%c' successfully\n", file_data[0]);
    fflush(stdout);

    // This line triggers the kernel bug - SEGV
    volatile char first_char = ((char *)ptr_5k)[0];
    printf("✅ Reading first byte '%c'\n", first_char);
    munmap(ptr_5k, 5120);
  }

  // Cleanup
  free(file_data);
  close(fd);
  unlink(filename);

  return 0;
}
```

### Expected behavior
The program should not SEGV.

### Environment
- Official docker asterinas/asterinas:0.15.0-20250516
- Intel(R) Xeon(R) Gold 6230R CPU @ 2.10GHz
- Asterinas version: main 0875cf6

### Log
- In Asterinas:
```
~ # /root/segv.c 
✓ Created 1KB test file

--- Test 1: 4KB mapping (expected: SUCCESS) ---
Creating 4096-byte mapping for 1024-byte file...
✓ 4KB mapping created at 0x7ffffff79000
✅ Reading first byte: 'A'

--- Test 2: 5KB mapping (expected: SEGV due to kernel bug) ---
Creating 5120-byte mapping for 1024-byte file...
✓ 5KB mapping created at 0x7ffffff79000
⚠️  About to read first byte - THIS WILL CAUSE SEGV:
Expected behavior: Should read 'A' successfully
Segmentation fault
```

- In Linux
```
✓ Created 1KB test file

--- Test 1: 4KB mapping (expected: SUCCESS) ---
Creating 4096-byte mapping for 1024-byte file...
✓ 4KB mapping created at 0x7f88613b0000
✅ Reading first byte: 'A'

--- Test 2: 5KB mapping (expected: SEGV due to kernel bug) ---
Creating 5120-byte mapping for 1024-byte file...
✓ 5KB mapping created at 0x7f88613af000
⚠️  About to read first byte - THIS WILL CAUSE SEGV:
Expected behavior: Should read 'A' successfully
✅ Reading first byte 'A'
```

### PR DESCRIPTION
**Pull request by cchanging**
Fixes #2201

### CODE REVIEW

File: kernel/src/vm/vmar/vm_mapping.rs [hunk 1]
```diff
@@ -199,6 +202,51 @@ impl VmMapping {
...
 
+        self.handle_single_page_fault(
+            vm_space,
+            page_aligned_addr,
+            page_fault_info.required_perms,
+            rss_delta,
+        )
+    }
+
+    fn prepare_page(
```
Comment (junyang-zh) [inline kernel/src/vm/vmar/vm_mapping.rs]: You can order the function impl `prepare_page` after `handle_single_page_fault`, which preserves the original order and would make the diff better to read. Also, the call to `handle_single_page_fault` will be immediately followed by the declaration. Extra readability.

**Review by junyang-zh — APPROVED** [review]
I am OK with the change. How about adding a regression test for it. Just port #2201 ? Maybe @Marsman1996 can co-author.

**Comment by lrh2000** [comment]
> How about adding a regression test for it.

(Want to say the same thing).

I think doing something similar to this (but of course with the type/offset/size adjusted) and trying to access the mapped memory should be easy. It's also more maintainable than writing a new test from scratch in an ad hoc style?
https://github.com/asterinas/asterinas/blob/3f1bf99b2ade568a09e3a483ec8bf0f75ca36608/test/apps/mmap/mmap_and_mremap.c#L147-L153

File: test/apps/mmap/mmap_beyond_the_file.c
Comment (lrh2000) [inline test/apps/mmap/mmap_beyond_the_file.c:1]: If you add a new file, you'll need to add it to `test/apps/scripts/process.sh`. Otherwise it won't be run by the CI.

File: test/apps/mmap/mmap_beyond_the_file.c [hunk 2]
```diff
@@ -0,0 +1,26 @@
...
+	TEST_SUCC(ftruncate(fd, 2 * PAGE_SIZE));
+
+	char *addr = CHECK_WITH(mmap(NULL, 4 * PAGE_SIZE,
+				     PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0),
+				_ret != MAP_FAILED);
+	TEST_RES(addr[1 * PAGE_SIZE], _ret == 0);
+	// The following operation (if uncommented) would cause a segmentation fault.
+	// TEST_RES(addr[3 * PAGE_SIZE], _ret == 0);
+
+	TEST_SUCC(munmap(addr, 4 * PAGE_SIZE));
```
Comment (lrh2000) [inline test/apps/mmap/mmap_beyond_the_file.c:24]: Please also close and unlink the file, although it does not seem to be very important.
https://github.com/asterinas/asterinas/blob/5e3e23bf7c5130a9251b265c5377d2e21769097c/test/apps/mmap/mmap_and_mremap.c#L169-L170

Otherwise LGTM too. Let @junyang-zh make the final decision to merge this PR after addressing the above issues, as he is the correct code owner.

File: kernel/src/vm/vmar/vm_mapping.rs [hunk 3]
```diff
@@ -320,22 +340,32 @@ impl VmMapping {
...
-
+        let around_page_addr = page_aligned_addr & SURROUNDING_PAGE_ADDR_MASK;
+        let size = min(vmo.valid_size(), self.map_size.get());
         let mut start_addr = max(around_page_addr, self.map_to_addr);
         let end_addr = min(
             start_addr + SURROUNDING_PAGE_NUM * PAGE_SIZE,
             self.map_to_addr + size,
         );
 
+        // The page fault address falls outside the VMO bounds. Only a single page fault is handled in this situation.
```
Comment (lrh2000) [inline kernel/src/vm/vmar/vm_mapping.rs]: This line is too long. Better to break it.
```suggestion
        // The page fault address falls outside the VMO bounds.
        // Only a single page fault is handled in this situation.
```

File: kernel/src/vm/vmar/vm_mapping.rs [hunk 4]
```diff
@@ -557,8 +587,13 @@ impl MappedVmo {
         Self { vmo, range }
     }
 
-    fn size(&self) -> usize {
-        self.range.len()
+    /// Returns the **valid** size of the `MappedVmo`.
+    ///
+    /// The **valid** size of a `MappedVmo` equals the portion of its accessible range
```
Comment (lrh2000) [inline kernel/src/vm/vmar/vm_mapping.rs]: Can "size" be equal to "portion"? Also, I guess here we mean the definition of the "valid size", so we should just use "is" instead of "equal".
```suggestion
    /// The **valid** size of a `MappedVmo` is the size of its accessible range
```
