### PR TITLE
[OSDK] Make OSDK forwarded commands unified and fix `make docs`

### LINKED ISSUE #657: [BUG] `cargo doc` reports error and fails
# Problem
`cargo doc` is used in `make docs` to generate API documentations. However, the command will fail currently. The problem seems to exist for a long time.

Before introducing OSDK, the `inventory` crate will report error. Since this crate is forked under Asterinas, we shoube be able to fix the error. 

iwEcAqNwbmcDAQTRCfIF0QJ2BrCwmeF5_LlFWwXOjUHN7ecAB9MAAAAAuoBoxQgACaJpbQoAC9IABSn4 png_720x720q90

After indroducing OSDK, new problem occurs. The `linux-bzimage-setup` panics when running `cargo doc`. 

截屏2024-02-29 15 30 54

If running `cargo doc --target x86_64-unknown-none` to avoid panic in `linux-bzimage-setup` , more error occurs.

# Possible solution

1. Fix the error in `inventory`
2. Make `linux-bzimage-setup` can also build under other target, like `x86_64-unknown-linux-gnu`, but should we allow this behavior?

### PR DESCRIPTION
**Pull request by junyang-zh**
Fix #657.

Considering all cargo commands simply wrapped by OSDK like `clippy` and `doc` or so, we just add target and `-Zbuild-std` options to it. All the other extra commandline arguments should be passed as-is and it's a burden to forward them one by one. That's why I unified their processing logic and bypass the Clap parser to some extent.

### CODE REVIEW

File: osdk/src/cli.rs [hunk 1]
```diff
@@ -68,10 +78,24 @@ pub enum OsdkSubcommand {
...
     #[command(about = "Execute kernel mode unit test by starting a VMM")]
     Test(TestArgs),
-    #[command(about = "Analyze the current package and report errors")]
+    #[command(about = "Wrapper for the `cargo check` command")]
     Check,
-    #[command(about = "Check the current package and catch common mistakes")]
+    #[command(about = "Wrapper for the `cargo clippy` command")]
     Clippy,
+    #[command(about = "Wrapper for the `cargo doc` command")]
+    Doc,
```
Comment (StevenJiang1110) [inline osdk/src/cli.rs:86]: I think these wrapper commands should also be parsed by `clap`, instead of be parsed manually. Like the following code: 

```rust

pub enum OsdkSubcommand {
    // Other subcommands......

    #[command(about = "Analyze the current package and report errors")]
    Check(WrapperArguments),
    #[command(about = "Check the current package and catch common mistakes")]
    Clippy(WrapperArguments),
    #[command(about = "Build a package's documentation")]
    Doc(WrapperArguments)
}

#[derive(Debug, Parser)]
pub struct WrapperArgument {
    #[arg(help = "Additional Cargo arguments", allow_hyphen_values = true)]
    pub args: Vec<String>
}
```

**Review by StevenJiang1110 — COMMENTED** [review]
Thanks for your contribution!

**Comment by junyang-zh** [comment]
The downside for letting clap parsing all following args is that we should use a weird `-- --` notation to pass values to cargo for `--` escaped values, like `cargo osdk clippy -- -- -D warnings` for `cargo clippy -- -D warnings`

File: osdk/src/cli.rs [hunk 2]
```diff
@@ -6,8 +6,8 @@ use clap::{crate_version, Args, Parser};
 
 use crate::{
     commands::{
-        execute_build_command, execute_check_command, execute_clippy_command, execute_new_command,
-        execute_run_command, execute_test_command,
+        execute_build_command, execute_new_command, execute_run_command, execute_test_command,
+        execute_wrapped_command,
```
Comment (tatetian) [inline osdk/src/cli.rs:10]: The wrapped command sounds weird to me. How about forwarded commands or proxied commands or redirected commands?

File: osdk/src/cli.rs [hunk 3]
```diff
@@ -68,10 +69,18 @@ pub enum OsdkSubcommand {
     Run(RunArgs),
     #[command(about = "Execute kernel mode unit test by starting a VMM")]
     Test(TestArgs),
-    #[command(about = "Analyze the current package and report errors")]
-    Check,
-    #[command(about = "Check the current package and catch common mistakes")]
-    Clippy,
+    #[command(about = "Wrapper for the `cargo check` command")]
```
Comment (tatetian) [inline osdk/src/cli.rs:72]: `Wrapper` is too implementation oriented. To a user, it is sufficient to know that `cargo osdk check` is equivalent to `cargo check`.

File: osdk/src/cli.rs [hunk 4]
```diff
@@ -68,10 +69,22 @@ pub enum OsdkSubcommand {
     Run(RunArgs),
     #[command(about = "Execute kernel mode unit test by starting a VMM")]
     Test(TestArgs),
-    #[command(about = "Analyze the current package and report errors")]
-    Check,
-    #[command(about = "Check the current package and catch common mistakes")]
-    Clippy,
+    #[command(about = "Check a local package and all of its dependencies for errors")]
+    Check(WrappedArguments),
```
Comment (tatetian) [inline osdk/src/cli.rs:73]: `WrappedArguments` --> `ForwardedArguments`

File: osdk/src/commands/mod.rs [hunk 5]
```diff
@@ -3,14 +3,25 @@
...
 mod util;
 
 pub use self::{
-    build::execute_build_command, check::execute_check_command, clippy::execute_clippy_command,
-    new::execute_new_command, run::execute_run_command, test::execute_test_command,
+    build::execute_build_command, new::execute_new_command, run::execute_run_command,
+    test::execute_test_command,
 };
+
+/// Execute the wrapped cargo command with args containing the subcommand and its arguments.
```
Comment (tatetian) [inline osdk/src/commands/mod.rs:16]:
```
/// Execute the forwarded cargo command
```

File: osdk/src/cli.rs (hunk 4 above)
Comment (junyang-zh) [reply osdk/src/cli.rs:73]: oops

**Review by tatetian — APPROVED** [review]
LGTM. Thanks for the contribution!
