### PR TITLE
Fix SMP boot for EFI handover

### LINKED ISSUE #1636: Failure when booting with `linux-efi-handover64` protocol and configuring multi-processor
### Describe the bug

In the `bsp_boot.S`, the Linux 64-bit Boot Protocol does not jump to `initial_boot_setup`, but directly jumps to `long_mode_in_low_address`, which results in no page table being established for bsp:

https://github.com/asterinas/asterinas/blob/05ff4415772bbf32a12a5cf49ba869beb4d70101/ostd/src/arch/x86/boot/bsp_boot.S#L43-L55

As a result, when initializing aps, the page table fails to load:

https://github.com/asterinas/asterinas/blob/05ff4415772bbf32a12a5cf49ba869beb4d70101/ostd/src/arch/x86/boot/ap_boot.S#L105-L109

### To Reproduce

Run:
```shell
make run LOG_LEVEL=debug BOOT_PROTOCOL=linux-efi-handover64 SMP=2
```

### Logs

```txt
[EFI stub] Relocations applied.
[EFI stub] Stub loaded at 0x70298000
[EFI stub] Loading payload.
[EFI stub] Exiting EFI boot services.
[EFI stub] Entered runtime services.
[EFI stub] Warning: number of E820 entries exceeded 128!
[EFI stub] Setting up the page table.
[EFI stub] Entering Asterinas entrypoint at 0x0000000008001200
[     0.000] INFO : Found usable region, start:1000, end:87000
[     0.000] INFO : Found usable region, start:88000, end:a0000
[     0.000] INFO : Found usable region, start:100000, end:800000
[     0.000] INFO : Found usable region, start:808000, end:80b000
[     0.000] INFO : Found usable region, start:80c000, end:810000
[     0.000] INFO : Found usable region, start:1500000, end:4000000
[     0.000] INFO : Found usable region, start:560f000, end:8000000
[     0.000] INFO : Found usable region, start:8df6be8, end:6b66c000
[     0.000] INFO : Found usable region, start:7bf4e000, end:7c6e6000
[     0.000] INFO : Found usable region, start:7e454000, end:7e475000
[     0.000] INFO : Found usable region, start:7e476000, end:7e478000
[     0.000] INFO : Initializing page metadata for physical memory up to 7f8ef000
[     0.000] INFO : Initializing the kernel page table
[     0.000] INFO : ACPI found signature:"FACP"
[     0.000] INFO : ACPI found signature:"APIC"
[     0.000] INFO : ACPI found signature:"HPET"
[     0.000] INFO : ACPI found signature:"MCFG"
[     0.000] INFO : ACPI found signature:"WAET"
[     0.000] INFO : ACPI found signature:"BGRT"
[     0.000] INFO : acpi init complete
[     0.000] INFO : x2APIC found!
[     0.000] INFO : [IOAPIC]: IOAPIC id: 0, version:32, max_redirection_entry:24, interrupt base:0
[     0.000] INFO : Found 2 processors.
[     0.000] INFO : Booting all application processors...
[     0.000] DEBUG: __ap_boot_stack_array_pointer: 0xffffffff800080e0
[     0.000] INFO : x2APIC ID:0, Version:14, Max LVT:5
root@cupcon03:~/asterinas#
```

### PR DESCRIPTION
**Pull request by junyang-zh**
Fix #1636 .

The boot page table was not initialized by the assembly during EFI boot. So APs don't get a proper page table. We let the BSP provide a boot page table address when starting APs.

After this fix SMP in EFI is still not ready. And I would start a issue tracking the problem that the GDT won't work with KVM and EFI handover boot.

### CODE REVIEW

**Comment by junyang-zh** [comment]
@boterinas ready

**Comment by junyang-zh** [comment]
@boterinas rerun

File: ostd/src/arch/x86/boot/smp.rs [hunk 1]
```diff
@@ -107,6 +108,24 @@ fn init_boot_stack_array() {
     }
 }
 
+fn fill_boot_pt_ptr() {
+    // This is defined in the boot assembly code.
+    extern "C" {
+        fn __boot_page_table_pointer();
```
Comment (tatetian) [inline ostd/src/arch/x86/boot/smp.rs:114]: I am very confused by this declaration. It is a pointer declared as a function. I expect the Rust declaration to be as follows.

```rust
extern "C" {
    static __boot_page_table_pointer: *const u8;
}
```

The `__ap_boot_stack_array_pointer` has exactly the same problem.
