### PR TITLE
Redo userspace (just slightly)

### LINKED ISSUE #666: [BUG] Uncaught panic happened in heap_allocator
I run 416.gamess , one of spec CPU 2006 test items,  but a pacnic happened:

```
~ # ./gamess_base.amd64-m64-gcc41-nn < exam29.config 
[ERROR]: Uncaught panic!
panicked at framework/aster-frame/src/vm/heap_allocator.rs:24:5:
Heap allocation error, layout = Layout { size: 659468632, align: 1 (1 << 0) }
```
This pacnic alse happened when I run 434.zeusmp.
the file of 434.zeusmp and 416.gamess: [https://github.com/skpupil/my_spec_test](url)

### PR DESCRIPTION
**Pull request by junyang-zh**
The default initial user stack is placed too low (512M). Moving it to the highest space availiable. Randomly padded.

Fix #666 (another part of the problem).

Also, the abusive use of global config in the framework is refactored.

### CODE REVIEW

File: kernel/aster-nix/src/process/program_loader/elf/init_stack.rs [hunk 1]
```diff
@@ -93,9 +99,13 @@ impl InitStack {
         }
     }
 
-    /// This function only work for first process
     pub fn new_default_config(argv: Vec<CString>, envp: Vec<CString>) -> Self {
-        let init_stack_top = INIT_STACK_BASE - PAGE_SIZE;
+        let nr_pages_padding = {
+            let mut random_nr_pages_padding: [u8; 1] = [0];
```
Comment (StevenJiang1110) [inline kernel/aster-nix/src/process/program_loader/elf/init_stack.rs:104]: Using `as_bytes_mut` method From `Pod` trait may be a bit more clear.
```rust
let mut random_nr_pages_padding: u8 = 0;
getrandom::getrandom(random_nr_pages_padding.as_bytes_mut());
```

**Review by StevenJiang1110 — COMMENTED** [review]
Thanks for your contribution to the virtual memory layout!

Could you please also edit the documentation in `aster-nix/src/process/process_vm/mod.rs` to reflect the change in this PR? Like

```rust
* |-----------------------|-------The highest user vm address
* |                       |
* |       Padding Pages   |
* |                       |
* |                       |
* --------------------------------The init stack base
* |                       |
* | User Stack(Init Stack)|
* |                       |
* |         ||            |
* ----------||----------------------The user stack top, grows down
* |         \/            |
* |                       |
* |     Free Areas        |
* |                       |
* |         /\            |
* ----------||---------------------The user heap top, grows up
* |         ||            |
* |                       |
* |        User Heap      |
* |                       |
* ----------------------------------The user heap base
* |                       |
* |        Free   Area    |
* |                       |
* ----------------------------------The root vmar lowest addr
```

**Comment by junyang-zh** [comment]
```
/*
 * The user's virtual memory space layout looks like below.
 *
 *  (high address)
 *  +---------------------+ <------+ The top of Vmar, which is the highest address usable
 *  | A reserved page     |          // FIXME: This should not be mappable but we neglected
 *  +---------------------+
 *  |                     |          0~255 randomly padded pages
 *  +---------------------+ <------+ The top of the initial user stack
 *  | User stack          |
 *  |                     |
 *  +---------||----------+ <------+ User stack top - ulimit, can be extended lower
 *  |         \/          |
 *  | ...                 |
 *  |                     |
 *  | MMAP Spaces         |
 *  |                     |
 *  | ...                 |
 *  |         /\          |
 *  +---------||----------+ <------+ The current program break
 *  | User heap           |
 *  |                     |
 *  +---------------------+ <------+ The original program break
 *  |                     |          0~255 randomly padded pages
 *  +---------------------+ <------+ The end of the program's last segment
 *  |                     |
 *  | Loaded segments     |
 *  | .text, .data, .bss  |
 *  | , etc.              |
 *  |                     |
 *  +---------------------+ <------+ The bottom of Vmar at 0x1_0000
 *  |                     |          64 KiB unusable space
 *  +---------------------+
 *  (low address)
 */
```

Here is the proposed change. But I found that the current user heap implemention is broken. I just made it aligned with some workarounds.

**Comment by StevenJiang1110** [comment]
> I tried to make our heap aligned with this definition but it seems that our current implementation is incorrigible. I want to address the change of the heap layout in our following work.

Yes, it is acceptable to postpone the modification of the heap layout. I suggest including the new layout (as you mentioned earlier) in the documentation of the `process_vm` module, as the original layout is outdated. Additionally, it would be helpful to add a TODO comment in the documentation for any pending tasks that have not been addressed yet.

**Review by StevenJiang1110 — APPROVED** [review]
LGTM! Thanks for your contribution!

File: kernel/aster-nix/src/process/process_vm/mod.rs [hunk 2]
```diff
@@ -14,30 +14,42 @@ use user_heap::UserHeap;
...
-* |                       |
-* ----------------------------------The user heap base
-*/
+ * The user's virtual memory space layout looks like below.
+ * TODO: The layout of the userheap does not match the current implementation,
+ * And currently the initial program break is a fixed value.
+ *
+ *  (high address)
+ *  +---------------------+ <------+ The top of Vmar, which is the highest address usable
+ *  | A reserved page     |          // FIXME: This should not be mappable but we neglected
```
Comment (lrh2000) [inline kernel/aster-nix/src/process/process_vm/mod.rs:23]: This is a very good point. I never knew that the last page in the lower half of virtual memory was unmappable. In fact, it's a workaround for some nasty CPU bugs, both Intel's and AMD's, as explained in the [Linux kernel source](https://github.com/torvalds/linux/blob/480e035fc4c714fb5536e64ab9db04fedc89e910/arch/x86/include/asm/page_64.h#L68-L78).

But if this is the case, why not just set `USERSPACE_LOWEST_UNUSABLE_VADDR` to `0x0000_7fff_ffff_f000`? This is exactly what Linux did for its [`task_size_max()` macro](https://github.com/torvalds/linux/blob/480e035fc4c714fb5536e64ab9db04fedc89e910/arch/x86/include/asm/page_64_types.h#L61). 

As far as I know, this is an architecture-specific workaround, and the guard page doesn't exist for other architectures. So encoding it in the `USERSPACE_LOWEST_UNUSABLE_VADDR` constant seems a bit more correct. Meanwhile, perhaps the above explanation from Linux kernel needs to be referenced to make things clearer.

File: kernel/aster-nix/src/process/process_vm/mod.rs [hunk 3]
```diff
@@ -14,30 +14,42 @@ use user_heap::UserHeap;
...
+ *  +---------------------+
+ *  |                     |          0~255 randomly padded pages
+ *  +---------------------+ <------+ The top of the initial user stack
+ *  | User stack          |
+ *  |                     |
+ *  +---------||----------+ <------+ User stack top - ulimit, can be extended lower
```
Comment (lrh2000) [inline kernel/aster-nix/src/process/process_vm/mod.rs:29]: Is it right to call this address stack "top"?

File: kernel/aster-nix/src/process/program_loader/elf/init_stack.rs [hunk 4]
```diff
@@ -93,9 +99,13 @@ impl InitStack {
         }
     }
 
-    /// This function only work for first process
     pub fn new_default_config(argv: Vec<CString>, envp: Vec<CString>) -> Self {
-        let init_stack_top = INIT_STACK_BASE - PAGE_SIZE;
+        let nr_pages_padding = {
+            let mut random_nr_pages_padding: u8 = 0;
+            getrandom::getrandom(random_nr_pages_padding.as_bytes_mut()).unwrap();
+            random_nr_pages_padding as usize + 1
```
Comment (lrh2000) [inline kernel/aster-nix/src/process/program_loader/elf/init_stack.rs:106]: Adding randomization without adding ways to disable it can make debugging more difficult. So I would argue against adding such randomization for the kernel offset and code/data segments.

But since I can't think of any cases where the stack location matters (who knows? maybe someday it does), I'm neutral with this change, but I still think it's a point worth mentioning.

Comment (junyang-zh) [reply kernel/aster-nix/src/process/program_loader/elf/init_stack.rs]: I once thought we could add a UASLR feature gate but the second thought yields it unnecessary:
 - If a user space program want to know the stack base to allow debugging, just info mappings or read procfs; they shall not rebuild the kernel;
 - If we want to debug it we can just read it.

However, a KASLR feature gate is necessary. I would think adding it in the future for easier debugging.

Comment (lrh2000) [reply kernel/aster-nix/src/process/program_loader/elf/init_stack.rs]: By default, GDB disables ASLR using the [personality](https://man7.org/linux/man-pages/man2/personality.2.html) system call with the `ADDR_NO_RANDOMIZE` argument. In addition, we can globally disable ASLR in Linux using `/proc/sys/kernel/randomize_va_space` in procfs or `norandmaps` on the kernel command line. As for kernel randomization, there is a `nokaslr` option on the Linux kernel command line.

> * If a user space program want to know the stack base to allow debugging, just info mappings or read procfs; they shall not rebuild the kernel;

It's a tedious process because we have to do "info mappings or read procfs" every time we (re)run the program we want to debug, which can be dozens of times before the bug is finally caught.

> * If we want to debug it we can just read it.

I don't know if there is a mature way to debug user space programs in Asterinas yet. (I don't think we support GDB yet, do we?) So I used to do this by making my user space program the `init` process, and then setting breakpoints directly at the user space addresses using the GDB attached to QEMU. The problem is that when the user space segments are always randomly placed, I will have a hard time figuring out what the address is and then changing the previous breakpoints accordingly.

Making _only_ the stack location random might be a fair change, and its impact is minimal compared to randomizing the code/data segments. So perhaps this discussion is somehow outside the scope of this PR? I'm not sure.

Comment (junyang-zh) [reply kernel/aster-nix/src/process/program_loader/elf/init_stack.rs]: Yep, in this PR only the stack is randomized and a whole system for configuring the ASLR feature (just impacting the stack) seems an overkill. And currently the user program's code and data segment are placed just as where the ELF says (except for the shared library to which we cannot do so).

Your idea is valuable and I do accept that we need kernel command line/procfs configurations if actual ASLR is fully introduced in the future.

File: kernel/aster-nix/src/process/process_vm/mod.rs [hunk 5]
```diff
@@ -14,30 +14,40 @@ use user_heap::UserHeap;
...
+ * TODO: The layout of the userheap does not match the current implementation,
+ * And currently the initial program break is a fixed value.
+ *
+ *  (high address)
+ *  +---------------------+ <------+ The top of Vmar, which is the highest address usable
+ *  |                     |          Randomly padded pages
+ *  +---------------------+ <------+ The base of the initial user stack
+ *  | User stack          |
+ *  |                     |
+ *  +---------||----------+ <------+ The user stack limit, can be extended lower
```
Comment (lrh2000) [inline kernel/aster-nix/src/process/process_vm/mod.rs:27]:
```suggestion
 *  +---------------------+ <------+ The top of Vmar, which is the highest usable address
 *  |                     |          Randomly padded pages
 *  +---------------------+ <------+ The base of the user stack (stack grows down)
 *  | User stack          |
 *  |                     |
 *  +---------||----------+ <------+ The limit of the user stack
```

File: kernel/aster-nix/src/process/program_loader/elf/init_stack.rs [hunk 6]
```diff
@@ -20,15 +20,16 @@ use crate::{
...
- * The initial stack of a process looks like below(This figure is from occlum):
+ * Illustration of the virtual memory space containing the processes' init stack:
  *
- *
- *  +---------------------+ <------+ Top of stack
- *  |                     |          (high address)
+ *  (high address)
+ *  +---------------------+ <------+ Highest address
+ *  |                     |          Random stack paddings
+ *  +---------------------+ <------+ The base of stack (stack grows down)
```
Comment (lrh2000) [inline kernel/aster-nix/src/process/program_loader/elf/init_stack.rs:31]:
```suggestion
 *  +---------------------+ <------+ Highest usable address
 *  |                     |          Random stack paddings
 *  +---------------------+ <------+ User stack base (stack grows down)
```

File: kernel/aster-nix/src/process/program_loader/elf/init_stack.rs [hunk 7]
```diff
@@ -62,8 +63,10 @@ pub const INIT_STACK_SIZE: usize = 0x1000 * 16; // 64KB
  *  +---------------------+
  *  |                     |
  *  |                     |
- *  +                     +
- *
+ *  +---------------------+
+ *  |                     |
+ *  +---------------------+ <------+ User stack default rlimit
```
Comment (lrh2000) [inline kernel/aster-nix/src/process/program_loader/elf/init_stack.rs:68]:
```suggestion
 *  +---------------------+ <------+ User stack limit
```

File: kernel/aster-nix/src/process/program_loader/elf/init_stack.rs (hunk 4 above)
Comment (lrh2000) [reply kernel/aster-nix/src/process/program_loader/elf/init_stack.rs]: Yes, it does not seem right to do that in this PR, of course. That is also not what I mean.

**Review by lrh2000 — APPROVED** [review]
The current version of this PR looks good to me. Above are just some nits that try to align comment styles within the same table. Feel free to accept or ignore such comments at your own discretion.

File: framework/aster-frame/src/vm/config.rs [hunk 8]
```diff
@@ -0,0 +1,40 @@
...
+pub fn kernel_loaded_offset() -> usize {
+    0xffff_ffff_8000_0000
+}
+
+/// The canonical higher half offset of x86_64. See
+/// <https://www.kernel.org/doc/html/latest/arch/x86/x86_64/mm.html>
+/// for more details.
+///
+/// We use this offset to manage the physical memory starting from 0x0.
+pub const KERNEL_PHYS_SPACE_OFFSET: usize = 0xffff_8000_0000_0000;
```
Comment (tatetian) [inline framework/aster-frame/src/vm/config.rs:36]: Defining the const value in the following form slightly improves readability.

```rust
/// The base address of the direct mapping of all physical memory in the kernel address space.
///
/// On x86-64, this base address is set as the _lowest_ address of the _high_ canonical addresses.
pub(crate) const PHYS_MEM_BASE_VADDR: Vaddr = 0xffff_8000_0000_0000;
```

File: framework/aster-frame/src/vm/config.rs [hunk 9]
```diff
@@ -0,0 +1,40 @@
+// SPDX-License-Identifier: MPL-2.0
+
+//! A configuration module for framework memory management.
+
+use super::Vaddr;
+
+pub const KERNEL_STACK_SIZE: usize = PAGE_SIZE * 64;
+pub const KERNEL_HEAP_SIZE: usize = PAGE_SIZE * 256;
```
Comment (tatetian) [inline framework/aster-frame/src/vm/config.rs:8]: The name `KERNEL_HEAP_SIZE` is not quite accurate as the heap size can grow. So `KERNEL_INIT_HEAP_SIZE` or `KERNEL_MIN_HEAP_SIZE` makes more sense.

File: framework/aster-frame/src/vm/config.rs [hunk 10]
```diff
@@ -0,0 +1,40 @@
...
+
+/// Typicall 64-bit systems have at least 48-bit virtual address space.
+/// Halving it to reserve half of the address space for the kernel.
```
Comment (tatetian) [inline framework/aster-frame/src/vm/config.rs:11]: > Halving it to reserve half of the address space for the kernel.

I don't understand this sentence.

File: framework/aster-frame/src/vm/config.rs [hunk 11]
```diff
@@ -0,0 +1,40 @@
...
+/// 
+/// Also, the top page is not regarded as usable since it's a workaround
+/// for the x86_64 CPUs' bugs. See
+/// <https://github.com/torvalds/linux/blob/480e035fc4c714fb5536e64ab9db04fedc89e910/arch/x86/include/asm/page_64.h#L68-L78>
+/// for the rationale.
+pub const USERSPACE_LOWEST_UNUSABLE_VADDR: Vaddr = 0x0000_8000_0000_0000 - PAGE_SIZE;
```
Comment (tatetian) [inline framework/aster-frame/src/vm/config.rs:17]: The const name is a bit of confusing becauses it only states no address below is unusable. It is not clear if some addresses above it are usable or will be used. To make it more clear, I suggest calling it `MAX_USER_VADDR`.

File: framework/aster-frame/src/vm/config.rs [hunk 12]
```diff
@@ -0,0 +1,40 @@
...
+
+// FIXME: the following constants are all architecture dependent. Need
+// a proper redesign.
```
Comment (tatetian) [inline framework/aster-frame/src/vm/config.rs:20]: So why not move them to `arch/x86/mm/mod.rs` or `arch/x86/mm/params.rs`?

The const values defined here is really arch dependent.

And yes, I do not think `config.rs` is the right file name. A configuration is more like a tunable value. A configuration lets you to make certain tradeoffs. But you cannot tune the page size of x86. And changing the base address of the direct mapping of physical memory does not provide you performance advantage. So these values are not configurations. "Parameters" is probably the better word.

Last, please hide these values from the users of Framework if the users do not need to care about them. I really don't think all of these const values should be public items in a public module.

File: framework/aster-frame/src/vm/config.rs [hunk 13]
```diff
@@ -0,0 +1,36 @@
...
+/// The canonical higher half offset of x86_64. See
+/// <https://www.kernel.org/doc/html/latest/arch/x86/x86_64/mm.html>
+/// for more details.
+///
+/// We use this offset to manage the physical memory starting from 0x0.
+pub const KERNEL_PHYS_SPACE_OFFSET: usize = 0xffff_8000_0000_0000;
+
+/// They should be the properties of IA32E regular pages.
+pub const PAGE_SIZE: usize = 0x1000;
+pub const PAGE_SIZE_BITS: usize = 0xc;
```
[the remark this answers is not in the document]
Comment (junyang-zh) [reply framework/aster-frame/src/vm/config.rs:40]: I found out that this originally existed constant is indeed not used. I'd like to remove it.

**Comment by junyang-zh** [comment]
Mostly resolved @tatetian. However any direct usage of `PAGE_SIZE` outside the framework is screwed anyway, some change suggested here really doesn't improve the status quo much and beyond scope of this PR. We will work on it in the future.

File: framework/aster-frame/src/vm/mod.rs [hunk 14]
```diff
@@ -32,20 +32,43 @@ pub use self::{
...
+/// Also, the top page is not regarded as usable since it's a workaround
+/// for some x86_64 CPUs' bugs. See
+/// <https://github.com/torvalds/linux/blob/480e035fc4c714fb5536e64ab9db04fedc89e910/arch/x86/include/asm/page_64.h#L68-L78>
+/// for the rationale.
+pub const MAX_USERSPACE_VADDR: Vaddr = 0x0000_8000_0000_0000 - PAGE_SIZE;
+
+/// The base address of the direct mapping of all physical memory in the kernel address space.
+///
+/// On x86-64, this base address is set as the _lowest_ address of the _high_ canonical addresses.
+pub(crate) const KERNEL_MEM_BASE_VADDR: Vaddr = 0xffff_8000_0000_0000;
```
[the remark this answers is not in the document]
Comment (junyang-zh) [reply framework/aster-frame/src/vm/mod.rs:52]: In my mind that our physical/virtual conversion is more like a hack when we need to parse plain pointers from the bootloader. In our robust implementation in the future these should be handled by the boot compatibility layer (the setup code). But the address space is indeed only used by the kernel. So I think my name is more future-proof although less specific.

**Review by tatetian — APPROVED** [review]
LGTM. Thanks for the contribution!
