### PR TITLE
Ensure non-tearing memory operations on `DmaCoherent`

### LINKED ISSUE #1089: Syscall test at Ext2, MicroVM occasionally fails
### To Reproduce

In CI, the syscall test at Ext2, MicroVM randomly output bad characters and then hang without panicking. There are some runs that seemed irrelevant with the PR modification:

https://github.com/asterinas/asterinas/actions/runs/10053473151/job/27786308763?pr=1088

https://github.com/asterinas/asterinas/actions/runs/10021055466/job/27699299104

They would pass the syscall test at ramfs (linux boot, normal VM), and then fail at Ext2, MicroVM.

### Logs

The log would look like this:

```
[Bn�731ns] : p�b����l���R<�����p�1�����protected range is not fully mappedphk���"} 
```

### PR DESCRIPTION
**Pull request by lrh2000**
Fix #1089 (#1103 doesn't really fix it, I can still reproduce it both locally and in the CI environment, but the problem goes away after this PR, so I think this PR actually fixes the problem)

Previously, memory operations on `DmaCoherent` generate `memmove` which copies the memory byte by byte:
https://github.com/asterinas/asterinas/blob/bdabea09c2ecc9a5fed6fe0bb0663e865d755ff0/kernel/comps/virtio/src/queue.rs#L283

The generated assembly code looks like this (after decompilation):
```c
                  lVar4 = (uVar7 * 0x1000 + *(long *)(*(long *)(lVar5 + 0x10) + 0x10) &
                          0xfffffffffffff000) - 0x800000000000;
                  lVar5 = lVar4 + uVar2;
                  uVar2 = (uVar10 + lVar4) - lVar5;
                  uVar7 = 4;
                  if (uVar2 < 4) {
                    uVar7 = uVar2;
                  }
                  compiler_builtins::mem::memmove(&local_34,lVar5,uVar7);
                  uVar10 = (ulong)local_34 << 0x20;
```
This is because such memory operations are performed by `VmReader::read`, which truncates the number of bytes to be copied by the number of available bytes:
https://github.com/asterinas/asterinas/blob/bdabea09c2ecc9a5fed6fe0bb0663e865d755ff0/ostd/src/mm/io.rs#L360-L364

This is obviously wrong. In the case of `DmaCoherent`, the buffer can be modified by the devices and read by Asterinas at the same time. For example, we check if there is a used element by loading the index, where the loading operation _must_ be a unit memory load instead of a `memove`. Otherwise the result of the load might be wrong, leading to wrong operations afterwards:
https://github.com/asterinas/asterinas/blob/bdabea09c2ecc9a5fed6fe0bb0663e865d755ff0/kernel/comps/virtio/src/queue.rs#L228-L234

This PR attempts to use [`ptr::read_volatile`](https://doc.rust-lang.org/std/ptr/fn.read_volatile.html) and [`ptr::write_volatile`](https://doc.rust-lang.org/std/ptr/fn.write_volatile.html) to solve this problem. Unfortunately, the exact conditions under which these two methods emit a single load/store operation are not yet clear (the Rust community does not guarantee this at the time of writing). But in practice, they should issue one instruction when the access size is 1, 2, 4, 8 on x86_64. This is checked by the newly added `assert_unit_memory_access` method.

After this PR, the generated assembly code for the Rust code mentioned at the beginning looks like this (after decompilation):
```c
uVar9 = (ulong)*puVar7 << 0x20;
```
So calls to `memmove` have disappeared.

### CODE REVIEW

**Comment by lrh2000** [comment]
The changes in this PR can be considered a workaround. I don't think it's a perfect solution. Maybe we need to make sure that `read_bytes` and `write_bytes` are not present in certain scenarios _from the API level_.

I'm also not sure how to deal with the alignment issue. Maybe we need to create more methods like `write_val_unaligned` and `read_val_unaligned`?

**Comment by StevenJiang1110** [comment]
> This PR attempts to use [ptr::read_volatile](https://doc.rust-lang.org/std/ptr/fn.read_volatile.html) and [ptr::write_volatile](https://doc.rust-lang.org/std/ptr/fn.write_volatile.html) to solve this problem. Unfortunately, the exact conditions under which these two methods emit a single load/store operation are not yet clear (the Rust community does not guarantee this at the time of writing)

How about using [atomic_load_relaxed](https://doc.rust-lang.org/std/intrinsics/fn.atomic_load_relaxed.html) other than read/write_volatile? 

The `atomic_load_relaxed` does not prohibits any compiler optimizations, and it should be lowered down to a single load instruction, so it does not bring any cost.

**Comment by StevenJiang1110** [comment]
> I'm also not sure how to deal with the alignment issue. Maybe we need to create more methods like write_val_unaligned and read_val_unaligned?

Personally, I think we have to provided this methods, if we do have the scenerio that values may be writen to unaligned address, just like [unaligned_volatile_load](https://doc.rust-lang.org/std/intrinsics/fn.unaligned_volatile_load.html) in std. The LLVM does not expose any alignment requirements for load/store instructions, so it's also sound to load/store from unaligned address.

**Comment by lrh2000** [comment]
> How about using [atomic_load_relaxed](https://doc.rust-lang.org/std/intrinsics/fn.atomic_load_relaxed.html) other than read/write_volatile?
> 
> The `atomic_load_relaxed` does not prohibits any compiler optimizations, and it should be lowered down to a single load instruction, so it does not bring any cost.

I think we _do_ want to prohibit compiler optimizations here.

- Atomic operations themself, without "volatile" sematics, are not designed to be used to communicate with external programs (in our case, the hardware devices). If the compiler can somehow prove that an atomic write is not useful, it can [optimize the atomic write away](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/n4455.html). We don't want to allow this because we know that we're communicating with external programs or devices, so our reads and writes should always matter. For the sematics of `ptr::write_volatile`, the Rust documentation says:
>> Volatile operations are intended to act on I/O memory, and are guaranteed to not be elided or reordered by the compiler across other volatile operations.

- Moreover: Atomic operations are meant to synchronize between multiple CPUs, not between CPUs and hardware devices. This can be easily understood by recognizing that the DMA memory barriers (e.g., [`dma_rmb`](https://elixir.bootlin.com/linux/v6.10.2/A/ident/dma_rmb) in the Linux kernel) and the SMP memory barriers (e.g., [`smp_rmb`](https://elixir.bootlin.com/linux/v6.10.2/A/ident/smp_rmb) in the Linux kernel) are not necessarily the same. Using atomic operations _cannot_ help us do the right synchronization between CPUs and devices. We already have some memory fences in our code base (see below), but sadly, all of them are incorrect and we shouldn't rely on them.
https://github.com/asterinas/asterinas/blob/bdabea09c2ecc9a5fed6fe0bb0663e865d755ff0/kernel/comps/virtio/src/queue.rs#L230-L231

> Personally, I think we have to provided this methods, if we do have the scenerio that values may be writen to unaligned address, just like [unaligned_volatile_load](https://doc.rust-lang.org/std/intrinsics/fn.unaligned_volatile_load.html) in std. The LLVM does not expose any alignment requirements for load/store instructions, so it's also sound to load/store from unaligned address.

Then maybe `read_val`/`write_val` should just panic if the alignment requirement is violated? But if we do that, this semantics will be different from `VmIo::read_val` and `VmIo::write_val`. Should we make the behavior the consistent?

**Comment by StevenJiang1110** [comment]
> I think we do want to prohibit compiler optimizations here.

Thanks for your explanation! It makes sense to me.

> Then maybe read_val/write_val should just panic if the alignment requirement is violated? 

Currently, it seems all `read_val`/`write_val` in `VmIo` does not respect the alignment of value. It reads bytes array (always from align 1) and turns the bytes as the value.

So how about using [unaligned_volatile_load](https://doc.rust-lang.org/std/intrinsics/fn.unaligned_volatile_load.html#) and (unaligned_volatile_load)[https://doc.rust-lang.org/std/intrinsics/fn.unaligned_volatile_store.html] instead of `ptr::read_volatile`/`ptr/write_volatile` in this PR? This should be consistent with current bahavior and does not require alignment check(which seems to break the unit test check in CI currently?)

Whether we should respect the alignment of value in the `VmIo` Interface may be discussed in a seperate place. Because the CI always fail without this PR, this PR may need to me merged as quickly as possible. But changing the `VmIo` interface may require more changes.

**Comment by lrh2000** [comment]
> So how about using [unaligned_volatile_load](https://doc.rust-lang.org/std/intrinsics/fn.unaligned_volatile_load.html#) and [unaligned_volatile_store](https://doc.rust-lang.org/std/intrinsics/fn.unaligned_volatile_store.html) instead of `ptr::read_volatile`/`ptr/write_volatile` in this PR?

I don't like it because if it's not aligned, we can basically have the same problem we had before this PR.

For example, one memory load instruction accessing two cache lines is actually two memory loads. The x86 CPU is powerful, so it won't throw an exception in this case.

Could you please take a look at the current solution? What do you think of it?

**Comment by lrh2000** [comment]
Some notes:
 - VmReader::read_val`/`VmWriter::write_val` still need to be fixed because they are inefficient, but in this PR I skip that and create two new methods called `read_val_no_tearing`/`write_val_no_tearing` directly.
 - The above moves the non-tearing assertion logic closer to `VmReader`/`VmWriter`, so we can reuse the logic in other structures like `IoMem` (not done in this PR though).

File: ostd/src/mm/io.rs [hunk 1]
```diff
@@ -553,6 +582,35 @@ impl<'a> VmWriter<'a, KernelSpace> {
         Ok(())
     }
 
+    /// Writes a value of the `Pod` type using one non-tearing memory store.
+    ///
+    /// If the length of the `Pod` type exceeds `self.remain()`, this method will return `Err`.
+    ///
+    /// # Panic
```
Comment (StevenJiang1110) [inline ostd/src/mm/io.rs:589]: Panic -> Panics

**Review by StevenJiang1110 — APPROVED** [review]
This PR is acceptable for me! We may see whether the CI panic disappears after this PR is merged.

Needs @tatetian for further review.

**Comment by lrh2000** [comment]
> One thing that still confuses me is that we only allow writing types with less than eight bytes(like u8, u16, u32, u64) to `DmaCoherent` at a time after this PR, which may be a too strong restriction. But the PR won't make things worse, so it's acceptable for me.

Yes, I actually agree with that.

I think it's the right restriction for `IoMem`. But having this constraint for `DmaCoherent` seems not so good. But fixing this problem probably requires a redesign of the `VmIo` API (since `SafePtr` can only accept a `VmIo` object), which is beyond the scope of this PR.

File: ostd/src/mm/io.rs [hunk 2]
```diff
@@ -672,3 +730,26 @@ impl<'a> From<&'a mut [u8]> for VmWriter<'a> {
...
+///
+/// We currently rely on this assertion to ensure that the memory operation created by
+/// `ptr::read_volatile` and `ptr::write_volatile` doesn't tear. However, the Rust documentation
+/// makes no such guarantee, and even the wording in the LLVM LangRef is ambiguous.
+///
+/// At this point, we can only _hope_ that this doesn't break in future versions of the Rust or
+/// LLVM compilers. However, this is unlikely to happen in practice, since the Linux kernel also
+/// uses "volatile" semantics to implement `READ_ONCE`/`WRITE_ONCE`.
+#[cfg(target_arch = "x86_64")]
+const fn assert_memory_access_no_tearing<T: Pod>() {
```
Comment (tatetian) [inline ostd/src/mm/io.rs:744]: Why not use `const_assert`?

```rust
const_assert! {
    let size = size_of::<T>();
    size == 0 || size == 1 || size == 2 || size == 4 || size == 8   
}
```

File: ostd/src/mm/io.rs [hunk 3]
```diff
@@ -672,3 +730,26 @@ impl<'a> From<&'a mut [u8]> for VmWriter<'a> {
...
+    let size = size_of::<T>();
+
+    if size == 0 || size == 1 || size == 2 || size == 4 || size == 8 {
```
Comment (tatetian) [inline ostd/src/mm/io.rs:747]: I don't think we want to read zero-sized values with `DmaCoherent`. Such usage almost always indicates a bug.

File: ostd/src/mm/io.rs [hunk 4]
```diff
@@ -553,11 +582,40 @@ impl<'a> VmWriter<'a, KernelSpace> {
...
+    /// This method will panic if the current position of the writer does not meet the alignment
+    /// requirements of type `T`.
+    pub fn write_val_no_tearing<T: Pod>(&mut self, new_val: &T) -> Result<()> {
+        const { assert_memory_access_no_tearing::<T>() };
+
+        if self.avail() < core::mem::size_of::<T>() {
+            return Err(Error::InvalidArgs);
+        }
+
+        assert!(self.cursor.cast::<T>().is_aligned());
```
Comment (tatetian) [inline ostd/src/mm/io.rs:604]: The pointer has been constructed twice. Once here, the other time just before `write_volatile`. You may want to consider adding a temp variable.

File: ostd/src/mm/io.rs [hunk 5]
```diff
@@ -391,6 +391,35 @@ impl<'a> VmReader<'a, KernelSpace> {
...
+    ///
+    /// # Panics
+    ///
+    /// This method will not compile (due to failed constant assertions) if the `Pod` type is too
+    /// large for the current architecture and the operation must be tear into multiple memory
+    /// loads.
+    ///
+    /// This method will panic if the current position of the reader does not meet the alignment
+    /// requirements of type `T`.
+    pub fn read_val_no_tearing<T: Pod>(&mut self) -> Result<T> {
```
Comment (tatetian) [inline ostd/src/mm/io.rs:407]: `read_once` seems to be a better name

File: ostd/src/mm/dma/dma_coherent.rs [hunk 6]
```diff
@@ -160,24 +165,26 @@ impl Drop for DmaCoherentInner {
 }
 
 impl VmIo for DmaCoherent {
-    fn read_bytes(&self, offset: usize, buf: &mut [u8]) -> crate::prelude::Result<()> {
-        self.inner.vm_segment.read_bytes(offset, buf)
+    fn read_bytes(&self, _offset: usize, _buf: &mut [u8]) -> Result<()> {
+        panic!(concat!(
+            "`DmaCoherent` must be accessed with non-tearing memory operations, ",
+            "please consider using `read_val` instead"
```
Comment (tatetian) [inline ostd/src/mm/dma/dma_coherent.rs:171]: Yes, we should fix `read_val`, but why forbid `read_bytes`? I don't think there is an architectural requirement that forbids all cache-coherent DMA areas from being read/written in a stream fashion. I think it is Virtio that demands accessing the fields of its configuration objects in single memory load/stores, not DMA.

I think we should add a `read_once` method to `SafePtr`.

```rust
impl<T: Pod, M: VmIo, R: TRights> SafePtr<T, M, TRightSet<R>> {
    #[require(R > Read)]
    pub fn read_once(&self) -> Result<T> {
        self.vm_obj.read_once(self.offset)
    }
}
```

And refactor the virtio driver to use the `read_once` method of `SafePtr` instead.

**Review by tatetian — COMMENTED** [review]
Good job! Everyone deserves a pat on the back. Finally we are fixing the annoying bugs that constantly fail our CI.

File: ostd/src/mm/io.rs (hunk 5 above)
Comment (lrh2000) [reply ostd/src/mm/io.rs:407]: I follow the term as it is used when the Rust team discusses the concept. For example, see https://rust-lang.zulipchat.com/#narrow/stream/136281-t-opsem/topic/Non-tearing.20volatile.20accesses.

File: ostd/src/mm/dma/dma_coherent.rs (hunk 6 above)
Comment (lrh2000) [reply ostd/src/mm/dma/dma_coherent.rs:171]: > Yes, we should fix read_val as a quick fix, but why forbid read_bytes? I don't think there is an architectural requirement that forbids all cache-coherent DMA areas from being read/written in a stream fashion. I think it is Virtio that demands accessing the fields of its configuration objects in single memory load/stores, not DMA.

I agree with that. But having `read_bytes` and `read_val` have different semantics is weird. As far as I am concerned, the following two should always be the same:
```rust
   reader.read_bytes(64, &mut buffer);
   let bytes: [u8; 64] = reader.read_val();
```

So since there are currently no users of `read_bytes`, changing it to just panic is acceptable to me.

The panic also serves as a note that `DmaCoherent` currently does not support reading/writing byte slices, neither with `read_bytes`/`write_bytes` nor with `read_val`/`write_val`. So future users should fix this problem first.

> A probably-more long-term solution, I think, is to add a `read_once` method to `SafePtr`.
> 
> ```rust
> impl<T: Pod, M: VmIo, R: TRights> SafePtr<T, M, TRightSet<R>> {
>     #[require(R > Read)]
>     pub fn read_once(&self) -> Result<T> {
>         self.vm_obj.read_once(self.offset)
>     }
> }
> ```
> 
> And refactor the virtio driver to use the `read_once` method of `SafePtr` instead.

Yes, I'm thinking about something like that. I can also try the solution in this PR if you like it.

Comment (tatetian) [reply ostd/src/mm/dma/dma_coherent.rs:171]: > having read_bytes and read_val have different semantics is weird.

I meant that they do have (and should, as you proposed) the same semantics if we have `read_once`, which is different from `read_bytes` and `read_val`. So we can still keep the current implementation of `read_val` and `read_bytes` intact and just add `read_once` and refactor the virtio driver.

File: ostd/src/mm/io.rs (hunk 5 above)
Comment (tatetian) [reply ostd/src/mm/io.rs:407]: Tearing means split a read/write into multiple reads/writes. So non-tearing means the same as once, but the latter is shorter. So I am ok with "non-tearing", but prefer "once"

Comment (lrh2000) [reply ostd/src/mm/io.rs:407]: OK. I also like shorter names. So I'll change it accordingly soon.

File: ostd/src/mm/io.rs (hunk 2 above)
Comment (lrh2000) [reply ostd/src/mm/io.rs:744]: I think I have tried this before. But it won't work due to a compiler error:
```
error[E0401]: can't use generic parameters from outer item
   --> ostd/src/mm/io.rs:748:30
    |
744 | const fn assert_memory_access_no_tearing<T: Pod>() {
    |                                          - type parameter from outer item
...
748 |         let size = size_of::<T>();
    |                              ^ use of generic parameter from outer item
    |
    = note: a `const` is a separate item from the item that contains it
```

Comment (tatetian) [reply ostd/src/mm/io.rs:744]: I see. It seems that we have encountered a limitation of the `static_assertion` crate.

There is another crate called `const-assert` that allows us to do this (an link to [Rust playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=82fc2ebb4e706b33507339de991b3918)).

```rust
pub struct VmReader {}

impl VmReader {
    pub fn read_once<T>(&self, offset: usize) -> T
    where
        Assert<{ is_atomic_type::<T>() }>: IsTrue
    {
        todo!()
    }
}

pub const fn is_atomic_type<T>() -> bool {
    let size = core::mem::size_of::<T>();
    size == 1 || size == 2 || size == 4 || size == 8    
}
```

No one seems to be using this crate. But [the crate is so small and obvious](https://github.com/Bajix/const-assert/blob/main/src/lib.rs) that it can hardly do anything wrong. This approach is more readable than our current approach.

**Review by tatetian — APPROVED** [review]
LGTM. Thanks for the contribution!
