### PR TITLE
Linked lists of `UniqueFrame`s

### LINKED ISSUE #1730: Introduce `UniquePage<M>`
# Background and Motivation

`Page<M>` in OSTD is cheaply clonable.

```rust
impl<M: PageMeta> Clone for Page<M> {
    fn clone(&self) -> Self {
        self.ref_count().fetch_add(1, Ordering::Relaxed);
        Self {
            ptr: self.ptr,
            _marker: PhantomData,
        }
    }
}
```

Cloned instances of a `Page<M>` object refer to the same underlying page -- and the associated page metadata. To ensure thread safety, our API can only provide an immutable reference to it.

```rust
impl<M: PageMeta> Page<M> {
    pub fn meta(&self) -> &M {
        unsafe { &*(self.ptr as *const M) }
    }
}
```

This means that if one wants to update the content of `M`, she has to adopt the internal mutability pattern by protecting part of `M` with a `SpinLock` or sorts.

This API, however, introduces unnecessary overheads when a `Page` object has only one instance (or owner). For example, a highly-optimized, custom implementation of page allocator may maintain a per-CPU list of free pages. All the `Page<M>` objects kept in the list are owned exclusively by the free list. So in theory, the page allocator should be able to have _mutable_ access to both the content and metadata of these `Page<M>` objects without _locking_.

The same argument can be made to `ContPages<M>`.

# Proposed Solution

## The new `UniquePage` type

I propose to add a new type, which provides mutable access to the associated metadata.

```rust
/// Same as `Page` but having the ownership _exclusively_.
#[repr(transparent)]
pub struct UniquePage<M>(Page<M>)

impl<M: PageMeta> UniquePage<M> {
    pub fn meta(&self) -> &M { ... }

    pub fn mut_meta(&mut self) -> &mut M { ... }
}
```

`Page` and `UniquePage` can be converted between each other.

```rust
impl<M> From<UniquePage<M>> for Page<T> {
    fn from(unique_page: UniquePage<M>) -> Self { ... }
}

impl<M> Page<M> {
    /// Converts this `Page` into `UniquePage`,
    /// or drops it if it is not unique.
    fn into_unique_or_drop(self) -> Option<UniquePage<M>> { ... }
}
```

All newly-created `Page<M>` are by definition uniquely owned. So the constructor method `from_unused` should be moved from `Page` to `UniquePage`.

```rust
impl<M: PageMeta> UniquePage<M> {
    pub fn from_unused(addr: Paddr, metadata: M) -> Self { ... }
}
```

For the same reason, the allocation API should be changed to return `UniquePage`.

```rust
pub(crate) fn alloc_single<M: PageMeta>(metadata: M) -> Option<UniquePage<M>> {
    ...
}
```

Similarly, we can extend `ContPages<M>` and add `UniqueContPages<M>`.

Naturally, one may wonder whether it makes sense to add `UniqueFrame`, a single-owner version of `Frame`. I don't see a direct user for now. So let's leave the decision for the future.

##  Extending `Page` with `try_mut_meta`

We may also add a new method to `Page`:

```rust
impl<M: PageMeta> Page<M> {
    /// Returns a mutable reference to the page metadata,
    /// if there are no other `Page` refer to the same underlying page.
    pub fn try_mut_meta(&mut self) -> Option<&mut M> { ... }
}
```

Of course, `try_mut_meta` needs to check if the reference count is equal to 1 upon every call to the method.

### LINKED ISSUE #1737: Support linked pages with intrusive collections
# Background and Motivation

One common task encountered page management is to organize pages in linked lists. For example, a custom page allocator may want to maintain per-CPU linked lists of free pages. One version of the page allocation injection PR (#1624) does this manually by maintaining the `next` and `prev` fields in the page metadata.

```rust
pub struct FreeMeta {
    value: usize,
    // The `prev` and `next` pointers store the **physical addresses**
    // of the designated memory pages.
    prev: Paddr,
    next: Paddr,
}

impl FreePage {
    pub fn meta_mut(&mut self) -> &mut FreeMeta {
        unsafe { &mut *(self.ptr as *mut FreeMeta) }
    }

    pub fn insert_after(&mut self, new_addr: Paddr) { ... }

    pub fn insert_before(&mut self, new_addr: Paddr) { ... }

    pub fn remove(&mut self) -> bool { ... }
}
```

Writing linked list manually is error prone and increases the size of OSTD. So I am wondering if it is possible to reuse the `LinkedList` provided by the `intrusive_collections` crate to _link pages_. The `intrusive_collections` crate is already part of the TCB. Its `LinkedList` has a user-friend interface, supports concurrent access, and seems to be quite efficient.

Here is an example how `LinkedList` is used to link a struct called `MyPage`.

```rust
struct MyPage {
    link: LinkedListLink,
    value: Cell<i32>,
}

intrusive_adapter!(MyPageAdapter = Box<MyPage>: MyPage { link: LinkedListLink });

let mut page_list = LinkedList::new(MyPageAdapter::new());
let page = Box::new(MyPage {
    link: LinkedListLink::new(),
    value: Cell::new(1),
});
page_list.push_back(page);
```

But obviously, this example has quite some gaps from what we want. First of all, we cannot use `Box`. Page management should be free from heap allocations to avoid chicken-egg dilemma. Second, the concept of a page is represented by `Page<M>` in OSTD. We cannot add an extra field like `link: LinkedListLink` to `Page`.

# Solution

I didn't test it. But I think the following solution should pull the trick.

The `intrusive_adapter` macro takes a pair of types: the pointer and value types. In the example above, the pointer type is `Box<MyPage>`; the value type is `MyPage`. These two types are pointer-value type pair because they can be converted back and forth thanks to the following implementation inside `intrusive_collections`.

```rust
#[cfg(feature = "alloc")]
unsafe impl<T: ?Sized> PointerOps for DefaultPointerOps<Box<T>> {
    type Value = T;
    type Pointer = Box<T>;

    #[inline]
    unsafe fn from_raw(&self, raw: *const T) -> Box<T> {
        Box::from_raw(raw as *mut T)
    }

    #[inline]
    fn into_raw(&self, ptr: Box<T>) -> *const T {
        Box::into_raw(ptr) as *const T
    }
}
```

It turns out that we should view `Page<M>` as the (smart) pointer type and `M` as the value type. Their pointer-value relationship can be established by OSTD by implementing `DefaultPointerOps`.

```rust
unsafe impl<M: ?Sized> PointerOps for DefaultPointerOps<Page<M>> {
    type Value = M;
    type Pointer = Page<M>;

    #[inline]
    unsafe fn from_raw(&self, raw: *const M) -> Page<M> {
        todo!("trivial")
    }

    #[inline]
    fn into_raw(&self, ptr: Page<M>) -> *const M {
        todo!("trivial")
    }
}
```

Now we can use `LinkedList` to link `Page<M>`. Here is an example.

```rust
```rust
// file: ostd/src/mm/page/mod.rs

#[cfg(test)]
mod test {
    use intrusive_collections::{LinkedList, LinkedListAtomicLink};

    pub struct LinkedPageMeta {
        id: u32,
        link: LinkedListAtomicLink,
    }

    impl LinkedPageMeta {
        pub fn new(id: u32) -> Self {
            Self {
                id,
                link: LinkedListAtomicLink::new(),
            }
        }
    }

    intrusive_adapter!(LinkedListAdapter = Page<LinkedPageMeta>: LinkedPageMeta { link: LinkedListAtomicLink });

    #[test]
    fn test_linked_pages() {
        use self::allocator::alloc_single;

        let page_1 = alloc_single(LinkedPageMeta::new(1)).unwrap();
        let page_2 = alloc_single(LinkedPageMeta::new(2)).unwrap();

        let mut page_list = LinkedList::new(LinkedListAdapter::new());
        page_list.push_front(page_1);
        page_list.push_front(page_2);

        assert_eq!(page_list.iter().map(|p| p.id.clone()).collect::<Vec<_>>(), [1, 2]);   
    }
}
```

### LINKED ISSUE #1740: Obtain a `Page` instance given the physical address of any in-use memory page
# Background and Motivation

We are [implementing custom page allocators](https://github.com/asterinas/asterinas/pull/1624) that can be injected into OSTD. So these page allocators are expected to implement the [buddy system](https://en.wikipedia.org/wiki/Buddy_system). 

In a buddy system, when a memory chunk (having a power-of-two number of pages) is deallocated and returned back to the page allocator, one needs to check if the "buddy" of the memory chunk also free. If so, the buddy system will (1) remove the buddy chunk from the free list for the chunk size, (2) merge the free chunk and its buddy into a larger free chunk, and (3) insert it into the free list for the larger chunk size.

In this process, one important step is to look up the buddy memory chunk given its physical memory address. Apparently, we do not want to maintain an extra indexing for this purpose. OSTD already has a built-in lookup table, which is the page meta system. Given any physical address, we should be able to recover its `Page<M>` object in O(1) complexity. To do so, one may propose to add the following new API.

```rust
impl<M> Page<M> {
    /// Constructs a new `Page<M>` object from a page that is already in use.
    ///
    /// This method succeeds by returning the `Page` object
    /// if the following conditions are met:
    /// 1. A `Page` object for the address already exists; and
    /// 2. The metadata type of existing `Page` objects is also `M`.
    pub fn from_used(paddr: Paddr, metadata: M) -> Option<Self> {
        todo!("trivial")
    }
}
```

From OSTD's point of view, the "free" buddy is "in use" because the buddy system must have created a `Page<M>` (where the concrete type for `M` is defined by the buddy system) object and pushed it into a "free" list (see also [the linked pages technique](https://github.com/asterinas/asterinas/issues/1737)). With the `Page::from_unused` API, the buddy system can recover the `Page` object for any buddy.

An easy piece of cake. Problem solved. Mission completed... or are we?

It turns out that this new API opens a soundness loophole when taking into account `UniquePage<M>` introduced in #1730. If one calls `Page::from_used` for acquire the memory page owned by a `UniquePage` and succeeds, then the unique owner property will be broken.

To prevent the invariant from being violated, one may propose to maintain a flag inside the page metadata and do some runtime checks within `Page::from_used`. But this requires flipping bits atomically when converting between `UniquePage<M>` and `Page<M>`. The added runtime cost will make the concept of `UniquePage` much less attractive or useful because it would no longer be a zero-cost, new-type wrapper for `Page`.

# Proposed Solution

To address the aforementioend technical difficulty, I introduce the concept of _exposable_ pages. Currently, pages are always _unexposable_ in the sense that once `Page` objects has been instatiated for a page, then the page is only accessible through those `Page` objects. One cannot _expose_ the page by creating `Page` objects out of thin air using the physical address.

In particular, if you are holding a `UniquePage` object or a `Page` object with reference count equals to 1, then you can be sure that no one will create new instances of `Page` objects and increase the reference count behind your back.

But sometimes we want to a page to be _exposable_, which means that everyone is allowed to create new `Page` instances for the page. The metadata of a exposable page implements a new marker trait named `Exposable`.

```rust
/// A marker trait for the metadata types of _exposable_ pages.
///
/// A page is expoable if it has `Page<M>` instances where `M: Exposable`.
/// `Page<M>` instances for an exposable page can be created 
/// from the physical address using `Page::expose`.
///
/// # Example
///
/// ```rust
/// pub struct ExposablePageMeta;
/// impl Exposable for ExposablePageMeta {}
///
/// // Create an exposable page
/// let addr = 0xdead0000;
/// let page = Page::from_unused(addr, ExposablePageMeta);
///
/// // Anyone can expose the page from its address
/// let page2 = Page::expose(addr);
/// assert!(page.meta() == page2.meta());
/// ```
pub trait Public {}
```

As shown by the example above, a new method called `expose` is added to `Page`.

```rust
impl<M> Page<M> {
    /// Constructs a new `Page<M>` object for an exposable page. 
    ///
    /// See `Exposable` for the definition of exposable pages.
    pub fn expose(paddr: Paddr) -> Option<Self> 
    where
        M: Expoable
    {
        todo!("trivial")
    }
}
```

An exposable page is initally created via `Page::<M>::from_unused` just like non-exposable pages.

## Interactions with `UniquePage`

Obviously, the uniqueness requirement of `UniquePage<M>` is incompatible with the semantics of exposable pages. So we need to maintain the following invariant:

**There exists no instances of `UniquePage<M>` where `M: Exposable`.**

So all constructor methods for `UniquePage` should be augmented to prevent creating `UniquePage<M: Exposable>`.

```rust
impl<M> UniquePage<M> {
    pub fn from_unused(paddr: Paddr, metadata: M) -> Self {
        assert!(!is_exposable::<M>());

        // ...
    }

    pub fn repurpose<P, F>(self, f: F) -> UniquePage<P> 
    where
        F: FnOnce(M) -> P
    {
        assert!(!is_exposable::<P>());

        // ...
    }
}

impl<M> Page<M> {
    /// Converts this `Page` into `UniquePage`,
    /// or drops it if it is not unique.
    fn into_unique_or_drop(self) -> Option<UniquePage<M>> {
        assert!(!is_exposable::<M>());

        // ...
    }
}
```

This magic `is_exposable` function can be implemented by leveraging some cutting-edge Rust features.

```rust
#![feature(specialization)]

pub fn is_exposable<M>() {
    pub trait IsExposable {
        const RES: bool;
    }

    impl<M> IsExposable for M {
        default const RES: bool = false;
    }

    impl<M: Public> IsExposable for M {
        const RES: bool = true;
    }

    <M as IsExposable>::RES
}
```

## Conversion from `Page<M: Exposable>` to `UniquePage<P>`

A new method is provided to convert 

```rust
impl<M> Page<M> {
    /// Turns an exposable page into an unexposable one.
    ///
    /// The given closure converts the current metadata of type `M: Exposable`
    /// to `P`, where `P` does not implement `Exposable`.
    ///
    /// This method succeeds if the reference count of the page to be 1.
    /// Otherwise, the method fails with `None`. 
    pub fn make_unexposable<P>(self, f: F) -> Option<UniquePage<P>>
    where
        M: Exposable,
        F: FnOnce(M) -> P,
    {
        assert!(!is_exposable::<P>());

        ...
    }
}
```

## Safe implementation under concurrency

The newly proposed APIs are tricky to implement correctly under concurrency.

For example, if a `Page<M: Exposable>` object is being dropped by a thread, while another thread attempts to create new `Page` instances on the address by invoking `Page::expose`. The first thread will decrease the reference count to 0, while the other is trying to increase it. Will the reference count be messed up?

As another example, a thread is converting the exposable status of a page by executing `Page::make_unexposable`, while another is calling `Page::expose` on the same physical address. Will an unexposable page be exposed during to some race conditions?

I have given some thoughts on the possible race conditions and come up with a draft implementation that I believe is free from concurrency bugs. The code takes into account of all `Page`'s methods that access or manipulate the reference count.

```rust
impl<M> Page<M> {
    pub fn try_mut_meta(&mut self) -> Option<&mut M> {
        assert!(!is_exposable::<M>());

        if self.ref_count().load(Acquire) != 1 {
            return None;
        }

        // SAFETY: This page is not exposable.
        // So we don't have to worry about `Page::expose` creating more instances.
        unsafe {
            todo!("trivial")    
        }
    }

    pub fn expose(paddr: Paddr) -> Option<Self> 
    where
        M: Exposable
    {
        // It is important that we use `fetch_update` instead of `fetch_add`.
        // Otherwise, the `drop` method will be unsound.
        let res = self.ref_cnt().fetch_update(Acquire, Relaxed, |old_cnt| {
            // Handle two situations where the expose operation must NOT succeed:
            // 1. The condition `old_cnt == 0` means that the page is free;
            // 2. The condition `old_cnt == LOCKED` means that the page is being changed from exposable to unexposable.
            if old_cnt == 0 || old_cnt == LOCKED {
                return None;
            }

            Some(old_cnt + 1);
        });

        if res.is_err() {
            return None;
        }

        // Ensure that the metadata type is M
        {
            // SAFETY: the reference count is non zero. So the vtable ptr must be valid.
            let expected_vtable_ptr = unsafe {
                self.vtable_ptr()
            };
            let actual_vtable_ptr = todo!("need to figure this one out");
            if actual_vtable_ptr != expected_vtable_ptr {
                self.ref_cnt().fetch_sub(1, Relase);
                return None;
            }
        }

        let new_page = todo!();

        Ok(new_page);
    }

    pub fn make_unexposable<P>(self, f: F) -> Option<UniquePage<P>>
    where
        M: Exposable,
        F: FnOnce(M) -> P,
    {
        assert!(!is_exposable::<P>());

        // Lock the reference count so that no other threads can
        // call `Page::expose` to create new instances.
        if self.ref_cnt().compare_exchange(1, LOCKED, AcqRel).is_err() {
            return None;
        }

        let new_self = todo!("do repurpose");

        // Unlock the reference count
        self.ref_cnt().store(1, Release);

        Some(new_self)
    }
}

// The reference count will be locked during `make_unexposable`
const LOCKED: usize = usize::max();

impl<M> Clone for Page<M> {
    fn clone(&self) -> Self {
        // No changes
        self.ref_count().fetch_add(1, Ordering::Relaxed);
        ...
    }
}

impl<M> Drop for Page<M> {
    fn drop(&mut self) {
        // No changes
        let last_ref_cnt = self.ref_count().fetch_sub(1, Ordering::Release);
        if last_ref_cnt == 1 {
            ...
        }
    }
}
```

### PR DESCRIPTION
**Pull request by junyang-zh**
The first commit introduces `UniqueFrame` and the ability to get a frame from a used physical address. Fix #1730 

The second commit offers a way to organize `Frame`s in linked lists without additional heap allocation. Helpful for
both the frame allocator (need free lists) and the slab cache (need slab lists). Fix #1737 

The reason why there's no lock-free list in this PR is that it is impossible to make a lock-free linked list that satisfies all
(1. no additional heap allocation) (2. $O(1)$ deletion when holding only pointer to a node) and (3. ABA free). [intrusive_collections](https://crates.io/crates/intrusive-collections)'s `AtomicLink` have 1. (and maybe 3., I am not quite sure and it looks very, very suspicious). [This paper](https://dl.acm.org/doi/pdf/10.1145/224964.224988) have 2. and 3. but not heap free since it requires additional auxiliary nodes. So we are kinda stuck here. I managed a locked version (which is tricky also).

Fix #1740 . But in a different way. I just make all types of pages "exposable" to other modules, i.e., any kernel modules can get a `Frame<dyn AnyFrameMeta>` out of any `paddr`, unrestricted. The mechanism to restrict a module accessing other module's metadata is simply make the type private. Let's assume that the frame allocator uses type `Frame<Link<FreeBuddyMeta>>` and `FreeBuddyMeta` is `pub(crate)`, although other modules can get `Frame<dyn AnyFrameMeta>` to it, they can't move it out of the list or know which level is it anyway. So currently there's no big problem except that other modules can read or write to the frame. #1740 fails in such a scenario since if you make `Link<FreeBuddyMeta>` not "exposable" you cannot use it yourself. If making it "exposable" it's no different than the apporach in this PR. I have an idea to further restrict inter-module access with minimal OSTD involvement but I don't think this PR is a proper place to do so.

There's already unit test cases but there's no usages of the linked list yet. I may post another PR relying on it and implement the frame allocator later.

### CODE REVIEW

File: ostd/src/sync/mutex.rs [hunk 1]
```diff
@@ -48,6 +49,16 @@ impl<T: ?Sized> Mutex<T> {
         self.queue.wait_until(|| self.try_lock_arc())
     }
 
+    /// Acquires the mutex through a [`Pin`].
+    ///
+    /// The method is similar to [`lock`], but it allows the inner data to be pinned.
+    ///
+    /// [`lock`]: Self::lock
+    #[track_caller]
+    pub fn lock_pinned(self: Pin<&Self>) -> PinMutexGuard<'_, T> {
```
[the remark this answers is not in the document]
Comment (junyang-zh) [reply ostd/src/sync/mutex.rs:58]: Thanks for pointing it out. I agree that it is not sound.

[the remark this answers is not in the document]
Comment (lrh2000) [reply ostd/src/sync/mutex.rs:58]: I'm thinking whether we want something like `Pin<Frame<Metadata>>`, which is something like `Pin<Box<Metadata>>` and seems to align more with the Rust documentation:
> [Pin](https://doc.rust-lang.org/std/pin/struct.Pin.html) is a wrapper around some kind of pointer Ptr which makes that pointer “pin” its pointee value in place, thus preventing the value referenced by that pointer from being moved or otherwise invalidated at that place in memory unless it implements [Unpin](https://doc.rust-lang.org/std/marker/trait.Unpin.html).

We need to prohibit the user from getting a `&mut Metadata` unless `Metadata: Unpin`. Not sure if this is feasible, though.

[the remark this answers is not in the document]
Comment (junyang-zh) [reply ostd/src/sync/mutex.rs]: > I'm thinking whether we want something like ...

@lrh2000 didn't read about the purpose of pinning. We had a private conversation and we have agreed on the context and the purpose and I want to explain to the rest of you here.

The target is to support $O(1)$ find&removal, i.e. if I get a pointer to a frame (`Frame`) and I have a mutable reference to the list (`&mut LinkedList`), I shall be able to remove the frame from the list in $O(1)$ time.

To achieve this, OSTD must be able to verify that 1. a frame can at most be in one list and 2. the frame is in that list. So originally we store the pointer to the list variable in the frame metadata, and make the list work only with `Pin<&mut LinkedList>`. Nevertheless it doesn't work out as expected.

So I pushed a new version, implemented by self-incrementing `u64` IDs for each linked list. The drawback is that creating linked lists would scale poorly on multi-core and if one is constantly creating lists we will run out of IDs in approximately 250 years. Currently there are only static list creators so the number of lists in the system is bounded. Maybe we would address the drawbacks in the future.

File: ostd/src/mm/frame/meta.rs [hunk 2]
```diff
@@ -162,7 +167,126 @@ macro_rules! impl_frame_meta_for {
...
+    ///
+    /// [`UniqueFrame`]: super::unique::UniqueFrame
+    Unique,
+    /// The provided physical address is out of bound.
+    OutOfBound,
+    /// The provided physical address is not aligned.
+    NotAligned,
+}
+
+/// Get the reference to a metadata slot.
```
Comment (lrh2000) [inline ostd/src/mm/frame/meta.rs:189]:
```suggestion
/// Gets the reference to a metadata slot.
```

File: ostd/src/mm/frame/meta.rs [hunk 3]
```diff
@@ -162,7 +167,126 @@ macro_rules! impl_frame_meta_for {
...
+    /// The resulting reference count held by the returned pointer is
+    /// [`REF_COUNT_UNIQUE`] if `as_unique_ptr` is `true`, otherwise `1`.
+    pub(super) fn get_from_unused<M: AnyFrameMeta>(
+        paddr: Paddr,
+        metadata: M,
+        as_unique_ptr: bool,
+    ) -> Result<*const Self, GetFrameError> {
+        // Checking unsafe preconditions of the `AnyFrameMeta` trait.
+        debug_assert!(size_of::<M>() <= FRAME_METADATA_MAX_SIZE);
+        debug_assert!(align_of::<M>() <= FRAME_METADATA_MAX_ALIGN);
```
Comment (lrh2000) [inline ostd/src/mm/frame/meta.rs]: We should probably move these checks to `write_meta` so that it covers both `get_from_unused` and `repurpose`.

**Review by lrh2000 — COMMENTED** [review]
Thanks for your efforts in implementation and addressing the above comments!

I just have some additional minor comments now.

File: ostd/src/mm/frame/meta.rs [hunk 4]
```diff
@@ -532,7 +532,7 @@ fn alloc_meta_frames(tot_nr_frames: usize) -> (usize, Paddr) {
     let slots = paddr_to_vaddr(start_paddr) as *mut MetaSlot;
 
     // Fill the metadata frames with a byte pattern of `REF_COUNT_UNUSED`.
-    debug_assert_eq!(REF_COUNT_UNUSED.to_ne_bytes(), [0xff, 0xff, 0xff, 0xff]);
+    debug_assert_eq!(REF_COUNT_UNUSED.to_ne_bytes(), [0xff; 8]);
```
[the remark this answers is not in the document]
Comment (junyang-zh) [reply ostd/src/mm/frame/meta.rs]: Sorry for the delay. The performance problem during boot is minor and I didn't test it. The current PR still follows the original way of initialization for the reason that I need to have a `in_list` field in the metadata slot.

I noticed that if we store the `in_list` field in the `Link` metadata type, we need to first confirm the type of a frame then tell if the frame is in a list. It isn't possible to store `UniqueFrame`s in lists, because you can't read a frame if it is held by a `UniqueFrame`. In that way, we would like to store `Frame` rather than `UniqueFrame` in lists. It brings overhead implementing Slabs because getting a `&mut Slab` always requires to move a slab out of the list and wait it to be unique.

Anyway, this discussion is out-of date right now.

File: ostd/src/mm/frame/linked_list.rs [hunk 5]
```diff
@@ -0,0 +1,674 @@
...
+/// To allow other metadata to be customized, this type is a wrapper around the
+/// actual metadata type `M`.
+///
+/// Linked list frames can be contained in a [`LinkedList`].
+#[derive(Debug)]
+pub struct Link<M> {
+    // The prev and next pointers are mutably borrowed when the list is mutably
+    // borrowed.
+    next: UnsafeCell<Option<NonNull<Link<M>>>>,
+    prev: UnsafeCell<Option<NonNull<Link<M>>>>,
```
Comment (lrh2000) [inline ostd/src/mm/frame/linked_list.rs:402]: It seems you've changed the linked list implementation to include `UniqueFrame` (instead of `Frame` in the original implementation), right? So during insertion and removal you have a mutable reference to `Link<M>`. That means you don't really need internal mutability now.

I think we can remove `UnsafeCell` here and just do it:
```patch
-                     *prev.as_mut().next.get_mut() = Some(frame_ptr);
+                     prev.as_mut().next = Some(frame_ptr);
```

File: ostd/src/mm/frame/linked_list.rs [hunk 6]
```diff
@@ -0,0 +1,674 @@
...
+    /// Creates a new linked list metadata.
+    pub const fn new(meta: M) -> Self {
+        Self {
+            next: UnsafeCell::new(None),
+            prev: UnsafeCell::new(None),
+            meta,
+        }
+    }
+
+    fn next_mut(&mut self) -> &mut Option<NonNull<Link<M>>> {
```
Comment (lrh2000) [inline ostd/src/mm/frame/linked_list.rs:436]: `next_mut`/`prev_mut` can be removed after removing `UnsafeCell`.

File: ostd/src/mm/frame/linked_list.rs [hunk 7]
```diff
@@ -0,0 +1,674 @@
...
+    /// next frame. If the cursor is pointing to the back of the list then it
+    /// is moved to the "ghost" non-element.
+    pub fn take_current(&mut self) -> Option<UniqueFrame<Link<M>>> {
+        let frame = self.current.map(|current| {
+            let meta_ptr = current.as_ptr() as *mut MetaSlot;
+            let paddr = mapping::meta_to_frame::<PagingConsts>(meta_ptr as Vaddr);
+            // SAFETY: The frame was forgotten when inserted into the linked list.
+            unsafe { UniqueFrame::<Link<M>>::from_raw(paddr) }
+        })?;
+        // SAFETY: We own the links with `&mut self`.
```
Comment (lrh2000) [inline ostd/src/mm/frame/linked_list.rs:288]: It might be better to insert a blank line between lines 287 and 288, because `frame` is referenced in several blocks of code below.

File: ostd/src/mm/frame/meta.rs [hunk 8]
```diff
@@ -105,6 +107,10 @@ pub(in crate::mm) struct MetaSlot {
     pub(super) ref_count: AtomicU64,
     /// The virtual table that indicates the type of the metadata.
     pub(super) vtable_ptr: UnsafeCell<MaybeUninit<FrameMetaVtablePtr>>,
+    /// This is only accessed by [`crate::mm::frame::linked_list`].
+    /// It stores 0 if the frame is not in any list, otherwise it stores the
+    /// ID of the list.
+    pub(super) in_list: AtomicU64,
```
Comment (lrh2000) [inline ostd/src/mm/frame/meta.rs:113]: Well, I was a bit hesitant about always having this field regardless of the metadata type. In fact, we should only have this field when the vtable ptr points to `Link<M>`.

I don't really have a better idea at the moment. Maybe we can tweak this as future work.

File: ostd/src/mm/frame/unique.rs [hunk 9]
```diff
@@ -147,3 +195,41 @@ impl<M: AnyFrameMeta + ?Sized> TryFrom<Frame<M>> for UniqueFrame<M> {
...
+    type Target = UniqueFrame<M>;
+
+    fn deref(&self) -> &Self::Target {
+        &self.inner
+    }
+}
+
+impl<M: AnyFrameMeta + ?Sized> DerefMut for UniqueFrameRefMut<'_, M> {
+    fn deref_mut(&mut self) -> &mut Self::Target {
+        &mut self.inner
```
Comment (lrh2000) [inline ostd/src/mm/frame/unique.rs:217]: 1. If we can get a `&mut UniqueFrame<M>` and then `core::mem::swap` the unique frame to replace the one behind the `UniqueFrameRefMut`, is that sound?
2. More seriously, if having a `&mut UniqueFrame<M>` also implies that we can have a mutable reference to the metadata (which is a `Link<M>`), then if we `core::mem::swap` the `Link<M>`, is that sound?

I don't really think about the first question, but the answer to the second question seems to be trivially negative. A `Link<M>` must be pinned, the invariant of the linked list will be broken if the `Link<M>` is moved to another address, so we cannot allow the user to `&mut Link<M>`. We used to prohibit this by putting all `Link<M>` in the linked list behind a `Frame`, but now we put them behind a `UniqueFrame`, which is problematic.

I think we should either roll back to the previous version, or invent something like `Pin<UniqueFrame<Link<M>>>` to fix this problem.

**Review by lrh2000 — COMMENTED** [review]
In the latest version, it seems that the linked list implementation has been changed to include `UniqueFrame` directly (instead of `Frame` in the original implementation).

Unfortunately, I think this leads to some soundness problems, please read the last inline comment first before checking other comments.

File: ostd/src/mm/frame/meta.rs (hunk 4 above)
[the remark this answers is not in the document]
Comment (lrh2000) [reply ostd/src/mm/frame/meta.rs]: Thanks for the explanation.

> Anyway, this discussion is out-of date right now.

Yes, this discussion is outdated, let's discuss below the soundness problems of storing `UniqueFrame` in the linked list.

File: ostd/src/mm/frame/meta.rs [hunk 10]
```diff
@@ -498,18 +504,18 @@ fn alloc_meta_frames(tot_nr_frames: usize) -> (usize, Paddr) {
...
-    // either not accessed or `MaybeUninit`).
-    unsafe {
-        core::ptr::write_bytes(
-            slots as *mut u8,
-            0xff,
-            tot_nr_frames * size_of::<MetaSlot>(),
-        );
+    // Initialize the metadata slots.
+    for i in 0..tot_nr_frames {
+        let slot = unsafe { slots.add(i) };
```
Comment (lrh2000) [inline ostd/src/mm/frame/meta.rs:509]:
```suggestion
        // SAFETY: The memory is successfully allocated with `tot_nr_frames` slots
        // so the index must be within the range.
        let slot = unsafe { slots.add(i) };
```

File: ostd/src/mm/frame/meta.rs [hunk 11]
```diff
@@ -498,18 +504,18 @@ fn alloc_meta_frames(tot_nr_frames: usize) -> (usize, Paddr) {
...
+        // SAFETY: The slot is valid and not in use.
+        unsafe {
```
Comment (lrh2000) [inline ostd/src/mm/frame/meta.rs:511]:
```suggestion
        // SAFETY: The memory is just allocated so we have exclusive access and
        // it's valid for writing.
        unsafe {
```

**Comment by junyang-zh** [comment]
Allow me to explain the change. This PR serves for the allocators #1789 #1783 at the moment. For the previous version of the linked list, which stores `Frame`s instead of `UniqueFrame`s, suffers from unavoidable overhead when implementing the allocators

A common usage of the linked list in the allocators is that we would check if a frame (which we have only a physical address of) is in a list or not. If affirmative, for the buddy system would extract this frame out of the list and merge with the buddy; for the slab allocator it may try to allocate a slot from it.

If we store a `Frame` in it, when doing the first step we would try inc the reference count of the frame and then read the metadata. If the rc is currently unique we would like to spin over it. Next when it is extracted we would like to convert it back to unique again, possibility spinning. In the fastest condition the previous version would cost extra 3x more atomic operations than the current approach.

This PR also optimizes the "telling if in llist part by storing the `in_list` field in the meta slot. This is ugly but allows us to tell if a frame is in a specific list by one relaxed read. Otherwise we would have to ensure that the type is correct before read, which costs a syncronization.

I am thinking to impl `UniqueFrame::<M>::meta_mut(&mut self) -> &muself` only if `M: Unpin`. And `Link` should be `!Unpin`. Does it look sound to you @lrh2000 ?

**Comment by lrh2000** [comment]
> Allow me to explain the change. This PR serves for the allocators #1789 #1783 at the moment. For the previous version of the linked list, which stores `Frame`s instead of `UniqueFrame`s, suffers from unavoidable overhead when implementing the allocators
> 
> A common usage of the linked list in the allocators is that we would check if a frame (which we have only a physical address of) is in a list or not. If affirmative, for the buddy system would extract this frame out of the list and merge with the buddy; for the slab allocator it may try to allocate a slot from it.
> 
> If we store a `Frame` in it, when doing the first step we would try inc the reference count of the frame and then read the metadata. If the rc is currently unique we would like to spin over it. Next when it is extracted we would like to convert it back to unique again, possibility spinning. In the fastest condition the previous version would cost extra 3x more atomic operations than the current approach.
> 
> This PR also optimizes the "telling if in llist part by storing the `in_list` field in the meta slot. This is ugly but allows us to tell if a frame is in a specific list by one relaxed read. Otherwise we would have to ensure that the type is correct before read, which costs a syncronization.

Thanks for the explanation. I've read it and I think we're on the same page.

> I am thinking to impl `UniqueFrame::<M>::meta_mut(&mut self) -> &mut self` only if `M: Unpin`. And `Link` should be `!Unpin`. Does it look sound to you @lrh2000 ?

I think it addresses the second problem, but not the first one:
>> 1. If we can get a `&mut UniqueFrame<M>` and then `core::mem::swap` the unique frame to replace the one behind the `UniqueFrameRefMut`, is that sound?
>> 2. More seriously, if having a `&mut UniqueFrame<M>` also implies that we can have a mutable reference to the metadata (which is a `Link<M>`), then if we `core::mem::swap` the `Link<M>`, is that sound?

Please check the comments in the `main` function below. I believe it's not sound ([playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=6c1d786996214285077b1ff92b153020)):

<details>
<summary> unsoundness </summary>

```rust
use std::{
    mem::ManuallyDrop,
    ops::{Deref, DerefMut},
};

struct RefMut<T> {
    data: ManuallyDrop<T>,
}
impl<T> Deref for RefMut<T> {
    type Target = T;

    fn deref(&self) -> &Self::Target {
        &self.data
    }
}
impl<T> DerefMut for RefMut<T> {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.data
    }
}

fn force_drop<T: Default>(cannot_drop: &mut RefMut<T>) {
    let mut data = Default::default();
    core::mem::swap(&mut data, cannot_drop.deref_mut());
    drop(data);
}

struct Test {
    can_drop: bool,
}
impl Default for Test {
    fn default() -> Self {
        Self { can_drop: true }
    }
}
impl Drop for Test {
    fn drop(&mut self) {
        if !self.can_drop {
            panic!("cannot drop");
        }
    }
}

fn main() {
    // This is a `UniqueFrame` that resides in a linked list, so it cannot be
    // dropped without first removing it from the list.
    let cannot_drop = ManuallyDrop::new(Test { can_drop: false });
    
    // This is a `UniqueFrameRefMut` that can be returned by
    // `CursorMut::current`.
    let mut cannot_drop_ref = RefMut { data: cannot_drop };

    // Oops, we dropped the `UniqueFrame` which is in the linked list.
    // Even worse, by the same principle, we can take it out and do whatever
    // we want since we gain ownership of the `UniqueFrame`.
    force_drop(&mut cannot_drop_ref);
}
```
</summary>

Do we really need `UniqueFrameRefMut`? If it's just a `UniqueFrameRef` (no `Mut`), I think the soundness problem goes away.

**Comment by junyang-zh** [comment]
> Do we really need UniqueFrameRefMut? If it's just a UniqueFrameRef (no Mut), I think the soundness problem goes away.

Your example makes sense. `UniqueFrameRefMut` is used for the slab allocator to allocate (`Slab::alloc(&mut self) -> Slot`) a slot in a slab which resides in a list. I was seeking a way to allocate a slot without extracting from the list and put it back again. Let me think of a more elegant solution.

File: ostd/src/mm/frame/meta.rs (hunk 8 above)
Comment (junyang-zh) [reply ostd/src/mm/frame/meta.rs:113]: I responded to it here: https://github.com/asterinas/asterinas/pull/1780#issuecomment-2603516947.

**Comment by junyang-zh** [comment]
I've adopted a new approach to allow allocating with `&mut SlabMeta` instead of `&mut UniqueFrame<Link<SlabMeta>>`, so that `UniqueFrameRefMut` won't be needed anymore.

**Review by lrh2000 — APPROVED** [review]
Thanks for addressing all the comments above.

The current changes look good to me. Just two more nits.

**Review by tatetian — APPROVED** [review]
LGTM. Thanks for the contribution!
