### PR TITLE
[TDX] Support for TDX release mode

### LINKED ISSUE #1052: MMIO access generates unexpected instruction
### Describe the bug

The [two lines in MMIO init file](https://github.com/asterinas/asterinas/blob/main/ostd/src/bus/mmio/mod.rs#L62-L63):

```rust
let value = unsafe { *(paddr_to_vaddr(current) as *const u32) };
if value == VIRTIO_MMIO_MAGIC {
```
will generate a `Cmp_rm32_imm32` instruction if we set `RELEASE=1`.

However, we expect to access the MMIO region using only read or write instructions. Only these cases are handled in TDX MMIO emulation.

Therefore, we need to prevent the compiler from generating similar instructions when accessing MMIO. (Currently only found this one)

### PR DESCRIPTION
**Pull request by Hsy-Intel**
1. Fix #1052 to avoid generating the `Cmp_rm32_imm32` MMIO instruction.
2. Use `tdx-guest` crate VE handler and support release mode for TDX.

### CODE REVIEW

**Comment by Hsy-Intel** [comment]
Conflicts fixed.

File: ostd/src/arch/x86/cpu/mod.rs [hunk 1]
```diff
@@ -45,103 +43,105 @@ pub struct CpuExceptionInfo {
     pub page_fault_addr: usize,
 }
 
+struct GeneralRegsWrapper(RawGeneralRegs);
```
Comment (tatetian) [inline ostd/src/arch/x86/cpu/mod.rs:46]: This struct is also for Intel TDX only. Wrap the type and its implementation block in a module and use a single `cfg` to control the compilation of the module.

In addition, the TDX-specific imports at the top of this file can be moved into this newly-added module and the TDX-specific code block in `UserContext::execute`.

File: ostd/src/arch/x86/cpu/tdx.rs [hunk 2]
```diff
@@ -0,0 +1,113 @@
+// SPDX-License-Identifier: MPL-2.0
+
+use tdx_guest::{handle_virtual_exception, tdcall, TdxTrapFrame};
+
+use crate::cpu::{RawGeneralRegs, UserContext};
+
+pub(crate) fn handle_virtualization_exception(user_context: &mut UserContext) {
```
Comment (tatetian) [inline ostd/src/arch/x86/cpu/tdx.rs:7]: The names of the two functions, `handle_virtual_exception` and `handle_virtualization_exception`, are too much alike. From names, a reader cannot get their relationship easily. Importing `handle_virtual_exception` with a prefix to make their relationship more obvious.

```rust
use tdx_guest::{handle_virtual_exception as do_handle_virtual_exception, tdcall, TdxTrapFrame};

pub(crate) fn handle_virtual_exception(user_context: &mut UserContext) {
    let ve_info = tdcall::get_veinfo().expect("#VE handler: fail to get VE info\n");
    let mut generalrags_wrapper = GeneralRegsWrapper(*user_context.general_regs_mut());
    do_handle_virtual_exception(&mut generalrags_wrapper, &ve_info);
    *user_context.general_regs_mut() = generalrags_wrapper.0;
}
```

File: ostd/src/arch/x86/cpu/tdx.rs [hunk 3]
```diff
@@ -0,0 +1,113 @@
...
+    let ve_info = tdcall::get_veinfo().expect("#VE handler: fail to get VE info\n");
+    let mut generalrags_wrapper = GeneralRegsWrapper(*user_context.general_regs_mut());
+    handle_virtual_exception(&mut generalrags_wrapper, &ve_info);
+    *user_context.general_regs_mut() = generalrags_wrapper.0;
```
Comment (tatetian) [inline ostd/src/arch/x86/cpu/tdx.rs:11]: So converting between the original and the wrapper types involving copying twice. This can be avoided if `GeneralRegsWrapper` takes a mutable reference of `RawGeneralRegs`.

```rust
struct GeneralRegsWrapper<'a>(&'a mut RawGeneralRegs);
```

**Review by tatetian — COMMENTED** [review]
The PR looks mostly good to me. Just some minor issues. And it should be rebased to the latest main branch.

**Review by tatetian — APPROVED** [review]
LGTM. Thanks for the contribution!
