### PR TITLE
Polish the page table safety model

### LINKED ISSUE #919: [RFC] Safety model about the page tables
# Background

This issue discusses the internal APIs of the page table. More specifically, the following two sets of APIs:
 - The APIs provided by `RawPageTableNode`/`PageTableNode`
   - Files: [`framework/aster-frame/src/mm/page_table/node.rs`](https://github.com/asterinas/asterinas/blob/main/framework/aster-frame/src/mm/page_table/node.rs)
 - The APIs provided by `PageTable`/`Cursor`/`CursorMut`
   - Files: [`framework/aster-frame/src/mm/page_table/mod.rs`](https://github.com/asterinas/asterinas/blob/main/framework/aster-frame/src/mm/page_table/mod.rs) and [`framework/aster-frame/src/mm/page_table/cursor.rs`](https://github.com/asterinas/asterinas/blob/main/framework/aster-frame/src/mm/page_table/cursor.rs)

The focus is on what kind of safety guarantees they can provide.

Currently, this question is not clearly answered. For example, consider the following API in `PageTableNode`:
https://github.com/asterinas/asterinas/blob/c6aa9f9ee860bbdcb8bb3444b630aff9f0ac14af/framework/aster-frame/src/mm/page_table/node.rs#L383-L388

This method is marked as unsafe because it can create arbitrary mappings. This is not a valid reason to mark it as unsafe, as the activation of a `RawPageTableNode` is already marked as unsafe, as shown in the following code snippet:
https://github.com/asterinas/asterinas/blob/c6aa9f9ee860bbdcb8bb3444b630aff9f0ac14af/framework/aster-frame/src/mm/page_table/node.rs#L112-L124

_If_ the above reason is considered valid, then _every_ modification method of `PageTableNode` must also be marked as unsafe. This is because a `PageTableNode` does not know its exact position in the page table, so it can be at a critical position (e.g. the kernel text). In such cases, its modification will never be safe in the sense of mapping safety.

https://github.com/asterinas/asterinas/blob/c6aa9f9ee860bbdcb8bb3444b630aff9f0ac14af/framework/aster-frame/src/mm/page_table/node.rs#L372-L373

https://github.com/asterinas/asterinas/blob/c6aa9f9ee860bbdcb8bb3444b630aff9f0ac14af/framework/aster-frame/src/mm/page_table/node.rs#L356-L362

Fortunately, the unsafety of the activation method `RawPageTableNode::activate` should have already captured the mapping safety, so I argue that all other modification methods like `PageTableNode::set_child_untracked` mentioned above should not consider the mapping safety again. However, it should consider the safety of the page tables themselves.

But the safety of the page tables themselves still involves a lot of things, like the following:
 - **Property 1**: If any PTE points to another page table, it must point to a valid page table.
 - **Property 2**: If any PTE points to a physical page, it can point to either a tracked frame or an untracked region of memory.
 - **Property 3**: If any PTE points to a physical page and the current page table node can only represent tracked mappings, the PTE must point to a tracked frame.
 - **Property 4**: If any PTE points to a physical page and the current page table node can only represent untracked mappings, the PTE must point to an untracked region of memory.
 - **Property 5**: If any PTE points to another page table, it must point to a page table that is on the next page level. If the next page level does not exist, the PTE cannot point to a page table.

The current design does indeed guarantee **Property 1** and **Property 2**, but the APIs need some revision to make them truly safe. However, it runs into difficulties when dropping the page tables, because the page table nodes do not know whether PTEs point to tracked frames or untracked regions of memory. The API change and the difficulties are described below as **Solution 1**.

To address the above difficulties, I think that it is possible to additionally guarantee **Property 3** and **Property 4** through safe APIs of page table nodes. I call this **Solution 2** below.

I don't think that **Property 5** needs to be guaranteed by `PageTableNode`. The reason is that it can be trivially guaranteed by the page table cursors. The page table cursors maintain a fixed-length array, where each slot can have a page table node at a certain level. It is clear enough, so there is little benefit to enforce these guarantees to the page table nodes.

# Solution 0

Do nothing.

**Pros:**
 - No more work to do!

**Cons:**
 - The current APIs are not as good as I would like them to be, and I think they are hard to maintain.

# Solution 1

The current design guarantees **Property 1** and **Property 2**. However, most of the `PageTableNode` APIs cannot be considered safe because they rely on the correctness of the input argument `in_untracked_range` to be memory safe:

https://github.com/asterinas/asterinas/blob/c6aa9f9ee860bbdcb8bb3444b630aff9f0ac14af/framework/aster-frame/src/mm/page_table/node.rs#L267-L268

For example, if someone passes `in_untracked_range = false` to `PageTableNode::child`, but the corresponding PTE actually points to an untracked memory range, then the untracked memory range will be cast to an tracked frame. This will cause serve memory safety issues.

To solve this problem, it is possible to create a new type called `MaybeTrackedPage`, which can be converted into a tracked frame (via the unsafe `assume_tracked` method) or an untracked region of memory (via the `assume_untracked` method) by the user:

https://github.com/asterinas/asterinas/blob/7f45a1bb29f5bf6d6ddb0d12fdb48dc1ca15852c/framework/aster-frame/src/mm/page_table/node.rs#L253-L268

Then the `PageTableNode::child` method can be made to return a wrapped type of `MaybeTrackedPage` (the `Child` wrapper handles cases where the PTE is empty or points to another page table):

https://github.com/asterinas/asterinas/blob/7f45a1bb29f5bf6d6ddb0d12fdb48dc1ca15852c/framework/aster-frame/src/mm/page_table/node.rs#L447-L448

I think this solution works well, _except_ for the annoying `Drop` implementation. Since the page table node has no way of knowing whether PTEs point to tracked frames or untracked regions of memory, it won't know how to drop them if such PTEs are encountered in the `Drop` method. So far it is assumed that only tracked frames can be dropped, as shown in the following code snippet:

https://github.com/asterinas/asterinas/blob/c6aa9f9ee860bbdcb8bb3444b630aff9f0ac14af/framework/aster-frame/src/mm/page_table/node.rs#L536-L540

But this assumption can easily be wrong. For example, a page table containing untracked regions of memory can be dropped if a huge page overwrites the PTE on a page table:

https://github.com/asterinas/asterinas/blob/c6aa9f9ee860bbdcb8bb3444b630aff9f0ac14af/framework/aster-frame/src/mm/page_table/node.rs#L474-L476

It is possible to work around this problem by adding methods such as `drop_deep_untracked` and `drop_deep_tracked`, which recursively drop all descendants of the current page table node, assuming they contain only tracked frames or untracked regions of memory. Then the `drop` method should not see any PTEs pointing to physical pages.

https://github.com/asterinas/asterinas/blob/7f45a1bb29f5bf6d6ddb0d12fdb48dc1ca15852c/framework/aster-frame/src/mm/page_table/node.rs#L303-L325

However, this solution is not very elegant.

**Pro:**
 - It was implemented in #918, see commits "Implement `MaybeTracked{,Page,PageRef}`" and "Clarify the safety model in `PageTableNode`".

**Cons:**
 - The dropping implementation is not ideal.
 - The cursor (and its users) must be careful about whether the PTE represents tracked frames or untracked regions of memory.

# Solution 2

One possible solution to solve the problem above is to make page table nodes aware whether it contains tracked frames or untracked regions of memory.

I think it is reasonable to make an additional assumption: a page table node cannot _directly_ contain both PTEs to tracked frames and PTEs to regions of memory. This limits the power of the page table a bit, but is still reasonable. On x86-64, each page table node representing a 1GiB mapping can have either tracked frames or untracked regions of memory, but not both, as 2MiB huge pages, which still seems flexible to me.

This information can be recorded in the page metadata, marking each page table as `Tracked` (diretly containing PTEs only to tracked frames), `Untracked` (directly contains PTEs only to untracked regions of memory), or `None` (directly containing no PTEs to physical pages). Then when dropping a page table, it is clear the PTEs can be dropped without problems.

A simple way to enforce the page metadata is to add assertions at the beginning of methods like `PageTableNode::set_child_frame` and `PageTableNode::set_child_untracked`. Compilers may be smart to check once and update a number of PTEs.

Alternatively, I think a better solution is to make page table cursors that operate on tracked frames and untracked regions of memory _different modes_ (like the existing `UserMode` and `KernelMode`). This way, whether a cursor operates on tracked frames or untracked regions can be determined at compile time, instead of at runtime as it is now:
https://github.com/asterinas/asterinas/blob/c6aa9f9ee860bbdcb8bb3444b630aff9f0ac14af/framework/aster-frame/src/mm/page_table/cursor.rs#L278-L282

Then the page table cursor and page table node implementation should be much clearer:
```rust
impl TrackedNode {
    fn set_child(&mut self, idx: usize, frame: Frame);
}

impl UntrackedNode {
    fn set_child(&mut self, idx: usize, paddr: Paddr);
}
```
```rust
// `TrackedMode` associates with `TrackedNode`
impl<M: TrackedMode> Cursor<M> {
    fn map(&mut self, frame: Frame, prop: PageProperty);
}

// `UntrackedMode` associates with `UntrackedNode`
impl<M: UntrackedMode> Cursor {
    fn map(&mut self, pa: &Range<Paddr>, prop: PageProperty);
}
```

**Pros:**
 - Improves clarity of cursor and node implementation.
 - Addresses the above problem.

**Cons:**
 - Cursor implementation requires more refactoring.
 - Cursor may not be as flexible as it is now, but are there use cases where accesses to tracked frames and untracked regions of memory have be mixed in one cursor?

cc @junyang-zh

### LINKED ISSUE #1399: Silently failed ktest in OSTD: untracked_map_unmap
### Describe the bug

https://github.com/asterinas/asterinas/actions/runs/11101937778/job/30840638910#step:6:634

The ktest `test_untracked_map_unmap` failed, but CI doesn't notice it. The failure is reproducible locally.

### To Reproduce

```bash
cd ostd && cargo osdk test test_untracked_map_unmap
```

### PR DESCRIPTION
**Pull request by junyang-zh**
Addresses the same problem pointed out by #919 , but in a somewhat different implementation.

This is based on #1369 

Fix #1399 
close #919

This PR contains many commits, but they serve one purpose as a whole: remove soundness problems and fix soundness bugs already popping up.

Big commits:
 1. The first commit fixes the problem that untracked mappings will be dropped as tracked;
 4. The fourth commit organizes the `page_table::node` implementation so the properties are expressed more clearly;

### CODE REVIEW

File: ostd/src/mm/page_table/node/child.rs [hunk 1]
```diff
@@ -0,0 +1,149 @@
...
+            Child::Untracked(pa, level, prop) => E::new_page(pa, level, prop),
+            Child::None => E::new_absent(),
+        }
+    }
+
+    /// Converts a PTE back to a child.
+    ///
+    /// # Safety
+    ///
+    /// The provided PTE must be casted using [`Child::into_pte`]. And the
```
Comment (cchanging) [inline ostd/src/mm/page_table/node/child.rs:118]: Does this sentence means that the input pte have to be obtained from `Child::into_pte`? There are some APIs like `read_pte`, which will get a stored pte instead of constructing a new one. Personally, I think this sentence a bit ambiguous, as it might give the first impression that a pte obtained from `read_pte` cannot be passed into this function. I think it may need to add some additional clarifications, such as: The input pte must be a valid pte. A valid pte is one constructed by `Child::into_pte` and will be stored in the page table.

File: ostd/src/mm/page/meta.rs [hunk 2]
```diff
@@ -180,29 +180,50 @@ impl Sealed for FrameMeta {}
...
+#[repr(u8)]
+pub(in crate::mm) enum MapTrackingStatus {
+    /// The page table node cannot contain references to any pages. It can only
+    /// contain references to child page table nodes.
+    NotApplicable,
+    /// The mapped pages are not tracked by metadata. If any child page table
+    /// nodes exist, they should also tracked.
+    Untracked,
+    /// The mapped pages are tracked by metadata. If any child page table nodes
+    /// exist, they should also tracked.
```
Comment (cchanging) [inline ostd/src/mm/page/meta.rs:213]: -> be tracked

**Review by cchanging — COMMENTED** [review]
Good job!

File: ostd/src/mm/page_table/cursor.rs [hunk 3]
```diff
@@ -818,7 +810,7 @@ where
             src.cur_node_mut().protect(idx, pte_prop);
 
             // Do copy.
-            let child = src.cur_node_mut().child(idx, true);
+            let child = src.cur_node_mut().child(idx);
```
[the remark this answers is not in the document]
Comment (junyang-zh) [reply ostd/src/mm/page_table/cursor.rs:813]: Planned, to be done.

File: ostd/src/mm/page_table/node/child.rs (hunk 1 above)
Comment (junyang-zh) [reply ostd/src/mm/page_table/node/child.rs:76]: There's absolutely no reason to cast a PTE that does not come from `Child::into_pte`. When you put it into a page table and read it back it still comes from `Child::into_pte` (although the hardware will modify some bits). I will polish the doc.

**Comment by junyang-zh** [comment]
Ok, now I am satisfied with the page table design myself. The new design incorporates two abstractions, the `Entry` view and the `Child` handle, which confined the place where the PTE is needed and improves performance.

**Comment by junyang-zh** [comment]
I think this pr should be separated.

File: ostd/src/mm/page_table/cursor.rs [hunk 4]
```diff
@@ -785,91 +780,45 @@ where
...
+                    op(&mut prop);
+                    self.jump(src_va).unwrap();
+                    let mapped_page_size = page.size();
+                    let original = self.map(page, prop);
+                    assert!(original.is_none());
+
+                    // Only move the source cursor forward since `Self::map` will do it.
+                    // This assertion is to ensure that they move by the same length.
+                    debug_assert_eq!(mapped_page_size, page_size::<C>(src.0.level));
                     src.0.move_forward();
```
Comment (lrh2000) [inline ostd/src/mm/page_table/cursor.rs:819]: This might be a slightly better way to group the statements.
```rust
                    let mapped_page_size = page.size();
                    
                    // Do protection.
                    src_entry.protect(op);
                    op(&mut prop);

                    // Do copy.
                    self.jump(src_va).unwrap();
                    let original = self.map(page, prop);
                    assert!(original.is_none());

                    // Only move the source cursor forward since `Self::map` will do it.
                    // This assertion is to ensure that they move by the same length.
                    debug_assert_eq!(mapped_page_size, page_size::<C>(src.0.level));
                    src.0.move_forward();
```

File: ostd/src/mm/page_table/node/child.rs [hunk 5]
```diff
@@ -0,0 +1,137 @@
...
+            if !pte.is_last(level) {
+                Child::PageTable(RawPageTableNode::from_paddr(paddr))
+            } else {
+                match is_tracked {
+                    MapTrackingStatus::Tracked => Child::Page(DynPage::from_raw(paddr), pte.prop()),
+                    MapTrackingStatus::Untracked => Child::Untracked(paddr, level, pte.prop()),
+                    MapTrackingStatus::NotApplicable => panic!("Invalid tracking status"),
+                }
+            }
+        }
```
Comment (lrh2000) [inline ostd/src/mm/page_table/node/child.rs:100]: This seems slightly better:
```rust
        if !pte.is_present() {
            return Child::None;
        }

        let paddr = pte.paddr();

        if !pte.is_last(level) {
            return Child::PageTable(RawPageTableNode::from_paddr(paddr));
        }

        match is_tracked {
            MapTrackingStatus::Tracked => Child::Page(DynPage::from_raw(paddr), pte.prop()),
            MapTrackingStatus::Untracked => Child::Untracked(paddr, level, pte.prop()),
            MapTrackingStatus::NotApplicable => panic!("Invalid tracking status"),
        }
```

The same goes for `clone_from_pte`.

File: ostd/src/mm/page_table/node/mod.rs [hunk 6]
```diff
@@ -155,6 +152,34 @@ where
             Page::<PageTablePageMeta<E, C>>::inc_ref_count(self.paddr());
         }
     }
+
+    /// Restore the handle to a page table node from a physical address.
```
Comment (lrh2000) [inline ostd/src/mm/page_table/node/mod.rs:156]: `Restore` -> `Restores`

**Review by lrh2000 — COMMENTED** [review]
https://github.com/asterinas/asterinas/issues/919 has been reopened, you can add "close #919" in the PR description.

Overall, the design looks good to me. But it seems that this PR is actually a bit ambiguous in answering the original question posed in #919: Which of the 1-5 properties does `PageTableNode` want to ensure? See detailed comments below.
 - At least I don't think I have a clear feeling after reading the code, because `debug_assert!` is just ambiguous, and I don't know if it means safety preconditions or logical error prevention.

**Comment by junyang-zh** [comment]
> Which of the 1-5 properties does PageTableNode want to ensure?

Now all of 5.

> What's the cost of using assert! here?

Although not significant, this is noticeable. For `lmbench/process_fork_lat` the average overall latency increased about 0.3 microseconds, (0.3/63=0.47%). The cost mainly comes from the need of recording an extra `level` field in the `RawPageTableNode` structure. Without adding this field we cannot check if a child is compatible, and if we require a locked handle when copying page tables there would be an extra locking operation.

I think that I can try to encode the level in the last zero bits of the physical address to see if it works.

File: ostd/src/mm/page_table/node/entry.rs [hunk 7]
```diff
@@ -0,0 +1,147 @@
...
+                .replace(Child::Untracked(small_pa, level - 1, prop));
+        }
+
+        let _ = self.replace(Child::PageTable(new_page.clone_raw()));
+
+        new_page
+    }
+
+    pub(super) fn new_at(node: &'a mut PageTableNode<E, C>, idx: usize) -> Self {
+        debug_assert!(idx < nr_subpage_per_huge::<C>());
```
[the remark this answers is not in the document]
Comment (junyang-zh) [reply ostd/src/mm/page_table/node/entry.rs:134]: The three methods `new_at`/`read_pte`/`write_pte` can only be accessed in the node module. So the satisfiability is contained. My concern is that if we mark it unsafe there would be many trivially true unsafe blocks. I think using debug assertions to mark such safety preconditions are just enough. Can you provide more insights about how should we deal with such cases?

[the remark this answers is not in the document]
Comment (lrh2000) [reply ostd/src/mm/page_table/node/entry.rs:134]: > The three methods `new_at`/`read_pte`/`write_pte` can only be accessed in the node module. So the satisfiability is contained.

Yes, in theory it's fine to mark all internal methods as _not_ unsafe, and since they're not public, our code is still sound with respect to the public APIs.

So it's more of a readability and maintainability issue. 

> My concern is that if we mark it unsafe there would be many trivially true unsafe blocks.

First, I'm not sure why you say "many". Currently, I believe `read_pte` is called only once (when constructing `Entry`) and `write_pte` is called only twice (when operating on `Entry`), and both are definitely not "many".

Second, I would argue that if some unsafe methods are called many times with the same trivially true safety comments, this just signals that our code needs refactoring.

For example, if `write_pte` needs to be called 10 times when operating on `Entry`, I would suggest that a better strategy is to abstract a safe method to do this:
```rust
impl Entry {
    fn write_pte(&mut self, something: Something) {
        // SAFETY: `self.index` is in bounds, guaranteed by the safety conditions of `Entry::new_at`.
        unsafe { self.node.write_pte(self.index, something) };
    }
}
```

(Actually, the introduction of `Entry` did a good job and helps the above argument. As you can see, before this PR, `node.read_pte`/`node.write_pte` can be called directly and the caller has to make sure the index is in bounds, but now after `Entry` is created, the index of `Entry` is always in bounds, so we can easily create safe wrappers).

> I think using debug assertions to mark such safety preconditions are just enough.

At least to me, the current implementation does not seem very reasonable.

For example, the implementation of `read_pte` is:
```rust
fn read_pte(&self, idx: usize) -> E {
    // ...

    // SAFETY: the index is within the bound and PTE is plain-old-data.
    unsafe { ptr.add(idx).read() }
}
```

The statement "the index is within the bound" does not make much sense because `idx` is just an (unchecked) input argument. The code just says that some preconditions need to be _upheld_, but the comments say that the precondition is _already met_, they just contradict each other.

So my point is: the correct, Rust-style way to express that some conditions must be upheld, is to mark the function as unsafe. Again, if they create duplicates, try to find a better way to wrap these unsafe methods.

[the remark this answers is not in the document]
Comment (lrh2000) [reply ostd/src/mm/page_table/node/entry.rs:134]: > Second, I would argue that if some unsafe methods are called many times with the same trivially true safety comments, this just signals that our code needs refactoring.
> 
> For example, if `write_pte` needs to be called 10 times when operating on `Entry`, I would suggest that a better strategy is to abstract a safe method to do this:
> 
> ```rust
> impl Entry {
>     fn write_pte(&mut self, something: Something) {
>         // SAFETY: `self.index` is in bounds, guaranteed by the safety conditions of `Entry::new_at`.
>         unsafe { self.node.write_pte(self.index, something) };
>     }
> }
> ```

I also note that this is not currently the case. I believe the validity of the PTE passed to `write_pte` is also another safety condition that is just never mentioned in the current implementation.

For example, I expect that the reasons why `write_pte` is sound in `protect` / `replace` are actually _different_. So there is no duplication.

```rust
    /// Operates on the mapping properties of the entry.
    pub(in crate::mm) fn protect(&mut self, op: &mut impl FnMut(&mut PageProperty)) {
        // ...        

        // SAFETY:
        // 1. The index is inbounds.
        // 2. We replace the PTE with a new one, which differs only in `PageProperty`, so it is
        //    still compatible with the current page table node.
        unsafe { self.node.write_pte(self.idx, self.pte) };
    }

    pub(in crate::mm) fn replace(self, new_child: Child<E, C>) -> Child<E, C> {
        assert!(new_child.is_compatible(self.node.level(), self.node.is_tracked()));

        // ...

        // SAFETY:
        // 1. The index is in bounds.
        // 2. The new PTE is compatible with the page table node, as asserted above.
        self.node.write_pte(self.idx, new_child.into_pte());

        old_child
    }
```

Well, I'm not sure if you think it's "obvious", but I think having these comments makes our implementation clearer.

[the remark this answers is not in the document]
Comment (junyang-zh) [reply ostd/src/mm/page_table/node/entry.rs:142]: Thanks very much for your explanation in depth. I have accepted your suggestion.

File: ostd/src/mm/page/mod.rs [hunk 8]
```diff
@@ -363,3 +330,22 @@ impl Drop for DynPage {
         }
     }
 }
+
+/// Increase the reference count of the page by one.
```
Comment (lrh2000) [inline ostd/src/mm/page/mod.rs:334]: `Increase` -> `Increases`

File: ostd/src/mm/page/mod.rs [hunk 9]
```diff
@@ -363,3 +330,22 @@ impl Drop for DynPage {
...
+///
+/// # Safety
+///
+/// The physical address must represent a valid page.
+///
+/// And the caller must ensure the metadata slot pointed through the corresponding
+/// virtual address is initialized by holding a reference count of the page firstly.
+/// Otherwise the function may add a reference count to an unused page.
```
Comment (lrh2000) [inline ostd/src/mm/page/mod.rs:342]: Not sure why this safety condition is _so complicated_. Can we simplify it like this?
```rust
/// # Safety
///
/// 1. The physical address must represent a valid page.
/// 2. The caller must have already held a reference to the page.
```

(Not a problem introduced by this PR, feel free to ignore it if you don't think it's better).

File: ostd/src/mm/page/mod.rs [hunk 10]
```diff
@@ -363,3 +330,22 @@ impl Drop for DynPage {
...
+pub(in crate::mm) unsafe fn inc_page_ref_count(paddr: Paddr) {
+    debug_assert!(paddr % PAGE_SIZE == 0);
+    debug_assert!(paddr < MAX_PADDR.load(Ordering::Relaxed) as Paddr);
+    let vaddr: Vaddr = mapping::page_to_meta::<PagingConsts>(paddr);
+    // SAFETY: The virtual address points to an initialized metadata slot.
+    (*(vaddr as *const MetaSlot))
```
Comment (lrh2000) [inline ostd/src/mm/page/mod.rs:348]: Try to add an `unsafe` block here as we have safety comments now. Someone trying to enable `unsafe_op_in_unsafe_fn` lint will benefit from this.

File: ostd/src/mm/page_table/cursor.rs [hunk 11]
```diff
@@ -190,12 +195,15 @@ where
                 break;
             }
 
-            let cur_pte = cursor.read_cur_pte();
-            if !cur_pte.is_present() || cur_pte.is_last(cursor.level) {
+            let entry = cursor.cur_entry();
+            if !entry.is_node() {
                 break;
             }
+            let Child::PageTable(child_pt) = cursor.cur_entry().to_owned() else {
```
Comment (lrh2000) [inline ostd/src/mm/page_table/cursor.rs:202]: `cursor.cur_entry()` -> `entry`

File: ostd/src/mm/page_table/cursor.rs [hunk 12]
```diff
@@ -283,78 +292,47 @@ where
...
         self.level += 1;
 
         // TODO: Drop page tables if page tables become empty.
     }
 
-    /// Goes down a level assuming a child page table exists.
-    fn level_down(&mut self) {
+    /// Goes down a level to a child page table.
+    fn push_level(&mut self, child_pt: PageTableNode<E, C>) {
         debug_assert!(self.level > 1);
```
Comment (lrh2000) [inline ostd/src/mm/page_table/cursor.rs:320]: `self.level - 1` will be used as an index later, so this debug assertion is meaningless.

File: ostd/src/mm/page_table/cursor.rs [hunk 13]
```diff
@@ -692,51 +691,47 @@ where
...
-                    .as_ref()
-                    .unwrap()
-                    .nr_children()
-                    == 0
-                {
-                    self.0.level_up();
+            // Go down if it's not a last entry.
+            if cur_entry.is_node() {
+                let Child::PageTable(pt) = cur_entry.to_owned() else {
+                    unreachable!("Already checked");
```
Comment (lrh2000) [inline ostd/src/mm/page_table/cursor.rs:708]: This pattern seems to occur multiple times, so perhaps there can be a `cur_entry.to_page_table()` method (i.e., `is_node() && to_owned()`).

File: ostd/src/mm/page_table/cursor.rs [hunk 14]
```diff
@@ -692,51 +691,47 @@ where
...
-                if self.0.in_tracked_range() {
-                    panic!("protecting part of a huge page");
-                } else {
-                    self.level_down_split();
-                    continue;
-                }
+            if cur_va % page_size::<C>(cur_level) != 0 || cur_va + page_size::<C>(cur_level) > end {
+                debug_assert!(cur_entry.is_last());
+                assert!(!cur_is_tracked, "Protecting part of a huge page");
+                let split_child = cur_entry.split_untracked_huge();
```
Comment (lrh2000) [inline ostd/src/mm/page_table/cursor.rs:726]: The above two `debug_assert!`/`assert!` becomes duplicate with the assertion in `split_untrack_huge`. Can we make it a `split_if_untracked_huge` and just unwrap here?

**Review by lrh2000 — COMMENTED** [review]
An incomplete review (the diffs shown in GitHub before `cursor.rs`, inclusive).

You push too often, which encourages me to submit reviews early to prevent them from becoming outdated.

**Comment by junyang-zh** [comment]
> You push too often, which encourages me to submit reviews early to prevent them from becoming outdated.

Sorry! I will try to limit the scope of this PR and prevent myself pushing a pile of impediment fixes of things I keep noticing as bad when working with this PR.

File: ostd/src/mm/page_table/node/mod.rs [hunk 15]
```diff
@@ -242,209 +268,73 @@ where
...
-    fn write_pte(&mut self, idx: usize, pte: E) {
-        // It should be ensured by the cursor.
+    /// This operation will leak the old child if the old PTE is present.
+    ///
+    /// # Safety
+    ///
+    /// The caller must ensure that the index is within the bound, and the
+    /// provided PTE is valid. A valid PTE, if points to a page, must point
+    /// to a valid owned page and the child should be compatible with the
+    /// node. The compatibility is specified by the [`Child::is_compatible`].
```
Comment (lrh2000) [inline ostd/src/mm/page_table/node/mod.rs:326]: The current form is acceptable, but can be made a bit more clearer. What about:
```rust
/// # Safety
///
/// 1. The index must be within the bound.
/// 2. The PTE must represent a compatible child (see [`Child::is_compatible`]) whose ownership is
///    passed to the page table node.
```

File: ostd/src/mm/page_table/node/mod.rs [hunk 16]
```diff
@@ -242,209 +268,73 @@ where
...
-            }
-        }
+    /// Gets the number of valid PTEs in the node.
+    pub(super) fn nr_children(&self) -> u16 {
+        // SAFETY: The lock is held so we have an exclusive access.
+        unsafe { *self.page.meta().nr_children.get() }
     }
 
-    /// Replace the child at the given index with a new child.
+    /// Read a non-owning PTE at the entry.
```
Comment (lrh2000) [inline ostd/src/mm/page_table/node/mod.rs:301]: `Read` -> `Reads`

What do you want to mean by saying "at the entry"? Perhaps you want to say "at the index"?

File: ostd/src/mm/page_table/node/entry.rs [hunk 17]
```diff
@@ -0,0 +1,159 @@
...
+                .replace(Child::Untracked(small_pa, level - 1, prop));
+        }
+
+        let _ = self.replace(Child::PageTable(new_page.clone_raw()));
+
+        Some(new_page)
+    }
+
+    /// Create a new entry at the node.
+    pub(super) fn new_at(node: &'a mut PageTableNode<E, C>, idx: usize) -> Self {
```
Comment (lrh2000) [inline ostd/src/mm/page_table/node/entry.rs:152]: As discussed earlier, let's mark `new_at` as unsafe.

The following `debug_assert!` can be replaced by safety conditions (keeping the `debug_assert!` is generally okay, but in this particular case it seems redundant since the only caller is `entry` and it does the `assert!`).

**Review by lrh2000 — COMMENTED** [review]
Finishing the remaining part of my review... Just a few more minor comments.

File: ostd/src/mm/page_table/cursor.rs (hunk 13 above)
Comment (junyang-zh) [reply ostd/src/mm/page_table/cursor.rs:705]: There's only two cases of `is_node() && to_owned()` I think. Perhaps it's not worthwhile to add a method for it. To fix it we need either to add a method that internally uses `unreachable` to unwrap a `Child`, or uses unsafe code to check and clone the child. Either of them seemed not elegant.

Comment (lrh2000) [reply ostd/src/mm/page_table/cursor.rs:705]: OK, I am not counting the number of `is_node() && to_owned()` exactly, just expressing a feeling while reviewing the code.

Since the count is only two, the current form is acceptable to me.

**Review by lrh2000 — APPROVED** [review]
Thanks! The current changes look good to me!

**Review by tatetian — APPROVED** [review]
LGTM. Thanks for the contribution!
