### PR TITLE
Fix the failure of device-related benchmarks

### LINKED ISSUE #1882: Benchmark fio/ext2_seq_read_bw failed
Today's `fio/ext2_seq_read_bw` failed, see [this](https://github.com/asterinas/asterinas/actions/runs/13707278780/job/38335572751#step:6:16). It can be reproduced locally, and the error shows it is something related to dma mapping.

```log
*** Running the FIO sequential read test (Ext2) ***
seqread: (g=0): rw=read, bs=(R) 1024KiB-1024KiB, (W) 1024KiB-1024KiB, (T) 1024KiB-1024KiB, ioengine=sync, iodepth=1
fio-3.37
Starting 1 thread
seqread: Laying out IO file (1 file / 1024MiB)
[     1.767] ERROR: Uncaught panic:
	called `Result::unwrap()` on an `Err` value: InvalidVaddrRange(8589934592, 8589938688)
	at /root/asterinas/ostd/src/arch/x86/iommu/dma_remapping/context_table.rs:309
	on CPU 0 by thread Some(Thread { task: (Weak), data: Any { .. }, status: AtomicThreadStatus(1), cpu_affinity: AtomicCpuSet { bits: [1] }, sched_attr: SchedAttr { policy: SchedPolicyState { kind: Atomi)
```

### PR DESCRIPTION
**Pull request by sdww0**
Fixes #1882.

See https://github.com/asterinas/asterinas/issues/1882#issuecomment-2746041436. In this PR, I set the `VADDR_RANGE` to `0..0x80_0000_0000` as a temporary fix for the failure of device-related benchmarks.

### CODE REVIEW

File: ostd/src/arch/x86/iommu/dma_remapping/second_stage.rs [hunk 1]
```diff
@@ -20,8 +20,12 @@ use crate::{
...
 
 impl PageTableMode for DeviceMode {
-    /// The device address space is 32-bit.
-    const VADDR_RANGE: Range<Vaddr> = 0..0x1_0000_0000;
+    /// The device address space, which is the same as the
+    /// usable physical memory.
+    //
+    // FIXME: We should adjust the ranges to match the device
+    // address space dynamically.
+    const VADDR_RANGE: Range<Vaddr> = 0..0x80_0000_0000;
```
Comment (junyang-zh) [inline ostd/src/arch/x86/iommu/dma_remapping/second_stage.rs:28]: I think `0x80_0000_0000` is not a bad choice because it happens to be the 39-bit address space and can be mapped with 3-level paging. That's the maximum we can support. If we are supporting devices that have only 32-bit address space in the future, I think it's the drivers' responsibility to make sure device addresses are in range. OSTD doesn't need to check this.

So I think the comments should be revised, and the FIXME can be removed:

```rust
/// The device address width we currently support is 39-bit.
const VADDR_RANGE: Range<Vaddr> = 0..0x80_0000_0000;
```

**Review by junyang-zh — APPROVED** [review]
Looks good to me! Thanks for your contribution.
